import type { LanguageColumn } from '../types.js';

type Forms = Record<string, string>;

// A Vallader noun: masculine or feminine (no neuter), plural in -s unless given (giat → giats,
// chasa → chasas; a noun in -s or -sch keeps it: ils uors). `mu`/`fu` are the uncountable ones,
// with no plural. Every form (verify).
const m = (base: string, plural = base + 's', extra: Forms = {}): Forms => ({ base, plural, gender: 'masc', count: 'singular', ...extra });
const f = (base: string, plural = base + 's', extra: Forms = {}): Forms => ({ base, plural, gender: 'fem', count: 'singular', ...extra });
const mu = (base: string, extra: Forms = {}): Forms => ({ base, gender: 'masc', count: 'singular', ...extra });
const fu = (base: string, extra: Forms = {}): Forms => ({ base, gender: 'fem', count: 'singular', ...extra });
const KIN = { kinship: '1' };
const NAME = { takes_article: '0' };

export const RM_VALLADER_NOUNS: LanguageColumn = {
  // Animals
  ANIMAL: f('bes-cha'),
  MAMMAL: m('mammifer'),
  CAT: m('giat', 'giats', { fem: 'giatta', fem_plural: 'giattas' }),
  // chan (Puter chaun).
  DOG: m('chan', 'chans', { fem: 'chagna', fem_plural: 'chagnas' }),
  BIRD: m('utschè', 'utschels'),
  FISH: m('pesch'),
  REPTILE: m('reptil'),
  AMPHIBIAN: m('amfibi'),
  INSECT: m('insect'),
  HORSE: m('chavagl', 'chavals', { fem: 'chavala', fem_plural: 'chavalas' }),
  PIG: m('portsch'),
  SHEEP: f('nuorsa'),
  GOAT: f('chaura'),
  RABBIT: m('conigl', 'conigls', { fem: 'conigla', fem_plural: 'coniglas' }),
  BEAR: m('uors', 'uors', { fem: 'uorsa', fem_plural: 'uorsas' }),
  LION: m('leun', 'leuns', { fem: 'leunessa', fem_plural: 'leunessas' }),
  TIGER: m('tiger'), // masculine (it: la tigre)
  // The felines, seeded on main while P04 was in flight; every form (verify).
  FELINE: m('felin'),
  LEOPARD: m('leopard'),
  PANTHER: f('pantera'),
  PUMA: m('puma'),
  CHEETAH: m('gepard'),
  ELEPHANT: m('elefant', 'elefants', { fem: 'elefantessa', fem_plural: 'elefantessas' }),
  MONKEY: f('schimgia'),
  DEER: m('tschierv'),
  WHALE: f('balena'),
  CHICKEN: f('giallina'),
  DUCK: f('anda'), // (verify)
  EAGLE: f('aivla'),
  OWL: f('tschuetta'), // (verify)
  PENGUIN: m('pinguin'),
  SHARK: m('squal'), // (verify)
  SALMON: m('salm'),
  SNAKE: f('serp'), // feminine (it: il serpente) (verify)
  TURTLE: f('tartaruga'),
  CROCODILE: m('crocodil'),
  LIZARD: f('luschaina'), // (verify)
  FROG: f('rana'), // (verify)
  BEE: f('avaina'),
  ANT: f('furmia'),
  BUTTERFLY: m('splerin'),
  MOSQUITO: f('zanzara'), // (verify)
  SPIDER: f('filunza'),
  WOLF: m('luf', 'lufs', { fem: 'lufa', fem_plural: 'lufas' }),
  FOX: f('vuolp'),
  BOVINE: m('bovin'),
  COW: f('vacha'),
  OX: m('bouv'),
  MOUSE: f('mür'), // la mür (the wall is il mür)
  FLY_INSECT: f('muos-cha'),

  // Things, substances, measures
  BOOK: m('cudesch'),
  AIR: mu('ajer'),
  GROUND: m('terrain'),
  WATER: fu('aua'),
  SPEED: f('sveltezza'),
  LIGHT: f('glüm'),
  SOUND: m('tun'),
  WAY: m('möd'),
  TIME: m('temp'),
  CARE: fu('chüra'),
  SIZE: f('grondezza'),
  HEIGHT: f('otezza'),
  LENGTH: f('lunghezza'),
  QUALITY: f('qualità', 'qualitats'),
  STRENGTH: f('forza'),
  AGE: f('età', 'etats'),
  TEMPERATURE: f('temperatura'),
  DISTANCE: f('distanza'),
  SHAPE: f('fuorma'),
  CIRCLE: m('circul'),
  LINE_MARK: f('lingia'),
  MONEY: mu('daner'), // (verify) daner / raps
  // il mangiar: food.
  FOOD: mu('mangiar'),
  ICE_CREAM: f('glatscha'), // (verify)
  SUGAR: mu('zücher'),
  LIQUID: mu('liquid'),
  CONTENT: m('cuntgnü', 'cuntgnüts'),
  PLACE: m('lö'),
  POINT_NOUN: m('punct'),
  AREA: f('zona'),
  CENTER: m('center'),
  SIDE: f('vart'),
  DESTINATION: f('destinaziun'),
  ORIGIN: f('origin'),
  PATH: m('percuors', 'percuors'),
  DIRECTION_SPACE: f('direcziun'),
  BUILDING: m('edifizi'),
  WALL: m('mür'),
  HOUSE: f('chasa'),
  HOME: f('chasa'),
  ROOM: f('stanza'),
  OFFICE: m('büro'),
  DOOR: f('porta'),
  CAR: m('auto'), // l'auto, masculine
  STICK: m('bastun'),
  ARROW_PROJECTILE: f('frizza'),
  BLADE: f('lama'),
  FIRE: m('fö'),
  FLAME: f('flomma'),
  COIN: f('munaida'),
  WING: f('ala'),
  TOOTH: m('dent'),
  TEAR: f('larma'),

  // People
  CHILD: m('uffant', 'uffants', { fem: 'uffanta', fem_plural: 'uffantas' }), // (verify) fem
  KID: m('mat', 'mats', { fem: 'matta', fem_plural: 'mattas' }),
  PERSON: f('persuna'),
  SPEAKER: m('pledader', 'pledaders', { fem: 'pledadra', fem_plural: 'pledadras' }), // (verify)
  COMPANION: m('cumpogn', 'cumpogns', { fem: 'cumpogna', fem_plural: 'cumpognas' }),
  RECIPIENT: m('destinatari', 'destinataris', { fem: 'destinataria', fem_plural: 'destinatarias' }),
  BOY: m('mat'),
  GIRL: f('matta'),
  MAN: m('hom', 'homens'),
  GUY: m('tip'),
  WOMAN: f('duonna'),
  BUTCHER: m('becher', 'bechers', { fem: 'bechra', fem_plural: 'bechras' }), // (verify)
  ANGEL: m('angel'),
  YOUNG_MAN: m('giuven'),
  YOUNG_WOMAN: f('giuvna'),
  BUILDER: m('constructur', 'constructurs', { fem: 'constructura', fem_plural: 'constructuras' }),
  CREATOR: m('creatur', 'creaturs', { fem: 'creatura', fem_plural: 'creaturas' }),
  STUDENT: m('student', 'students', { fem: 'studenta', fem_plural: 'studentas' }),
  POSSESSOR: m('possessur', 'possessurs', { fem: 'possessura', fem_plural: 'possessuras' }),

  // Family
  PARENT: m('genitur', 'geniturs', { fem: 'genitura', fem_plural: 'genituras' }),
  FATHER: m('bap', 'baps', KIN),
  RELATIVE: m('parent', 'parents', { fem: 'parenta', fem_plural: 'parentas' }),
  FAMILY: f('famiglia'),
  MOTHER: f('mamma', 'mammas', KIN),
  CHILD_OFFSPRING: m('figl', 'figls', { fem: 'figlia', fem_plural: 'figlias', ...KIN }),
  SON: m('figl', 'figls', KIN),
  DAUGHTER: f('figlia', 'figlias', KIN),
  SIBLING: m('frar', 'frars', { fem: 'sour', fem_plural: 'sours', ...KIN }),
  BROTHER: m('frar', 'frars', KIN),
  SISTER: f('sour', 'sours', KIN),
  SPOUSE: m('consort', 'consorts', { fem: 'consorta', fem_plural: 'consortas' }),
  HUSBAND: m('marid', 'marids', KIN),
  WIFE: f('duonna', 'duonnas', KIN), // (verify) duonna / consorta
  // tat, tatta: grandfather, grandmother.
  GRANDPARENT: m('tat', 'tats', { fem: 'tatta', fem_plural: 'tattas', ...KIN }),
  GRANDFATHER: m('tat', 'tats', KIN),
  GRANDMOTHER: f('tatta', 'tattas', KIN),
  GRANDCHILD: m('abiadi', 'abiadis', { fem: 'abiadia', fem_plural: 'abiadias', ...KIN }),
  GRANDSON: m('abiadi', 'abiadis', KIN),
  GRANDDAUGHTER: f('abiadia', 'abiadias', KIN),
  UNCLE: m('barba', 'barbas', KIN),
  AUNT: f('amda', 'amdas', KIN),
  COUSIN: m('cusdrin', 'cusdrins', { fem: 'cusdrina', fem_plural: 'cusdrinas', ...KIN }),
  NEPHEW: m('nev', 'nevs', KIN), // (verify)
  NIECE: f('neza', 'nezas', KIN), // (verify)
  MOTHER_IN_LAW: f('sögra', 'sögras', KIN),
  FATHER_IN_LAW: m('sör', 'sörs', KIN), // (verify)
  SON_IN_LAW: m('schender', 'schenders', KIN), // (verify)
  DAUGHTER_IN_LAW: f('nora', 'noras', KIN), // (verify)
  BROTHER_IN_LAW: m('cugnà', 'cugnats', KIN),
  SISTER_IN_LAW: f('cugnada', 'cugnadas', KIN),
  STEPFATHER: m('padrast'), // (verify)
  STEPMOTHER: f('madrasta'), // (verify)
  MOM: f('mamma'),
  DAD: m('papa'),
  PARTNER: m('partenari', 'partenaris', { fem: 'partenaria', fem_plural: 'partenarias' }),
  BOYFRIEND: m('marus'), // (verify)
  GIRLFRIEND: f('marusa'), // (verify)
  FIANCE: m('fidanzà', 'fidanzats', { fem: 'fidanzada', fem_plural: 'fidanzadas' }),
  FRIEND: m('ami', 'amis', { fem: 'amia', fem_plural: 'amias' }),

  // Life, feeling, body
  LIFE: f('vita'),
  END: f('fin'),
  BEGINNING: m('cumanzamaint'),
  DEATH: f('mort'),
  FEELING: m('sentimaint'),
  AFFECTION: fu('affecziun'),
  BODY: m('corp'),
  ORGAN: m('organ'),
  TESTICLE: m('testicul'),
  OVARY: m('ovari'),
  MILK: mu('lat'),
  GRASS: fu('erba'),
  HEAT: fu('chalur'), // feminine (it: il calore)
  EYE: m('ögl'),
  HAND: f('man'),
  HEAD: f('testa'),
  FACE: f('fatscha'),
  BACK_BODY: m('dies', 'dies'),
  HEALTH: fu('sandà'),
  JOY: fu('algrezcha'),
  SORROW: fu('tristezza'),
  REST: mu('pos'),
  ATTENTION: fu('attenziun'),
  ABILITY: f('abiltà', 'abiltats'),
  DUTY: m('dovair'),
  KINDNESS: fu('amabiltà'),
  WISDOM: fu('sapienza'),
  FOLLY: fu('narria'), // (verify)
  MIND: f('ment'),

  // Places, peoples
  MARKET: m('marchà', 'marchats'),
  LEGEND: f('legenda'),
  PRISON: f('praschun'),
  CONTINENT: m('continent'),
  AFRICA: fu('Africa'),
  PETER: mu('Peider', NAME),
  MARY: fu('Maria', NAME),
  DIETH: mu('Dieth', NAME),
  // sar before a name, with no article (sar Peider) — it: il signor Rossi, so takes_article flips.
  MR: m('signur', 'signurs', { before_name: 'sar', takes_article: '0' }),
  EUROPE: fu('Europa'),
  ASIA: fu('Asia'),
  OCEANIA: fu('Oceania'),
  NORTH_AMERICA: fu('America dal Nord'),
  SOUTH_AMERICA: fu('America dal Süd'),
  ANTARCTICA: fu('Antarctica'),
  COUNTRY: m('pajais', 'pajais'),
  CITY: f('cità', 'citats'),
  ENGLAND: fu('Ingalterra'),
  ITALY: fu('Italia'),
  FRANCE: fu('Frantscha'),
  GERMANY: fu('Germania'),
  SPAIN: fu('Spagna'),
  JAPAN: mu('Giapun'),
  PORTUGAL: mu('Portugal'),
  ZURICH: mu('Turich', NAME), // gender (verify)
  LAND: fu('terra'),
  NATION: f('naziun'),
  SCHOOL: f('scoula'),
  COMPANY_BUSINESS: f('interpraisa'),
  TEAM: f('squadra'),
  COMMUNITY: f('cumünanza'),
  UNIVERSITY: f('università', 'universitats'),
  SERVICE: m('servezzan'),
  BUSINESS: mu('commerzi'),
  STATE_NATION: m('stadi'),
  POWER: f('pussanza'),
  GOVERNMENT: m('guvern'),
  PARTY_POLITICAL: f('partida'),
  LAW: f('ledscha'),
  COURT_LAW: m('tribunal'),
  RIGHT_NOUN: m('dret'),
  WAR: f('guerra'),
  WORLD: m('muond'),

  // Languages — lowercase, as Vallader writes them.
  LANGUAGE: f('lingua'),
  ENGLISH: mu('inglais'),
  ITALIAN: mu('talian'),
  FRENCH: mu('frances'),
  GERMAN: mu('tudais-ch'),
  SPANISH: mu('spagnöl'),
  JAPANESE: mu('giapunais'),
  PORTUGUESE: mu('portugais'),
  SWISS_GERMAN: mu('tudais-ch svizzer'),
  ROMANSH: mu('rumantsch'),
  CATALAN: mu('catalan'),
  POLISH: mu('polac'), // (verify)
  RUMANTSCH_GRISCHUN: mu('rumantsch grischun'),
  SURSILVAN: mu('sursilvan'),
  VALLADER: mu('vallader'),
  SPELLING: f('ortografia'),

  // Time
  PERIOD_TIME: f('perioda'),
  MOMENT: m('mumaint'),
  DAY: m('di', 'dis', { temporal_prep: 'in' }),
  HOUR: f('ura'),
  MINUTE: f('minuta'), // la minuta, feminine (it: il minuto)
  MONTH: m('mais', 'mais', { temporal_prep: 'in' }),
  WEEK: f('eivna', 'eivnas', { temporal_prep: 'in' }),
  NIGHT: f('not'),
  MORNING: f('damaun', 'damauns', { temporal_bare: '1' }),
  YEAR: m('on', 'ons', { temporal_prep: 'in' }),

  // Grammar
  PARTICIPANT_GRAMMAR: m('participant'),
  AGENT_GRAMMAR: m('agent'),
  SUBJECT_GRAMMAR: m('subject'),
  VOCATIVE: m('vocativ'),
  OBJECT_GRAMMAR: m('object'),
  SUBJECT_COMPLEMENT: m('cumplemaint predicativ dal subject', 'cumplemaints predicativs dal subject'),
  OBJECT_COMPLEMENT: m("cumplemaint predicativ da l'object", "cumplemaints predicativs da l'object"),
  INSTRUMENTAL: m('cumplemaint da mez', 'cumplemaints da mez'),
  COMITATIVE: m('cumplemaint da cumpagnia', 'cumplemaints da cumpagnia'),
  ADVERBIAL_OF_MANNER: m('cumplemaint da möd', 'cumplemaints da möd'),
  COMPLEMENT_GRAMMAR: m('cumplemaint'),
  LOCATIVE: m('cumplemaint da lö', 'cumplemaints da lö'),
  DIRECTION: m('cumplemaint da direcziun', 'cumplemaints da direcziun'),
  SOURCE: m("cumplemaint d'origin", "cumplemaints d'origin"),
  ROUTE: m('cumplemaint da percuors', 'cumplemaints da percuors'),
  CAUSE_COMPLEMENT: m('cumplemaint da chaschun', 'cumplemaints da chaschun'),
  TEMPORAL_COMPLEMENT: m('cumplemaint da temp', 'cumplemaints da temp'),
  PURPOSE_COMPLEMENT: m('cumplemaint da böt', 'cumplemaints da böt'),
  OPPONENT_COMPLEMENT: m('cumplemaint da dischavantag', 'cumplemaints da dischavantag'), // (verify)
  TOPIC_COMPLEMENT: m("cumplemaint d'argumaint", "cumplemaints d'argumaint"),
  ROLE_COMPLEMENT: m('cumplemaint da rolla', 'cumplemaints da rolla'),
  INTERJECTION: f('interjecziun'),
  TERMINUS: m('cumplemaint da termin', 'cumplemaints da termin'),
  NOUN: m('substantiv'),
  PRONOUN: m('pronom'),
  VERB: m('verb'),
  ADVERB: m('adverb'),
  ADJECTIVE: m('adjectiv'),
  INFINITIVE_PHRASE: f('frasa infinitiva', 'frasas infinitivas'),
  VERB_PHRASE: m('sintagma verbal', 'sintagmas verbals'),
  NOUN_PHRASE: m('sintagma nominal', 'sintagmas nominals'),
  CLAUSE: f('proposiziun'),
  RELATIVE_CLAUSE: f('proposiziun relativa', 'proposiziuns relativas'),
  STATEMENT: f('proposiziun declarativa', 'proposiziuns declarativas'),
  CONDITION: f('cundiziun'),
  COORDINATION: f('coordinaziun'),
  CONJUNCT: m('congiunct'),
  CONJUNCTION: f('conjuncziun'),
  MODIFIER: m('modificatur'),
  HYPERNYM: m('iperonim'),
  DETERMINER: m('determinant'),
  ARTICLE: m('artichel'),
  DEMONSTRATIVE: m('demonstrativ'),
  QUANTIFIER: m('quantificatur'),
  PERIOD_SENTENCE: f('perioda'),
  PERIOD_PUNCTUATION: m('punct'),
  BRACKET: f('parantesa'),
  PERSON_GRAMMAR: f('persuna'),
  NUMBER_GRAMMAR: m('numer'),
  SINGULAR_GRAMMAR: m('singular'),
  PLURAL_GRAMMAR: m('plural'),
  CASE_GRAMMAR: m('cas', 'cas'),
  DATIVE: m('dativ'),
  GENITIVE: m('genitiv'),
  GENDER: m('gener'),
  TENSE: m('temp'),
  PRESENT_TENSE: m('preschaint'),
  PAST_TENSE: m('passà', 'passats'),
  FUTURE_TENSE: m('futur'),
  ASPECT: m('aspet'),
  VOICE: f('diatesa'),
  POLARITY: f('polarità', 'polaritats'),
  SENTIMENT: f('valütaziun'),
  MOOD: m('modus', 'modus'),
  DEGREE_GRAMMAR: m('grad'),
  POSITIVE_DEGREE: m('grad positiv', 'grads positivs'),
  STANDARD_OF_COMPARISON: m('term da cumparegliaziun', 'terms da cumparegliaziun'), // (verify)
  COMPARISON_SET: f('gruppa da cumparegliaziun', 'gruppas da cumparegliaziun'), // (verify)
  MODAL: m('verb modal', 'verbs modals'),

  // Interface
  COMMAND: m('cumond'),
  ORDER: m('uorden'),
  INSTRUCTION: f('instrucziun'),
  REGISTER: m('register'),
  FORMALITY: fu('formalità'),
  OPTION: f('opziun'),
  BUTTON: m('buttun'),
  KEYBOARD: f('tastatura'),
  KEY: f('tasta'), // feminine (it: il tasto)
  ARROW: f('frizza'),
  REGION: f('regiun'),
  GROUP: f('gruppa'), // feminine (it: il gruppo)
  MEMBER: m('commember'),
  PARTY_CELEBRATION: f('festa'),
  ROW: f('lingia'),
  MENU: m('menu'),
  TAB: m('tab'), // (verify)
  TARGET: f('destinaziun'),
  HELP: mu('agüd'),
  NAVIGATION: fu('navigaziun'),
  NAME_NOUN: m('nom'),
  ALIAS: m('alias', 'alias'),
  TITLE: m('titel'),
  LOADING: mu('chargiamaint'),
  INTERFACE: f('interfatscha'),
  SERVER: m('server'),
  RESULT: m('resultat'),
  IMPORT_NOUN: f('importaziun'),
  ICON: f('icona'),
  FILE: f('datoteca'),
  CLIPBOARD: f('memoria intermediara', 'memorias intermediaras'), // (verify)
  LINE: f('lingia'),
  HISTORY: fu('cronologia'),
  WORKSPACE: m('spazi da lavur', 'spazis da lavur'),
  USAGE: mu('adöver'),
  EXAMPLE: m('exaimpel'),
  CONSOLE: f('consola'),
  CANVAS: f('taila'),
  PREVIEW: f('prevista'), // (verify)
  TOOLBAR: f("barra d'utensils", "barras d'utensils"),
  LIST: f('glista'),
  VALUE: f('valur'), // feminine (it: il valore)
  CURSOR: m('cursur'),
  TEXT: m('text'),
  REFERENCE: f('referenza'),
  SLOT: f('fessura'),
  SLOT_COMPUTING: m('slot'),
  SLOT_MACHINE: f('maschina da gö', 'maschinas da gö'),
  WORD: m('pled'),
  MEANING: f('significaziun'),
  PHRASE: f('frasa'),
  FACT: m('fat'),
  REASON: m('motiv'),
  INFORMATION: fu('infuormaziun'),
  PROBABILITY: f('probabiltà', 'probabiltats'),
  TRANSLATION: f('traducziun'),
  QUESTION: f('dumonda'),
  TELEPHONE: m('telefon'),
  CONTAINER: m('recipiaint'),
  MAP: f('charta'),
  NODE: m('nuf'),
  RELATIONSHIP: f('relaziun'),
  NUMBER: m('numer'),
  NUMBER_LABEL: m('numer'),
  QUANTITY: f('quantità', 'quantitats'),
  UNIT: f('unità', 'unitats'),
  PERCENT: m('pertschient', 'pertschient'),
  CATEGORY: f('categoria'),
  KIND_SORT: f('sort'),

  // Abstract things
  CAUSE: f('chaschun'),
  PROPERTY: mu('possess'),
  FEATURE: f('caracteristica'),
  DOMAIN: f('domena'), // (verify)
  MEANS: m('mez'),
  PURPOSE: m('böt'),
  USE_NOUN: m('adöver'),
  WORK_NOUN: fu('lavur'),
  RESEARCH: fu('perscrutaziun'),
  STUDY_NOUN: m('stüdi'),
  MATERIAL: m('material'),
  WOOD: mu('lain'),
  LEVEL: m('nivel'),
  PROCESS: m('process', 'process'),
  CHANGE_NOUN: m('müdamaint'),
  SYSTEM: m('sistem'),
  PROGRAM_SOFTWARE: m('program'),
  PROGRAM_SHOW: f('emischiun'),
  CONCEPT: m('concept'),
  IDEA: f('idea'),
  ACTION: f('acziun'),
  EVENT: m('evenimaint'),
  RACE: f('cuorsa'),
  GAME: m('gö'),
  OBJECT_THING: m('oget'),
  DEVICE: m('apparat'),
  BOMB: f('bomba'),
  THING: f('chosa'),
  PROBLEM: m('problem'),
  ISSUE: f('fatschenda'), // (verify)
  CASE_INSTANCE: m('cas', 'cas'),
  BEING: m('esser'),
  STORY: f('istorgia'),
  HISTORY_PAST: fu('istorgia'),
  // novitats: a plural noun, as it: notizie.
  NEWS: { base: 'novitats', gender: 'fem', count: 'plural' },
  SUBSTANCE: fu('substanza'),
  STATE: m('stadi'),
  GAS: mu('gas'),
  ERROR: m('sbagl'),
  REALITY: f('realtà', 'realtats'),
  PICTURE: m('purtret'),
  SCREEN: m('visur'), // (verify)
  PART: f('part'),
};
