import type { LanguageColumn } from '../types.js';

// The adjectives (P04-E5 D1): the attributive masculine singular (base), the feminine and the two
// plurals, and the predicative masculine singular — Sursilvan's -s (in paun bun / il paun ei buns),
// stored, not derived, so the review can correct it cell by cell (E9 reads it). A participle
// adjective agrees as the participle does: -au, -ada, -ai, -adas, predicative -aus. The predicative
// masculine plural is the attributive one, so predicative_masc_pl is never stored (verify).
// position: 'pre' marks the adjectives that normally precede the noun. Every form is (verify).
export const RM_SURSILV_ADJECTIVES: LanguageColumn = {
  BIG: { base: 'grond', fem: 'gronda', masc_plural: 'gronds', fem_plural: 'grondas', predicative_masc_sg: 'gronds' },
  SMALL: { base: 'pign', fem: 'pintga', masc_plural: 'pigns', fem_plural: 'pintgas', predicative_masc_sg: 'pigns' },
  HIGH: { base: 'ault', fem: 'aulta', masc_plural: 'aults', fem_plural: 'aultas', predicative_masc_sg: 'aults' },
  LONG: { base: 'liung', fem: 'liunga', masc_plural: 'liungs', fem_plural: 'liungas', predicative_masc_sg: 'liungs' },
  GREAT: { base: 'grond', fem: 'gronda', masc_plural: 'gronds', fem_plural: 'grondas', predicative_masc_sg: 'gronds', position: 'pre' },
  LOW: { base: 'bass', fem: 'bassa', masc_plural: 'bass', fem_plural: 'bassas', predicative_masc_sg: 'bass' },
  NEAR: { base: 'vischin', fem: 'vischina', masc_plural: 'vischins', fem_plural: 'vischinas', predicative_masc_sg: 'vischins' },
  FAR: { base: 'lontan', fem: 'lontana', masc_plural: 'lontans', fem_plural: 'lontanas', predicative_masc_sg: 'lontans' },
  // prenominal bien (Bien di!) is not modelled; the engine places bun after the noun (verify)
  GOOD: { base: 'bun', fem: 'buna', masc_plural: 'buns', fem_plural: 'bunas', predicative_masc_sg: 'buns', content_clause_mood: 'subjunctive' },
  BAD: { base: 'nausch', fem: 'nauscha', masc_plural: 'nauschs', fem_plural: 'nauschas', predicative_masc_sg: 'nauschs' },
  HAPPY: { base: 'ventireivel', fem: 'ventireivla', masc_plural: 'ventireivels', fem_plural: 'ventireivlas', predicative_masc_sg: 'ventireivels' },
  // jeu stun bein: an adverb, so it does not agree
  OKAY: { base: 'bein', fem: 'bein', masc_plural: 'bein', fem_plural: 'bein', predicative_masc_sg: 'bein', copula: 'BE_FARING' },
  SAD: { base: 'trist', fem: 'trista', masc_plural: 'trists', fem_plural: 'tristas', predicative_masc_sg: 'trists' },
  OLD: { base: 'vegl', fem: 'veglia', masc_plural: 'vegls', fem_plural: 'veglias', predicative_masc_sg: 'vegls', position: 'pre' },
  YOUNG: { base: 'giuven', fem: 'giuvna', masc_plural: 'giuvens', fem_plural: 'giuvnas', predicative_masc_sg: 'giuvens' },
  ELDER: { base: 'pli vegl', fem: 'pli veglia', masc_plural: 'pli vegls', fem_plural: 'pli veglias', predicative_masc_sg: 'pli vegls' },
  YOUNGER: { base: 'pli giuven', fem: 'pli giuvna', masc_plural: 'pli giuvens', fem_plural: 'pli giuvnas', predicative_masc_sg: 'pli giuvens' },
  ADULT: { base: 'carschiu', fem: 'carschida', masc_plural: 'carschi', fem_plural: 'carschidas', predicative_masc_sg: 'carschius' },
  MALE: { base: 'masculin', fem: 'masculina', masc_plural: 'masculins', fem_plural: 'masculinas', predicative_masc_sg: 'masculins' },
  FEMALE: { base: 'feminin', fem: 'feminina', masc_plural: 'feminins', fem_plural: 'femininas', predicative_masc_sg: 'feminins' },
  CASTRATED: { base: 'castrau', fem: 'castrada', masc_plural: 'castrai', fem_plural: 'castradas', predicative_masc_sg: 'castraus' },
  NEW: { base: 'niev', fem: 'nova', masc_plural: 'novs', fem_plural: 'novas', predicative_masc_sg: 'novs' },
  BEAUTIFUL: { base: 'bi', fem: 'bella', masc_plural: 'bials', fem_plural: 'bellas', predicative_masc_sg: 'bials', position: 'pre' },
  STRONG: { base: 'ferm', fem: 'ferma', masc_plural: 'ferms', fem_plural: 'fermas', predicative_masc_sg: 'ferms' },
  WEAK: { base: 'flaivel', fem: 'flaivla', masc_plural: 'flaivels', fem_plural: 'flaivlas', predicative_masc_sg: 'flaivels' },
  TIRED: { base: 'stanchel', fem: 'stancla', masc_plural: 'stanchels', fem_plural: 'stanclas', predicative_masc_sg: 'stanchels' },
  HUNGRY: { base: 'fomentau', fem: 'fomentada', masc_plural: 'fomentai', fem_plural: 'fomentadas', predicative_masc_sg: 'fomentaus' },
  COLD: { base: 'freid', fem: 'freida', masc_plural: 'freids', fem_plural: 'freidas', predicative_masc_sg: 'freids' },
  COLD_CLIMATE: { base: 'freid', fem: 'freida', masc_plural: 'freids', fem_plural: 'freidas', predicative_masc_sg: 'freids' },
  WARM: { base: 'cordial', fem: 'cordiala', masc_plural: 'cordials', fem_plural: 'cordialas', predicative_masc_sg: 'cordials' },
  HOT: { base: 'cauld', fem: 'caulda', masc_plural: 'caulds', fem_plural: 'cauldas', predicative_masc_sg: 'caulds' },
  HOT_CLIMATE: { base: 'cauld', fem: 'caulda', masc_plural: 'caulds', fem_plural: 'cauldas', predicative_masc_sg: 'caulds' },
  INTERESTING: { base: 'interessant', fem: 'interessanta', masc_plural: 'interessants', fem_plural: 'interessantas', predicative_masc_sg: 'interessants' },
  IMPORTANT: { base: 'impurtont', fem: 'impurtonta', masc_plural: 'impurtonts', fem_plural: 'impurtontas', predicative_masc_sg: 'impurtonts' },
  QUICK: { base: 'spert', fem: 'sperta', masc_plural: 'sperts', fem_plural: 'spertas', predicative_masc_sg: 'sperts' },
  BROWN: { base: 'brin', fem: 'brina', masc_plural: 'brins', fem_plural: 'brinas', predicative_masc_sg: 'brins' },
  BLACK: { base: 'ner', fem: 'nera', masc_plural: 'ners', fem_plural: 'neras', predicative_masc_sg: 'ners' },
  WHITE: { base: 'alv', fem: 'alva', masc_plural: 'alvs', fem_plural: 'alvas', predicative_masc_sg: 'alvs' },
  DARK: { base: 'stgir', fem: 'stgira', masc_plural: 'stgirs', fem_plural: 'stgiras', predicative_masc_sg: 'stgirs' },
  WILD: { base: 'selvadi', fem: 'selvadia', masc_plural: 'selvadis', fem_plural: 'selvadias', predicative_masc_sg: 'selvadis' },
  DOMESTIC: { base: 'domestic', fem: 'domestica', masc_plural: 'domestics', fem_plural: 'domesticas', predicative_masc_sg: 'domestics' },
  CANINE: { base: 'canin', fem: 'canina', masc_plural: 'canins', fem_plural: 'caninas', predicative_masc_sg: 'canins' },
  LAZY: { base: 'marsch', fem: 'marscha', masc_plural: 'marschs', fem_plural: 'marschas', predicative_masc_sg: 'marschs' },
  CAREFUL: { base: 'attent', fem: 'attenta', masc_plural: 'attents', fem_plural: 'attentas', predicative_masc_sg: 'attents' },
  POSSIBLE: { base: 'pusseivel', fem: 'pusseivla', masc_plural: 'pusseivels', fem_plural: 'pusseivlas', predicative_masc_sg: 'pusseivels', content_clause_mood: 'subjunctive' },
  ABLE: { base: 'capabel', fem: 'capabla', masc_plural: 'capabels', fem_plural: 'capablas', predicative_masc_sg: 'capabels', infinitive_link: 'da' },
  OBLIGED: { base: 'obligau', fem: 'obligada', masc_plural: 'obligai', fem_plural: 'obligadas', predicative_masc_sg: 'obligaus', infinitive_link: 'da' },
  ALLOWED: { base: 'lubiu', fem: 'lubida', masc_plural: 'lubi', fem_plural: 'lubidas', predicative_masc_sg: 'lubius', infinitive_link: 'da' },
  WHOLE: { base: 'entir', fem: 'entira', masc_plural: 'entirs', fem_plural: 'entiras', predicative_masc_sg: 'entirs' },
  ROUND: { base: 'radund', fem: 'radunda', masc_plural: 'radunds', fem_plural: 'radundas', predicative_masc_sg: 'radunds' },
  SHARP: { base: 'tagliont', fem: 'taglionta', masc_plural: 'taglionts', fem_plural: 'tagliontas', predicative_masc_sg: 'taglionts' },
  LOUD: { base: 'ferm', fem: 'ferma', masc_plural: 'ferms', fem_plural: 'fermas', predicative_masc_sg: 'ferms' },
  WRITTEN: { base: 'scret', fem: 'screta', masc_plural: 'screts', fem_plural: 'scretas', predicative_masc_sg: 'screts' },
  LOADED: { base: 'cargau', fem: 'cargada', masc_plural: 'cargai', fem_plural: 'cargadas', predicative_masc_sg: 'cargaus' },
  TIDY: { base: 'urdinau', fem: 'urdinada', masc_plural: 'urdinai', fem_plural: 'urdinadas', predicative_masc_sg: 'urdinaus' },
  SAVED: { base: 'memorisau', fem: 'memorisada', masc_plural: 'memorisai', fem_plural: 'memorisadas', predicative_masc_sg: 'memorisaus' },
  ADDED: { base: 'agiuntau', fem: 'agiuntada', masc_plural: 'agiuntai', fem_plural: 'agiuntadas', predicative_masc_sg: 'agiuntaus' },
  REMOVED: { base: 'allontanau', fem: 'allontanada', masc_plural: 'allontanai', fem_plural: 'allontanadas', predicative_masc_sg: 'allontanaus' },
  FAILED: { base: 'falliu', fem: 'fallida', masc_plural: 'falli', fem_plural: 'fallidas', predicative_masc_sg: 'fallius' },
  COPIED: { base: 'copiau', fem: 'copiada', masc_plural: 'copiai', fem_plural: 'copiadas', predicative_masc_sg: 'copiaus' },
  LINKED: { base: 'colliau', fem: 'colliada', masc_plural: 'colliai', fem_plural: 'colliadas', predicative_masc_sg: 'colliaus' },
  PINNED: { base: 'fixau', fem: 'fixada', masc_plural: 'fixai', fem_plural: 'fixadas', predicative_masc_sg: 'fixaus' },
  UNPINNED: { base: 'distaccau', fem: 'distaccada', masc_plural: 'distaccai', fem_plural: 'distaccadas', predicative_masc_sg: 'distaccaus' },
  RECENT: { base: 'recent', fem: 'recenta', masc_plural: 'recents', fem_plural: 'recentas', predicative_masc_sg: 'recents' },
  NUMBERED: { base: 'numerau', fem: 'numerada', masc_plural: 'numerai', fem_plural: 'numeradas', predicative_masc_sg: 'numeraus' },
  ACTIVE: { base: 'activ', fem: 'activa', masc_plural: 'activs', fem_plural: 'activas', predicative_masc_sg: 'activs' },
  UNTITLED: { base: 'senza tetel', fem: 'senza tetel', masc_plural: 'senza tetel', fem_plural: 'senza tetel', predicative_masc_sg: 'senza tetel' },
  EMPTY: { base: 'vit', fem: 'vida', masc_plural: 'vits', fem_plural: 'vidas', predicative_masc_sg: 'vits' },
  VALID: { base: 'valeivel', fem: 'valeivla', masc_plural: 'valeivels', fem_plural: 'valeivlas', predicative_masc_sg: 'valeivels' },
  MISSING: { base: 'mancont', fem: 'manconta', masc_plural: 'manconts', fem_plural: 'mancontas', predicative_masc_sg: 'manconts' },
  UNKNOWN: { base: 'nunenconuschent', fem: 'nunenconuschenta', masc_plural: 'nunenconuschents', fem_plural: 'nunenconuschentas', predicative_masc_sg: 'nunenconuschents' },
  KNOWN: { base: 'enconuschent', fem: 'enconuschenta', masc_plural: 'enconuschents', fem_plural: 'enconuschentas', predicative_masc_sg: 'enconuschents' },
  UNEXPECTED: { base: 'nunspitgau', fem: 'nunspitgada', masc_plural: 'nunspitgai', fem_plural: 'nunspitgadas', predicative_masc_sg: 'nunspitgaus' },
  SINGULAR: { base: 'singular', fem: 'singulara', masc_plural: 'singulars', fem_plural: 'singularas', predicative_masc_sg: 'singulars' },
  PLURAL: { base: 'plural', fem: 'plurala', masc_plural: 'plurals', fem_plural: 'pluralas', predicative_masc_sg: 'plurals' },
  NEUTER: { base: 'neutral', fem: 'neutrala', masc_plural: 'neutrals', fem_plural: 'neutralas', predicative_masc_sg: 'neutrals' },
  DEFINITE: { base: 'definit', fem: 'definita', masc_plural: 'definits', fem_plural: 'definitas', predicative_masc_sg: 'definits' },
  INDEFINITE: { base: 'indefinit', fem: 'indefinita', masc_plural: 'indefinits', fem_plural: 'indefinitas', predicative_masc_sg: 'indefinits' },
  ZERO: { base: 'zero', fem: 'zero', masc_plural: 'zero', fem_plural: 'zero', predicative_masc_sg: 'zero' },
  PROXIMAL: { base: 'proximal', fem: 'proximala', masc_plural: 'proximals', fem_plural: 'proximalas', predicative_masc_sg: 'proximals' },
  DISTAL: { base: 'distal', fem: 'distala', masc_plural: 'distals', fem_plural: 'distalas', predicative_masc_sg: 'distals' },
  PARTITIVE: { base: 'partitiv', fem: 'partitiva', masc_plural: 'partitivs', fem_plural: 'partitivas', predicative_masc_sg: 'partitivs' },
  NEGATIVE: { base: 'negativ', fem: 'negativa', masc_plural: 'negativs', fem_plural: 'negativas', predicative_masc_sg: 'negativs' },
  MULTAL: { base: 'multal', fem: 'multala', masc_plural: 'multals', fem_plural: 'multalas', predicative_masc_sg: 'multals' },
  PAUCAL: { base: 'paucal', fem: 'paucala', masc_plural: 'paucals', fem_plural: 'paucalas', predicative_masc_sg: 'paucals' },
  UNIVERSAL: { base: 'universal', fem: 'universala', masc_plural: 'universals', fem_plural: 'universalas', predicative_masc_sg: 'universals' },
  DISTRIBUTIVE: { base: 'distributiv', fem: 'distributiva', masc_plural: 'distributivs', fem_plural: 'distributivas', predicative_masc_sg: 'distributivs' },
  EXHAUSTIVE: { base: 'exhaustiv', fem: 'exhaustiva', masc_plural: 'exhaustivs', fem_plural: 'exhaustivas', predicative_masc_sg: 'exhaustivs' },
  DUAL: { base: 'dual', fem: 'duala', masc_plural: 'duals', fem_plural: 'dualas', predicative_masc_sg: 'duals' },
  PROPORTIONAL: { base: 'proporziunal', fem: 'proporziunala', masc_plural: 'proporziunals', fem_plural: 'proporziunalas', predicative_masc_sg: 'proporziunals' },
  MULTIPLE: { base: 'multipel', fem: 'multipla', masc_plural: 'multipels', fem_plural: 'multiplas', predicative_masc_sg: 'multipels' },
  SUFFICIENT: { base: 'sufficient', fem: 'sufficienta', masc_plural: 'sufficients', fem_plural: 'sufficientas', predicative_masc_sg: 'sufficients' },
  APPROXIMATE: { base: 'approximativ', fem: 'approximativa', masc_plural: 'approximativs', fem_plural: 'approximativas', predicative_masc_sg: 'approximativs' },
  SIMILATIVE: { base: 'similativ', fem: 'similativa', masc_plural: 'similativs', fem_plural: 'similativas', predicative_masc_sg: 'similativs' },
  FIRST: { base: 'emprem', fem: 'emprema', masc_plural: 'emprems', fem_plural: 'empremas', predicative_masc_sg: 'emprems', position: 'pre' },
  SECOND: { base: 'secund', fem: 'secunda', masc_plural: 'secunds', fem_plural: 'secundas', predicative_masc_sg: 'secunds', position: 'pre' },
  THIRD: { base: 'tierz', fem: 'tiarza', masc_plural: 'tierzs', fem_plural: 'tiarzas', predicative_masc_sg: 'tierzs', position: 'pre' },
  NEXT: { base: 'proxim', fem: 'proxima', masc_plural: 'proxims', fem_plural: 'proximas', predicative_masc_sg: 'proxims', position: 'pre' },
  PREVIOUS: { base: 'precedent', fem: 'precedenta', masc_plural: 'precedents', fem_plural: 'precedentas', predicative_masc_sg: 'precedents' },
  LAST_FINAL: { base: 'davos', fem: 'davosa', masc_plural: 'davos', fem_plural: 'davosas', predicative_masc_sg: 'davos', position: 'pre' },
  LAST_PREVIOUS: { base: 'vargau', fem: 'vargada', masc_plural: 'vargai', fem_plural: 'vargadas', predicative_masc_sg: 'vargaus' },
  NEXT_COMING: { base: 'proxim', fem: 'proxima', masc_plural: 'proxims', fem_plural: 'proximas', predicative_masc_sg: 'proxims', position: 'pre' },
  SAME: { base: 'medem', fem: 'medema', masc_plural: 'medems', fem_plural: 'medemas', predicative_masc_sg: 'medems', position: 'pre', predicate_article: '1' },
  DIFFERENT: { base: 'different', fem: 'differenta', masc_plural: 'differents', fem_plural: 'differentas', predicative_masc_sg: 'differents' },
  SURE: { base: 'segir', fem: 'segira', masc_plural: 'segirs', fem_plural: 'segiras', predicative_masc_sg: 'segirs' },
  REAL_EXISTING: { base: 'real', fem: 'reala', masc_plural: 'reals', fem_plural: 'realas', predicative_masc_sg: 'reals' },
  REAL_GENUINE: { base: 'ver', fem: 'vera', masc_plural: 'vers', fem_plural: 'veras', predicative_masc_sg: 'vers' },
  AMERICAN: { base: 'american', fem: 'americana', masc_plural: 'americans', fem_plural: 'americanas', predicative_masc_sg: 'americans' },
  RIGHT_CORRECT: { base: 'gest', fem: 'gesta', masc_plural: 'gests', fem_plural: 'gestas', predicative_masc_sg: 'gests', content_clause_mood: 'subjunctive' },
  RIGHT_SIDE: { base: 'dretg', fem: 'dretga', masc_plural: 'dretgs', fem_plural: 'dretgas', predicative_masc_sg: 'dretgs' },
  IMPERSONAL: { base: 'impersunal', fem: 'impersunala', masc_plural: 'impersunals', fem_plural: 'impersunalas', predicative_masc_sg: 'impersunals' },
  OTHER: { base: 'auter', fem: 'autra', masc_plural: 'auters', fem_plural: 'autras', predicative_masc_sg: 'auters', position: 'pre', after_pronoun: 'auter' },
  OPPOSITE: { base: 'contrari', fem: 'contraria', masc_plural: 'contraris', fem_plural: 'contrarias', predicative_masc_sg: 'contraris' },
  MAIN: { base: 'principal', fem: 'principala', masc_plural: 'principals', fem_plural: 'principalas', predicative_masc_sg: 'principals' },
  CONDITIONAL: { base: 'condiziunal', fem: 'condiziunala', masc_plural: 'condiziunals', fem_plural: 'condiziunalas', predicative_masc_sg: 'condiziunals' },
  COORDINATED: { base: 'coordinau', fem: 'coordinada', masc_plural: 'coordinai', fem_plural: 'coordinadas', predicative_masc_sg: 'coordinaus' },
  SUBORDINATE: { base: 'subordinau', fem: 'subordinada', masc_plural: 'subordinai', fem_plural: 'subordinadas', predicative_masc_sg: 'subordinaus' },
  COPULATIVE: { base: 'copulativ', fem: 'copulativa', masc_plural: 'copulativs', fem_plural: 'copulativas', predicative_masc_sg: 'copulativs' },
  DISJUNCTIVE: { base: 'disjunctiv', fem: 'disjunctiva', masc_plural: 'disjunctivs', fem_plural: 'disjunctivas', predicative_masc_sg: 'disjunctivs' },
  ADVERSATIVE: { base: 'adversativ', fem: 'adversativa', masc_plural: 'adversativs', fem_plural: 'adversativas', predicative_masc_sg: 'adversativs' },
  EXPLICATIVE: { base: 'explicativ', fem: 'explicativa', masc_plural: 'explicativs', fem_plural: 'explicativas', predicative_masc_sg: 'explicativs' },
  CONCLUSIVE: { base: 'conclusiv', fem: 'conclusiva', masc_plural: 'conclusivs', fem_plural: 'conclusivas', predicative_masc_sg: 'conclusivs' },
  TEMPORAL: { base: 'temporal', fem: 'temporala', masc_plural: 'temporals', fem_plural: 'temporalas', predicative_masc_sg: 'temporals' },
  SPATIAL: { base: 'spazial', fem: 'spaziala', masc_plural: 'spazials', fem_plural: 'spazialas', predicative_masc_sg: 'spazials' },
  NATIONAL: { base: 'naziunal', fem: 'naziunala', masc_plural: 'naziunals', fem_plural: 'naziunalas', predicative_masc_sg: 'naziunals' },
  SOCIAL: { base: 'social', fem: 'sociala', masc_plural: 'socials', fem_plural: 'socialas', predicative_masc_sg: 'socials' },
  POLITICAL: { base: 'politic', fem: 'politica', masc_plural: 'politics', fem_plural: 'politicas', predicative_masc_sg: 'politics' },
  PUBLIC: { base: 'public', fem: 'publica', masc_plural: 'publics', fem_plural: 'publicas', predicative_masc_sg: 'publics' },
  NEUTRAL: { base: 'neutral', fem: 'neutrala', masc_plural: 'neutrals', fem_plural: 'neutralas', predicative_masc_sg: 'neutrals' },
  ACTIVE_VOICE: { base: 'activ', fem: 'activa', masc_plural: 'activs', fem_plural: 'activas', predicative_masc_sg: 'activs' },
  PASSIVE: { base: 'passiv', fem: 'passiva', masc_plural: 'passivs', fem_plural: 'passivas', predicative_masc_sg: 'passivs' },
  HUMBLE_GRAMMAR: { base: 'humil', fem: 'humila', masc_plural: 'humils', fem_plural: 'humilas', predicative_masc_sg: 'humils' },
  PROGRESSIVE: { base: 'progressiv', fem: 'progressiva', masc_plural: 'progressivs', fem_plural: 'progressivas', predicative_masc_sg: 'progressivs' },
  PROSPECTIVE: { base: 'prospectiv', fem: 'prospectiva', masc_plural: 'prospectivs', fem_plural: 'prospectivas', predicative_masc_sg: 'prospectivs' },
  RESULTATIVE: { base: 'resultativ', fem: 'resultativa', masc_plural: 'resultativs', fem_plural: 'resultativas', predicative_masc_sg: 'resultativs' },
  POSITIVE: { base: 'positiv', fem: 'positiva', masc_plural: 'positivs', fem_plural: 'positivas', predicative_masc_sg: 'positivs' },
  SEMANTIC: { base: 'semantic', fem: 'semantica', masc_plural: 'semantics', fem_plural: 'semanticas', predicative_masc_sg: 'semantics' },
  DIRECT: { base: 'direct', fem: 'directa', masc_plural: 'directs', fem_plural: 'directas', predicative_masc_sg: 'directs' },
  INDIRECT: { base: 'indirect', fem: 'indirecta', masc_plural: 'indirects', fem_plural: 'indirectas', predicative_masc_sg: 'indirects' },
  UNCONNECTED: { base: 'nuncolliau', fem: 'nuncolliada', masc_plural: 'nuncolliai', fem_plural: 'nuncolliadas', predicative_masc_sg: 'nuncolliaus' },
  HIDDEN: { base: 'zuppau', fem: 'zuppada', masc_plural: 'zuppai', fem_plural: 'zuppadas', predicative_masc_sg: 'zuppaus' },
  CLOSED: { base: 'serrau', fem: 'serrada', masc_plural: 'serrai', fem_plural: 'serradas', predicative_masc_sg: 'serraus' },
  OPEN_ADJECTIVE: { base: 'aviert', fem: 'averta', masc_plural: 'averts', fem_plural: 'avertas', predicative_masc_sg: 'averts' },
  VISIBLE: { base: 'visibel', fem: 'visibla', masc_plural: 'visibels', fem_plural: 'visiblas', predicative_masc_sg: 'visibels' },
  SWEET: { base: 'dultsch', fem: 'dultscha', masc_plural: 'dultschs', fem_plural: 'dultschas', predicative_masc_sg: 'dultschs' },
  SOLID: { base: 'solid', fem: 'solida', masc_plural: 'solids', fem_plural: 'solidas', predicative_masc_sg: 'solids' },
  PRESENT: { base: 'present', fem: 'presenta', masc_plural: 'presents', fem_plural: 'presentas', predicative_masc_sg: 'presents' },
  PAST: { base: 'vargau', fem: 'vargada', masc_plural: 'vargai', fem_plural: 'vargadas', predicative_masc_sg: 'vargaus' },
  FUTURE: { base: 'futur', fem: 'futura', masc_plural: 'futurs', fem_plural: 'futuras', predicative_masc_sg: 'futurs' },
  OWN_ADJECTIVE: { base: 'agen', fem: 'atgna', masc_plural: 'agens', fem_plural: 'atgnas', predicative_masc_sg: 'agens', position: 'pre' },
  SOLE: { base: 'sulet', fem: 'suletta', masc_plural: 'sulets', fem_plural: 'sulettas', predicative_masc_sg: 'sulets', position: 'pre' },
  STANDARD: { base: 'standard', fem: 'standard', masc_plural: 'standard', fem_plural: 'standard', predicative_masc_sg: 'standard' },
  MANIFOLD: { base: 'multifar', fem: 'multifara', masc_plural: 'multifars', fem_plural: 'multifaras', predicative_masc_sg: 'multifars' },
};
