import type { LanguageColumn } from '../types.js';

// The nouns (P04-E5): base, plural where countable, gender and count, the feminine of a noun that has
// one, and the Italian entry's flags. The article (il, la, igl, l', ils, las) is the engine's, never
// stored. A gender that differs from Italian's says so. Every form is (verify) until P04-E19.
export const RM_SURSILV_NOUNS: LanguageColumn = {
  ANIMAL: { base: 'animal', plural: 'animals', gender: 'masc', count: 'singular' },
  MAMMAL: { base: 'mamifer', plural: 'mamifers', gender: 'masc', count: 'singular' },
  CAT: { base: 'gat', plural: 'gats', gender: 'masc', count: 'singular', fem: 'gatta', fem_plural: 'gattas' },
  DOG: { base: 'tgaun', plural: 'tgauns', gender: 'masc', count: 'singular', fem: 'tgaunina', fem_plural: 'tgauninas' },
  // plural utschals (verify)
  BIRD: { base: 'utschi', plural: 'utschals', gender: 'masc', count: 'singular' },
  FISH: { base: 'pesch', plural: 'peschs', gender: 'masc', count: 'singular' },
  REPTILE: { base: 'reptil', plural: 'reptils', gender: 'masc', count: 'singular' },
  AMPHIBIAN: { base: 'amfibi', plural: 'amfibis', gender: 'masc', count: 'singular' },
  INSECT: { base: 'insect', plural: 'insects', gender: 'masc', count: 'singular' },
  // plural cavals (verify)
  HORSE: { base: 'cavagl', plural: 'cavals', gender: 'masc', count: 'singular', fem: 'cavalla', fem_plural: 'cavallas' },
  PIG: { base: 'piertg', plural: 'piertgs', gender: 'masc', count: 'singular' },
  SHEEP: { base: 'nuorsa', plural: 'nuorsas', gender: 'fem', count: 'singular' },
  GOAT: { base: 'caura', plural: 'cauras', gender: 'fem', count: 'singular' },
  RABBIT: { base: 'cunigl', plural: 'cunigls', gender: 'masc', count: 'singular', fem: 'cuniglia', fem_plural: 'cuniglias' },
  BEAR: { base: 'urs', plural: 'urs', gender: 'masc', count: 'singular', fem: 'ursa', fem_plural: 'ursas' },
  LION: { base: 'liun', plural: 'liuns', gender: 'masc', count: 'singular', fem: 'liunessa', fem_plural: 'liunessas' },
  // masculine in Romansh (it la tigre)
  TIGER: { base: 'tiger', plural: 'tigers', gender: 'masc', count: 'singular' },
  // The felines, seeded on main while P04 was in flight; every form (verify).
  FELINE: { base: 'felin', plural: 'felins', gender: 'masc', count: 'singular' },
  LEOPARD: { base: 'leopard', plural: 'leopards', gender: 'masc', count: 'singular' },
  PANTHER: { base: 'pantera', plural: 'panteras', gender: 'fem', count: 'singular' },
  PUMA: { base: 'puma', plural: 'pumas', gender: 'masc', count: 'singular' },
  CHEETAH: { base: 'gepard', plural: 'gepards', gender: 'masc', count: 'singular' },
  ELEPHANT: { base: 'elefant', plural: 'elefants', gender: 'masc', count: 'singular', fem: 'elefanta', fem_plural: 'elefantas' },
  MONKEY: { base: 'schimgia', plural: 'schimgias', gender: 'fem', count: 'singular' },
  DEER: { base: 'tschierv', plural: 'tschiervs', gender: 'masc', count: 'singular' },
  WHALE: { base: 'balena', plural: 'balenas', gender: 'fem', count: 'singular' },
  CHICKEN: { base: 'gaglina', plural: 'gaglinas', gender: 'fem', count: 'singular' },
  DUCK: { base: 'anda', plural: 'andas', gender: 'fem', count: 'singular' },
  EAGLE: { base: 'evla', plural: 'evlas', gender: 'fem', count: 'singular' },
  // feminine (it il gufo)
  OWL: { base: 'tschuetta', plural: 'tschuettas', gender: 'fem', count: 'singular' },
  PENGUIN: { base: 'pinguin', plural: 'pinguins', gender: 'masc', count: 'singular' },
  SEAGULL: { base: 'muetta', plural: 'muettas', gender: 'fem', count: 'singular' },
  SWALLOW: { base: 'randulina', plural: 'randulinas', gender: 'fem', count: 'singular' },
  PARROT: { base: 'papagagl', plural: 'papagagls', gender: 'masc', count: 'singular' },
  SHARK: { base: 'squagl', plural: 'squagls', gender: 'masc', count: 'singular' },
  SALMON: { base: 'salm', plural: 'salms', gender: 'masc', count: 'singular' },
  SNAKE: { base: 'siarp', plural: 'siarps', gender: 'masc', count: 'singular' },
  TURTLE: { base: 'tartaruga', plural: 'tartarugas', gender: 'fem', count: 'singular' },
  CROCODILE: { base: 'crocodil', plural: 'crocodils', gender: 'masc', count: 'singular' },
  // masculine (it la lucertola)
  LIZARD: { base: 'luschard', plural: 'luschards', gender: 'masc', count: 'singular' },
  FROG: { base: 'rauna', plural: 'raunas', gender: 'fem', count: 'singular' },
  // masculine (it l'ape, f)
  BEE: { base: 'avieul', plural: 'avieuls', gender: 'masc', count: 'singular' },
  ANT: { base: 'furmicla', plural: 'furmiclas', gender: 'fem', count: 'singular' },
  BUTTERFLY: { base: 'tschitta', plural: 'tschittas', gender: 'fem', count: 'singular' },
  // masculine (it la zanzara)
  MOSQUITO: { base: 'mustgin', plural: 'mustgins', gender: 'masc', count: 'singular' },
  SPIDER: { base: 'filien', plural: 'filiens', gender: 'masc', count: 'singular' },
  BOOK: { base: 'cudisch', plural: 'cudischs', gender: 'masc', count: 'singular' },
  AIR: { base: 'aria', gender: 'fem', count: 'singular' },
  GROUND: { base: 'terren', plural: 'terrens', gender: 'masc', count: 'singular' },
  WATER: { base: 'aua', gender: 'fem', count: 'singular' },
  SPEED: { base: 'sveltezia', plural: 'sveltezias', gender: 'fem', count: 'singular' },
  LIGHT: { base: 'glisch', plural: 'glischs', gender: 'fem', count: 'singular' },
  SOUND: { base: 'tun', plural: 'tuns', gender: 'masc', count: 'singular' },
  // feminine (it il modo)
  WAY: { base: 'moda', plural: 'modas', gender: 'fem', count: 'singular' },
  TIME: { base: 'temps', plural: 'temps', gender: 'masc', count: 'singular' },
  CARE: { base: 'tgira', gender: 'fem', count: 'singular' },
  SIZE: { base: 'grondezia', plural: 'grondezias', gender: 'fem', count: 'singular' },
  HEIGHT: { base: 'altezia', plural: 'altezias', gender: 'fem', count: 'singular' },
  LENGTH: { base: 'lunghezia', plural: 'lunghezias', gender: 'fem', count: 'singular' },
  QUALITY: { base: 'qualitad', plural: 'qualitads', gender: 'fem', count: 'singular' },
  STRENGTH: { base: 'forza', plural: 'forzas', gender: 'fem', count: 'singular' },
  AGE: { base: 'vegliadetgna', plural: 'vegliadetgnas', gender: 'fem', count: 'singular' },
  TEMPERATURE: { base: 'temperatura', plural: 'temperaturas', gender: 'fem', count: 'singular' },
  DISTANCE: { base: 'distanza', plural: 'distanzas', gender: 'fem', count: 'singular' },
  SHAPE: { base: 'fuorma', plural: 'fuormas', gender: 'fem', count: 'singular' },
  CIRCLE: { base: 'rudi', plural: 'rudis', gender: 'masc', count: 'singular' },
  LINE_MARK: { base: 'lingia', plural: 'lingias', gender: 'fem', count: 'singular' },
  // a plural noun, ils daners, as it notizie is (count: plural)
  MONEY: { base: 'daners', gender: 'masc', count: 'plural' },
  // feminine (it il cibo)
  FOOD: { base: 'vivonda', gender: 'fem', count: 'singular' },
  ICE_CREAM: { base: 'glatscha', plural: 'glatschas', gender: 'fem', count: 'singular' },
  SUGAR: { base: 'zucher', gender: 'masc', count: 'singular' },
  LIQUID: { base: 'liquid', gender: 'masc', count: 'singular' },
  CONTENT: { base: 'cuntegn', plural: 'cuntegns', gender: 'masc', count: 'singular' },
  // plural lius (verify)
  PLACE: { base: 'liug', plural: 'lius', gender: 'masc', count: 'singular' },
  POINT_NOUN: { base: 'punct', plural: 'puncts', gender: 'masc', count: 'singular' },
  AREA: { base: 'zona', plural: 'zonas', gender: 'fem', count: 'singular' },
  CENTER: { base: 'center', plural: 'centers', gender: 'masc', count: 'singular' },
  // feminine (it il lato)
  SIDE: { base: 'vart', plural: 'varts', gender: 'fem', count: 'singular' },
  DESTINATION: { base: 'destinaziun', plural: 'destinaziuns', gender: 'fem', count: 'singular' },
  ORIGIN: { base: 'origin', plural: 'origins', gender: 'fem', count: 'singular' },
  PATH: { base: 'traject', plural: 'trajects', gender: 'masc', count: 'singular' },
  DIRECTION_SPACE: { base: 'direcziun', plural: 'direcziuns', gender: 'fem', count: 'singular' },
  BUILDING: { base: 'edifeci', plural: 'edificis', gender: 'masc', count: 'singular' },
  WALL: { base: 'mir', plural: 'mirs', gender: 'masc', count: 'singular' },
  HOUSE: { base: 'casa', plural: 'casas', gender: 'fem', count: 'singular' },
  HOME: { base: 'casa', plural: 'casas', gender: 'fem', count: 'singular' },
  ROOM: { base: 'stanza', plural: 'stanzas', gender: 'fem', count: 'singular' },
  OFFICE: { base: 'biro', plural: 'biros', gender: 'masc', count: 'singular' },
  // masculine (it la porta)
  DOOR: { base: 'isch', plural: 'ischs', gender: 'masc', count: 'singular' },
  // masculine (it la macchina)
  CAR: { base: 'auto', plural: 'autos', gender: 'masc', count: 'singular' },
  // affon is masculine only; a girl child is mattatscha (verify)
  CHILD: { base: 'affon', plural: 'affons', gender: 'masc', count: 'singular', fem: 'mattatscha', fem_plural: 'mattatschas' },
  KID: { base: 'mattatsch', plural: 'mattatschs', gender: 'masc', count: 'singular', fem: 'mattatscha', fem_plural: 'mattatschas' },
  PERSON: { base: 'persuna', plural: 'persunas', gender: 'fem', count: 'singular' },
  SPEAKER: { base: 'plidader', plural: 'plidaders', gender: 'masc', count: 'singular', fem: 'plidadra', fem_plural: 'plidadras' },
  COMPANION: { base: 'compogn', plural: 'compogns', gender: 'masc', count: 'singular', fem: 'compogna', fem_plural: 'compognas' },
  RECIPIENT: { base: 'destinatari', plural: 'destinataris', gender: 'masc', count: 'singular', fem: 'destinataria', fem_plural: 'destinatarias' },
  FOX: { base: 'uolp', plural: 'uolps', gender: 'fem', count: 'singular' },
  BOY: { base: 'buob', plural: 'buobs', gender: 'masc', count: 'singular' },
  GIRL: { base: 'matta', plural: 'mattas', gender: 'fem', count: 'singular' },
  MAN: { base: 'um', plural: 'umens', gender: 'masc', count: 'singular' },
  GUY: { base: 'tip', plural: 'tips', gender: 'masc', count: 'singular' },
  WOMAN: { base: 'dunna', plural: 'dunnas', gender: 'fem', count: 'singular' },
  WOLF: { base: 'luf', plural: 'lufs', gender: 'masc', count: 'singular', fem: 'lufa', fem_plural: 'lufas' },
  BOVINE: { base: 'bovin', plural: 'bovins', gender: 'masc', count: 'singular' },
  COW: { base: 'vacca', plural: 'vaccas', gender: 'fem', count: 'singular' },
  OX: { base: 'bov', plural: 'bovs', gender: 'masc', count: 'singular' },
  BUTCHER: { base: 'mazler', plural: 'mazlers', gender: 'masc', count: 'singular', fem: 'mazlera', fem_plural: 'mazleras' },
  ANGEL: { base: 'aunghel', plural: 'aunghels', gender: 'masc', count: 'singular' },
  LIFE: { base: 'veta', plural: 'vetas', gender: 'fem', count: 'singular' },
  END: { base: 'fin', plural: 'fins', gender: 'fem', count: 'singular' },
  // feminine (it l'inizio, m)
  BEGINNING: { base: 'entschatta', plural: 'entschattas', gender: 'fem', count: 'singular' },
  DEATH: { base: 'mort', plural: 'morts', gender: 'fem', count: 'singular' },
  FEELING: { base: 'sentiment', plural: 'sentiments', gender: 'masc', count: 'singular' },
  AFFECTION: { base: 'affecziun', gender: 'fem', count: 'singular' },
  // feminine (it il topo)
  MOUSE: { base: 'miur', plural: 'miurs', gender: 'fem', count: 'singular' },
  FLY_INSECT: { base: 'mustga', plural: 'mustgas', gender: 'fem', count: 'singular' },
  STICK: { base: 'bastun', plural: 'bastuns', gender: 'masc', count: 'singular' },
  ARROW_PROJECTILE: { base: 'frezza', plural: 'frezzas', gender: 'fem', count: 'singular' },
  BLADE: { base: 'lama', plural: 'lamas', gender: 'fem', count: 'singular' },
  FIRE: { base: 'fiug', plural: 'fiugs', gender: 'masc', count: 'singular' },
  FLAME: { base: 'flomma', plural: 'flommas', gender: 'fem', count: 'singular' },
  PARENT: { base: 'genitur', plural: 'geniturs', gender: 'masc', count: 'singular', fem: 'genitura', fem_plural: 'genituras' },
  FATHER: { base: 'bab', plural: 'babs', gender: 'masc', count: 'singular', kinship: '1' },
  RELATIVE: { base: 'parent', plural: 'parents', gender: 'masc', count: 'singular', fem: 'parenta', fem_plural: 'parentas' },
  FAMILY: { base: 'famiglia', plural: 'famiglias', gender: 'fem', count: 'singular' },
  MOTHER: { base: 'mumma', plural: 'mummas', gender: 'fem', count: 'singular', kinship: '1' },
  CHILD_OFFSPRING: { base: 'fegl', plural: 'fegls', gender: 'masc', count: 'singular', fem: 'feglia', fem_plural: 'feglias', kinship: '1' },
  SON: { base: 'fegl', plural: 'fegls', gender: 'masc', count: 'singular', kinship: '1' },
  DAUGHTER: { base: 'feglia', plural: 'feglias', gender: 'fem', count: 'singular', kinship: '1' },
  SIBLING: { base: 'frar', plural: 'frars', gender: 'masc', count: 'singular', fem: 'sora', fem_plural: 'soras', kinship: '1' },
  BROTHER: { base: 'frar', plural: 'frars', gender: 'masc', count: 'singular', kinship: '1' },
  SISTER: { base: 'sora', plural: 'soras', gender: 'fem', count: 'singular', kinship: '1' },
  SPOUSE: { base: 'consort', plural: 'consorts', gender: 'masc', count: 'singular', fem: 'consorta', fem_plural: 'consortas' },
  // miu um, my husband
  HUSBAND: { base: 'um', plural: 'umens', gender: 'masc', count: 'singular', kinship: '1' },
  // mia dunna, my wife
  WIFE: { base: 'dunna', plural: 'dunnas', gender: 'fem', count: 'singular', kinship: '1' },
  GRANDPARENT: { base: 'tat', plural: 'tats', gender: 'masc', count: 'singular', fem: 'tatta', fem_plural: 'tattas', kinship: '1' },
  GRANDFATHER: { base: 'tat', plural: 'tats', gender: 'masc', count: 'singular', kinship: '1' },
  GRANDMOTHER: { base: 'tatta', plural: 'tattas', gender: 'fem', count: 'singular', kinship: '1' },
  GRANDCHILD: { base: 'biadi', plural: 'biadis', gender: 'masc', count: 'singular', fem: 'biadia', fem_plural: 'biadias', kinship: '1' },
  GRANDSON: { base: 'biadi', plural: 'biadis', gender: 'masc', count: 'singular', kinship: '1' },
  GRANDDAUGHTER: { base: 'biadia', plural: 'biadias', gender: 'fem', count: 'singular', kinship: '1' },
  UNCLE: { base: 'aug', plural: 'augs', gender: 'masc', count: 'singular', kinship: '1' },
  AUNT: { base: 'onda', plural: 'ondas', gender: 'fem', count: 'singular', kinship: '1' },
  COUSIN: { base: 'cusrin', plural: 'cusrins', gender: 'masc', count: 'singular', fem: 'cusrina', fem_plural: 'cusrinas', kinship: '1' },
  NEPHEW: { base: 'nev', plural: 'nevs', gender: 'masc', count: 'singular', kinship: '1' },
  NIECE: { base: 'neiza', plural: 'neizas', gender: 'fem', count: 'singular', kinship: '1' },
  MOTHER_IN_LAW: { base: 'sira', plural: 'siras', gender: 'fem', count: 'singular', kinship: '1' },
  FATHER_IN_LAW: { base: 'sir', plural: 'sirs', gender: 'masc', count: 'singular', kinship: '1' },
  SON_IN_LAW: { base: 'schender', plural: 'schenders', gender: 'masc', count: 'singular', kinship: '1' },
  DAUGHTER_IN_LAW: { base: 'brit', plural: 'brits', gender: 'fem', count: 'singular', kinship: '1' },
  BROTHER_IN_LAW: { base: 'quinau', plural: 'quinai', gender: 'masc', count: 'singular', kinship: '1' },
  SISTER_IN_LAW: { base: 'quinada', plural: 'quinadas', gender: 'fem', count: 'singular', kinship: '1' },
  STEPFATHER: { base: 'padrester', plural: 'padresters', gender: 'masc', count: 'singular' },
  STEPMOTHER: { base: 'madrastra', plural: 'madrastras', gender: 'fem', count: 'singular' },
  MOM: { base: 'mamma', plural: 'mammas', gender: 'fem', count: 'singular' },
  DAD: { base: 'papa', plural: 'papas', gender: 'masc', count: 'singular' },
  PARTNER: { base: 'partenari', plural: 'partenaris', gender: 'masc', count: 'singular', fem: 'partenaria', fem_plural: 'partenarias' },
  BOYFRIEND: { base: 'amitg', plural: 'amitgs', gender: 'masc', count: 'singular' },
  GIRLFRIEND: { base: 'amitga', plural: 'amitgas', gender: 'fem', count: 'singular' },
  FIANCE: { base: 'spus', plural: 'spus', gender: 'masc', count: 'singular', fem: 'spusa', fem_plural: 'spusas' },
  FRIEND: { base: 'amitg', plural: 'amitgs', gender: 'masc', count: 'singular', fem: 'amitga', fem_plural: 'amitgas' },
  // feminine (it il mercato)
  MARKET: { base: 'fiera', plural: 'fieras', gender: 'fem', count: 'singular' },
  COIN: { base: 'muneida', plural: 'muneidas', gender: 'fem', count: 'singular' },
  LEGEND: { base: 'legenda', plural: 'legendas', gender: 'fem', count: 'singular' },
  WING: { base: 'ala', plural: 'alas', gender: 'fem', count: 'singular' },
  TOOTH: { base: 'dent', plural: 'dents', gender: 'masc', count: 'singular' },
  TEAR: { base: 'larma', plural: 'larmas', gender: 'fem', count: 'singular' },
  YOUNG_MAN: { base: 'giuven', plural: 'giuvens', gender: 'masc', count: 'singular' },
  YOUNG_WOMAN: { base: 'giuvna', plural: 'giuvnas', gender: 'fem', count: 'singular' },
  PRISON: { base: 'perschun', plural: 'perschuns', gender: 'fem', count: 'singular' },
  BUILDER: { base: 'constructur', plural: 'constructurs', gender: 'masc', count: 'singular', fem: 'constructura', fem_plural: 'constructuras' },
  // from scaffir, to create
  CREATOR: { base: 'scaffider', plural: 'scaffiders', gender: 'masc', count: 'singular', fem: 'scaffidra', fem_plural: 'scaffidras' },
  PHRASE: { base: 'frasa', plural: 'frasas', gender: 'fem', count: 'singular' },
  SLOT: { base: 'fessa', plural: 'fessas', gender: 'fem', count: 'singular' },
  SLOT_COMPUTING: { base: 'slot', plural: 'slots', gender: 'masc', count: 'singular' },
  SLOT_MACHINE: { base: 'maschina da gieu', plural: 'maschinas da gieu', gender: 'fem', count: 'singular' },
  // masculine (it la parola)
  WORD: { base: 'plaid', plural: 'plaids', gender: 'masc', count: 'singular' },
  MEANING: { base: 'muntada', plural: 'muntadas', gender: 'fem', count: 'singular' },
  FACT: { base: 'fatg', plural: 'fatgs', gender: 'masc', count: 'singular' },
  REASON: { base: 'motiv', plural: 'motivs', gender: 'masc', count: 'singular' },
  INFORMATION: { base: 'informaziun', gender: 'fem', count: 'singular' },
  PROBABILITY: { base: 'probabilitad', plural: 'probabilitads', gender: 'fem', count: 'singular' },
  TRANSLATION: { base: 'translaziun', plural: 'translaziuns', gender: 'fem', count: 'singular' },
  QUESTION: { base: 'damonda', plural: 'damondas', gender: 'fem', count: 'singular' },
  TELEPHONE: { base: 'telefon', plural: 'telefons', gender: 'masc', count: 'singular' },
  MIND: { base: 'spért', plural: 'spérts', gender: 'masc', count: 'singular' },
  CONTINENT: { base: 'continent', plural: 'continents', gender: 'masc', count: 'singular' },
  AFRICA: { base: 'Africa', gender: 'fem', count: 'singular' },
  PETER: { base: 'Pieder', gender: 'masc', count: 'singular', takes_article: '0' },
  MARY: { base: 'Maria', gender: 'fem', count: 'singular', takes_article: '0' },
  DIETH: { base: 'Dieth', gender: 'masc', count: 'singular', takes_article: '0' },
  MR: { base: 'signur', plural: 'signurs', gender: 'masc', count: 'singular', before_name: 'signur', takes_article: '1' },
  EUROPE: { base: 'Europa', gender: 'fem', count: 'singular' },
  ASIA: { base: 'Asia', gender: 'fem', count: 'singular' },
  OCEANIA: { base: 'Oceania', gender: 'fem', count: 'singular' },
  NORTH_AMERICA: { base: 'America dil Nord', gender: 'fem', count: 'singular' },
  SOUTH_AMERICA: { base: 'America dil Sid', gender: 'fem', count: 'singular' },
  ANTARCTICA: { base: 'Antarctica', gender: 'fem', count: 'singular' },
  // feminine (it il paese)
  COUNTRY: { base: 'tiara', plural: 'tiaras', gender: 'fem', count: 'singular' },
  // marcau, the town (verify against citad)
  CITY: { base: 'marcau', plural: 'marcaus', gender: 'masc', count: 'singular' },
  ENGLAND: { base: 'Engheltiara', gender: 'fem', count: 'singular' },
  ITALY: { base: 'Italia', gender: 'fem', count: 'singular' },
  FRANCE: { base: 'Frontscha', gender: 'fem', count: 'singular' },
  GERMANY: { base: 'Germania', gender: 'fem', count: 'singular' },
  SPAIN: { base: 'Spagna', gender: 'fem', count: 'singular' },
  JAPAN: { base: 'Giapun', gender: 'masc', count: 'singular' },
  PORTUGAL: { base: 'Portugal', gender: 'masc', count: 'singular' },
  // gender of a town name (verify)
  ZURICH: { base: 'Turitg', gender: 'masc', count: 'singular', takes_article: '0' },
  // masculine (it la lingua)
  LANGUAGE: { base: 'lungatg', plural: 'lungatgs', gender: 'masc', count: 'singular' },
  ENGLISH: { base: 'englais', gender: 'masc', count: 'singular' },
  ITALIAN: { base: 'talian', gender: 'masc', count: 'singular' },
  FRENCH: { base: 'franzos', gender: 'masc', count: 'singular' },
  GERMAN: { base: 'tudestg', gender: 'masc', count: 'singular' },
  SPANISH: { base: 'spagnol', gender: 'masc', count: 'singular' },
  JAPANESE: { base: 'giapunes', gender: 'masc', count: 'singular' },
  PORTUGUESE: { base: 'portughes', gender: 'masc', count: 'singular' },
  SWISS_GERMAN: { base: 'tudestg svizzer', gender: 'masc', count: 'singular' },
  // the Sursilvan name of the language (RG rumantsch)
  ROMANSH: { base: 'romontsch', gender: 'masc', count: 'singular' },
  CATALAN: { base: 'catalan', gender: 'masc', count: 'singular' },
  POLISH: { base: 'polac', gender: 'masc', count: 'singular' }, // (verify)
  LITHUANIAN: { base: 'lituan', gender: 'masc', count: 'singular' }, // (verify)
  RUMANTSCH_GRISCHUN: { base: 'rumantsch grischun', gender: 'masc', count: 'singular' },
  SURSILVAN: { base: 'sursilvan', gender: 'masc', count: 'singular' },
  VALLADER: { base: 'vallader', gender: 'masc', count: 'singular' },
  SPELLING: { base: 'ortografia', plural: 'ortografias', gender: 'fem', count: 'singular' },
  PERIOD_TIME: { base: 'perioda', plural: 'periodas', gender: 'fem', count: 'singular' },
  MOMENT: { base: 'mument', plural: 'muments', gender: 'masc', count: 'singular' },
  DAY: { base: 'di', plural: 'dis', gender: 'masc', count: 'singular', temporal_prep: 'en' },
  HOUR: { base: 'ura', plural: 'uras', gender: 'fem', count: 'singular' },
  MINUTE: { base: 'minuta', plural: 'minutas', gender: 'fem', count: 'singular' },
  MONTH: { base: 'meins', plural: 'meins', gender: 'masc', count: 'singular', temporal_prep: 'en' },
  WEEK: { base: 'jamna', plural: 'jamnas', gender: 'fem', count: 'singular', temporal_prep: 'en' },
  NIGHT: { base: 'notg', plural: 'notgs', gender: 'fem', count: 'singular' },
  MORNING: { base: 'damaun', plural: 'damauns', gender: 'fem', count: 'singular', temporal_bare: '1' },
  YEAR: { base: 'onn', plural: 'onns', gender: 'masc', count: 'singular', temporal_prep: 'en' },
  PARTICIPANT_GRAMMAR: { base: 'participont', plural: 'participonts', gender: 'masc', count: 'singular' },
  AGENT_GRAMMAR: { base: 'agent', plural: 'agents', gender: 'masc', count: 'singular' },
  SUBJECT_GRAMMAR: { base: 'subject', plural: 'subjects', gender: 'masc', count: 'singular' },
  VOCATIVE: { base: 'vocativ', plural: 'vocativs', gender: 'masc', count: 'singular' },
  OBJECT_GRAMMAR: { base: 'object', plural: 'objects', gender: 'masc', count: 'singular' },
  SUBJECT_COMPLEMENT: { base: 'cumplement predicativ dil subject', plural: 'cumplements predicativs dil subject', gender: 'masc', count: 'singular' },
  OBJECT_COMPLEMENT: { base: 'cumplement predicativ digl object', plural: 'cumplements predicativs digl object', gender: 'masc', count: 'singular' },
  INSTRUMENTAL: { base: 'cumplement dil med', plural: 'cumplements dil med', gender: 'masc', count: 'singular' },
  COMITATIVE: { base: 'cumplement da cumpignia', plural: 'cumplements da cumpignia', gender: 'masc', count: 'singular' },
  ADVERBIAL_OF_MANNER: { base: 'cumplement da moda', plural: 'cumplements da moda', gender: 'masc', count: 'singular' },
  COMPLEMENT_GRAMMAR: { base: 'cumplement', plural: 'cumplements', gender: 'masc', count: 'singular' },
  LOCATIVE: { base: 'cumplement da liug', plural: 'cumplements da liug', gender: 'masc', count: 'singular' },
  DIRECTION: { base: 'cumplement da direcziun', plural: 'cumplements da direcziun', gender: 'masc', count: 'singular' },
  SOURCE: { base: 'cumplement d\'origin', plural: 'cumplements d\'origin', gender: 'masc', count: 'singular' },
  ROUTE: { base: 'cumplement da traject', plural: 'cumplements da traject', gender: 'masc', count: 'singular' },
  CAUSE_COMPLEMENT: { base: 'cumplement da caschun', plural: 'cumplements da caschun', gender: 'masc', count: 'singular' },
  TEMPORAL_COMPLEMENT: { base: 'cumplement da temps', plural: 'cumplements da temps', gender: 'masc', count: 'singular' },
  PURPOSE_COMPLEMENT: { base: 'cumplement da finamira', plural: 'cumplements da finamira', gender: 'masc', count: 'singular' },
  OPPONENT_COMPLEMENT: { base: 'cumplement da disavantatg', plural: 'cumplements da disavantatg', gender: 'masc', count: 'singular' },
  TOPIC_COMPLEMENT: { base: 'cumplement da tema', plural: 'cumplements da tema', gender: 'masc', count: 'singular' },
  ROLE_COMPLEMENT: { base: 'cumplement da rolla', plural: 'cumplements da rolla', gender: 'masc', count: 'singular' },
  INTERJECTION: { base: 'interjecziun', plural: 'interjecziuns', gender: 'fem', count: 'singular' },
  TERMINUS: { base: 'cumplement da termin', plural: 'cumplements da termin', gender: 'masc', count: 'singular' },
  NOUN: { base: 'substantiv', plural: 'substantivs', gender: 'masc', count: 'singular' },
  PRONOUN: { base: 'pronom', plural: 'pronoms', gender: 'masc', count: 'singular' },
  VERB: { base: 'verb', plural: 'verbs', gender: 'masc', count: 'singular' },
  ADVERB: { base: 'adverb', plural: 'adverbs', gender: 'masc', count: 'singular' },
  ADJECTIVE: { base: 'adjectiv', plural: 'adjectivs', gender: 'masc', count: 'singular' },
  INFINITIVE_PHRASE: { base: 'frasa infinitiva', plural: 'frasas infinitivas', gender: 'fem', count: 'singular' },
  VERB_PHRASE: { base: 'sintagma verbal', plural: 'sintagmas verbals', gender: 'masc', count: 'singular' },
  NOUN_PHRASE: { base: 'sintagma nominal', plural: 'sintagmas nominals', gender: 'masc', count: 'singular' },
  CLAUSE: { base: 'proposiziun', plural: 'proposiziuns', gender: 'fem', count: 'singular' },
  RELATIVE_CLAUSE: { base: 'proposiziun relativa', plural: 'proposiziuns relativas', gender: 'fem', count: 'singular' },
  STATEMENT: { base: 'proposiziun enunciativa', plural: 'proposiziuns enunciativas', gender: 'fem', count: 'singular' },
  CONDITION: { base: 'condiziun', plural: 'condiziuns', gender: 'fem', count: 'singular' },
  COORDINATION: { base: 'coordinaziun', plural: 'coordinaziuns', gender: 'fem', count: 'singular' },
  CONJUNCT: { base: 'conjunct', plural: 'conjuncts', gender: 'masc', count: 'singular' },
  CONJUNCTION: { base: 'conjuncziun', plural: 'conjuncziuns', gender: 'fem', count: 'singular' },
  MODIFIER: { base: 'modificatur', plural: 'modificaturs', gender: 'masc', count: 'singular' },
  HYPERNYM: { base: 'hiperonim', plural: 'hiperonims', gender: 'masc', count: 'singular' },
  DETERMINER: { base: 'determinant', plural: 'determinants', gender: 'masc', count: 'singular' },
  ARTICLE: { base: 'artechel', plural: 'artechels', gender: 'masc', count: 'singular' },
  DEMONSTRATIVE: { base: 'demonstrativ', plural: 'demonstrativs', gender: 'masc', count: 'singular' },
  QUANTIFIER: { base: 'quantificatur', plural: 'quantificaturs', gender: 'masc', count: 'singular' },
  PERIOD_SENTENCE: { base: 'perioda', plural: 'periodas', gender: 'fem', count: 'singular' },
  PERIOD_PUNCTUATION: { base: 'punct', plural: 'puncts', gender: 'masc', count: 'singular' },
  BRACKET: { base: 'parentesa', plural: 'parentesas', gender: 'fem', count: 'singular' },
  CONTAINER: { base: 'recipient', plural: 'recipients', gender: 'masc', count: 'singular' },
  MAP: { base: 'carta', plural: 'cartas', gender: 'fem', count: 'singular' },
  NODE: { base: 'nuv', plural: 'nuvs', gender: 'masc', count: 'singular' },
  RELATIONSHIP: { base: 'relaziun', plural: 'relaziuns', gender: 'fem', count: 'singular' },
  PERSON_GRAMMAR: { base: 'persuna', plural: 'persunas', gender: 'fem', count: 'singular' },
  NUMBER: { base: 'numer', plural: 'numers', gender: 'masc', count: 'singular' },
  NUMBER_LABEL: { base: 'numer', plural: 'numers', gender: 'masc', count: 'singular' },
  QUANTITY: { base: 'quantitad', plural: 'quantitads', gender: 'fem', count: 'singular' },
  UNIT: { base: 'unitad', plural: 'unitads', gender: 'fem', count: 'singular' },
  PERCENT: { base: 'pertschien', plural: 'pertschien', gender: 'masc', count: 'singular' },
  CATEGORY: { base: 'categoria', plural: 'categorias', gender: 'fem', count: 'singular' },
  // feminine, la sort (it il tipo)
  KIND_SORT: { base: 'sort', plural: 'sorts', gender: 'fem', count: 'singular' },
  NUMBER_GRAMMAR: { base: 'numerus', plural: 'numerus', gender: 'masc', count: 'singular' },
  SINGULAR_GRAMMAR: { base: 'singular', plural: 'singulars', gender: 'masc', count: 'singular' },
  PLURAL_GRAMMAR: { base: 'plural', plural: 'plurals', gender: 'masc', count: 'singular' },
  CASE_GRAMMAR: { base: 'cass', plural: 'cass', gender: 'masc', count: 'singular' },
  DATIVE: { base: 'dativ', plural: 'dativs', gender: 'masc', count: 'singular' },
  GENITIVE: { base: 'genitiv', plural: 'genitivs', gender: 'masc', count: 'singular' },
  GENDER: { base: 'gener', plural: 'geners', gender: 'masc', count: 'singular' },
  TENSE: { base: 'temps', plural: 'temps', gender: 'masc', count: 'singular' },
  PRESENT_TENSE: { base: 'present', plural: 'presents', gender: 'masc', count: 'singular' },
  PAST_TENSE: { base: 'vargau', plural: 'vargai', gender: 'masc', count: 'singular' },
  FUTURE_TENSE: { base: 'futur', plural: 'futurs', gender: 'masc', count: 'singular' },
  ASPECT: { base: 'aspect', plural: 'aspects', gender: 'masc', count: 'singular' },
  VOICE: { base: 'diatesa', plural: 'diatesas', gender: 'fem', count: 'singular' },
  POLARITY: { base: 'polaritad', plural: 'polaritads', gender: 'fem', count: 'singular' },
  SENTIMENT: { base: 'valetaziun', plural: 'valetaziuns', gender: 'fem', count: 'singular' },
  MOOD: { base: 'modus', plural: 'modus', gender: 'masc', count: 'singular' },
  DEGREE_GRAMMAR: { base: 'grad', plural: 'grads', gender: 'masc', count: 'singular' },
  POSITIVE_DEGREE: { base: 'grad positiv', plural: 'grads positivs', gender: 'masc', count: 'singular' },
  STANDARD_OF_COMPARISON: { base: 'term da cumparegliaziun', plural: 'terms da cumparegliaziun', gender: 'masc', count: 'singular' },
  COMPARISON_SET: { base: 'gruppa da cumparegliaziun', plural: 'gruppas da cumparegliaziun', gender: 'fem', count: 'singular' },
  MODAL: { base: 'verb modal', plural: 'verbs modals', gender: 'masc', count: 'singular' },
  COMMAND: { base: 'cumond', plural: 'cumonds', gender: 'masc', count: 'singular' },
  ORDER: { base: 'ordinaziun', plural: 'ordinaziuns', gender: 'fem', count: 'singular' },
  INSTRUCTION: { base: 'instrucziun', plural: 'instrucziuns', gender: 'fem', count: 'singular' },
  REGISTER: { base: 'register', plural: 'registers', gender: 'masc', count: 'singular' },
  FORMALITY: { base: 'formalitad', gender: 'fem', count: 'singular' },
  OPTION: { base: 'opziun', plural: 'opziuns', gender: 'fem', count: 'singular' },
  BUTTON: { base: 'buttun', plural: 'buttuns', gender: 'masc', count: 'singular' },
  KEYBOARD: { base: 'tastatura', plural: 'tastaturas', gender: 'fem', count: 'singular' },
  // feminine (it il tasto)
  KEY: { base: 'tasta', plural: 'tastas', gender: 'fem', count: 'singular' },
  ARROW: { base: 'frezza', plural: 'frezzas', gender: 'fem', count: 'singular' },
  REGION: { base: 'regiun', plural: 'regiuns', gender: 'fem', count: 'singular' },
  // feminine (it il gruppo)
  GROUP: { base: 'gruppa', plural: 'gruppas', gender: 'fem', count: 'singular' },
  MEMBER: { base: 'commember', plural: 'commembers', gender: 'masc', count: 'singular' },
  PARTY_CELEBRATION: { base: 'fiasta', plural: 'fiastas', gender: 'fem', count: 'singular' },
  ROW: { base: 'lingia', plural: 'lingias', gender: 'fem', count: 'singular' },
  MENU: { base: 'menu', plural: 'menus', gender: 'masc', count: 'singular' },
  TAB: { base: 'tab', plural: 'tabs', gender: 'masc', count: 'singular' },
  TARGET: { base: 'destinaziun', plural: 'destinaziuns', gender: 'fem', count: 'singular' },
  HELP: { base: 'agid', gender: 'masc', count: 'singular' },
  NAVIGATION: { base: 'navigaziun', gender: 'fem', count: 'singular' },
  NAME_NOUN: { base: 'num', plural: 'nums', gender: 'masc', count: 'singular' },
  ALIAS: { base: 'alias', plural: 'alias', gender: 'masc', count: 'singular' },
  TITLE: { base: 'tetel', plural: 'tetels', gender: 'masc', count: 'singular' },
  LOADING: { base: 'cargament', gender: 'masc', count: 'singular' },
  INTERFACE: { base: 'interfatscha', plural: 'interfatschas', gender: 'fem', count: 'singular' },
  SERVER: { base: 'server', plural: 'servers', gender: 'masc', count: 'singular' },
  RESULT: { base: 'resultat', plural: 'resultats', gender: 'masc', count: 'singular' },
  IMPORT_NOUN: { base: 'import', plural: 'imports', gender: 'masc', count: 'singular' },
  ICON: { base: 'icona', plural: 'iconas', gender: 'fem', count: 'singular' },
  // feminine (it il file)
  FILE: { base: 'datoteca', plural: 'datotecas', gender: 'fem', count: 'singular' },
  CLIPBOARD: { base: 'memoria intermediara', plural: 'memorias intermediaras', gender: 'fem', count: 'singular' },
  LINE: { base: 'lingia', plural: 'lingias', gender: 'fem', count: 'singular' },
  HISTORY: { base: 'cronologia', gender: 'fem', count: 'singular' },
  WORKSPACE: { base: 'spazi da lavur', plural: 'spazis da lavur', gender: 'masc', count: 'singular' },
  USAGE: { base: 'diever', gender: 'masc', count: 'singular' },
  EXAMPLE: { base: 'exempel', plural: 'exempels', gender: 'masc', count: 'singular' },
  CONSOLE: { base: 'consola', plural: 'consolas', gender: 'fem', count: 'singular' },
  CANVAS: { base: 'tela', plural: 'telas', gender: 'fem', count: 'singular' },
  PREVIEW: { base: 'avantvesta', plural: 'avantvestas', gender: 'fem', count: 'singular' },
  TOOLBAR: { base: 'lingia d\'utensils', plural: 'lingias d\'utensils', gender: 'fem', count: 'singular' },
  LIST: { base: 'glista', plural: 'glistas', gender: 'fem', count: 'singular' },
  // feminine (it il valore)
  VALUE: { base: 'valur', plural: 'valurs', gender: 'fem', count: 'singular' },
  CURSOR: { base: 'cursur', plural: 'cursurs', gender: 'masc', count: 'singular' },
  TEXT: { base: 'text', plural: 'texts', gender: 'masc', count: 'singular' },
  REFERENCE: { base: 'referenza', plural: 'referenzas', gender: 'fem', count: 'singular' },
  CAUSE: { base: 'caschun', plural: 'caschuns', gender: 'fem', count: 'singular' },
  POSSESSOR: { base: 'possessur', plural: 'possessurs', gender: 'masc', count: 'singular', fem: 'possessura', fem_plural: 'possessuras' },
  PROPERTY: { base: 'possess', gender: 'masc', count: 'singular' },
  FEATURE: { base: 'caracteristica', plural: 'caracteristicas', gender: 'fem', count: 'singular' },
  DOMAIN: { base: 'domini', plural: 'dominis', gender: 'masc', count: 'singular' },
  MEANS: { base: 'med', plural: 'meds', gender: 'masc', count: 'singular' },
  PURPOSE: { base: 'finamira', plural: 'finamiras', gender: 'fem', count: 'singular' },
  USE_NOUN: { base: 'diever', plural: 'dievers', gender: 'masc', count: 'singular' },
  WORK_NOUN: { base: 'lavur', gender: 'fem', count: 'singular' },
  RESEARCH: { base: 'perscrutaziun', gender: 'fem', count: 'singular' },
  STUDY_NOUN: { base: 'studi', plural: 'studis', gender: 'masc', count: 'singular' },
  MATERIAL: { base: 'material', plural: 'materials', gender: 'masc', count: 'singular' },
  WOOD: { base: 'lenn', gender: 'masc', count: 'singular' },
  LEVEL: { base: 'nivel', plural: 'nivels', gender: 'masc', count: 'singular' },
  PROCESS: { base: 'process', plural: 'process', gender: 'masc', count: 'singular' },
  CHANGE_NOUN: { base: 'midada', plural: 'midadas', gender: 'fem', count: 'singular' },
  SYSTEM: { base: 'sistem', plural: 'sistems', gender: 'masc', count: 'singular' },
  PROGRAM_SOFTWARE: { base: 'program', plural: 'programs', gender: 'masc', count: 'singular' },
  PROGRAM_SHOW: { base: 'emissiun', plural: 'emissiuns', gender: 'fem', count: 'singular' },
  CONCEPT: { base: 'concept', plural: 'concepts', gender: 'masc', count: 'singular' },
  IDEA: { base: 'idea', plural: 'ideas', gender: 'fem', count: 'singular' },
  ACTION: { base: 'acziun', plural: 'acziuns', gender: 'fem', count: 'singular' },
  EVENT: { base: 'eveniment', plural: 'eveniments', gender: 'masc', count: 'singular' },
  RACE: { base: 'cursa', plural: 'cursas', gender: 'fem', count: 'singular' },
  GAME: { base: 'gieu', plural: 'gieus', gender: 'masc', count: 'singular' },
  OBJECT_THING: { base: 'object', plural: 'objects', gender: 'masc', count: 'singular' },
  DEVICE: { base: 'apparat', plural: 'apparats', gender: 'masc', count: 'singular' },
  BOMB: { base: 'bomba', plural: 'bombas', gender: 'fem', count: 'singular' },
  THING: { base: 'caussa', plural: 'caussas', gender: 'fem', count: 'singular' },
  PROBLEM: { base: 'problem', plural: 'problems', gender: 'masc', count: 'singular' },
  ISSUE: { base: 'questiun', plural: 'questiuns', gender: 'fem', count: 'singular' },
  CASE_INSTANCE: { base: 'cass', plural: 'cass', gender: 'masc', count: 'singular' },
  BEING: { base: 'esser', plural: 'essers', gender: 'masc', count: 'singular' },
  BODY: { base: 'tgierp', plural: 'tgierps', gender: 'masc', count: 'singular' },
  ORGAN: { base: 'organ', plural: 'organs', gender: 'masc', count: 'singular' },
  TESTICLE: { base: 'testichel', plural: 'testichels', gender: 'masc', count: 'singular' },
  OVARY: { base: 'ovari', plural: 'ovaris', gender: 'masc', count: 'singular' },
  MILK: { base: 'latg', gender: 'masc', count: 'singular' },
  GRASS: { base: 'jarva', gender: 'fem', count: 'singular' },
  HEAT: { base: 'calira', gender: 'fem', count: 'singular' },
  EYE: { base: 'egl', plural: 'egls', gender: 'masc', count: 'singular' },
  // masculine, il maun (it la mano)
  HAND: { base: 'maun', plural: 'mauns', gender: 'masc', count: 'singular' },
  // masculine (it la testa)
  HEAD: { base: 'tgau', plural: 'tgaus', gender: 'masc', count: 'singular' },
  FACE: { base: 'fatscha', plural: 'fatschas', gender: 'fem', count: 'singular' },
  BACK_BODY: { base: 'dies', plural: 'dies', gender: 'masc', count: 'singular' },
  HEALTH: { base: 'sanadad', gender: 'fem', count: 'singular' },
  STORY: { base: 'historia', plural: 'historias', gender: 'fem', count: 'singular' },
  HISTORY_PAST: { base: 'historia', gender: 'fem', count: 'singular' },
  NEWS: { base: 'novitads', gender: 'fem', count: 'plural' },
  SUBSTANCE: { base: 'substanza', gender: 'fem', count: 'singular' },
  STATE: { base: 'stadi', plural: 'stadis', gender: 'masc', count: 'singular' },
  GAS: { base: 'gas', gender: 'masc', count: 'singular' },
  JOY: { base: 'legria', gender: 'fem', count: 'singular' },
  SORROW: { base: 'tristezia', gender: 'fem', count: 'singular' },
  ERROR: { base: 'sbagl', plural: 'sbagls', gender: 'masc', count: 'singular' },
  REALITY: { base: 'realitad', plural: 'realitads', gender: 'fem', count: 'singular' },
  REST: { base: 'ruaus', gender: 'masc', count: 'singular' },
  ATTENTION: { base: 'attenziun', gender: 'fem', count: 'singular' },
  ABILITY: { base: 'capacitad', plural: 'capacitads', gender: 'fem', count: 'singular' },
  DUTY: { base: 'obligaziun', plural: 'obligaziuns', gender: 'fem', count: 'singular' },
  KINDNESS: { base: 'amabladad', gender: 'fem', count: 'singular' },
  WISDOM: { base: 'sabientscha', gender: 'fem', count: 'singular' },
  FOLLY: { base: 'narradad', gender: 'fem', count: 'singular' },
  LAND: { base: 'tiara', gender: 'fem', count: 'singular' },
  NATION: { base: 'naziun', plural: 'naziuns', gender: 'fem', count: 'singular' },
  SCHOOL: { base: 'scola', plural: 'scolas', gender: 'fem', count: 'singular' },
  STUDENT: { base: 'student', plural: 'students', gender: 'masc', count: 'singular', fem: 'studenta', fem_plural: 'studentas' },
  COMPANY_BUSINESS: { base: 'interpresa', plural: 'interpresas', gender: 'fem', count: 'singular' },
  TEAM: { base: 'equipa', plural: 'equipas', gender: 'fem', count: 'singular' },
  COMMUNITY: { base: 'cuminonza', plural: 'cuminonzas', gender: 'fem', count: 'singular' },
  UNIVERSITY: { base: 'universitad', plural: 'universitads', gender: 'fem', count: 'singular' },
  SERVICE: { base: 'survetsch', plural: 'survetschs', gender: 'masc', count: 'singular' },
  BUSINESS: { base: 'commerzi', gender: 'masc', count: 'singular' },
  STATE_NATION: { base: 'stadi', plural: 'stadis', gender: 'masc', count: 'singular' },
  POWER: { base: 'pussonza', plural: 'pussonzas', gender: 'fem', count: 'singular' },
  GOVERNMENT: { base: 'regenza', plural: 'regenzas', gender: 'fem', count: 'singular' },
  PARTY_POLITICAL: { base: 'partida', plural: 'partidas', gender: 'fem', count: 'singular' },
  LAW: { base: 'lescha', plural: 'leschas', gender: 'fem', count: 'singular' },
  COURT_LAW: { base: 'dretgira', plural: 'dretgiras', gender: 'fem', count: 'singular' },
  RIGHT_NOUN: { base: 'dretg', plural: 'dretgs', gender: 'masc', count: 'singular' },
  WAR: { base: 'uiara', plural: 'uiaras', gender: 'fem', count: 'singular' },
  WORLD: { base: 'mund', plural: 'munds', gender: 'masc', count: 'singular' },
  PICTURE: { base: 'maletg', plural: 'maletgs', gender: 'masc', count: 'singular' },
  SCREEN: { base: 'monitur', plural: 'moniturs', gender: 'masc', count: 'singular' },
  PART: { base: 'part', plural: 'parts', gender: 'fem', count: 'singular' },
};
