import type { LanguageColumn } from '../types.js';

// The nouns, keyed as Spanish's are (style-ca.md): `base`, `plural` where the noun counts, `gender`,
// `count`, and `fem`/`fem_plural` for a person or animal that has a feminine. The plural follows the
// spelling: *-a → -es* (*casa, cases*; *-ca → -ques*, *-ga → -gues*, *-ja → -ges*, *-gua → -gües*),
// a stressed vowel takes *-ns* (*ratolí, ratolins*), a sibilant *-os* (*peix, peixos*). *l', d'* before
// a vowel are the engine's, never stored; `no_elision` marks a feminine noun in unstressed *i-, u-,
// hi-, hu-* that keeps a whole *la* (*la universitat*). Language names are lowercase. Spanish's
// `stressed_a` (*el agua*) is dropped: Catalan has no such rule (*l'aigua*, *l'àguila*). Every form is
// (verify) until the native review (P03-E11); the marked ones are the choices most worth a second look.
type Forms = Record<string, string>;
const noun = (gender: 'masc' | 'fem', base: string, plural?: string, extra: Forms = {}): Forms => ({
  base, ...(plural === undefined ? {} : { plural }), gender, count: 'singular', ...extra,
});
const m = (base: string, plural?: string, extra?: Forms) => noun('masc', base, plural, extra);
const f = (base: string, plural?: string, extra?: Forms) => noun('fem', base, plural, extra);
/** A person or animal noun with its feminine. */
const mf = (base: string, plural: string, fem: string, fem_plural: string, extra: Forms = {}) =>
  m(base, plural, { fem, fem_plural, ...extra });
/** A feminine noun in unstressed *i-, u-, hi-, hu-*: *la universitat*, not *l'universitat*. */
const NO_ELISION = { no_elision: '1' };
/** A language name or proper noun that takes the article, as Spanish's does (*el català*). */
const ART = { takes_article: '1' };
/** A complement name of the grammar: *complement circumstancial de lloc*. */
const cc = (of: string) => m(`complement circumstancial ${of}`, `complements circumstancials ${of}`);

export const CA_NOUNS: LanguageColumn = {
  // Animals.
  ANIMAL: m('animal', 'animals'),
  MAMMAL: m('mamífer', 'mamífers'),
  FELINE: m('felí', 'felins'),
  CAT: mf('gat', 'gats', 'gata', 'gates'),
  DOG: mf('gos', 'gossos', 'gossa', 'gosses'),
  BIRD: m('ocell', 'ocells'),
  FISH: m('peix', 'peixos'),
  REPTILE: m('rèptil', 'rèptils'),
  AMPHIBIAN: m('amfibi', 'amfibis'),
  INSECT: m('insecte', 'insectes'),
  HORSE: mf('cavall', 'cavalls', 'euga', 'egües'),
  PIG: mf('porc', 'porcs', 'truja', 'truges'), // (verify) truja or porca for the sow
  SHEEP: f('ovella', 'ovelles'),
  GOAT: f('cabra', 'cabres'),
  RABBIT: mf('conill', 'conills', 'conilla', 'conilles'),
  // *os* without the accent since the 2017 reform, as the bone.
  BEAR: mf('os', 'ossos', 'ossa', 'osses'), // (verify)
  LION: mf('lleó', 'lleons', 'lleona', 'lleones'),
  TIGER: mf('tigre', 'tigres', 'tigressa', 'tigresses'),
  LEOPARD: mf('lleopard', 'lleopards', 'lleoparda', 'lleopardes'), // (verify) fem
  PANTHER: f('pantera', 'panteres'),
  PUMA: m('puma', 'pumes'),
  CHEETAH: m('guepard', 'guepards'),
  ELEPHANT: mf('elefant', 'elefants', 'elefanta', 'elefantes'),
  MONKEY: mf('mico', 'micos', 'mona', 'mones'), // (verify)
  DEER: mf('cérvol', 'cérvols', 'cérvola', 'cérvoles'), // (verify) fem
  WHALE: f('balena', 'balenes'),
  CHICKEN: f('gallina', 'gallines'),
  DUCK: mf('ànec', 'ànecs', 'ànega', 'ànegues'),
  EAGLE: f('àguila', 'àguiles'),
  OWL: m('mussol', 'mussols'),
  PENGUIN: m('pingüí', 'pingüins'),
  SEAGULL: f('gavina', 'gavines'),
  SWALLOW: f('oreneta', 'orenetes'),
  PARROT: m('lloro', 'lloros'),
  SHARK: m('tauró', 'taurons'),
  SALMON: m('salmó', 'salmons'),
  SNAKE: f('serp', 'serps'),
  TURTLE: f('tortuga', 'tortugues'),
  CROCODILE: m('cocodril', 'cocodrils'),
  LIZARD: m('llangardaix', 'llangardaixos'),
  FROG: f('granota', 'granotes'),
  BEE: f('abella', 'abelles'),
  ANT: f('formiga', 'formigues'),
  BUTTERFLY: f('papallona', 'papallones'),
  MOSQUITO: m('mosquit', 'mosquits'),
  SPIDER: f('aranya', 'aranyes'),

  // Things, substances and measures.
  BOOK: m('llibre', 'llibres'),
  AIR: m('aire'),
  GROUND: m('sòl', 'sòls'),
  WATER: f('aigua'),
  SPEED: f('velocitat', 'velocitats'),
  LIGHT: f('llum', 'llums'),
  SOUND: m('so', 'sons'),
  WAY: f('manera', 'maneres'),
  TIME: m('temps', 'temps'),
  CARE: f('cura'),
  SIZE: f('mida', 'mides'),
  HEIGHT: f('alçada', 'alçades'),
  LENGTH: f('longitud', 'longituds'),
  QUALITY: f('qualitat', 'qualitats'),
  STRENGTH: f('força', 'forces'),
  AGE: f('edat', 'edats'),
  TEMPERATURE: f('temperatura', 'temperatures'),
  DISTANCE: f('distància', 'distàncies'),
  SHAPE: f('forma', 'formes'),
  CIRCLE: m('cercle', 'cercles'),
  LINE_MARK: f('línia', 'línies'),
  // *els diners*: a plural-only noun, as Spanish stores *las noticias* (NEWS).
  MONEY: m('diners', undefined, { count: 'plural' }), // (verify)
  FOOD: m('menjar'),
  ICE_CREAM: m('gelat', 'gelats'),
  SUGAR: m('sucre'),
  LIQUID: m('líquid'),
  CONTENT: m('contingut', 'continguts'),

  // Places.
  PLACE: m('lloc', 'llocs'),
  POINT_NOUN: m('punt', 'punts'),
  AREA: f('zona', 'zones'),
  CENTER: m('centre', 'centres'),
  SIDE: m('costat', 'costats'),
  DESTINATION: f('destinació', 'destinacions'),
  ORIGIN: m('origen', 'orígens'),
  PATH: m('recorregut', 'recorreguts'),
  DIRECTION_SPACE: f('direcció', 'direccions'),
  BUILDING: m('edifici', 'edificis'),
  WALL: f('paret', 'parets'),
  HOUSE: f('casa', 'cases'),
  HOME: f('llar', 'llars'),
  ROOM: f('habitació', 'habitacions'),
  OFFICE: f('oficina', 'oficines'),
  DOOR: f('porta', 'portes'),
  CAR: m('cotxe', 'cotxes'),

  // People.
  CHILD: mf('nen', 'nens', 'nena', 'nenes'),
  KID: mf('nano', 'nanos', 'nana', 'nanes'), // (verify) casual register
  PERSON: f('persona', 'persones'),
  SPEAKER: mf('parlant', 'parlants', 'parlant', 'parlants'),
  COMPANION: mf('company', 'companys', 'companya', 'companyes'),
  RECIPIENT: mf('destinatari', 'destinataris', 'destinatària', 'destinatàries'),
  // Feminine for the species (*la guineu*), one form for either sex.
  FOX: f('guineu', 'guineus', { fem: 'guineu', fem_plural: 'guineus' }),
  BOY: m('nen', 'nens'),
  GIRL: f('nena', 'nenes'),
  MAN: m('home', 'homes'),
  GUY: m('paio', 'paios'), // (verify) casual register
  WOMAN: f('dona', 'dones'),
  WOLF: mf('llop', 'llops', 'lloba', 'llobes'),
  BOVINE: m('boví', 'bovins'),
  COW: f('vaca', 'vaques'),
  OX: m('bou', 'bous'),
  BUTCHER: mf('carnisser', 'carnissers', 'carnissera', 'carnisseres'),
  ANGEL: m('àngel', 'àngels'),

  // Life and feeling.
  LIFE: f('vida', 'vides'),
  // *la fi* (the end), feminine; *el fi* is the purpose.
  END: f('fi', 'fins'),
  BEGINNING: m('començament', 'començaments'),
  DEATH: f('mort', 'morts'),
  FEELING: m('sentiment', 'sentiments'),
  AFFECTION: m('afecte'),
  MOUSE: m('ratolí', 'ratolins'),
  FLY_INSECT: f('mosca', 'mosques'),
  STICK: m('pal', 'pals'),
  ARROW_PROJECTILE: f('fletxa', 'fletxes'),
  BLADE: f('fulla', 'fulles'),
  FIRE: m('foc', 'focs'),
  FLAME: f('flama', 'flames'),

  // Kinship. PARENT mirrors Spanish: *progenitor* in the singular, *pares* in the plural.
  PARENT: mf('progenitor', 'pares', 'progenitora', 'progenitores'),
  FATHER: m('pare', 'pares'),
  RELATIVE: mf('parent', 'parents', 'parenta', 'parentes'),
  FAMILY: f('família', 'famílies'),
  MOTHER: f('mare', 'mares'),
  CHILD_OFFSPRING: mf('fill', 'fills', 'filla', 'filles'),
  SON: m('fill', 'fills'),
  DAUGHTER: f('filla', 'filles'),
  SIBLING: mf('germà', 'germans', 'germana', 'germanes'),
  BROTHER: m('germà', 'germans'),
  SISTER: f('germana', 'germanes'),
  SPOUSE: mf('cònjuge', 'cònjuges', 'cònjuge', 'cònjuges'),
  HUSBAND: m('marit', 'marits'),
  WIFE: f('esposa', 'esposes'),
  GRANDPARENT: mf('avi', 'avis', 'àvia', 'àvies'),
  GRANDFATHER: m('avi', 'avis'),
  GRANDMOTHER: f('àvia', 'àvies'),
  // *net* without the accent since the 2017 reform.
  GRANDCHILD: mf('net', 'nets', 'neta', 'netes'),
  GRANDSON: m('net', 'nets'),
  GRANDDAUGHTER: f('neta', 'netes'),
  UNCLE: m('oncle', 'oncles'),
  AUNT: f('tia', 'ties'),
  COUSIN: mf('cosí', 'cosins', 'cosina', 'cosines'),
  NEPHEW: m('nebot', 'nebots'),
  NIECE: f('neboda', 'nebodes'),
  MOTHER_IN_LAW: f('sogra', 'sogres'),
  FATHER_IN_LAW: m('sogre', 'sogres'),
  SON_IN_LAW: m('gendre', 'gendres'),
  DAUGHTER_IN_LAW: f('nora', 'nores'),
  BROTHER_IN_LAW: m('cunyat', 'cunyats'),
  SISTER_IN_LAW: f('cunyada', 'cunyades'),
  STEPFATHER: m('padrastre', 'padrastres'),
  STEPMOTHER: f('madrastra', 'madrastres'),
  MOM: f('mama', 'mames', { as_name: '1' }),
  DAD: m('papa', 'papes', { as_name: '1' }),
  PARTNER: f('parella', 'parelles'),
  BOYFRIEND: m('xicot', 'xicots'),
  GIRLFRIEND: f('xicota', 'xicotes'),
  FIANCE: mf('promès', 'promesos', 'promesa', 'promeses'),
  FRIEND: mf('amic', 'amics', 'amiga', 'amigues'),

  MARKET: m('mercat', 'mercats'),
  COIN: f('moneda', 'monedes'),
  LEGEND: f('llegenda', 'llegendes'),
  WING: f('ala', 'ales'),
  TOOTH: f('dent', 'dents'),
  TEAR: f('llàgrima', 'llàgrimes'),
  YOUNG_MAN: m('jove', 'joves'),
  YOUNG_WOMAN: f('jove', 'joves'),
  PRISON: f('presó', 'presons'),
  BUILDER: mf('constructor', 'constructors', 'constructora', 'constructores'),
  CREATOR: mf('creador', 'creadors', 'creadora', 'creadores'),

  // Language and knowledge.
  PHRASE: f('frase', 'frases'),
  SLOT: f('ranura', 'ranures'),
  SLOT_COMPUTING: m('slot', 'slots'), // (verify) the loanword, as Spanish keeps it
  SLOT_MACHINE: f('màquina escurabutxaques', 'màquines escurabutxaques'),
  WORD: f('paraula', 'paraules'),
  MEANING: m('significat', 'significats'),
  FACT: m('fet', 'fets'),
  REASON: f('raó', 'raons'),
  INFORMATION: f('informació', undefined, NO_ELISION),
  PROBABILITY: f('probabilitat', 'probabilitats'),
  TRANSLATION: f('traducció', 'traduccions'),
  QUESTION: f('pregunta', 'preguntes'),
  TELEPHONE: m('telèfon', 'telèfons'),
  MIND: f('ment', 'ments'),

  // Continents, names, countries and cities. Catalan gives *l'Àfrica, l'Àsia, l'Amèrica* and *el
  // Japó* the article where Spanish gives none (verify with the engine's reading of `takes_article`).
  CONTINENT: m('continent', 'continents'),
  AFRICA: f('Àfrica', undefined, ART), // (verify) article
  PETER: m('Pere'),
  MARY: f('Maria'),
  DIETH: m('Dieth'),
  MR: m('senyor', 'senyors', ART),
  EUROPE: f('Europa'),
  ASIA: f('Àsia', undefined, ART), // (verify) article
  OCEANIA: f('Oceania'),
  NORTH_AMERICA: f('Amèrica del Nord', undefined, ART), // (verify) article
  SOUTH_AMERICA: f('Amèrica del Sud', undefined, ART), // (verify) article
  ANTARCTICA: f('Antàrtida', undefined, ART),
  COUNTRY: m('país', 'països'),
  CITY: f('ciutat', 'ciutats'),
  ENGLAND: f('Anglaterra'),
  ITALY: f('Itàlia'),
  FRANCE: f('França'),
  GERMANY: f('Alemanya'),
  SPAIN: f('Espanya'),
  JAPAN: m('Japó', undefined, ART), // (verify) article
  PORTUGAL: m('Portugal'),
  // *Zúric*, stressed on the first syllable, so written with the accent.
  ZURICH: m('Zúric'), // (verify)

  // Languages, lowercase, with the article (*el català*).
  LANGUAGE: f('llengua', 'llengües'),
  ENGLISH: m('anglès', undefined, ART),
  ITALIAN: m('italià', undefined, ART),
  FRENCH: m('francès', undefined, ART),
  GERMAN: m('alemany', undefined, ART),
  SPANISH: m('espanyol', undefined, ART),
  JAPANESE: m('japonès', undefined, ART),
  PORTUGUESE: m('portuguès', undefined, ART),
  SWISS_GERMAN: m('alemany suís', undefined, ART),
  ROMANSH: m('romanx', undefined, ART),
  RUMANTSCH_GRISCHUN: m('rumantsch grischun', undefined, ART),
  SURSILVAN: m('sursilvà', undefined, ART), // (verify)
  VALLADER: m('vallader', undefined, ART),
  CATALAN: m('català', undefined, ART),
  POLISH: m('polonès', undefined, ART),
  SPELLING: f('ortografia', 'ortografies'),

  // Time.
  PERIOD_TIME: m('període', 'períodes'),
  MOMENT: m('moment', 'moments'),
  DAY: m('dia', 'dies'),
  HOUR: f('hora', 'hores'),
  MINUTE: m('minut', 'minuts'),
  MONTH: m('mes', 'mesos'),
  WEEK: f('setmana', 'setmanes'),
  NIGHT: f('nit', 'nits'),
  MORNING: m('matí', 'matins'),
  YEAR: m('any', 'anys'),

  // The grammar's own terms, as Catalan school grammar names them.
  PARTICIPANT_GRAMMAR: m('participant', 'participants'),
  AGENT_GRAMMAR: m('agent', 'agents'),
  SUBJECT_GRAMMAR: m('subjecte', 'subjectes'),
  VOCATIVE: m('vocatiu', 'vocatius'),
  OBJECT_GRAMMAR: m('complement directe', 'complements directes'), // (verify) Spanish has bare complemento
  SUBJECT_COMPLEMENT: m('atribut', 'atributs'),
  OBJECT_COMPLEMENT: m("complement predicatiu de l'objecte", "complements predicatius de l'objecte"), // (verify)
  INSTRUMENTAL: cc("d'instrument"),
  COMITATIVE: cc('de companyia'),
  ADVERBIAL_OF_MANNER: cc('de manera'),
  COMPLEMENT_GRAMMAR: m('complement', 'complements'),
  LOCATIVE: cc('de lloc'),
  DIRECTION: cc('de direcció'),
  SOURCE: cc('de procedència'),
  ROUTE: cc('de trajecte'),
  CAUSE_COMPLEMENT: cc('de causa'),
  TEMPORAL_COMPLEMENT: cc('de temps'),
  PURPOSE_COMPLEMENT: cc('de finalitat'),
  OPPONENT_COMPLEMENT: cc("d'oposició"),
  TOPIC_COMPLEMENT: cc('de tema'),
  ROLE_COMPLEMENT: cc('de funció'),
  INTERJECTION: f('interjecció', 'interjeccions', NO_ELISION),
  TERMINUS: m('complement indirecte', 'complements indirectes'),
  NOUN: m('substantiu', 'substantius'),
  PRONOUN: m('pronom', 'pronoms'),
  VERB: m('verb', 'verbs'),
  ADVERB: m('adverbi', 'adverbis'),
  ADJECTIVE: m('adjectiu', 'adjectius'),
  INFINITIVE_PHRASE: f("oració d'infinitiu", "oracions d'infinitiu"), // (verify)
  VERB_PHRASE: m('sintagma verbal', 'sintagmes verbals'),
  NOUN_PHRASE: m('sintagma nominal', 'sintagmes nominals'),
  CLAUSE: f('oració', 'oracions'),
  RELATIVE_CLAUSE: f('oració de relatiu', 'oracions de relatiu'),
  STATEMENT: f('oració enunciativa', 'oracions enunciatives'),
  CONDITION: f('condició', 'condicions'),
  COORDINATION: f('coordinació', 'coordinacions'),
  CONJUNCT: m('membre coordinat', 'membres coordinats'),
  CONJUNCTION: f('conjunció', 'conjuncions'),
  MODIFIER: m('modificador', 'modificadors'),
  HYPERNYM: m('hiperònim', 'hiperònims'),
  DETERMINER: m('determinant', 'determinants'),
  ARTICLE: m('article', 'articles'),
  DEMONSTRATIVE: m('demostratiu', 'demostratius'),
  QUANTIFIER: m('quantificador', 'quantificadors'),
  PERIOD_SENTENCE: m('període', 'períodes'),
  PERIOD_PUNCTUATION: m('punt', 'punts'),
  BRACKET: m('parèntesi', 'parèntesis'),
  CONTAINER: m('recipient', 'recipients'),
  MAP: m('mapa', 'mapes'),
  NODE: m('node', 'nodes'),
  RELATIONSHIP: f('relació', 'relacions'),
  PERSON_GRAMMAR: f('persona', 'persones'),
  // The IEC tells the value (*nombre*) from the label (*número*), where Spanish has *número* for both.
  NUMBER: m('nombre', 'nombres'),
  NUMBER_LABEL: m('número', 'números'),
  QUANTITY: f('quantitat', 'quantitats'),
  UNIT: f('unitat', 'unitats', NO_ELISION),
  PERCENT: m('per cent', 'per cent'),
  CATEGORY: f('categoria', 'categories'),
  KIND_SORT: m('tipus', 'tipus'),
  NUMBER_GRAMMAR: m('nombre', 'nombres'),
  SINGULAR_GRAMMAR: m('singular', 'singulars'),
  PLURAL_GRAMMAR: m('plural', 'plurals'),
  CASE_GRAMMAR: m('cas', 'casos'),
  DATIVE: m('datiu', 'datius'),
  GENITIVE: m('genitiu', 'genitius'),
  GENDER: m('gènere', 'gèneres'),
  TENSE: m('temps', 'temps'),
  PRESENT_TENSE: m('present', 'presents'),
  PAST_TENSE: m('passat', 'passats'),
  FUTURE_TENSE: m('futur', 'futurs'),
  ASPECT: m('aspecte', 'aspectes'),
  VOICE: f('veu', 'veus'),
  POLARITY: f('polaritat', 'polaritats'),
  SENTIMENT: f('valoració', 'valoracions'),
  MOOD: m('mode', 'modes'),
  DEGREE_GRAMMAR: m('grau', 'graus'),
  POSITIVE_DEGREE: m('grau positiu', 'graus positius'),
  STANDARD_OF_COMPARISON: m('terme de comparació', 'termes de comparació'),
  COMPARISON_SET: m('conjunt de comparació', 'conjunts de comparació'),
  MODAL: m('verb modal', 'verbs modals'),

  // The interface.
  // *ordre* (feminine) is TERMCAT's word for a typed command, and the everyday one for an order.
  COMMAND: f('ordre', 'ordres'), // (verify)
  ORDER: f('ordre', 'ordres'),
  INSTRUCTION: f('instrucció', 'instruccions', NO_ELISION),
  REGISTER: m('registre', 'registres'),
  FORMALITY: f('formalitat'),
  OPTION: f('opció', 'opcions'),
  BUTTON: m('botó', 'botons'),
  KEYBOARD: m('teclat', 'teclats'),
  KEY: f('tecla', 'tecles'),
  ARROW: f('fletxa', 'fletxes'),
  REGION: f('zona', 'zones'),
  GROUP: m('grup', 'grups'),
  MEMBER: m('membre', 'membres'),
  PARTY_CELEBRATION: f('festa', 'festes'),
  ROW: f('fila', 'files'),
  MENU: m('menú', 'menús'),
  TAB: f('pestanya', 'pestanyes'),
  TARGET: f('destinació', 'destinacions'),
  HELP: f('ajuda'),
  NAVIGATION: f('navegació'),
  NAME_NOUN: m('nom', 'noms'),
  ALIAS: m('àlies', 'àlies'),
  TITLE: m('títol', 'títols'),
  LOADING: f('càrrega'),
  INTERFACE: f('interfície', 'interfícies', NO_ELISION),
  SERVER: m('servidor', 'servidors'),
  RESULT: m('resultat', 'resultats'),
  IMPORT_NOUN: f('importació', 'importacions', NO_ELISION),
  ICON: f('icona', 'icones', NO_ELISION),
  FILE: m('fitxer', 'fitxers'),
  CLIPBOARD: m('porta-retalls', 'porta-retalls'),
  LINE: f('línia', 'línies'),
  HISTORY: m('historial'),
  WORKSPACE: m('espai de treball', 'espais de treball'),
  USAGE: m('ús'),
  EXAMPLE: m('exemple', 'exemples'),
  CONSOLE: f('consola', 'consoles'),
  CANVAS: m('llenç', 'llenços'),
  PREVIEW: f('previsualització', 'previsualitzacions'), // (verify)
  TOOLBAR: f("barra d'eines", "barres d'eines"),
  LIST: f('llista', 'llistes'),
  VALUE: m('valor', 'valors'),
  CURSOR: m('cursor', 'cursors'),
  TEXT: m('text', 'textos'),
  REFERENCE: f('referència', 'referències'),

  // Abstract nouns.
  CAUSE: f('causa', 'causes'),
  POSSESSOR: mf('posseïdor', 'posseïdors', 'posseïdora', 'posseïdores'),
  PROPERTY: f('propietat'),
  FEATURE: f('característica', 'característiques'),
  DOMAIN: m('domini', 'dominis'),
  MEANS: m('mitjà', 'mitjans'),
  PURPOSE: f('finalitat', 'finalitats'),
  USE_NOUN: m('ús', 'usos'),
  WORK_NOUN: m('treball'),
  RESEARCH: f('recerca'),
  STUDY_NOUN: m('estudi', 'estudis'),
  MATERIAL: m('material', 'materials'),
  WOOD: f('fusta'),
  LEVEL: m('nivell', 'nivells'),
  PROCESS: m('procés', 'processos'),
  CHANGE_NOUN: m('canvi', 'canvis'),
  SYSTEM: m('sistema', 'sistemes'),
  PROGRAM_SOFTWARE: m('programa', 'programes'),
  PROGRAM_SHOW: m('programa', 'programes'),
  CONCEPT: m('concepte', 'conceptes'),
  IDEA: f('idea', 'idees', NO_ELISION),
  ACTION: f('acció', 'accions'),
  EVENT: m('esdeveniment', 'esdeveniments'),
  RACE: f('cursa', 'curses'),
  GAME: m('joc', 'jocs'),
  OBJECT_THING: m('objecte', 'objectes'),
  DEVICE: m('dispositiu', 'dispositius'),
  BOMB: f('bomba', 'bombes'),
  THING: f('cosa', 'coses'),
  PROBLEM: m('problema', 'problemes'),
  ISSUE: f('qüestió', 'qüestions'),
  CASE_INSTANCE: m('cas', 'casos'),
  BEING: m('ésser', 'éssers'),

  // The body.
  BODY: m('cos', 'cossos'),
  ORGAN: m('òrgan', 'òrgans'),
  TESTICLE: m('testicle', 'testicles'),
  OVARY: m('ovari', 'ovaris'),
  MILK: f('llet'),
  GRASS: f('herba'),
  // *la calor*, feminine in Catalan.
  HEAT: f('calor'),
  EYE: m('ull', 'ulls'),
  HAND: f('mà', 'mans'),
  HEAD: m('cap', 'caps'),
  FACE: f('cara', 'cares'),
  BACK_BODY: f('esquena', 'esquenes'),
  HEALTH: f('salut'),

  STORY: f('història', 'històries', NO_ELISION),
  HISTORY_PAST: f('història', undefined, NO_ELISION),
  // *les notícies*: plural-only, as Spanish's.
  NEWS: f('notícies', undefined, { count: 'plural' }),
  SUBSTANCE: f('substància'),
  STATE: m('estat', 'estats'),
  GAS: m('gas'),
  JOY: f('alegria'),
  SORROW: f('tristesa'),
  ERROR: m('error', 'errors'),
  REALITY: f('realitat', 'realitats'),
  REST: m('descans'),
  ATTENTION: f('atenció'),
  ABILITY: f('capacitat', 'capacitats'),
  DUTY: m('deure', 'deures'),
  KINDNESS: f('amabilitat'),
  WISDOM: f('saviesa'),
  FOLLY: f('bogeria'),

  // Society.
  LAND: f('terra'),
  NATION: f('nació', 'nacions'),
  SCHOOL: f('escola', 'escoles'),
  STUDENT: mf('estudiant', 'estudiants', 'estudiant', 'estudiants'),
  COMPANY_BUSINESS: f('empresa', 'empreses'),
  TEAM: m('equip', 'equips'),
  COMMUNITY: f('comunitat', 'comunitats'),
  UNIVERSITY: f('universitat', 'universitats', NO_ELISION),
  SERVICE: m('servei', 'serveis'),
  BUSINESS: m('comerç'),
  STATE_NATION: m('Estat', 'Estats'), // (verify) capital, as Spanish's
  POWER: m('poder', 'poders'),
  GOVERNMENT: m('govern', 'governs'),
  PARTY_POLITICAL: m('partit', 'partits'),
  LAW: f('llei', 'lleis'),
  COURT_LAW: m('tribunal', 'tribunals'),
  RIGHT_NOUN: m('dret', 'drets'),
  WAR: f('guerra', 'guerres'),
  WORLD: m('món', 'mons'),
  PICTURE: f('imatge', 'imatges', NO_ELISION),
  SCREEN: f('pantalla', 'pantalles'),
  PART: f('part', 'parts'),
};
