/**
 * Catalan's review sheet (P03-E11) — generated, never hand-written; the Romansh tool
 * (`romanshReviewSheet.ts`) with Catalan's verb columns:
 *
 *   npm run build --workspace=packages/shared && npm run build --workspace=packages/engine
 *   npx tsx packages/engine/test/tools/catalanReviewSheet.ts > docs/features/P-planning/P03-catalan/review-sheet-ca.md
 *
 * Every string the Catalan row can say, beside Spanish (the language the column borrows from) and
 * English: the lexicon, every sentence the suite pins, every UI string and every engine-composed
 * definition. A word the column borrowed (`BORROWED`) is marked **borrowed**.
 *
 * The UI strings and definitions are the backend's boot renders, which read the built engine: build
 * `shared` and `engine` first, as above, or the sheet shows the previous build.
 */
import { existsSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const code = 'ca';

// The seed and the boot renders log as they go; the sheet is stdout, so they are silenced.
console.log = () => {};
console.warn = () => {};
const { concepts, COLUMNS, BORROWED, NONFINITE } = await import('../../../backend/src/concepts/index.js');
await import('../harness.js');
const { buildUiStrings } = await import('../../../backend/src/uiStrings.js');
const { buildConceptDefinitions } = await import('../../../backend/src/definitions.js');

const here = path.dirname(fileURLToPath(import.meta.url));
const closest = COLUMNS[code as keyof typeof COLUMNS]!.closest;
const borrowed = new Set(BORROWED[code as keyof typeof BORROWED] ?? []);
const cell = (text: string | undefined) => (text ?? '').replace(/\|/g, '\\|');
const out: string[] = [];
const say = (line = '') => out.push(line);

type Seed = (typeof concepts)[number];
const byRole = (role: string) => concepts.filter((c) => c.role === role);
const formsIn = (c: Seed, language: string) => ({ ...c.forms[language], ...(NONFINITE[c.id]?.[language] ?? {}) });
const mark = (c: Seed) => (borrowed.has(c.id) ? ' **borrowed**' : '');

say('# Catalan (`ca`) — the review sheet');
say();
say('Generated by `packages/engine/test/tools/catalanReviewSheet.ts` (P03-E11). **Do not edit by');
say(`hand**: a correction is a data edit in \`packages/backend/src/concepts/${code}/\` or a pin in`);
say(`\`packages/engine/test/languages/${code}.test.ts\`, and the sheet is regenerated. Mark each row in the`);
say(`review copy, not here. Compared with \`${closest}\`, the language the column borrows from; a row marked`);
say('**borrowed** is that language\'s word standing in until Catalan is given its own. Central Catalan,');
say('IEC standard; the conventions are in [style-ca.md](style-ca.md).');
say();

// ── The lexicon ─────────────────────────────────────────────────────────────
const verbs = byRole('verb');
say(`## 1. Verbs (${verbs.length})`);
say();
say(`| concept | \`${closest}\` | \`${code}\` | present | imperfect 3sg | future 3sg | conditional 3sg | subjunctive 3sg | past subjunctive 3sg | gerund | participle (m, f, mpl, fpl) | command (tu, nosaltres, vosaltres) |`);
say('|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const c of verbs) {
  const g = formsIn(c, code);
  const persons = ['1sg', '2sg', '3sg', '1pl', '2pl', '3pl'].map((p) => g[`${p}_present`] ?? '').join(', ');
  const participles = ['participle', 'participle_fem', 'participle_plural', 'participle_fem_plural'].map((k) => g[k] ?? '').join(', ');
  const commands = ['2sg', '1pl', '2pl'].map((p) => g[`${p}_imperative`] ?? '').join(', ');
  say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${cell(persons)} | ${cell(g['3sg_imperfect'])} | ${cell(g['3sg_future'])} | ${cell(g['3sg_conditional'])} | ${cell(g['3sg_subjunctive'])} | ${cell(g['3sg_past_subjunctive'])} | ${cell(g['gerund'])} | ${cell(participles)} | ${cell(commands)} |`);
}
say();

const nouns = byRole('noun');
say(`## 2. Nouns (${nouns.length})`);
say();
say(`| concept | \`${closest}\` | \`${code}\` | plural | gender | other forms |`);
say('|---|---|---|---|---|---|');
for (const c of nouns) {
  const g = formsIn(c, code);
  const other = Object.entries(g)
    .filter(([k]) => !['base', 'plural', 'gender', 'count'].includes(k))
    .map(([k, v]) => `${k}: ${v}`)
    .join('; ');
  say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${cell(g['plural'])} | ${cell(g['gender'])} | ${cell(other)} |`);
}
say();

const others = ['adjective', 'adverb', 'pronoun', 'interjection'];
others.forEach((role, i) => {
  const list = byRole(role);
  say(`## ${i + 3}. ${role[0]!.toUpperCase()}${role.slice(1)}s (${list.length})`);
  say();
  say(`| concept | \`${closest}\` | \`${code}\` | other forms |`);
  say('|---|---|---|---|');
  for (const c of list) {
    const g = formsIn(c, code);
    const other = Object.entries(g).filter(([k]) => k !== 'base').map(([k, v]) => `${k}: ${v}`).join('; ');
    say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${cell(other)} |`);
  }
  say();
});

// ── The suite's sentences ───────────────────────────────────────────────────
// Read off the suite rather than re-rendered: they are exactly the pins a correction changes.
const suitePath = path.join(here, '..', 'languages', `${code}.test.ts`);
const suite = existsSync(suitePath) ? readFileSync(suitePath, 'utf8') : '';
// A label may escape its apostrophes (\'), and a sentence with one is double-quoted ("l'um.").
const pinned = [...suite.matchAll(/^\s*\['((?:[^'\\]|\\.)+)',[^\n]*, (?:'([^']*)'|"([^"]*)")\],$/gm)]
  .map((m) => [m[1]!.replace(/\\'/g, "'"), m[2] ?? m[3]!] as const);
const bare = [...suite.matchAll(/toBe\((?:'([^']+)'|"([^"]+)")\)/g)].map((m) => (m[1] ?? m[2])!).filter((t) => !pinned.some(([, s]) => s === t));
say(`## 7. The suite's sentences (${pinned.length + bare.length})`);
say();
say(`Each row is a pin in \`${code}.test.ts\`; the rows in its \`test.fails\` blocks are what the review is`);
say('asked to rule on, not what ships.');
say();
say(`| row | \`${code}\` |`);
say('|---|---|');
for (const [label, text] of pinned) say(`| ${cell(label)} | ${cell(text)} |`);
for (const text of bare) say(`| | ${cell(text)} |`);
say();

// ── The interface ───────────────────────────────────────────────────────────
const strings = buildUiStrings() as unknown as Record<string, Record<string, string>>;
const keys = Object.keys(strings);
say(`## 8. UI strings (${keys.length})`);
say();
say(`| key | \`en\` | \`${closest}\` | \`${code}\` |`);
say('|---|---|---|---|');
for (const key of keys) say(`| ${key} | ${cell(strings[key]!['en'])} | ${cell(strings[key]![closest])} | ${cell(strings[key]![code])} |`);
say();

const definitions = buildConceptDefinitions();
say(`## 9. Engine-composed definitions (${definitions.size})`);
say();
say(`| concept | \`en\` | \`${closest}\` | \`${code}\` |`);
say('|---|---|---|---|');
for (const [id, byLanguage] of definitions) say(`| ${id} | ${cell(byLanguage['en'])} | ${cell(byLanguage[closest])} | ${cell(byLanguage[code as keyof typeof byLanguage])} |`);
say();

const total = verbs.length + nouns.length + others.reduce((n, r) => n + byRole(r).length, 0)
  + pinned.length + bare.length + keys.length + definitions.size;
out.splice(9, 0, `**${total} rows** in nine sections, ${borrowed.size} of the words borrowed, re-measured at generation.`, '');
process.stdout.write(`${out.join('\n')}\n`);
