/**
 * The Swiss German review sheet (P10-E14 D1) — generated, never hand-written.
 *
 *   npm run build --workspace=packages/shared && npm run build --workspace=packages/engine
 *   npx tsx packages/engine/test/tools/gswReviewSheet.ts > docs/features/P-planning/P10-swiss-german/review-sheet.md
 *
 * Every string the `gsw` row can say, beside the Standard German (and English) it was written against:
 * the lexicon (every verb's cells, every noun's plural and gender, every adjective, adverb, pronoun),
 * every sentence the `gsw` suite pins, every UI string and every engine-composed definition. The
 * reviewer marks each row; a correction becomes a data edit or a pin change (E14 D3). Regenerate after
 * any change to the corpus or the engine, so the sheet in the repo is the one the engine speaks.
 *
 * The UI strings and definitions are the backend's boot renders, which read the built engine: build
 * `shared` and `engine` first, as above, or the sheet shows the previous build.
 */
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

// The seed and the boot renders log as they go; the sheet is stdout, so they are silenced.
console.log = () => {};
console.warn = () => {};
const { concepts, GSW, NONFINITE } = await import('../../../backend/src/concepts/index.js');
await import('../harness.js');
const { buildUiStrings } = await import('../../../backend/src/uiStrings.js');
const { buildConceptDefinitions } = await import('../../../backend/src/definitions.js');

const here = path.dirname(fileURLToPath(import.meta.url));
const cell = (text: string | undefined) => (text ?? '').replace(/\|/g, '\\|');
const out: string[] = [];
const say = (line = '') => out.push(line);

const byRole = (role: string) => concepts.filter((c) => c.role === role);
const de = (c: (typeof concepts)[number]) => ({ ...c.forms['de'], ...(NONFINITE[c.id]?.['de'] ?? {}) });

say('# Swiss German (`gsw`) — the review sheet');
say();
say('Generated by `packages/engine/test/tools/gswReviewSheet.ts` (P10-E14 D1). **Do not edit by hand**: a');
say('correction is a data edit in `packages/backend/src/concepts/gsw/` or a pin in');
say('`packages/engine/test/languages/gsw.test.ts`, and the sheet is regenerated. Mark each row in the');
say('review copy, not here. Zürichdeutsch (P10 D1), Dieth spelling ([style sheet](dieth-style-sheet.md)).');
say();

// ── The lexicon ─────────────────────────────────────────────────────────────
const verbs = byRole('verb');
say(`## 1. Verbs (${verbs.length})`);
say();
say('| concept | `de` | `gsw` | ich | du | er/si/es | mir/ir/si | participle | aux | command |');
say('|---|---|---|---|---|---|---|---|---|---|');
for (const c of verbs) {
  const g = GSW[c.id] ?? {};
  say(`| ${c.id} | ${cell(de(c)['base'])} | ${cell(g['base'])} | ${cell(g['1sg_present'])} | ${cell(g['2sg_present'])} | ${cell(g['3sg_present'])} | ${cell(g['1pl_present'])} | ${cell(g['participle'])} | ${g['aux'] === 'be' ? 'sii' : 'haa'} | ${cell(g['2sg_imperative'])} |`);
}
say();

const nouns = byRole('noun');
say(`## 2. Nouns (${nouns.length})`);
say();
say('| concept | `de` | `gsw` | plural | gender | other forms |');
say('|---|---|---|---|---|---|');
for (const c of nouns) {
  const g = GSW[c.id] ?? {};
  const other = Object.entries(g)
    .filter(([k]) => !['base', 'plural', 'gender', 'count'].includes(k))
    .map(([k, v]) => `${k}: ${v}`)
    .join('; ');
  say(`| ${c.id} | ${cell(de(c)['base'])} | ${cell(g['base'])} | ${cell(g['plural'])} | ${cell(g['gender'])} | ${cell(other)} |`);
}
say();

for (const role of ['adjective', 'adverb', 'pronoun', 'interjection']) {
  const list = byRole(role);
  say(`## ${role === 'adjective' ? 3 : role === 'adverb' ? 4 : role === 'pronoun' ? 5 : 6}. ${role[0]!.toUpperCase()}${role.slice(1)}s (${list.length})`);
  say();
  say('| concept | `de` | `gsw` | other forms |');
  say('|---|---|---|---|');
  for (const c of list) {
    const g = GSW[c.id] ?? {};
    const other = Object.entries(g).filter(([k]) => k !== 'base').map(([k, v]) => `${k}: ${v}`).join('; ');
    say(`| ${c.id} | ${cell(de(c)['base'])} | ${cell(g['base'])} | ${cell(other)} |`);
  }
  say();
}

// ── The suite's sentences ───────────────────────────────────────────────────
// Read off the suite rather than re-rendered: they are exactly the pins a correction changes.
const suite = readFileSync(path.join(here, '..', 'languages', 'gsw.test.ts'), 'utf8');
const pinned = [...suite.matchAll(/^\s*\['([^']+)',[^\n]*, '([^']*)'\],$/gm)].map((m) => [m[1]!, m[2]!] as const);
const bare = [...suite.matchAll(/toBe\('([^']+)'\)/g)].map((m) => m[1]!).filter((t) => !pinned.some(([, s]) => s === t));
say(`## 7. The suite's sentences (${pinned.length + bare.length})`);
say();
say('Each row is a pin in `gsw.test.ts`; the rows in its `test.fails` blocks are the order the review is');
say('asked to rule on (P10 D11), not what ships.');
say();
say('| row | `gsw` |');
say('|---|---|');
for (const [label, text] of pinned) say(`| ${cell(label)} | ${cell(text)} |`);
for (const text of bare) say(`| | ${cell(text)} |`);
say();

// ── The interface ───────────────────────────────────────────────────────────
const strings = buildUiStrings() as unknown as Record<string, Record<string, string>>;
const keys = Object.keys(strings);
say(`## 8. UI strings (${keys.length})`);
say();
say('| key | `en` | `de` | `gsw` |');
say('|---|---|---|---|');
for (const key of keys) say(`| ${key} | ${cell(strings[key]!['en'])} | ${cell(strings[key]!['de'])} | ${cell(strings[key]!['gsw'])} |`);
say();

const definitions = buildConceptDefinitions();
say(`## 9. Engine-composed definitions (${definitions.size})`);
say();
say('| concept | `en` | `de` | `gsw` |');
say('|---|---|---|---|');
for (const [id, byLanguage] of definitions) say(`| ${id} | ${cell(byLanguage['en'])} | ${cell(byLanguage['de'])} | ${cell(byLanguage['gsw'])} |`);
say();

const total = verbs.length + nouns.length + ['adjective', 'adverb', 'pronoun', 'interjection'].reduce((n, r) => n + byRole(r).length, 0)
  + pinned.length + bare.length + keys.length + definitions.size;
out.splice(7, 0, `**${total} rows** in nine sections, re-measured at generation (E14 D1: P10 §4's 630 is stale).`, '');
process.stdout.write(`${out.join('\n')}\n`);
