/**
 * Lithuanian's review sheet (P18-E12) — generated, never hand-written; Polish's tool
 * (`polishReviewSheet.ts`) with Lithuanian's tenses, and the nouns grouped by declension class so a
 * reviewer reads one class helper's output at a time (P18 §4, §7):
 *
 *   npm run build --workspace=packages/shared && npm run build --workspace=packages/engine
 *   npx tsx packages/engine/test/tools/lithuanianReviewSheet.ts > docs/features/O-open/P18-lithuanian/review-sheet-lt.md
 *
 * Every string the Lithuanian row can say, beside English (Polish, the language the column borrows
 * from, is not the reader's gloss): the lexicon, every sentence the suite pins, every UI string and every engine-composed
 * definition. A word the column borrowed (`BORROWED`) is marked **borrowed**.
 *
 * The UI strings and definitions are the backend's boot renders, which read the built engine: build
 * `shared` and `engine` first, as above, or the sheet shows the previous build.
 */
import { existsSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const code = 'lt';

// The seed and the boot renders log as they go; the sheet is stdout, so they are silenced.
console.log = () => {};
console.warn = () => {};
const { concepts, COLUMNS, BORROWED, NONFINITE } = await import('../../../backend/src/concepts/index.js');
await import('../harness.js');
const { buildUiStrings } = await import('../../../backend/src/uiStrings.js');
const { buildConceptDefinitions } = await import('../../../backend/src/definitions.js');

const here = path.dirname(fileURLToPath(import.meta.url));
// The gloss column; `COLUMNS.lt.closest` (Polish) is only the borrowing fallback.
const closest = 'en';
const borrowed = new Set(BORROWED[code as keyof typeof BORROWED] ?? []);
const cell = (text: string | undefined) => (text ?? '').replace(/\|/g, '\\|');
const out: string[] = [];
const say = (line = '') => out.push(line);

type Seed = (typeof concepts)[number];
const byRole = (role: string) => concepts.filter((c) => c.role === role);
const formsIn = (c: Seed, language: string) => ({ ...c.forms[language], ...(NONFINITE[c.id]?.[language] ?? {}) });
const mark = (c: Seed) => (borrowed.has(c.id) ? ' **borrowed**' : '');

say('# Lithuanian (`lt`) — the review sheet');
say();
say('Generated by `packages/engine/test/tools/lithuanianReviewSheet.ts` (P18-E12). **Do not edit by');
say(`hand**: a correction is a data edit in \`packages/backend/src/concepts/${code}/\` or a pin in`);
say(`\`packages/engine/test/languages/${code}.test.ts\`, and the sheet is regenerated. Mark each row in the`);
say(`review copy, not here. Glossed in \`${closest}\`; a row marked **borrowed** is Polish's word standing in`);
say('until Lithuanian is given its own. Standard Lithuanian (VLKK); the conventions and the keys are in');
say('[style-lt.md](style-lt.md).');
say();

// ── The lexicon ─────────────────────────────────────────────────────────────
const verbs = byRole('verb');
say(`## 1. Verbs (${verbs.length})`);
say();
say(`| concept | \`${closest}\` | imperfective | present | past | future | command | perfective | past | future | command | other |`);
say('|---|---|---|---|---|---|---|---|---|---|---|---|');
// The 3rd person is one form in both numbers (style-lt.md), so five cells a tense.
const PERSONS = ['1sg', '2sg', '3sg', '1pl', '2pl'];
const IMPERATIVE = ['2sg_imperative', '1pl_imperative', '2pl_imperative'];
const TENSES = ['present', 'past', 'future'];
for (const c of verbs) {
  const g = formsIn(c, code);
  const list = (keys: string[], prefix = '') => keys.map((k) => g[`${prefix}${k}`] ?? '').join(', ');
  const tense = (t: string, prefix = '') => list(PERSONS.map((p) => `${p}_${t}`), prefix);
  const shown = new Set(['', 'pf_'].flatMap((p) => ['base', ...IMPERATIVE, ...TENSES.flatMap((t) => [...PERSONS, '3pl'].map((q) => `${q}_${t}`))].map((k) => `${p}${k}`)));
  const other = Object.entries(g).filter(([k]) => !shown.has(k)).map(([k, v]) => `${k}: ${v}`).join('; ');
  const pf = g['pf_base'] !== undefined;
  const aspect = (prefix: string) => [...TENSES.map((t) => tense(t, prefix)), list(IMPERATIVE, prefix)].map(cell).join(' | ');
  say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${aspect('')} | ${cell(g['pf_base'])} | ${pf ? aspect('pf_') : ' |  |  | '} | ${cell(other)} |`);
}
say();

const nouns = byRole('noun');
say(`## 2. Nouns (${nouns.length})`);
say();
say(`| concept | \`${closest}\` | gender | singular (nom, gen, dat, acc, ins, loc, voc) | plural (nom, gen, dat, acc, ins, loc) | other forms |`);
say('|---|---|---|---|---|---|');
const SG = ['base', 'gen_sg', 'dat_sg', 'acc_sg', 'ins_sg', 'loc_sg', 'voc_sg'];
const PL = ['plural', 'gen_pl', 'dat_pl', 'acc_pl', 'ins_pl', 'loc_pl'];
// The declension class, read off the nominative's ending (the helper that wrote it, style-lt.md).
const CLASSES: [string, RegExp][] = [['-ias', /ias$/], ['-jas', /jas$/], ['-as', /as$/], ['-is (masc)', /is$/], ['-ys', /ys$/],
  ['-us', /us$/], ['-a', /a$/], ['-ė', /ė$/], ['other (irregular, multiword, plural-only)', /$/]];
const classOf = (c: Seed) => {
  const g = formsIn(c, code);
  const base = (g['base'] ?? '').split(' ').at(-1)!;
  if (g['plurale_tantum'] || (g['base'] ?? '').includes(' ')) return CLASSES.length - 1;
  if (/is$/.test(base) && g['gender'] === 'fem') return CLASSES.length - 1; // the i-stems are few: read them with the irregulars
  return CLASSES.findIndex(([, re]) => re.test(base));
};
const sorted = [...nouns].sort((a, b) => classOf(a) - classOf(b));
let heading = -1;
for (const c of sorted) {
  const g = formsIn(c, code);
  if (classOf(c) !== heading) {
    heading = classOf(c);
    say(`| **${CLASSES[heading]![0]}** | | | | | |`);
  }
  const other = Object.entries(g)
    .filter(([k]) => ![...SG, ...PL, 'gender', 'count'].includes(k))
    .map(([k, v]) => `${k}: ${v}`)
    .join('; ');
  const plural = g['plural'] === undefined ? '' : PL.map((k) => g[k] ?? '').join(', ');
  say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['gender'])} | ${cell(SG.map((k) => g[k] ?? '').join(', '))} | ${cell(plural)} | ${cell(other)} |`);
}
say();

const others = ['adjective', 'adverb', 'pronoun', 'interjection'];
others.forEach((role, i) => {
  const list = byRole(role);
  say(`## ${i + 3}. ${role[0]!.toUpperCase()}${role.slice(1)}s (${list.length})`);
  say();
  say(`| concept | \`${closest}\` | \`${code}\` | other forms |`);
  say('|---|---|---|---|');
  for (const c of list) {
    const g = formsIn(c, code);
    const other = Object.entries(g).filter(([k]) => k !== 'base').map(([k, v]) => `${k}: ${v}`).join('; ');
    say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${cell(other)} |`);
  }
  say();
});

// ── The suite's sentences ───────────────────────────────────────────────────
// Read off the suite rather than re-rendered: they are exactly the pins a correction changes.
const suitePath = path.join(here, '..', 'languages', `${code}.test.ts`);
const suite = existsSync(suitePath) ? readFileSync(suitePath, 'utf8') : '';
// A label may escape its apostrophes (\'), and a sentence with one is double-quoted ("l'um.").
const pinned = [...suite.matchAll(/^\s*\['((?:[^'\\]|\\.)+)',[^\n]*, (?:'([^']*)'|"([^"]*)")\],$/gm)]
  .map((m) => [m[1]!.replace(/\\'/g, "'"), m[2] ?? m[3]!] as const);
const bare = [...suite.matchAll(/toBe\((?:'([^']+)'|"([^"]+)")\)/g)].map((m) => (m[1] ?? m[2])!).filter((t) => !pinned.some(([, s]) => s === t));
say(`## 7. The suite's sentences (${pinned.length + bare.length})`);
say();
say(`Each row is a pin in \`${code}.test.ts\`; the rows in its \`test.fails\` blocks are what the review is`);
say('asked to rule on, not what ships.');
say();
say(`| row | \`${code}\` |`);
say('|---|---|');
for (const [label, text] of pinned) say(`| ${cell(label)} | ${cell(text)} |`);
for (const text of bare) say(`| | ${cell(text)} |`);
say();

// ── The interface ───────────────────────────────────────────────────────────
const strings = buildUiStrings() as unknown as Record<string, Record<string, string>>;
const keys = Object.keys(strings);
say(`## 8. UI strings (${keys.length})`);
say();
say(`| key | \`en\` | \`${code}\` |`);
say('|---|---|---|');
for (const key of keys) say(`| ${key} | ${cell(strings[key]!['en'])} | ${cell(strings[key]![code])} |`);
say();

const definitions = buildConceptDefinitions();
say(`## 9. Engine-composed definitions (${definitions.size})`);
say();
say(`| concept | \`en\` | \`${code}\` |`);
say('|---|---|---|');
for (const [id, byLanguage] of definitions) say(`| ${id} | ${cell(byLanguage['en'])} | ${cell(byLanguage[code as keyof typeof byLanguage])} |`);
say();

const total = verbs.length + nouns.length + others.reduce((n, r) => n + byRole(r).length, 0)
  + pinned.length + bare.length + keys.length + definitions.size;
out.splice(9, 0, `**${total} rows** in nine sections, ${borrowed.size} of the words borrowed, re-measured at generation.`, '');
process.stdout.write(`${out.join('\n')}\n`);
