/**
 * Polish's review sheet (P05-E11) — generated, never hand-written; the Catalan tool
 * (`catalanReviewSheet.ts`) with Polish's case and aspect columns:
 *
 *   npm run build --workspace=packages/shared && npm run build --workspace=packages/engine
 *   npx tsx packages/engine/test/tools/polishReviewSheet.ts > docs/features/O-open/P05-polish/review-sheet-pl.md
 *
 * Every string the Polish row can say, beside English (German, the language the column borrows from,
 * shares no words with it, so English is the gloss): the lexicon, every sentence the suite pins, every UI string and every engine-composed
 * definition. A word the column borrowed (`BORROWED`) is marked **borrowed**.
 *
 * The UI strings and definitions are the backend's boot renders, which read the built engine: build
 * `shared` and `engine` first, as above, or the sheet shows the previous build.
 */
import { existsSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const code = 'pl';

// The seed and the boot renders log as they go; the sheet is stdout, so they are silenced.
console.log = () => {};
console.warn = () => {};
const { concepts, COLUMNS, BORROWED, NONFINITE } = await import('../../../backend/src/concepts/index.js');
await import('../harness.js');
const { buildUiStrings } = await import('../../../backend/src/uiStrings.js');
const { buildConceptDefinitions } = await import('../../../backend/src/definitions.js');

const here = path.dirname(fileURLToPath(import.meta.url));
// The gloss column; `COLUMNS.pl.closest` (German) is only the borrowing fallback.
const closest = 'en';
const borrowed = new Set(BORROWED[code as keyof typeof BORROWED] ?? []);
const cell = (text: string | undefined) => (text ?? '').replace(/\|/g, '\\|');
const out: string[] = [];
const say = (line = '') => out.push(line);

type Seed = (typeof concepts)[number];
const byRole = (role: string) => concepts.filter((c) => c.role === role);
const formsIn = (c: Seed, language: string) => ({ ...c.forms[language], ...(NONFINITE[c.id]?.[language] ?? {}) });
const mark = (c: Seed) => (borrowed.has(c.id) ? ' **borrowed**' : '');

say('# Polish (`pl`) — the review sheet');
say();
say('Generated by `packages/engine/test/tools/polishReviewSheet.ts` (P05-E11). **Do not edit by');
say(`hand**: a correction is a data edit in \`packages/backend/src/concepts/${code}/\` or a pin in`);
say(`\`packages/engine/test/languages/${code}.test.ts\`, and the sheet is regenerated. Mark each row in the`);
say(`review copy, not here. Glossed in \`${closest}\`; a row marked **borrowed** is German's word standing in`);
say('until Polish is given its own. Standard written Polish; the conventions and the keys are in');
say('[style-pl.md](style-pl.md).');
say();

// ── The lexicon ─────────────────────────────────────────────────────────────
const verbs = byRole('verb');
say(`## 1. Verbs (${verbs.length})`);
say();
say(`| concept | \`${closest}\` | imperfective | present | past (m, f, n, vir, nvir) | command | perfective | future | past (m, f, n, vir, nvir) | command | other |`);
say('|---|---|---|---|---|---|---|---|---|---|---|');
const PERSONS = ['1sg', '2sg', '3sg', '1pl', '2pl', '3pl'];
const PAST = ['past_masc', 'past_fem', 'past_neut', 'past_virile', 'past_nonvirile'];
const IMPERATIVE = ['2sg_imperative', '1pl_imperative', '2pl_imperative'];
for (const c of verbs) {
  const g = formsIn(c, code);
  const list = (keys: string[], prefix = '') => keys.map((k) => g[`${prefix}${k}`] ?? '').join(', ');
  const shown = new Set(['base', 'pf_base', ...['', 'pf_'].flatMap((p) => [...PAST, ...IMPERATIVE].map((k) => `${p}${k}`)),
    ...PERSONS.map((p) => `${p}_present`), ...PERSONS.map((p) => `pf_${p}_future`)]);
  const other = Object.entries(g).filter(([k]) => !shown.has(k)).map(([k, v]) => `${k}: ${v}`).join('; ');
  const perfective = g['pf_base'] !== undefined;
  say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${cell(list(PERSONS.map((p) => `${p}_present`)))} | ${cell(list(PAST))} | ${cell(list(IMPERATIVE))} | ${cell(g['pf_base'])} | ${perfective ? cell(list(PERSONS.map((p) => `pf_${p}_future`))) : ''} | ${perfective ? cell(list(PAST, 'pf_')) : ''} | ${perfective ? cell(list(IMPERATIVE, 'pf_')) : ''} | ${cell(other)} |`);
}
say();

const nouns = byRole('noun');
say(`## 2. Nouns (${nouns.length})`);
say();
say(`| concept | \`${closest}\` | gender | singular (nom, gen, dat, acc, ins, loc, voc) | plural (nom, gen, dat, acc, ins, loc) | other forms |`);
say('|---|---|---|---|---|---|');
const SG = ['base', 'gen_sg', 'dat_sg', 'acc_sg', 'ins_sg', 'loc_sg', 'voc_sg'];
const PL = ['plural', 'gen_pl', 'dat_pl', 'acc_pl', 'ins_pl', 'loc_pl'];
for (const c of nouns) {
  const g = formsIn(c, code);
  const other = Object.entries(g)
    .filter(([k]) => ![...SG, ...PL, 'gender', 'count'].includes(k))
    .map(([k, v]) => `${k}: ${v}`)
    .join('; ');
  const plural = g['plural'] === undefined ? '' : PL.map((k) => g[k] ?? '').join(', ');
  say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['gender'])} | ${cell(SG.map((k) => g[k] ?? '').join(', '))} | ${cell(plural)} | ${cell(other)} |`);
}
say();

const others = ['adjective', 'adverb', 'pronoun', 'interjection'];
others.forEach((role, i) => {
  const list = byRole(role);
  say(`## ${i + 3}. ${role[0]!.toUpperCase()}${role.slice(1)}s (${list.length})`);
  say();
  say(`| concept | \`${closest}\` | \`${code}\` | other forms |`);
  say('|---|---|---|---|');
  for (const c of list) {
    const g = formsIn(c, code);
    const other = Object.entries(g).filter(([k]) => k !== 'base').map(([k, v]) => `${k}: ${v}`).join('; ');
    say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${cell(other)} |`);
  }
  say();
});

// ── The suite's sentences ───────────────────────────────────────────────────
// Read off the suite rather than re-rendered: they are exactly the pins a correction changes.
const suitePath = path.join(here, '..', 'languages', `${code}.test.ts`);
const suite = existsSync(suitePath) ? readFileSync(suitePath, 'utf8') : '';
// A label may escape its apostrophes (\'), and a sentence with one is double-quoted ("l'um.").
const pinned = [...suite.matchAll(/^\s*\['((?:[^'\\]|\\.)+)',[^\n]*, (?:'([^']*)'|"([^"]*)")\],$/gm)]
  .map((m) => [m[1]!.replace(/\\'/g, "'"), m[2] ?? m[3]!] as const);
const bare = [...suite.matchAll(/toBe\((?:'([^']+)'|"([^"]+)")\)/g)].map((m) => (m[1] ?? m[2])!).filter((t) => !pinned.some(([, s]) => s === t));
say(`## 7. The suite's sentences (${pinned.length + bare.length})`);
say();
say(`Each row is a pin in \`${code}.test.ts\`; the rows in its \`test.fails\` blocks are what the review is`);
say('asked to rule on, not what ships.');
say();
say(`| row | \`${code}\` |`);
say('|---|---|');
for (const [label, text] of pinned) say(`| ${cell(label)} | ${cell(text)} |`);
for (const text of bare) say(`| | ${cell(text)} |`);
say();

// ── The interface ───────────────────────────────────────────────────────────
const strings = buildUiStrings() as unknown as Record<string, Record<string, string>>;
const keys = Object.keys(strings);
say(`## 8. UI strings (${keys.length})`);
say();
say(`| key | \`en\` | \`${code}\` |`);
say('|---|---|---|');
for (const key of keys) say(`| ${key} | ${cell(strings[key]!['en'])} | ${cell(strings[key]![code])} |`);
say();

const definitions = buildConceptDefinitions();
say(`## 9. Engine-composed definitions (${definitions.size})`);
say();
say(`| concept | \`en\` | \`${code}\` |`);
say('|---|---|---|');
for (const [id, byLanguage] of definitions) say(`| ${id} | ${cell(byLanguage['en'])} | ${cell(byLanguage[code as keyof typeof byLanguage])} |`);
say();

const total = verbs.length + nouns.length + others.reduce((n, r) => n + byRole(r).length, 0)
  + pinned.length + bare.length + keys.length + definitions.size;
out.splice(9, 0, `**${total} rows** in nine sections, ${borrowed.size} of the words borrowed, re-measured at generation.`, '');
process.stdout.write(`${out.join('\n')}\n`);
