/**
 * A Romansh variety's review sheet (P04-E19 D1) — generated, never hand-written. One tool for the
 * three varieties, after the Swiss German one (`gswReviewSheet.ts`):
 *
 *   npm run build --workspace=packages/shared && npm run build --workspace=packages/engine
 *   npx tsx packages/engine/test/tools/romanshReviewSheet.ts rm-sursilv > docs/features/O-open/P04-romansh/review-sheet-rm-sursilv.md
 *
 * Every string the variety's row can say, beside its closest language (Italian for Rumantsch
 * Grischun, Rumantsch Grischun for the two idioms) and English: the lexicon, every sentence its
 * suite pins, every UI string and every engine-composed definition. A word the column borrowed from
 * the closest language (`BORROWED`) is marked **borrowed** — the first thing a reviewer replaces.
 *
 * The UI strings and definitions are the backend's boot renders, which read the built engine: build
 * `shared` and `engine` first, as above, or the sheet shows the previous build.
 */
import { existsSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const VARIETIES: Record<string, string> = {
  'rm-rumgr': 'Rumantsch Grischun',
  'rm-sursilv': 'Sursilvan',
  'rm-vallader': 'Vallader',
};
const code = process.argv[2] ?? '';
if (!VARIETIES[code]) {
  process.stderr.write(`usage: romanshReviewSheet.ts <${Object.keys(VARIETIES).join('|')}>\n`);
  process.exit(1);
}

// The seed and the boot renders log as they go; the sheet is stdout, so they are silenced.
console.log = () => {};
console.warn = () => {};
const { concepts, COLUMNS, BORROWED, NONFINITE } = await import('../../../backend/src/concepts/index.js');
await import('../harness.js');
const { buildUiStrings } = await import('../../../backend/src/uiStrings.js');
const { buildConceptDefinitions } = await import('../../../backend/src/definitions.js');

const here = path.dirname(fileURLToPath(import.meta.url));
const closest = COLUMNS[code as keyof typeof COLUMNS]!.closest;
const borrowed = new Set(BORROWED[code as keyof typeof BORROWED] ?? []);
const cell = (text: string | undefined) => (text ?? '').replace(/\|/g, '\\|');
const out: string[] = [];
const say = (line = '') => out.push(line);

type Seed = (typeof concepts)[number];
const byRole = (role: string) => concepts.filter((c) => c.role === role);
const formsIn = (c: Seed, language: string) => ({ ...c.forms[language], ...(NONFINITE[c.id]?.[language] ?? {}) });
const mark = (c: Seed) => (borrowed.has(c.id) ? ' **borrowed**' : '');

say(`# ${VARIETIES[code]} (\`${code}\`) — the review sheet`);
say();
say('Generated by `packages/engine/test/tools/romanshReviewSheet.ts` (P04-E19 D1). **Do not edit by');
say(`hand**: a correction is a data edit in \`packages/backend/src/concepts/${code}/\` or a pin in`);
say(`\`packages/engine/test/languages/${code}.test.ts\`, and the sheet is regenerated. Mark each row in the`);
say(`review copy, not here. Compared with \`${closest}\`, the language the column borrows from; a row marked`);
say('**borrowed** is that language\'s word standing in until the variety is given its own.');
say();

// ── The lexicon ─────────────────────────────────────────────────────────────
const verbs = byRole('verb');
say(`## 1. Verbs (${verbs.length})`);
say();
say(`| concept | \`${closest}\` | \`${code}\` | 1sg | 2sg | 3sg | 1pl | 2pl | 3pl | imperfect 3sg | conditional 3sg | participle | aux | command |`);
say('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const c of verbs) {
  const g = formsIn(c, code);
  const persons = ['1sg', '2sg', '3sg', '1pl', '2pl', '3pl'].map((p) => cell(g[`${p}_present`])).join(' | ');
  say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${persons} | ${cell(g['3sg_imperfect'])} | ${cell(g['3sg_conditional'])} | ${cell(g['participle'])} | ${g['aux'] === 'be' ? 'esser' : 'haver'} | ${cell(g['2sg_imperative'])} |`);
}
say();

const nouns = byRole('noun');
say(`## 2. Nouns (${nouns.length})`);
say();
say(`| concept | \`${closest}\` | \`${code}\` | plural | gender | other forms |`);
say('|---|---|---|---|---|---|');
for (const c of nouns) {
  const g = formsIn(c, code);
  const other = Object.entries(g)
    .filter(([k]) => !['base', 'plural', 'gender', 'count'].includes(k))
    .map(([k, v]) => `${k}: ${v}`)
    .join('; ');
  say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${cell(g['plural'])} | ${cell(g['gender'])} | ${cell(other)} |`);
}
say();

const others = ['adjective', 'adverb', 'pronoun', 'interjection'];
others.forEach((role, i) => {
  const list = byRole(role);
  say(`## ${i + 3}. ${role[0]!.toUpperCase()}${role.slice(1)}s (${list.length})`);
  say();
  say(`| concept | \`${closest}\` | \`${code}\` | other forms |`);
  say('|---|---|---|---|');
  for (const c of list) {
    const g = formsIn(c, code);
    const other = Object.entries(g).filter(([k]) => k !== 'base').map(([k, v]) => `${k}: ${v}`).join('; ');
    say(`| ${c.id}${mark(c)} | ${cell(formsIn(c, closest)['base'])} | ${cell(g['base'])} | ${cell(other)} |`);
  }
  say();
});

// ── The suite's sentences ───────────────────────────────────────────────────
// Read off the suite rather than re-rendered: they are exactly the pins a correction changes.
const suitePath = path.join(here, '..', 'languages', `${code}.test.ts`);
const suite = existsSync(suitePath) ? readFileSync(suitePath, 'utf8') : '';
// A label may escape its apostrophes (\'), and a sentence with one is double-quoted ("l'um.").
const pinned = [...suite.matchAll(/^\s*\['((?:[^'\\]|\\.)+)',[^\n]*, (?:'([^']*)'|"([^"]*)")\],$/gm)]
  .map((m) => [m[1]!.replace(/\\'/g, "'"), m[2] ?? m[3]!] as const);
const bare = [...suite.matchAll(/toBe\((?:'([^']+)'|"([^"]+)")\)/g)].map((m) => (m[1] ?? m[2])!).filter((t) => !pinned.some(([, s]) => s === t));
say(`## 7. The suite's sentences (${pinned.length + bare.length})`);
say();
say(`Each row is a pin in \`${code}.test.ts\`; the rows in its \`test.fails\` blocks are what the review is`);
say('asked to rule on, not what ships.');
say();
say(`| row | \`${code}\` |`);
say('|---|---|');
for (const [label, text] of pinned) say(`| ${cell(label)} | ${cell(text)} |`);
for (const text of bare) say(`| | ${cell(text)} |`);
say();

// ── The interface ───────────────────────────────────────────────────────────
const strings = buildUiStrings() as unknown as Record<string, Record<string, string>>;
const keys = Object.keys(strings);
say(`## 8. UI strings (${keys.length})`);
say();
say(`| key | \`en\` | \`${closest}\` | \`${code}\` |`);
say('|---|---|---|---|');
for (const key of keys) say(`| ${key} | ${cell(strings[key]!['en'])} | ${cell(strings[key]![closest])} | ${cell(strings[key]![code])} |`);
say();

const definitions = buildConceptDefinitions();
say(`## 9. Engine-composed definitions (${definitions.size})`);
say();
say(`| concept | \`en\` | \`${closest}\` | \`${code}\` |`);
say('|---|---|---|---|');
for (const [id, byLanguage] of definitions) say(`| ${id} | ${cell(byLanguage['en'])} | ${cell(byLanguage[closest])} | ${cell(byLanguage[code as keyof typeof byLanguage])} |`);
say();

const total = verbs.length + nouns.length + others.reduce((n, r) => n + byRole(r).length, 0)
  + pinned.length + bare.length + keys.length + definitions.size;
out.splice(8, 0, `**${total} rows** in nine sections, ${borrowed.size} of the words borrowed, re-measured at generation.`, '');
process.stdout.write(`${out.join('\n')}\n`);
