import type { ConceptSeed } from '../types.js';

// Ditransitive verbs (license a recipient/theme). The recipient is the `terminus` complement
// — the dative "to whom" — which these verbs declare like any other complement-taking verb.
export const ditransitiveVerbs: ConceptSeed[] = [
  {
    id: 'GIVE',
    role: 'verb',
    transitivity: 'ditransitive',
    complements: ['manner', 'terminus', 'cause'],
    description: 'to hand something to someone',
    emoji: '🎁',
    forms: {
      en: {
        base: 'give',
        '1sg_present': 'give', '2sg_present': 'give', '3sg_present': 'gives',
        '1pl_present': 'give', '2pl_present': 'give', '3pl_present': 'give',
        past: 'gave',
      },
      it: {
        base: 'dare',
        '1sg_present': 'do', '2sg_present': 'dai', '3sg_present': 'dà',
        '1pl_present': 'diamo', '2pl_present': 'date', '3pl_present': 'danno',
        '1sg_past': 'diedi', '2sg_past': 'desti', '3sg_past': 'diede',
        '1pl_past': 'demmo', '2pl_past': 'deste', '3pl_past': 'diedero',
        '1sg_future': 'darò', '2sg_future': 'darai', '3sg_future': 'darà',
        '1pl_future': 'daremo', '2pl_future': 'darete', '3pl_future': 'daranno',
      },
      fr: {
        base: 'donner',
        '1sg_present': 'donne', '2sg_present': 'donnes', '3sg_present': 'donne',
        '1pl_present': 'donnons', '2pl_present': 'donnez', '3pl_present': 'donnent',
        '1sg_past': 'donnai', '2sg_past': 'donnas', '3sg_past': 'donna',
        '1pl_past': 'donnâmes', '2pl_past': 'donnâtes', '3pl_past': 'donnèrent',
        '1sg_future': 'donnerai', '2sg_future': 'donneras', '3sg_future': 'donnera',
        '1pl_future': 'donnerons', '2pl_future': 'donnerez', '3pl_future': 'donneront',
      },
      de: {
        base: 'geben',
        '1sg_present': 'gebe', '2sg_present': 'gibst', '3sg_present': 'gibt',
        '1pl_present': 'geben', '2pl_present': 'gebt', '3pl_present': 'geben',
        '1sg_past': 'gab', '2sg_past': 'gabst', '3sg_past': 'gab',
        '1pl_past': 'gaben', '2pl_past': 'gabt', '3pl_past': 'gaben',
      },
      es: {
        base: 'dar',
        '1sg_present': 'doy', '2sg_present': 'das', '3sg_present': 'da',
        '1pl_present': 'damos', '2pl_present': 'dais', '3pl_present': 'dan',
        '1sg_past': 'di', '2sg_past': 'diste', '3sg_past': 'dio',
        '1pl_past': 'dimos', '2pl_past': 'disteis', '3pl_past': 'dieron',
        '1sg_future': 'daré', '2sg_future': 'darás', '3sg_future': 'dará',
        '1pl_future': 'daremos', '2pl_future': 'daréis', '3pl_future': 'darán',
      },
      ja: {
        base: 'あげる',
        masu_present: 'あげます',
      },
      pt: {
        base: 'dar',
        '1sg_present': 'dou', '2sg_present': 'dás', '3sg_present': 'dá',
        '1pl_present': 'damos', '2pl_present': 'dais', '3pl_present': 'dão',
        '1sg_past': 'dei', '2sg_past': 'deu', '3sg_past': 'deu',
        '1pl_past': 'demos', '2pl_past': 'deram', '3pl_past': 'deram',
        '1sg_future': 'darei', '2sg_future': 'dará', '3sg_future': 'dará',
        '1pl_future': 'daremos', '2pl_future': 'darão', '3pl_future': 'darão',
      },
    },
  },

  {
    id: 'SHOW',
    role: 'verb',
    transitivity: 'ditransitive',
    complements: ['manner', 'terminus', 'cause'],
    description: 'to make something visible to someone',
    emoji: '👁️',
    forms: {
      en: {
        base: 'show',
        '1sg_present': 'show', '2sg_present': 'show', '3sg_present': 'shows',
        '1pl_present': 'show', '2pl_present': 'show', '3pl_present': 'show',
        past: 'showed',
      },
      it: {
        base: 'mostrare',
        '1sg_present': 'mostro', '2sg_present': 'mostri', '3sg_present': 'mostra',
        '1pl_present': 'mostriamo', '2pl_present': 'mostrate', '3pl_present': 'mostrano',
        '1sg_past': 'mostrai', '2sg_past': 'mostrasti', '3sg_past': 'mostrò',
        '1pl_past': 'mostrammo', '2pl_past': 'mostraste', '3pl_past': 'mostrarono',
        '1sg_future': 'mostrerò', '2sg_future': 'mostrerai', '3sg_future': 'mostrerà',
        '1pl_future': 'mostreremo', '2pl_future': 'mostrerete', '3pl_future': 'mostreranno',
      },
      fr: {
        base: 'montrer',
        '1sg_present': 'montre', '2sg_present': 'montres', '3sg_present': 'montre',
        '1pl_present': 'montrons', '2pl_present': 'montrez', '3pl_present': 'montrent',
        '1sg_past': 'montrai', '2sg_past': 'montras', '3sg_past': 'montra',
        '1pl_past': 'montrâmes', '2pl_past': 'montrâtes', '3pl_past': 'montrèrent',
        '1sg_future': 'montrerai', '2sg_future': 'montreras', '3sg_future': 'montrera',
        '1pl_future': 'montrerons', '2pl_future': 'montrerez', '3pl_future': 'montreront',
      },
      de: {
        base: 'zeigen',
        '1sg_present': 'zeige', '2sg_present': 'zeigst', '3sg_present': 'zeigt',
        '1pl_present': 'zeigen', '2pl_present': 'zeigt', '3pl_present': 'zeigen',
        '1sg_past': 'zeigte', '2sg_past': 'zeigtest', '3sg_past': 'zeigte',
        '1pl_past': 'zeigten', '2pl_past': 'zeigtet', '3pl_past': 'zeigten',
      },
      es: {
        base: 'mostrar',
        '1sg_present': 'muestro', '2sg_present': 'muestras', '3sg_present': 'muestra',
        '1pl_present': 'mostramos', '2pl_present': 'mostráis', '3pl_present': 'muestran',
        '1sg_past': 'mostré', '2sg_past': 'mostraste', '3sg_past': 'mostró',
        '1pl_past': 'mostramos', '2pl_past': 'mostrasteis', '3pl_past': 'mostraron',
        '1sg_future': 'mostraré', '2sg_future': 'mostrarás', '3sg_future': 'mostrará',
        '1pl_future': 'mostraremos', '2pl_future': 'mostraréis', '3pl_future': 'mostrarán',
      },
      ja: {
        base: '見せる',
        reading: 'みせる',
        masu_present: '見せます',
        masu_present_reading: 'みせます',
      },
      pt: {
        base: 'mostrar',
        '1sg_present': 'mostro', '2sg_present': 'mostras', '3sg_present': 'mostra',
        '1pl_present': 'mostramos', '2pl_present': 'mostram', '3pl_present': 'mostram',
        '1sg_past': 'mostrei', '2sg_past': 'mostrou', '3sg_past': 'mostrou',
        '1pl_past': 'mostramos', '2pl_past': 'mostraram', '3pl_past': 'mostraram',
        '1sg_future': 'mostrarei', '2sg_future': 'mostrará', '3sg_future': 'mostrará',
        '1pl_future': 'mostraremos', '2pl_future': 'mostrarão', '3pl_future': 'mostrarão',
      },
    },
  },

  {
    id: 'SEND',
    role: 'verb',
    transitivity: 'ditransitive',
    complements: ['manner', 'terminus', 'cause'],
    description: 'to dispatch something to someone',
    emoji: '📨',
    forms: {
      en: {
        base: 'send',
        '1sg_present': 'send', '2sg_present': 'send', '3sg_present': 'sends',
        '1pl_present': 'send', '2pl_present': 'send', '3pl_present': 'send',
        past: 'sent',
      },
      it: {
        base: 'mandare',
        '1sg_present': 'mando', '2sg_present': 'mandi', '3sg_present': 'manda',
        '1pl_present': 'mandiamo', '2pl_present': 'mandate', '3pl_present': 'mandano',
        '1sg_past': 'mandai', '2sg_past': 'mandasti', '3sg_past': 'mandò',
        '1pl_past': 'mandammo', '2pl_past': 'mandaste', '3pl_past': 'mandarono',
        '1sg_future': 'manderò', '2sg_future': 'manderai', '3sg_future': 'manderà',
        '1pl_future': 'manderemo', '2pl_future': 'manderete', '3pl_future': 'manderanno',
      },
      fr: {
        base: 'envoyer',
        '1sg_present': 'envoie', '2sg_present': 'envoies', '3sg_present': 'envoie',
        '1pl_present': 'envoyons', '2pl_present': 'envoyez', '3pl_present': 'envoient',
        '1sg_past': 'envoyai', '2sg_past': 'envoyas', '3sg_past': 'envoya',
        '1pl_past': 'envoyâmes', '2pl_past': 'envoyâtes', '3pl_past': 'envoyèrent',
        '1sg_future': 'enverrai', '2sg_future': 'enverras', '3sg_future': 'enverra',
        '1pl_future': 'enverrons', '2pl_future': 'enverrez', '3pl_future': 'enverront',
      },
      de: {
        base: 'schicken',
        '1sg_present': 'schicke', '2sg_present': 'schickst', '3sg_present': 'schickt',
        '1pl_present': 'schicken', '2pl_present': 'schickt', '3pl_present': 'schicken',
        '1sg_past': 'schickte', '2sg_past': 'schicktest', '3sg_past': 'schickte',
        '1pl_past': 'schickten', '2pl_past': 'schicktet', '3pl_past': 'schickten',
      },
      es: {
        base: 'enviar',
        '1sg_present': 'envío', '2sg_present': 'envías', '3sg_present': 'envía',
        '1pl_present': 'enviamos', '2pl_present': 'enviáis', '3pl_present': 'envían',
        '1sg_past': 'envié', '2sg_past': 'enviaste', '3sg_past': 'envió',
        '1pl_past': 'enviamos', '2pl_past': 'enviasteis', '3pl_past': 'enviaron',
        '1sg_future': 'enviaré', '2sg_future': 'enviarás', '3sg_future': 'enviará',
        '1pl_future': 'enviaremos', '2pl_future': 'enviaréis', '3pl_future': 'enviarán',
      },
      ja: {
        base: '送る',
        reading: 'おくる',
        masu_present: '送ります',
        masu_present_reading: 'おくります',
      },
      pt: {
        base: 'enviar',
        '1sg_present': 'envio', '2sg_present': 'envia', '3sg_present': 'envia',
        '1pl_present': 'enviamos', '2pl_present': 'enviam', '3pl_present': 'enviam',
        '1sg_past': 'enviei', '2sg_past': 'enviou', '3sg_past': 'enviou',
        '1pl_past': 'enviamos', '2pl_past': 'enviaram', '3pl_past': 'enviaram',
        '1sg_future': 'enviarei', '2sg_future': 'enviará', '3sg_future': 'enviará',
        '1pl_future': 'enviaremos', '2pl_future': 'enviarão', '3pl_future': 'enviarão',
      },
    },
  },
];
