import type { ConceptSeed } from '../types.js';

// Plain intransitive verbs.
export const intransitiveVerbs: ConceptSeed[] = [
  {
    id: 'RUN',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['locative', 'direction', 'source', 'route', 'cause'],
    description: 'to move quickly on foot',
    emoji: '🏃',
    forms: {
      en: {
        base: 'run',
        '1sg_present': 'run', '2sg_present': 'run', '3sg_present': 'runs',
        '1pl_present': 'run', '2pl_present': 'run', '3pl_present': 'run',
        past: 'ran',
      },
      it: {
        base: 'correre',
        '1sg_present': 'corro', '2sg_present': 'corri', '3sg_present': 'corre',
        '1pl_present': 'corriamo', '2pl_present': 'correte', '3pl_present': 'corrono',
        '1sg_past': 'corsi', '2sg_past': 'corresti', '3sg_past': 'corse',
        '1pl_past': 'corremmo', '2pl_past': 'correste', '3pl_past': 'corsero',
        '1sg_future': 'correrò', '2sg_future': 'correrai', '3sg_future': 'correrà',
        '1pl_future': 'correremo', '2pl_future': 'correrete', '3pl_future': 'correranno',
      },
      fr: {
        base: 'courir',
        '1sg_present': 'cours', '2sg_present': 'cours', '3sg_present': 'court',
        '1pl_present': 'courons', '2pl_present': 'courez', '3pl_present': 'courent',
        '1sg_past': 'courus', '2sg_past': 'courus', '3sg_past': 'courut',
        '1pl_past': 'courûmes', '2pl_past': 'courûtes', '3pl_past': 'coururent',
        '1sg_future': 'courrai', '2sg_future': 'courras', '3sg_future': 'courra',
        '1pl_future': 'courrons', '2pl_future': 'courrez', '3pl_future': 'courront',
      },
      de: {
        base: 'laufen',
        '1sg_present': 'laufe', '2sg_present': 'läufst', '3sg_present': 'läuft',
        '1pl_present': 'laufen', '2pl_present': 'lauft', '3pl_present': 'laufen',
        '1sg_past': 'lief', '2sg_past': 'liefst', '3sg_past': 'lief',
        '1pl_past': 'liefen', '2pl_past': 'lieft', '3pl_past': 'liefen',
      },
      es: {
        base: 'correr',
        '1sg_present': 'corro', '2sg_present': 'corres', '3sg_present': 'corre',
        '1pl_present': 'corremos', '2pl_present': 'corréis', '3pl_present': 'corren',
        '1sg_past': 'corrí', '2sg_past': 'corriste', '3sg_past': 'corrió',
        '1pl_past': 'corrimos', '2pl_past': 'corristeis', '3pl_past': 'corrieron',
        '1sg_future': 'correré', '2sg_future': 'correrás', '3sg_future': 'correrá',
        '1pl_future': 'correremos', '2pl_future': 'correréis', '3pl_future': 'correrán',
      },
      ja: {
        base: '走る',
        reading: 'はしる',
        masu_present: '走ります',
        masu_present_reading: 'はしります',
      },
      pt: {
        base: 'correr',
        '1sg_present': 'corro', '2sg_present': 'corre', '3sg_present': 'corre',
        '1pl_present': 'corremos', '2pl_present': 'correm', '3pl_present': 'correm',
        '1sg_past': 'corri', '2sg_past': 'correu', '3sg_past': 'correu',
        '1pl_past': 'corremos', '2pl_past': 'correram', '3pl_past': 'correram',
        '1sg_future': 'correrei', '2sg_future': 'correrá', '3sg_future': 'correrá',
        '1pl_future': 'correremos', '2pl_future': 'correrão', '3pl_future': 'correrão',
      },
    },
  },

  {
    id: 'JUMP',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['locative', 'direction', 'source', 'route', 'cause'],
    description: 'to propel oneself into the air',
    emoji: '🦘',
    forms: {
      en: {
        base: 'jump',
        '1sg_present': 'jump', '2sg_present': 'jump', '3sg_present': 'jumps',
        '1pl_present': 'jump', '2pl_present': 'jump', '3pl_present': 'jump',
        past: 'jumped',
      },
      it: {
        base: 'saltare',
        '1sg_present': 'salto', '2sg_present': 'salti', '3sg_present': 'salta',
        '1pl_present': 'saltiamo', '2pl_present': 'saltate', '3pl_present': 'saltano',
        '1sg_past': 'saltai', '2sg_past': 'saltasti', '3sg_past': 'saltò',
        '1pl_past': 'saltammo', '2pl_past': 'saltaste', '3pl_past': 'saltarono',
        '1sg_future': 'salterò', '2sg_future': 'salterai', '3sg_future': 'salterà',
        '1pl_future': 'salteremo', '2pl_future': 'salterete', '3pl_future': 'salteranno',
      },
      fr: {
        base: 'sauter',
        '1sg_present': 'saute', '2sg_present': 'sautes', '3sg_present': 'saute',
        '1pl_present': 'sautons', '2pl_present': 'sautez', '3pl_present': 'sautent',
        '1sg_past': 'sautai', '2sg_past': 'sautas', '3sg_past': 'sauta',
        '1pl_past': 'sautâmes', '2pl_past': 'sautâtes', '3pl_past': 'sautèrent',
        '1sg_future': 'sauterai', '2sg_future': 'sauteras', '3sg_future': 'sautera',
        '1pl_future': 'sauterons', '2pl_future': 'sauterez', '3pl_future': 'sauteront',
      },
      de: {
        base: 'springen',
        '1sg_present': 'springe', '2sg_present': 'springst', '3sg_present': 'springt',
        '1pl_present': 'springen', '2pl_present': 'springt', '3pl_present': 'springen',
        '1sg_past': 'sprang', '2sg_past': 'sprangst', '3sg_past': 'sprang',
        '1pl_past': 'sprangen', '2pl_past': 'sprangt', '3pl_past': 'sprangen',
      },
      es: {
        base: 'saltar',
        '1sg_present': 'salto', '2sg_present': 'saltas', '3sg_present': 'salta',
        '1pl_present': 'saltamos', '2pl_present': 'saltáis', '3pl_present': 'saltan',
        '1sg_past': 'salté', '2sg_past': 'saltaste', '3sg_past': 'saltó',
        '1pl_past': 'saltamos', '2pl_past': 'saltasteis', '3pl_past': 'saltaron',
        '1sg_future': 'saltaré', '2sg_future': 'saltarás', '3sg_future': 'saltará',
        '1pl_future': 'saltaremos', '2pl_future': 'saltaréis', '3pl_future': 'saltarán',
      },
      ja: {
        base: '跳ぶ',
        reading: 'とぶ',
        masu_present: '跳びます',
        masu_present_reading: 'とびます',
      },
      pt: {
        base: 'pular',
        '1sg_present': 'pulo', '2sg_present': 'pula', '3sg_present': 'pula',
        '1pl_present': 'pulamos', '2pl_present': 'pulam', '3pl_present': 'pulam',
        '1sg_past': 'pulei', '2sg_past': 'pulou', '3sg_past': 'pulou',
        '1pl_past': 'pulamos', '2pl_past': 'pularam', '3pl_past': 'pularam',
        '1sg_future': 'pularei', '2sg_future': 'pulará', '3sg_future': 'pulará',
        '1pl_future': 'pularemos', '2pl_future': 'pularão', '3pl_future': 'pularão',
      },
    },
  },

  {
    id: 'COME',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['locative', 'direction', 'source', 'route', 'cause'],
    description: 'to move toward the speaker or a place',
    emoji: '🚶',
    forms: {
      en: {
        base: 'come',
        '1sg_present': 'come', '2sg_present': 'come', '3sg_present': 'comes',
        '1pl_present': 'come', '2pl_present': 'come', '3pl_present': 'come',
        past: 'came',
      },
      it: {
        base: 'venire',
        '1sg_present': 'vengo', '2sg_present': 'vieni', '3sg_present': 'viene',
        '1pl_present': 'veniamo', '2pl_present': 'venite', '3pl_present': 'vengono',
        '1sg_past': 'venni', '2sg_past': 'venisti', '3sg_past': 'venne',
        '1pl_past': 'venimmo', '2pl_past': 'veniste', '3pl_past': 'vennero',
        '1sg_future': 'verrò', '2sg_future': 'verrai', '3sg_future': 'verrà',
        '1pl_future': 'verremo', '2pl_future': 'verrete', '3pl_future': 'verranno',
      },
      fr: {
        base: 'venir',
        '1sg_present': 'viens', '2sg_present': 'viens', '3sg_present': 'vient',
        '1pl_present': 'venons', '2pl_present': 'venez', '3pl_present': 'viennent',
        '1sg_past': 'vins', '2sg_past': 'vins', '3sg_past': 'vint',
        '1pl_past': 'vînmes', '2pl_past': 'vîntes', '3pl_past': 'vinrent',
        '1sg_future': 'viendrai', '2sg_future': 'viendras', '3sg_future': 'viendra',
        '1pl_future': 'viendrons', '2pl_future': 'viendrez', '3pl_future': 'viendront',
      },
      de: {
        base: 'kommen',
        '1sg_present': 'komme', '2sg_present': 'kommst', '3sg_present': 'kommt',
        '1pl_present': 'kommen', '2pl_present': 'kommt', '3pl_present': 'kommen',
        '1sg_past': 'kam', '2sg_past': 'kamst', '3sg_past': 'kam',
        '1pl_past': 'kamen', '2pl_past': 'kamt', '3pl_past': 'kamen',
      },
      es: {
        base: 'venir',
        '1sg_present': 'vengo', '2sg_present': 'vienes', '3sg_present': 'viene',
        '1pl_present': 'venimos', '2pl_present': 'venís', '3pl_present': 'vienen',
        '1sg_past': 'vine', '2sg_past': 'viniste', '3sg_past': 'vino',
        '1pl_past': 'vinimos', '2pl_past': 'vinisteis', '3pl_past': 'vinieron',
        '1sg_future': 'vendré', '2sg_future': 'vendrás', '3sg_future': 'vendrá',
        '1pl_future': 'vendremos', '2pl_future': 'vendréis', '3pl_future': 'vendrán',
      },
      ja: {
        base: '来る',
        reading: 'くる',
        masu_present: '来ます',
        masu_present_reading: 'きます',
      },
      pt: {
        base: 'vir',
        '1sg_present': 'venho', '2sg_present': 'vem', '3sg_present': 'vem',
        '1pl_present': 'vimos', '2pl_present': 'vêm', '3pl_present': 'vêm',
        '1sg_past': 'vim', '2sg_past': 'veio', '3sg_past': 'veio',
        '1pl_past': 'viemos', '2pl_past': 'vieram', '3pl_past': 'vieram',
        '1sg_future': 'virei', '2sg_future': 'virá', '3sg_future': 'virá',
        '1pl_future': 'viremos', '2pl_future': 'virão', '3pl_future': 'virão',
      },
    },
  },

  {
    id: 'CRY',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['cause'],
    description: 'to weep; to shed tears',
    emoji: '😭',
    synonym: 'weep',
    forms: {
      en: {
        base: 'cry',
        '1sg_present': 'cry', '2sg_present': 'cry', '3sg_present': 'cries',
        '1pl_present': 'cry', '2pl_present': 'cry', '3pl_present': 'cry',
        past: 'cried',
      },
      it: {
        base: 'piangere',
        '1sg_present': 'piango', '2sg_present': 'piangi', '3sg_present': 'piange',
        '1pl_present': 'piangiamo', '2pl_present': 'piangete', '3pl_present': 'piangono',
        '1sg_past': 'piansi', '2sg_past': 'piangesti', '3sg_past': 'pianse',
        '1pl_past': 'piangemmo', '2pl_past': 'piangeste', '3pl_past': 'piansero',
        '1sg_future': 'piangerò', '2sg_future': 'piangerai', '3sg_future': 'piangerà',
        '1pl_future': 'piangeremo', '2pl_future': 'piangerete', '3pl_future': 'piangeranno',
      },
      fr: {
        base: 'pleurer',
        '1sg_present': 'pleure', '2sg_present': 'pleures', '3sg_present': 'pleure',
        '1pl_present': 'pleurons', '2pl_present': 'pleurez', '3pl_present': 'pleurent',
        '1sg_past': 'pleurai', '2sg_past': 'pleuras', '3sg_past': 'pleura',
        '1pl_past': 'pleurâmes', '2pl_past': 'pleurâtes', '3pl_past': 'pleurèrent',
        '1sg_future': 'pleurerai', '2sg_future': 'pleureras', '3sg_future': 'pleurera',
        '1pl_future': 'pleurerons', '2pl_future': 'pleurerez', '3pl_future': 'pleureront',
      },
      de: {
        base: 'weinen',
        '1sg_present': 'weine', '2sg_present': 'weinst', '3sg_present': 'weint',
        '1pl_present': 'weinen', '2pl_present': 'weint', '3pl_present': 'weinen',
        '1sg_past': 'weinte', '2sg_past': 'weintest', '3sg_past': 'weinte',
        '1pl_past': 'weinten', '2pl_past': 'weintet', '3pl_past': 'weinten',
      },
      es: {
        base: 'llorar',
        '1sg_present': 'lloro', '2sg_present': 'lloras', '3sg_present': 'llora',
        '1pl_present': 'lloramos', '2pl_present': 'lloráis', '3pl_present': 'lloran',
        '1sg_past': 'lloré', '2sg_past': 'lloraste', '3sg_past': 'lloró',
        '1pl_past': 'lloramos', '2pl_past': 'llorasteis', '3pl_past': 'lloraron',
        '1sg_future': 'lloraré', '2sg_future': 'llorarás', '3sg_future': 'llorará',
        '1pl_future': 'lloraremos', '2pl_future': 'lloraréis', '3pl_future': 'llorarán',
      },
      ja: {
        base: '泣く',
        reading: 'なく',
        masu_present: '泣きます',
        masu_present_reading: 'なきます',
      },
      pt: {
        base: 'chorar',
        '1sg_present': 'choro', '2sg_present': 'chora', '3sg_present': 'chora',
        '1pl_present': 'choramos', '2pl_present': 'choram', '3pl_present': 'choram',
        '1sg_past': 'chorei', '2sg_past': 'chorou', '3sg_past': 'chorou',
        '1pl_past': 'choramos', '2pl_past': 'choraram', '3pl_past': 'choraram',
        '1sg_future': 'chorarei', '2sg_future': 'chorará', '3sg_future': 'chorará',
        '1pl_future': 'choraremos', '2pl_future': 'chorarão', '3pl_future': 'chorarão',
      },
    },
  },

  {
    id: 'BURN',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['cause'],
    description: 'to be on fire; to undergo combustion',
    emoji: '🔥',
    synonym: 'be on fire',
    forms: {
      en: {
        base: 'burn',
        '1sg_present': 'burn', '2sg_present': 'burn', '3sg_present': 'burns',
        '1pl_present': 'burn', '2pl_present': 'burn', '3pl_present': 'burn',
        past: 'burned',
      },
      it: {
        base: 'bruciare',
        '1sg_present': 'brucio', '2sg_present': 'bruci', '3sg_present': 'brucia',
        '1pl_present': 'bruciamo', '2pl_present': 'bruciate', '3pl_present': 'bruciano',
        '1sg_past': 'bruciai', '2sg_past': 'bruciasti', '3sg_past': 'bruciò',
        '1pl_past': 'bruciammo', '2pl_past': 'bruciaste', '3pl_past': 'bruciarono',
        '1sg_future': 'brucerò', '2sg_future': 'brucerai', '3sg_future': 'brucerà',
        '1pl_future': 'bruceremo', '2pl_future': 'brucerete', '3pl_future': 'bruceranno',
      },
      fr: {
        base: 'brûler',
        '1sg_present': 'brûle', '2sg_present': 'brûles', '3sg_present': 'brûle',
        '1pl_present': 'brûlons', '2pl_present': 'brûlez', '3pl_present': 'brûlent',
        '1sg_past': 'brûlai', '2sg_past': 'brûlas', '3sg_past': 'brûla',
        '1pl_past': 'brûlâmes', '2pl_past': 'brûlâtes', '3pl_past': 'brûlèrent',
        '1sg_future': 'brûlerai', '2sg_future': 'brûleras', '3sg_future': 'brûlera',
        '1pl_future': 'brûlerons', '2pl_future': 'brûlerez', '3pl_future': 'brûleront',
      },
      de: {
        base: 'brennen',
        '1sg_present': 'brenne', '2sg_present': 'brennst', '3sg_present': 'brennt',
        '1pl_present': 'brennen', '2pl_present': 'brennt', '3pl_present': 'brennen',
        '1sg_past': 'brannte', '2sg_past': 'branntest', '3sg_past': 'brannte',
        '1pl_past': 'brannten', '2pl_past': 'branntet', '3pl_past': 'brannten',
      },
      es: {
        base: 'arder',
        '1sg_present': 'ardo', '2sg_present': 'ardes', '3sg_present': 'arde',
        '1pl_present': 'ardemos', '2pl_present': 'ardéis', '3pl_present': 'arden',
        '1sg_past': 'ardí', '2sg_past': 'ardiste', '3sg_past': 'ardió',
        '1pl_past': 'ardimos', '2pl_past': 'ardisteis', '3pl_past': 'ardieron',
        '1sg_future': 'arderé', '2sg_future': 'arderás', '3sg_future': 'arderá',
        '1pl_future': 'arderemos', '2pl_future': 'arderéis', '3pl_future': 'arderán',
      },
      ja: {
        base: '燃える',
        reading: 'もえる',
        masu_present: '燃えます',
        masu_present_reading: 'もえます',
      },
      pt: {
        base: 'arder',
        '1sg_present': 'ardo', '2sg_present': 'arde', '3sg_present': 'arde',
        '1pl_present': 'ardemos', '2pl_present': 'ardem', '3pl_present': 'ardem',
        '1sg_past': 'ardi', '2sg_past': 'ardeu', '3sg_past': 'ardeu',
        '1pl_past': 'ardemos', '2pl_past': 'arderam', '3pl_past': 'arderam',
        '1sg_future': 'arderei', '2sg_future': 'arderá', '3sg_future': 'arderá',
        '1pl_future': 'arderemos', '2pl_future': 'arderão', '3pl_future': 'arderão',
      },
    },
  },
];
