import type { ConceptSeed } from '../types.js';

// Motion & copular verbs (license locative / direction / source / route).
export const motionVerbs: ConceptSeed[] = [
  {
    id: 'GO',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['locative', 'direction', 'source', 'route', 'cause'],
    description: 'to move or travel from one place to another',
    emoji: '🚶',
    forms: {
      en: {
        base: 'go',
        '1sg_present': 'go', '2sg_present': 'go', '3sg_present': 'goes',
        '1pl_present': 'go', '2pl_present': 'go', '3pl_present': 'go',
        past: 'went',
      },
      it: {
        base: 'andare',
        '1sg_present': 'vado', '2sg_present': 'vai', '3sg_present': 'va',
        '1pl_present': 'andiamo', '2pl_present': 'andate', '3pl_present': 'vanno',
        '1sg_past': 'andai', '2sg_past': 'andasti', '3sg_past': 'andò',
        '1pl_past': 'andammo', '2pl_past': 'andaste', '3pl_past': 'andarono',
        '1sg_future': 'andrò', '2sg_future': 'andrai', '3sg_future': 'andrà',
        '1pl_future': 'andremo', '2pl_future': 'andrete', '3pl_future': 'andranno',
      },
      fr: {
        base: 'aller',
        '1sg_present': 'vais', '2sg_present': 'vas', '3sg_present': 'va',
        '1pl_present': 'allons', '2pl_present': 'allez', '3pl_present': 'vont',
        '1sg_past': 'allai', '2sg_past': 'allas', '3sg_past': 'alla',
        '1pl_past': 'allâmes', '2pl_past': 'allâtes', '3pl_past': 'allèrent',
        '1sg_future': 'irai', '2sg_future': 'iras', '3sg_future': 'ira',
        '1pl_future': 'irons', '2pl_future': 'irez', '3pl_future': 'iront',
      },
      de: {
        base: 'gehen',
        '1sg_present': 'gehe', '2sg_present': 'gehst', '3sg_present': 'geht',
        '1pl_present': 'gehen', '2pl_present': 'geht', '3pl_present': 'gehen',
        '1sg_past': 'ging', '2sg_past': 'gingst', '3sg_past': 'ging',
        '1pl_past': 'gingen', '2pl_past': 'gingt', '3pl_past': 'gingen',
      },
      es: {
        base: 'ir',
        '1sg_present': 'voy', '2sg_present': 'vas', '3sg_present': 'va',
        '1pl_present': 'vamos', '2pl_present': 'vais', '3pl_present': 'van',
        '1sg_past': 'fui', '2sg_past': 'fuiste', '3sg_past': 'fue',
        '1pl_past': 'fuimos', '2pl_past': 'fuisteis', '3pl_past': 'fueron',
        '1sg_future': 'iré', '2sg_future': 'irás', '3sg_future': 'irá',
        '1pl_future': 'iremos', '2pl_future': 'iréis', '3pl_future': 'irán',
      },
      ja: {
        base: '行く',
        reading: 'いく',
        masu_present: '行きます',
        masu_present_reading: 'いきます',
      },
      pt: {
        base: 'ir',
        '1sg_present': 'vou', '2sg_present': 'vai', '3sg_present': 'vai',
        '1pl_present': 'vamos', '2pl_present': 'vão', '3pl_present': 'vão',
        '1sg_past': 'fui', '2sg_past': 'foi', '3sg_past': 'foi',
        '1pl_past': 'fomos', '2pl_past': 'foram', '3pl_past': 'foram',
        '1sg_future': 'irei', '2sg_future': 'irá', '3sg_future': 'irá',
        '1pl_future': 'iremos', '2pl_future': 'irão', '3pl_future': 'irão',
      },
    },
  },

  {
    id: 'BECOME',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['predicative', 'cause'],
    description: 'to come to be; to change into a different state',
    emoji: '🦋',
    forms: {
      en: {
        base: 'become',
        '1sg_present': 'become', '2sg_present': 'become', '3sg_present': 'becomes',
        '1pl_present': 'become', '2pl_present': 'become', '3pl_present': 'become',
        past: 'became',
      },
      it: {
        base: 'diventare',
        '1sg_present': 'divento', '2sg_present': 'diventi', '3sg_present': 'diventa',
        '1pl_present': 'diventiamo', '2pl_present': 'diventate', '3pl_present': 'diventano',
        '1sg_past': 'diventai', '2sg_past': 'diventasti', '3sg_past': 'diventò',
        '1pl_past': 'diventammo', '2pl_past': 'diventaste', '3pl_past': 'diventarono',
        '1sg_future': 'diventerò', '2sg_future': 'diventerai', '3sg_future': 'diventerà',
        '1pl_future': 'diventeremo', '2pl_future': 'diventerete', '3pl_future': 'diventeranno',
      },
      fr: {
        base: 'devenir',
        '1sg_present': 'deviens', '2sg_present': 'deviens', '3sg_present': 'devient',
        '1pl_present': 'devenons', '2pl_present': 'devenez', '3pl_present': 'deviennent',
        '1sg_past': 'devins', '2sg_past': 'devins', '3sg_past': 'devint',
        '1pl_past': 'devînmes', '2pl_past': 'devîntes', '3pl_past': 'devinrent',
        '1sg_future': 'deviendrai', '2sg_future': 'deviendras', '3sg_future': 'deviendra',
        '1pl_future': 'deviendrons', '2pl_future': 'deviendrez', '3pl_future': 'deviendront',
      },
      de: {
        base: 'werden',
        '1sg_present': 'werde', '2sg_present': 'wirst', '3sg_present': 'wird',
        '1pl_present': 'werden', '2pl_present': 'werdet', '3pl_present': 'werden',
        '1sg_past': 'wurde', '2sg_past': 'wurdest', '3sg_past': 'wurde',
        '1pl_past': 'wurden', '2pl_past': 'wurdet', '3pl_past': 'wurden',
      },
      es: {
        base: 'volverse',
        '1sg_present': 'me vuelvo', '2sg_present': 'te vuelves', '3sg_present': 'se vuelve',
        '1pl_present': 'nos volvemos', '2pl_present': 'os volvéis', '3pl_present': 'se vuelven',
        '1sg_past': 'me volví', '2sg_past': 'te volviste', '3sg_past': 'se volvió',
        '1pl_past': 'nos volvimos', '2pl_past': 'os volvisteis', '3pl_past': 'se volvieron',
        '1sg_future': 'me volveré', '2sg_future': 'te volverás', '3sg_future': 'se volverá',
        '1pl_future': 'nos volveremos', '2pl_future': 'os volveréis', '3pl_future': 'se volverán',
      },
      ja: {
        base: 'なる',
        reading: 'なる',
        masu_present: 'なります',
        masu_present_reading: 'なります',
      },
      pt: {
        base: 'tornar-se',
        '1sg_present': 'me torno', '2sg_present': 'te tornas', '3sg_present': 'se torna',
        '1pl_present': 'nos tornamos', '2pl_present': 'se tornam', '3pl_present': 'se tornam',
        '1sg_past': 'me tornei', '2sg_past': 'te tornaste', '3sg_past': 'se tornou',
        '1pl_past': 'nos tornamos', '2pl_past': 'se tornaram', '3pl_past': 'se tornaram',
        '1sg_future': 'me tornarei', '2sg_future': 'te tornarás', '3sg_future': 'se tornará',
        '1pl_future': 'nos tornaremos', '2pl_future': 'se tornarão', '3pl_future': 'se tornarão',
      },
    },
  },

  {
    id: 'SEEM',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['predicative', 'locative', 'cause', 'terminus'],
    description: 'to give the impression of being; to appear to be',
    emoji: '🤔',
    forms: {
      en: {
        base: 'seem',
        '1sg_present': 'seem', '2sg_present': 'seem', '3sg_present': 'seems',
        '1pl_present': 'seem', '2pl_present': 'seem', '3pl_present': 'seem',
        past: 'seemed',
      },
      it: {
        base: 'sembrare',
        '1sg_present': 'sembro', '2sg_present': 'sembri', '3sg_present': 'sembra',
        '1pl_present': 'sembriamo', '2pl_present': 'sembrate', '3pl_present': 'sembrano',
        '1sg_past': 'sembrai', '2sg_past': 'sembrasti', '3sg_past': 'sembrò',
        '1pl_past': 'sembrammo', '2pl_past': 'sembraste', '3pl_past': 'sembrarono',
        '1sg_future': 'sembrerò', '2sg_future': 'sembrerai', '3sg_future': 'sembrerà',
        '1pl_future': 'sembreremo', '2pl_future': 'sembrerete', '3pl_future': 'sembreranno',
      },
      fr: {
        base: 'sembler',
        '1sg_present': 'semble', '2sg_present': 'sembles', '3sg_present': 'semble',
        '1pl_present': 'semblons', '2pl_present': 'semblez', '3pl_present': 'semblent',
        '1sg_past': 'semblai', '2sg_past': 'semblas', '3sg_past': 'sembla',
        '1pl_past': 'semblâmes', '2pl_past': 'semblâtes', '3pl_past': 'semblèrent',
        '1sg_future': 'semblerai', '2sg_future': 'sembleras', '3sg_future': 'semblera',
        '1pl_future': 'semblerons', '2pl_future': 'semblerez', '3pl_future': 'sembleront',
      },
      de: {
        base: 'scheinen',
        '1sg_present': 'scheine', '2sg_present': 'scheinst', '3sg_present': 'scheint',
        '1pl_present': 'scheinen', '2pl_present': 'scheint', '3pl_present': 'scheinen',
        '1sg_past': 'schien', '2sg_past': 'schienst', '3sg_past': 'schien',
        '1pl_past': 'schienen', '2pl_past': 'schient', '3pl_past': 'schienen',
      },
      es: {
        base: 'parecer',
        '1sg_present': 'parezco', '2sg_present': 'pareces', '3sg_present': 'parece',
        '1pl_present': 'parecemos', '2pl_present': 'parecéis', '3pl_present': 'parecen',
        '1sg_past': 'parecí', '2sg_past': 'pareciste', '3sg_past': 'pareció',
        '1pl_past': 'parecimos', '2pl_past': 'parecisteis', '3pl_past': 'parecieron',
        '1sg_future': 'pareceré', '2sg_future': 'parecerás', '3sg_future': 'parecerá',
        '1pl_future': 'pareceremos', '2pl_future': 'pareceréis', '3pl_future': 'parecerán',
      },
      ja: {
        base: '思える',
        reading: 'おもえる',
        masu_present: '思えます',
        masu_present_reading: 'おもえます',
      },
      pt: {
        base: 'parecer',
        '1sg_present': 'pareço', '2sg_present': 'pareces', '3sg_present': 'parece',
        '1pl_present': 'parecemos', '2pl_present': 'parecem', '3pl_present': 'parecem',
        '1sg_past': 'pareci', '2sg_past': 'pareceu', '3sg_past': 'pareceu',
        '1pl_past': 'parecemos', '2pl_past': 'pareceram', '3pl_past': 'pareceram',
        '1sg_future': 'parecerei', '2sg_future': 'parecerá', '3sg_future': 'parecerá',
        '1pl_future': 'pareceremos', '2pl_future': 'parecerão', '3pl_future': 'parecerão',
      },
    },
  },

  {
    id: 'APPEAR',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['predicative', 'locative', 'cause', 'terminus'],
    description: 'to come into view; to look or seem a certain way',
    emoji: '👀',
    forms: {
      en: {
        base: 'appear',
        '1sg_present': 'appear', '2sg_present': 'appear', '3sg_present': 'appears',
        '1pl_present': 'appear', '2pl_present': 'appear', '3pl_present': 'appear',
        past: 'appeared',
      },
      it: {
        base: 'apparire',
        '1sg_present': 'appaio', '2sg_present': 'appari', '3sg_present': 'appare',
        '1pl_present': 'appariamo', '2pl_present': 'apparite', '3pl_present': 'appaiono',
        '1sg_past': 'apparvi', '2sg_past': 'apparisti', '3sg_past': 'apparve',
        '1pl_past': 'apparimmo', '2pl_past': 'appariste', '3pl_past': 'apparvero',
        '1sg_future': 'apparirò', '2sg_future': 'apparirai', '3sg_future': 'apparirà',
        '1pl_future': 'appariremo', '2pl_future': 'apparirete', '3pl_future': 'appariranno',
      },
      fr: {
        base: 'apparaître',
        '1sg_present': 'apparais', '2sg_present': 'apparais', '3sg_present': 'apparaît',
        '1pl_present': 'apparaissons', '2pl_present': 'apparaissez', '3pl_present': 'apparaissent',
        '1sg_past': 'apparus', '2sg_past': 'apparus', '3sg_past': 'apparut',
        '1pl_past': 'apparûmes', '2pl_past': 'apparûtes', '3pl_past': 'apparurent',
        '1sg_future': 'apparaîtrai', '2sg_future': 'apparaîtras', '3sg_future': 'apparaîtra',
        '1pl_future': 'apparaîtrons', '2pl_future': 'apparaîtrez', '3pl_future': 'apparaîtront',
      },
      de: {
        base: 'erscheinen',
        '1sg_present': 'erscheine', '2sg_present': 'erscheinst', '3sg_present': 'erscheint',
        '1pl_present': 'erscheinen', '2pl_present': 'erscheint', '3pl_present': 'erscheinen',
        '1sg_past': 'erschien', '2sg_past': 'erschienst', '3sg_past': 'erschien',
        '1pl_past': 'erschienen', '2pl_past': 'erschient', '3pl_past': 'erschienen',
      },
      es: {
        base: 'aparecer',
        '1sg_present': 'aparezco', '2sg_present': 'apareces', '3sg_present': 'aparece',
        '1pl_present': 'aparecemos', '2pl_present': 'aparecéis', '3pl_present': 'aparecen',
        '1sg_past': 'aparecí', '2sg_past': 'apareciste', '3sg_past': 'apareció',
        '1pl_past': 'aparecimos', '2pl_past': 'aparecisteis', '3pl_past': 'aparecieron',
        '1sg_future': 'apareceré', '2sg_future': 'aparecerás', '3sg_future': 'aparecerá',
        '1pl_future': 'apareceremos', '2pl_future': 'apareceréis', '3pl_future': 'aparecerán',
      },
      ja: {
        base: '見える',
        reading: 'みえる',
        masu_present: '見えます',
        masu_present_reading: 'みえます',
      },
      pt: {
        base: 'aparecer',
        '1sg_present': 'apareço', '2sg_present': 'apareces', '3sg_present': 'aparece',
        '1pl_present': 'aparecemos', '2pl_present': 'aparecem', '3pl_present': 'aparecem',
        '1sg_past': 'apareci', '2sg_past': 'apareceu', '3sg_past': 'apareceu',
        '1pl_past': 'aparecemos', '2pl_past': 'apareceram', '3pl_past': 'apareceram',
        '1sg_future': 'aparecerei', '2sg_future': 'aparecerá', '3sg_future': 'aparecerá',
        '1pl_future': 'apareceremos', '2pl_future': 'aparecerão', '3pl_future': 'aparecerão',
      },
    },
  },

  {
    // The copula "to be" + a predicate adjective — the plain "is careful" that BECOME/SEEM/
    // APPEAR can't express. `copula: '1'` is the marker the en engine reads to negate directly
    // ("is not careful", not "*does not be") and the ja engine reads to render です (慎重です),
    // not the になる-flavoured に. it/fr/de/es/pt treat it as an ordinary intransitive verb whose
    // predicative adjective agrees with the subject — the path BECOME already exercises.
    id: 'BE',
    role: 'verb',
    transitivity: 'intransitive',
    complements: ['predicative', 'locative', 'cause'],
    description: 'to have a quality or state; the copula',
    emoji: '🟰',
    forms: {
      en: {
        base: 'be', copula: '1',
        '1sg_present': 'am', '2sg_present': 'are', '3sg_present': 'is',
        '1pl_present': 'are', '2pl_present': 'are', '3pl_present': 'are',
        '1sg_past': 'was', '2sg_past': 'were', '3sg_past': 'was',
        '1pl_past': 'were', '2pl_past': 'were', '3pl_past': 'were',
      },
      it: {
        base: 'essere', copula: '1',
        '1sg_present': 'sono', '2sg_present': 'sei', '3sg_present': 'è',
        '1pl_present': 'siamo', '2pl_present': 'siete', '3pl_present': 'sono',
        '1sg_past': 'fui', '2sg_past': 'fosti', '3sg_past': 'fu',
        '1pl_past': 'fummo', '2pl_past': 'foste', '3pl_past': 'furono',
        '1sg_future': 'sarò', '2sg_future': 'sarai', '3sg_future': 'sarà',
        '1pl_future': 'saremo', '2pl_future': 'sarete', '3pl_future': 'saranno',
      },
      fr: {
        base: 'être', copula: '1',
        '1sg_present': 'suis', '2sg_present': 'es', '3sg_present': 'est',
        '1pl_present': 'sommes', '2pl_present': 'êtes', '3pl_present': 'sont',
        '1sg_past': 'fus', '2sg_past': 'fus', '3sg_past': 'fut',
        '1pl_past': 'fûmes', '2pl_past': 'fûtes', '3pl_past': 'furent',
        '1sg_future': 'serai', '2sg_future': 'seras', '3sg_future': 'sera',
        '1pl_future': 'serons', '2pl_future': 'serez', '3pl_future': 'seront',
      },
      de: {
        base: 'sein', copula: '1',
        '1sg_present': 'bin', '2sg_present': 'bist', '3sg_present': 'ist',
        '1pl_present': 'sind', '2pl_present': 'seid', '3pl_present': 'sind',
        '1sg_past': 'war', '2sg_past': 'warst', '3sg_past': 'war',
        '1pl_past': 'waren', '2pl_past': 'wart', '3pl_past': 'waren',
      },
      es: {
        base: 'ser', copula: '1',
        '1sg_present': 'soy', '2sg_present': 'eres', '3sg_present': 'es',
        '1pl_present': 'somos', '2pl_present': 'sois', '3pl_present': 'son',
        '1sg_past': 'fui', '2sg_past': 'fuiste', '3sg_past': 'fue',
        '1pl_past': 'fuimos', '2pl_past': 'fuisteis', '3pl_past': 'fueron',
        '1sg_future': 'seré', '2sg_future': 'serás', '3sg_future': 'será',
        '1pl_future': 'seremos', '2pl_future': 'seréis', '3pl_future': 'serán',
      },
      ja: {
        // Rendered specially by the engine (copula です on the predicate), so these are a
        // safety fallback only — BE is never picked without a predicative.
        base: 'です', copula: '1',
        masu_present: 'です',
      },
      pt: {
        base: 'ser', copula: '1',
        '1sg_present': 'sou', '2sg_present': 'és', '3sg_present': 'é',
        '1pl_present': 'somos', '2pl_present': 'sois', '3pl_present': 'são',
        '1sg_past': 'fui', '2sg_past': 'foste', '3sg_past': 'foi',
        '1pl_past': 'fomos', '2pl_past': 'fostes', '3pl_past': 'foram',
        '1sg_future': 'serei', '2sg_future': 'serás', '3sg_future': 'será',
        '1pl_future': 'seremos', '2pl_future': 'sereis', '3pl_future': 'serão',
      },
    },
  },
];
