/**
 * Non-finite verb forms that feed the grammatical *aspect* (progressive / prospective /
 * resultative). Kept as one table rather than scattered across every verb block: the seed
 * loop merges the per-language entry into that verb's forms before persisting them.
 *   • gerund     — present participle / gerundio / gerúndio (en/it/es/pt progressive).
 *   • participle — past participle (all Romance + de/en resultative; fr also for resultative).
 *   • te / te_reading — Japanese te-form, the base for the progressive and the perfect's ～ている.
 *   • nai / nai_reading — Japanese plain negative (食べない), the base for the negative たら
 *     (食べなかったら) and for every plain negative predicate: a negated relative clause (食べない猫,
 *     食べなかった猫), citation (食べない。) and purpose clause (食べないために) (B13).
 *   • passive / passive_reading — Japanese passive (食べられる), on the **transitive** verbs, the
 *     only ones a passive plan can reach (A01). Where the six European languages build their
 *     passive from an auxiliary plus the `participle` already here, Japanese has morphology:
 *     ichidan takes られる (食べる → 食べられる), godan the あ-stem + れる (飲む → 飲まれる), and the
 *     irregulars share no rule at all (する → される, 来る → 来られる), so the form is stored rather
 *     than derived, exactly as the participles and te-forms above are. What the engine derives
 *     from it is free: 〜れる/られる is itself an ichidan verb, so the whole polite paradigm
 *     (食べられます / 食べられました / 食べられません) follows from this one form.
 *   • participle_passive — the **short** participle of a verb that has two (an abundant
 *     participle), spoken where the copula governs it and so in the passive: pt salvar is
 *     *tinha salvado* but *foi salva*. Absent = the one `participle` serves both.
 *   • aux        — "be" on the verbs whose resultative selects the BE auxiliary instead of
 *     the HAVE default (it essere / fr être / de sein). Selection is lexical, not syntactic,
 *     and it does not match across languages: "correre" takes avere but "laufen" takes sein.
 *     Absent = HAVE. es/pt/en/ja have a single auxiliary and ignore the key.
 * French/German need no gerund (their progressive is periphrastic on the infinitive/adverb);
 * Japanese needs only the te-form. Irregular forms (gone, corso, gegangen, visto…) can't be
 * derived by rule, so they are listed explicitly. Copular verbs (become/seem/appear) get
 * best-effort forms — aspect on them is linguistically marginal.
 */
export const NONFINITE: Record<string, Record<string, Record<string, string>>> = {
  // The copula's resultative selects BE in it/de (è stato / ist gewesen); fr/es/pt/en use
  // HAVE (a été / ha sido / tem sido / has been). Aspect on a copula is marginal, so these
  // are best-effort. ja renders the copula specially and never reads a te-form.
  BE: {
    en: { gerund: 'being', participle: 'been' },
    it: { gerund: 'essendo', participle: 'stato', aux: 'be' },
    fr: { participle: 'été' }, de: { participle: 'gewesen', aux: 'be' },
    es: { gerund: 'siendo', participle: 'sido' },
    pt: { gerund: 'sendo', participle: 'sido' },
  },
  CUT: {
    en: { gerund: 'cutting', participle: 'cut' },
    it: { gerund: 'tagliando', participle: 'tagliato' },
    fr: { participle: 'coupé' }, de: { participle: 'geschnitten' },
    es: { gerund: 'cortando', participle: 'cortado' },
    pt: { gerund: 'cortando', participle: 'cortado' },
    ja: { te: '切って', te_reading: 'きって', nai: '切らない', nai_reading: 'きらない', passive: '切られる', passive_reading: 'きられる' },
  },
  EAT: {
    en: { gerund: 'eating', participle: 'eaten' },
    it: { gerund: 'mangiando', participle: 'mangiato' },
    fr: { participle: 'mangé' }, de: { participle: 'gegessen' },
    es: { gerund: 'comiendo', participle: 'comido' },
    pt: { gerund: 'comendo', participle: 'comido' },
    ja: { te: '食べて', te_reading: 'たべて', nai: '食べない', nai_reading: 'たべない', passive: '食べられる', passive_reading: 'たべられる' },
  },
  // EAT's animal sense (A157): German alone differs — the strong Partizip is "gefressen".
  EAT_ANIMAL: {
    en: { gerund: 'eating', participle: 'eaten' },
    it: { gerund: 'mangiando', participle: 'mangiato' },
    fr: { participle: 'mangé' }, de: { participle: 'gefressen' },
    es: { gerund: 'comiendo', participle: 'comido' },
    pt: { gerund: 'comendo', participle: 'comido' },
    ja: { te: '食べて', te_reading: 'たべて', nai: '食べない', nai_reading: 'たべない', passive: '食べられる', passive_reading: 'たべられる' },
  },
  DRINK: {
    en: { gerund: 'drinking', participle: 'drunk' },
    it: { gerund: 'bevendo', participle: 'bevuto' },
    fr: { participle: 'bu' }, de: { participle: 'getrunken' },
    es: { gerund: 'bebiendo', participle: 'bebido' },
    pt: { gerund: 'bebendo', participle: 'bebido' },
    ja: { te: '飲んで', te_reading: 'のんで', nai: '飲まない', nai_reading: 'のまない', passive: '飲まれる', passive_reading: 'のまれる' },
  },
  POUR: {
    en: { gerund: 'pouring', participle: 'poured' },
    it: { gerund: 'versando', participle: 'versato' },
    fr: { participle: 'versé' }, de: { participle: 'gegossen' },
    es: { gerund: 'vertiendo', participle: 'vertido' },
    pt: { gerund: 'vertendo', participle: 'vertido' },
    ja: { te: '注いで', te_reading: 'そそいで', nai: '注がない', nai_reading: 'そそがない', passive: '注がれる', passive_reading: 'そそがれる' },
  },
  CONSUME: {
    en: { gerund: 'consuming', participle: 'consumed' },
    it: { gerund: 'consumando', participle: 'consumato' },
    fr: { participle: 'consommé' }, de: { participle: 'konsumiert' },
    es: { gerund: 'consumiendo', participle: 'consumido' },
    pt: { gerund: 'consumindo', participle: 'consumido' },
    ja: { te: '摂取して', te_reading: 'せっしゅして', nai: '摂取しない', nai_reading: 'せっしゅしない', passive: '摂取される', passive_reading: 'せっしゅされる' },
  },
  RUN: {
    en: { gerund: 'running', participle: 'run' },
    it: { gerund: 'correndo', participle: 'corso' },
    fr: { participle: 'couru' }, de: { participle: 'gelaufen', aux: 'be' },
    es: { gerund: 'corriendo', participle: 'corrido' },
    pt: { gerund: 'correndo', participle: 'corrido' },
    ja: { te: '走って', te_reading: 'はしって', nai: '走らない', nai_reading: 'はしらない' },
  },
  SEE: {
    en: { gerund: 'seeing', participle: 'seen' },
    it: { gerund: 'vedendo', participle: 'visto' },
    fr: { participle: 'vu' }, de: { participle: 'gesehen' },
    es: { gerund: 'viendo', participle: 'visto' },
    pt: { gerund: 'vendo', participle: 'visto' },
    ja: { te: '見て', te_reading: 'みて', nai: '見ない', nai_reading: 'みない', passive: '見られる', passive_reading: 'みられる' },
  },
  LOVE: {
    en: { gerund: 'loving', participle: 'loved' },
    it: { gerund: 'amando', participle: 'amato' },
    fr: { participle: 'aimé' }, de: { participle: 'geliebt' },
    es: { gerund: 'amando', participle: 'amado' },
    pt: { gerund: 'amando', participle: 'amado' },
    ja: { te: '愛して', te_reading: 'あいして', nai: '愛さない', nai_reading: 'あいさない', passive: '愛される', passive_reading: 'あいされる' },
  },
  DESIRE: {
    en: { gerund: 'desiring', participle: 'desired' },
    it: { gerund: 'desiderando', participle: 'desiderato' },
    fr: { participle: 'désiré' }, de: { participle: 'gewünscht' },
    es: { gerund: 'deseando', participle: 'deseado' },
    pt: { gerund: 'desejando', participle: 'desejado' },
    ja: { te: '望んで', te_reading: 'のぞんで', nai: '望まない', nai_reading: 'のぞまない', passive: '望まれる', passive_reading: 'のぞまれる' },
  },
  KILL: {
    en: { gerund: 'killing', participle: 'killed' },
    it: { gerund: 'uccidendo', participle: 'ucciso' },
    fr: { participle: 'tué' }, de: { participle: 'getötet' },
    es: { gerund: 'matando', participle: 'matado' },
    pt: { gerund: 'matando', participle: 'matado' },
    ja: { te: '殺して', te_reading: 'ころして', nai: '殺さない', nai_reading: 'ころさない', passive: '殺される', passive_reading: 'ころされる' },
  },
  KNOW: {
    en: { gerund: 'knowing', participle: 'known' },
    it: { gerund: 'sapendo', participle: 'saputo' },
    fr: { participle: 'su' }, de: { participle: 'gewusst' },
    es: { gerund: 'sabiendo', participle: 'sabido' },
    pt: { gerund: 'sabendo', participle: 'sabido' },
    ja: { te: '知って', te_reading: 'しって', nai: '知らない', nai_reading: 'しらない', passive: '知られる', passive_reading: 'しられる' },
  },
  KNOW_ACQUAINTED: {
    en: { gerund: 'knowing', participle: 'known' },
    it: { gerund: 'conoscendo', participle: 'conosciuto' },
    fr: { participle: 'connu' }, de: { participle: 'gekannt' },
    es: { gerund: 'conociendo', participle: 'conocido' },
    pt: { gerund: 'conhecendo', participle: 'conhecido' },
    ja: { te: '知って', te_reading: 'しって', nai: '知らない', nai_reading: 'しらない', passive: '知られる', passive_reading: 'しられる' },
  },
  // prevedere's participle is vedere's strong visto, prefixed: previsto.
  EXPECT: {
    en: { gerund: 'expecting', participle: 'expected' },
    it: { gerund: 'prevedendo', participle: 'previsto' },
    fr: { participle: 'attendu' }, de: { participle: 'erwartet' },
    es: { gerund: 'esperando', participle: 'esperado' },
    pt: { gerund: 'esperando', participle: 'esperado' },
    ja: { te: '予想して', te_reading: 'よそうして', nai: '予想しない', nai_reading: 'よそうしない', passive: '予想される', passive_reading: 'よそうされる' },
  },
  READ: {
    en: { gerund: 'reading', participle: 'read' },
    it: { gerund: 'leggendo', participle: 'letto' },
    fr: { participle: 'lu' }, de: { participle: 'gelesen' },
    es: { gerund: 'leyendo', participle: 'leído' },
    pt: { gerund: 'lendo', participle: 'lido' },
    ja: { te: '読んで', te_reading: 'よんで', nai: '読まない', nai_reading: 'よまない', passive: '読まれる', passive_reading: 'よまれる' },
  },
  JUMP: {
    en: { gerund: 'jumping', participle: 'jumped' },
    it: { gerund: 'saltando', participle: 'saltato' },
    fr: { participle: 'sauté' }, de: { participle: 'gesprungen', aux: 'be' },
    es: { gerund: 'saltando', participle: 'saltado' },
    pt: { gerund: 'pulando', participle: 'pulado' },
    ja: { te: '跳んで', te_reading: 'とんで', nai: '跳ばない', nai_reading: 'とばない' },
  },
  COME: {
    en: { gerund: 'coming', participle: 'come' },
    it: { gerund: 'venendo', participle: 'venuto', aux: 'be' },
    fr: { participle: 'venu', aux: 'be' }, de: { participle: 'gekommen', aux: 'be' },
    es: { gerund: 'viniendo', participle: 'venido' },
    pt: { gerund: 'vindo', participle: 'vindo' },
    ja: { te: '来て', te_reading: 'きて', nai: '来ない', nai_reading: 'こない' },
  },
  CRY: {
    en: { gerund: 'crying', participle: 'cried' },
    it: { gerund: 'piangendo', participle: 'pianto' },
    fr: { participle: 'pleuré' }, de: { participle: 'geweint' },
    es: { gerund: 'llorando', participle: 'llorado' },
    pt: { gerund: 'chorando', participle: 'chorado' },
    ja: { te: '泣いて', te_reading: 'ないて', nai: '泣かない', nai_reading: 'なかない' },
  },
  SUFFER: {
    en: { gerund: 'suffering', participle: 'suffered' },
    it: { gerund: 'soffrendo', participle: 'sofferto' },
    fr: { participle: 'souffert' }, de: { participle: 'gelitten' },
    es: { gerund: 'sufriendo', participle: 'sufrido' },
    pt: { gerund: 'sofrendo', participle: 'sofrido' },
    ja: { te: '苦しんで', te_reading: 'くるしんで', nai: '苦しまない', nai_reading: 'くるしまない' },
  },
  CRY_OUT: {
    en: { gerund: 'crying', participle: 'cried' },
    it: { gerund: 'gridando', participle: 'gridato' },
    fr: { participle: 'crié' }, de: { participle: 'gerufen' },
    es: { gerund: 'gritando', participle: 'gritado' },
    pt: { gerund: 'gritando', participle: 'gritado' },
    ja: { te: '叫んで', te_reading: 'さけんで', nai: '叫ばない', nai_reading: 'さけばない', passive: '叫ばれる', passive_reading: 'さけばれる' },
  },
  BITE: {
    en: { gerund: 'biting', participle: 'bitten' },
    it: { gerund: 'mordendo', participle: 'morso' },
    fr: { participle: 'mordu' }, de: { participle: 'gebissen' },
    es: { gerund: 'mordiendo', participle: 'mordido' },
    pt: { gerund: 'mordendo', participle: 'mordido' },
    ja: { te: '噛んで', te_reading: 'かんで', nai: '噛まない', nai_reading: 'かまない', passive: '噛まれる', passive_reading: 'かまれる' },
  },
  BEAT: {
    en: { gerund: 'beating', participle: 'beaten' },
    it: { gerund: 'battendo', participle: 'battuto' },
    fr: { participle: 'battu' }, de: { participle: 'geschlagen' },
    es: { gerund: 'batiendo', participle: 'batido' },
    pt: { gerund: 'batendo', participle: 'batido' },
    ja: { te: '打って', te_reading: 'うって', nai: '打たない', nai_reading: 'うたない', passive: '打たれる', passive_reading: 'うたれる' },
  },
  BURN: {
    en: { gerund: 'burning', participle: 'burned' },
    it: { gerund: 'bruciando', participle: 'bruciato' },
    fr: { participle: 'brûlé' }, de: { participle: 'gebrannt' },
    es: { gerund: 'ardiendo', participle: 'ardido' },
    pt: { gerund: 'ardendo', participle: 'ardido' },
    ja: { te: '燃えて', te_reading: 'もえて', nai: '燃えない', nai_reading: 'もえない' },
  },
  SET_ON_FIRE: {
    en: { gerund: 'burning', participle: 'burned' },
    it: { gerund: 'bruciando', participle: 'bruciato' },
    fr: { participle: 'brûlé' }, de: { participle: 'verbrannt' },
    es: { gerund: 'quemando', participle: 'quemado' },
    pt: { gerund: 'queimando', participle: 'queimado' },
    ja: { te: '燃やして', te_reading: 'もやして', nai: '燃やさない', nai_reading: 'もやさない', passive: '燃やされる', passive_reading: 'もやされる' },
  },
  EXTINGUISH: {
    en: { gerund: 'putting out', participle: 'put out' },
    it: { gerund: 'spegnendo', participle: 'spento' },
    fr: { participle: 'éteint' }, de: { participle: 'gelöscht' },
    es: { gerund: 'apagando', participle: 'apagado' },
    pt: { gerund: 'apagando', participle: 'apagado' },
    ja: { te: '消して', te_reading: 'けして', nai: '消さない', nai_reading: 'けさない', passive: '消される', passive_reading: 'けされる' },
  },
  BUY: {
    en: { gerund: 'buying', participle: 'bought' },
    it: { gerund: 'comprando', participle: 'comprato' },
    fr: { participle: 'acheté' }, de: { participle: 'gekauft' },
    es: { gerund: 'comprando', participle: 'comprado' },
    pt: { gerund: 'comprando', participle: 'comprado' },
    ja: { te: '買って', te_reading: 'かって', nai: '買わない', nai_reading: 'かわない', passive: '買われる', passive_reading: 'かわれる' },
  },
  OWN: {
    en: { gerund: 'owning', participle: 'owned' },
    it: { gerund: 'possedendo', participle: 'posseduto' },
    fr: { participle: 'possédé' }, de: { participle: 'besessen' },
    es: { gerund: 'poseyendo', participle: 'poseído' },
    pt: { gerund: 'possuindo', participle: 'possuído' },
    ja: { te: '所有して', te_reading: 'しょゆうして', nai: '所有しない', nai_reading: 'しょゆうしない', passive: '所有される', passive_reading: 'しょゆうされる' },
  },
  HOLD: {
    en: { gerund: 'holding', participle: 'held' },
    it: { gerund: 'contenendo', participle: 'contenuto' },
    fr: { participle: 'contenu' }, de: { participle: 'enthalten' },
    es: { gerund: 'conteniendo', participle: 'contenido' },
    pt: { gerund: 'contendo', participle: 'contido' },
    ja: { te: '保持して', te_reading: 'ほじして', nai: '保持しない', nai_reading: 'ほじしない', passive: '保持される', passive_reading: 'ほじされる' },
  },
  // it includere → incluso, fr inclure → inclus (the feminine incluse); ja 含む is godan.
  INCLUDE: {
    en: { gerund: 'including', participle: 'included' },
    it: { gerund: 'includendo', participle: 'incluso' },
    fr: { participle: 'inclus' }, de: { participle: 'umfasst' },
    es: { gerund: 'incluyendo', participle: 'incluido' },
    pt: { gerund: 'incluindo', participle: 'incluído' },
    ja: { te: '含んで', te_reading: 'ふくんで', nai: '含まない', nai_reading: 'ふくまない', passive: '含まれる', passive_reading: 'ふくまれる' },
  },
  CLICK: {
    en: { gerund: 'clicking', participle: 'clicked' },
    it: { gerund: 'cliccando', participle: 'cliccato' },
    fr: { participle: 'cliqué' }, de: { participle: 'geklickt' },
    es: { gerund: 'clicando', participle: 'clicado' },
    pt: { gerund: 'clicando', participle: 'clicado' },
    ja: { te: 'クリックして', te_reading: 'くりっくして', nai: 'クリックしない', nai_reading: 'くりっくしない', passive: 'クリックされる', passive_reading: 'くりっくされる' },
  },
  CHOOSE: {
    en: { gerund: 'choosing', participle: 'chosen' },
    it: { gerund: 'scegliendo', participle: 'scelto' },
    fr: { participle: 'choisi' }, de: { participle: 'gewählt' },
    es: { gerund: 'eligiendo', participle: 'elegido' },
    pt: { gerund: 'escolhendo', participle: 'escolhido' },
    ja: { te: '選んで', te_reading: 'えらんで', nai: '選ばない', nai_reading: 'えらばない', passive: '選ばれる', passive_reading: 'えらばれる' },
  },
  FILTER: {
    en: { gerund: 'filtering', participle: 'filtered' },
    it: { gerund: 'filtrando', participle: 'filtrato' },
    fr: { participle: 'filtré' }, de: { participle: 'gefiltert' },
    es: { gerund: 'filtrando', participle: 'filtrado' },
    pt: { gerund: 'filtrando', participle: 'filtrado' },
    ja: { te: '絞り込んで', te_reading: 'しぼりこんで', nai: '絞り込まない', nai_reading: 'しぼりこまない', passive: '絞り込まれる', passive_reading: 'しぼりこまれる' },
  },
  SELECT: {
    en: { gerund: 'selecting', participle: 'selected' },
    it: { gerund: 'selezionando', participle: 'selezionato' },
    fr: { participle: 'sélectionné' }, de: { participle: 'selektiert' },
    es: { gerund: 'seleccionando', participle: 'seleccionado' },
    pt: { gerund: 'selecionando', participle: 'selecionado' },
    ja: { te: '選択して', te_reading: 'せんたくして', nai: '選択しない', nai_reading: 'せんたくしない', passive: '選択される', passive_reading: 'せんたくされる' },
  },
  TYPE: {
    en: { gerund: 'typing', participle: 'typed' },
    it: { gerund: 'digitando', participle: 'digitato' },
    fr: { participle: 'tapé' }, de: { participle: 'getippt' },
    es: { gerund: 'tecleando', participle: 'tecleado' },
    pt: { gerund: 'digitando', participle: 'digitado' },
    ja: { te: '入力して', te_reading: 'にゅうりょくして', nai: '入力しない', nai_reading: 'にゅうりょくしない', passive: '入力される', passive_reading: 'にゅうりょくされる' },
  },
  GIVE: {
    en: { gerund: 'giving', participle: 'given' },
    it: { gerund: 'dando', participle: 'dato' },
    fr: { participle: 'donné' }, de: { participle: 'gegeben' },
    es: { gerund: 'dando', participle: 'dado' },
    pt: { gerund: 'dando', participle: 'dado' },
    ja: { te: 'あげて', te_reading: 'あげて', nai: 'あげない', passive: 'あげられる' },
  },
  // P09's three new verbs (localization B64, B65). All take HAVE: imparare, vendere and trasmettere
  // select avere. The irregular participles are en sold and broadcast, it trasmesso, fr appris;
  // German verkaufen takes no ge- after its unstressed ver-, and ausstrahlen puts it after the
  // particle (ausgestrahlt).
  SELL: {
    en: { gerund: 'selling', participle: 'sold' },
    it: { gerund: 'vendendo', participle: 'venduto' },
    fr: { participle: 'vendu' }, de: { participle: 'verkauft' },
    es: { gerund: 'vendiendo', participle: 'vendido' },
    pt: { gerund: 'vendendo', participle: 'vendido' },
    ja: { te: '売って', te_reading: 'うって', nai: '売らない', nai_reading: 'うらない', passive: '売られる', passive_reading: 'うられる' },
  },
  LEARN: {
    en: { gerund: 'learning', participle: 'learned' },
    it: { gerund: 'imparando', participle: 'imparato' },
    fr: { participle: 'appris' }, de: { participle: 'gelernt' },
    es: { gerund: 'aprendiendo', participle: 'aprendido' },
    pt: { gerund: 'aprendendo', participle: 'aprendido' },
    ja: { te: '学んで', te_reading: 'まなんで', nai: '学ばない', nai_reading: 'まなばない' },
  },
  BROADCAST: {
    en: { gerund: 'broadcasting', participle: 'broadcast' },
    it: { gerund: 'trasmettendo', participle: 'trasmesso' },
    fr: { participle: 'diffusé' }, de: { participle: 'ausgestrahlt' },
    es: { gerund: 'emitiendo', participle: 'emitido' },
    pt: { gerund: 'transmitindo', participle: 'transmitido' },
    ja: { te: '放送して', te_reading: 'ほうそうして', nai: '放送しない', nai_reading: 'ほうそうしない', passive: '放送される', passive_reading: 'ほうそうされる' },
  },
  SHOW: {
    en: { gerund: 'showing', participle: 'shown' },
    it: { gerund: 'mostrando', participle: 'mostrato' },
    fr: { participle: 'montré' }, de: { participle: 'gezeigt' },
    es: { gerund: 'mostrando', participle: 'mostrado' },
    pt: { gerund: 'mostrando', participle: 'mostrado' },
    ja: { te: '見せて', te_reading: 'みせて', nai: '見せない', nai_reading: 'みせない', passive: '見せられる', passive_reading: 'みせられる' },
  },
  SEND: {
    en: { gerund: 'sending', participle: 'sent' },
    it: { gerund: 'mandando', participle: 'mandato' },
    fr: { participle: 'envoyé' }, de: { participle: 'geschickt' },
    es: { gerund: 'enviando', participle: 'enviado' },
    pt: { gerund: 'enviando', participle: 'enviado' },
    ja: { te: '送って', te_reading: 'おくって', nai: '送らない', nai_reading: 'おくらない', passive: '送られる', passive_reading: 'おくられる' },
  },
  GO: {
    en: { gerund: 'going', participle: 'gone', aux: 'be' }, // "is gone", not "has gone"
    it: { gerund: 'andando', participle: 'andato', aux: 'be' },
    fr: { participle: 'allé', aux: 'be' }, de: { participle: 'gegangen', aux: 'be' },
    es: { gerund: 'yendo', participle: 'ido' },
    pt: { gerund: 'indo', participle: 'ido' },
    ja: { te: '行って', te_reading: 'いって', nai: '行かない', nai_reading: 'いかない' },
  },
  // Going back selects BE where GO does (è tornato, est revenu, ist zurückgekehrt); English keeps
  // "has returned" (unlike "is gone").
  RETURN: {
    en: { gerund: 'returning', participle: 'returned' },
    it: { gerund: 'tornando', participle: 'tornato', aux: 'be' },
    fr: { participle: 'revenu', aux: 'be' }, de: { participle: 'zurückgekehrt', aux: 'be' },
    es: { gerund: 'volviendo', participle: 'vuelto' },
    pt: { gerund: 'voltando', participle: 'voltado' },
    ja: { te: '戻って', te_reading: 'もどって', nai: '戻らない', nai_reading: 'もどらない' },
  },
  // A pronominal verb selects essere / être in it and fr ("si è mosso", "s'est déplacé"); the German
  // reflexive takes haben ("hat sich bewegt"). The it / es / pt gerunds carry the clitic, which the
  // engine agrees with the subject ("sta muovendomi", "estoy moviéndome").
  MOVE_ONESELF: {
    en: { gerund: 'moving', participle: 'moved' },
    it: { gerund: 'muovendosi', participle: 'mosso', aux: 'be' },
    fr: { participle: 'déplacé', aux: 'be' }, de: { participle: 'bewegt' },
    es: { gerund: 'moviéndose', participle: 'movido' },
    pt: { gerund: 'movendo-se', participle: 'movido' },
    ja: { te: '移動して', te_reading: 'いどうして', nai: '移動しない', nai_reading: 'いどうしない' },
  },
  BECOME: {
    en: { gerund: 'becoming', participle: 'become' },
    it: { gerund: 'diventando', participle: 'diventato', aux: 'be' },
    fr: { participle: 'devenu', aux: 'be' }, de: { participle: 'geworden', aux: 'be' },
    es: { gerund: 'volviéndose', participle: 'vuelto' },
    pt: { gerund: 'tornando-se', participle: 'tornado' },
    ja: { te: 'なって', te_reading: 'なって', nai: 'ならない', nai_reading: 'ならない' },
  },
  SEEM: {
    en: { gerund: 'seeming', participle: 'seemed' },
    it: { gerund: 'sembrando', participle: 'sembrato', aux: 'be' },
    fr: { participle: 'semblé' }, de: { participle: 'geschienen' },
    es: { gerund: 'pareciendo', participle: 'parecido' },
    pt: { gerund: 'parecendo', participle: 'parecido' },
    ja: { te: '思えて', te_reading: 'おもえて', nai: '思えない', nai_reading: 'おもえない' },
  },
  APPEAR: {
    en: { gerund: 'appearing', participle: 'appeared' },
    it: { gerund: 'apparendo', participle: 'apparso', aux: 'be' },
    fr: { participle: 'apparu', aux: 'be' }, de: { participle: 'erschienen', aux: 'be' },
    es: { gerund: 'apareciendo', participle: 'aparecido' },
    pt: { gerund: 'aparecendo', participle: 'aparecido' },
    ja: { te: '現れて', te_reading: 'あらわれて', nai: '現れない', nai_reading: 'あらわれない' },
  },
  TRANSLATE: {
    en: { gerund: 'translating', participle: 'translated' },
    it: { gerund: 'traducendo', participle: 'tradotto' },
    fr: { participle: 'traduit' }, de: { participle: 'übersetzt' },
    es: { gerund: 'traduciendo', participle: 'traducido' },
    pt: { gerund: 'traduzindo', participle: 'traduzido' },
    ja: { te: '翻訳して', te_reading: 'ほんやくして', nai: '翻訳しない', nai_reading: 'ほんやくしない', passive: '翻訳される', passive_reading: 'ほんやくされる' },
  },
  SAVE: {
    en: { gerund: 'saving', participle: 'saved' },
    it: { gerund: 'salvando', participle: 'salvato' },
    fr: { participle: 'enregistré' }, de: { participle: 'gespeichert' },
    es: { gerund: 'guardando', participle: 'guardado' },
    // Abundant participle: the perfect takes the long form (tinha salvado), the copula the
    // short one — which is what a passive is built on (foi salva). See `passiveParticiple`.
    pt: { gerund: 'salvando', participle: 'salvado', participle_passive: 'salvo' },
    ja: { te: '保存して', te_reading: 'ほぞんして', nai: '保存しない', nai_reading: 'ほぞんしない', passive: '保存される', passive_reading: 'ほぞんされる' },
  },
  LOAD: {
    en: { gerund: 'loading', participle: 'loaded' },
    it: { gerund: 'caricando', participle: 'caricato' },
    fr: { participle: 'chargé' }, de: { participle: 'geladen' },
    es: { gerund: 'cargando', participle: 'cargado' },
    pt: { gerund: 'carregando', participle: 'carregado' },
    ja: { te: '読み込んで', te_reading: 'よみこんで', nai: '読み込まない', nai_reading: 'よみこまない', passive: '読み込まれる', passive_reading: 'よみこまれる' },
  },
  ADD: {
    en: { gerund: 'adding', participle: 'added' },
    it: { gerund: 'aggiungendo', participle: 'aggiunto' },
    fr: { participle: 'ajouté' }, de: { participle: 'hinzugefügt' },
    es: { gerund: 'añadiendo', participle: 'añadido' },
    pt: { gerund: 'adicionando', participle: 'adicionado' },
    ja: { te: '加えて', te_reading: 'くわえて', nai: '加えない', nai_reading: 'くわえない', passive: '加えられる', passive_reading: 'くわえられる' },
  },
  LINK: {
    en: { gerund: 'linking', participle: 'linked' },
    it: { gerund: 'collegando', participle: 'collegato' },
    fr: { participle: 'relié' }, de: { participle: 'verbunden' },
    es: { gerund: 'enlazando', participle: 'enlazado' },
    pt: { gerund: 'ligando', participle: 'ligado' },
    ja: { te: 'つないで', te_reading: 'つないで', nai: 'つながない', nai_reading: 'つながない', passive: 'つながれる', passive_reading: 'つながれる' },
  },
  EXPORT: {
    en: { gerund: 'exporting', participle: 'exported' },
    it: { gerund: 'esportando', participle: 'esportato' },
    fr: { participle: 'exporté' }, de: { participle: 'exportiert' },
    es: { gerund: 'exportando', participle: 'exportado' },
    pt: { gerund: 'exportando', participle: 'exportado' },
    ja: { te: '書き出して', te_reading: 'かきだして', nai: '書き出さない', nai_reading: 'かきださない', passive: '書き出される', passive_reading: 'かきだされる' },
  },
  IMPORT: {
    en: { gerund: 'importing', participle: 'imported' },
    it: { gerund: 'importando', participle: 'importato' },
    fr: { participle: 'importé' }, de: { participle: 'importiert' },
    es: { gerund: 'importando', participle: 'importado' },
    pt: { gerund: 'importando', participle: 'importado' },
    ja: { te: '取り込んで', te_reading: 'とりこんで', nai: '取り込まない', nai_reading: 'とりこまない', passive: '取り込まれる', passive_reading: 'とりこまれる' },
  },
  CLEAR: {
    en: { gerund: 'clearing', participle: 'cleared' },
    it: { gerund: 'cancellando', participle: 'cancellato' },
    fr: { participle: 'effacé' }, de: { participle: 'gelöscht' },
    es: { gerund: 'borrando', participle: 'borrado' },
    pt: { gerund: 'limpando', participle: 'limpado' },
    ja: { te: '消去して', te_reading: 'しょうきょして', nai: '消去しない', nai_reading: 'しょうきょしない', passive: '消去される', passive_reading: 'しょうきょされる' },
  },
  // it rimosso is irregular. de entfernt takes no ge- after its unstressed ent-, where löschen does
  // (gelöscht). pt excluído keeps the accent that splits its u-i.
  REMOVE: {
    en: { gerund: 'removing', participle: 'removed' },
    it: { gerund: 'rimuovendo', participle: 'rimosso' },
    fr: { participle: 'retiré' }, de: { participle: 'entfernt' },
    es: { gerund: 'quitando', participle: 'quitado' },
    pt: { gerund: 'removendo', participle: 'removido' },
    ja: { te: '取り除いて', te_reading: 'とりのぞいて', nai: '取り除かない', nai_reading: 'とりのぞかない', passive: '取り除かれる', passive_reading: 'とりのぞかれる' },
  },
  DELETE: {
    en: { gerund: 'deleting', participle: 'deleted' },
    it: { gerund: 'eliminando', participle: 'eliminato' },
    fr: { participle: 'supprimé' }, de: { participle: 'gelöscht' },
    es: { gerund: 'eliminando', participle: 'eliminado' },
    pt: { gerund: 'excluindo', participle: 'excluído' },
    ja: { te: '削除して', te_reading: 'さくじょして', nai: '削除しない', nai_reading: 'さくじょしない', passive: '削除される', passive_reading: 'さくじょされる' },
  },
  COORDINATE: {
    en: { gerund: 'coordinating', participle: 'coordinated' },
    it: { gerund: 'coordinando', participle: 'coordinato' },
    fr: { participle: 'coordonné' }, de: { participle: 'koordiniert' },
    es: { gerund: 'coordinando', participle: 'coordinado' },
    pt: { gerund: 'coordenando', participle: 'coordenado' },
    ja: { te: '調整して', te_reading: 'ちょうせいして', nai: '調整しない', nai_reading: 'ちょうせいしない', passive: '調整される', passive_reading: 'ちょうせいされる' },
  },
  // it crollare and de kollabieren both select BE; the fr participle drops the reflexive clitic
  // its finite forms carry, so the resultative reads as the resulting state ("est effondré").
  COLLAPSE: {
    en: { gerund: 'collapsing', participle: 'collapsed' },
    it: { gerund: 'crollando', participle: 'crollato', aux: 'be' },
    fr: { participle: 'effondré', aux: 'be' }, de: { participle: 'kollabiert', aux: 'be' },
    es: { gerund: 'colapsando', participle: 'colapsado' },
    pt: { gerund: 'desabando', participle: 'desabado' },
    ja: { te: '崩れて', te_reading: 'くずれて', nai: '崩れない', nai_reading: 'くずれない' },
  },
  TIDY_UP: {
    en: { gerund: 'tidying up', participle: 'tidied up' },
    it: { gerund: 'riordinando', participle: 'riordinato' },
    fr: { participle: 'rangé' }, de: { participle: 'geordnet' },
    es: { gerund: 'ordenando', participle: 'ordenado' },
    pt: { gerund: 'arrumando', participle: 'arrumado' },
    ja: { te: '片付けて', te_reading: 'かたづけて', nai: '片付けない', nai_reading: 'かたづけない', passive: '片付けられる', passive_reading: 'かたづけられる' },
  },
  MAKE: {
    en: { gerund: 'making', participle: 'made' },
    it: { gerund: 'facendo', participle: 'fatto' },
    fr: { participle: 'fait' }, de: { participle: 'gemacht' },
    es: { gerund: 'haciendo', participle: 'hecho' },
    pt: { gerund: 'fazendo', participle: 'feito' },
    ja: { te: '作って', te_reading: 'つくって', nai: '作らない', nai_reading: 'つくらない', passive: '作られる', passive_reading: 'つくられる' },
  },
  CREATE: {
    en: { gerund: 'creating', participle: 'created' },
    it: { gerund: 'creando', participle: 'creato' },
    fr: { participle: 'créé' }, de: { participle: 'erschaffen' },
    es: { gerund: 'creando', participle: 'creado' },
    pt: { gerund: 'criando', participle: 'criado' },
    ja: { te: '生み出して', te_reading: 'うみだして', nai: '生み出さない', nai_reading: 'うみださない', passive: '生み出される', passive_reading: 'うみだされる' },
  },
  DESTROY: {
    en: { gerund: 'destroying', participle: 'destroyed' },
    it: { gerund: 'distruggendo', participle: 'distrutto' },
    fr: { participle: 'détruit' }, de: { participle: 'zerstört' },
    es: { gerund: 'destruyendo', participle: 'destruido' },
    pt: { gerund: 'destruindo', participle: 'destruído' },
    ja: { te: '破壊して', te_reading: 'はかいして', nai: '破壊しない', nai_reading: 'はかいしない', passive: '破壊される', passive_reading: 'はかいされる' },
  },
  PERCEIVE: {
    en: { gerund: 'perceiving', participle: 'perceived' },
    it: { gerund: 'percependo', participle: 'percepito' },
    fr: { participle: 'perçu' }, de: { participle: 'empfunden' },
    es: { gerund: 'percibiendo', participle: 'percibido' },
    pt: { gerund: 'percebendo', participle: 'percebido' },
    ja: { te: '知覚して', te_reading: 'ちかくして', nai: '知覚しない', nai_reading: 'ちかくしない', passive: '知覚される', passive_reading: 'ちかくされる' },
  },
  UNDERSTAND: {
    en: { gerund: 'understanding', participle: 'understood' },
    it: { gerund: 'comprendendo', participle: 'compreso' },
    fr: { participle: 'compris' }, de: { participle: 'verstanden' },
    es: { gerund: 'comprendiendo', participle: 'comprendido' },
    pt: { gerund: 'compreendendo', participle: 'compreendido' },
    ja: { te: '理解して', te_reading: 'りかいして', nai: '理解しない', nai_reading: 'りかいしない', passive: '理解される', passive_reading: 'りかいされる' },
  },
  // Genus verbs for the B12–B18 verb definitions. All transitive/ditransitive → HAVE auxiliary.
  HAVE: {
    en: { gerund: 'having', participle: 'had' },
    it: { gerund: 'avendo', participle: 'avuto' },
    fr: { participle: 'eu' }, de: { participle: 'gehabt' },
    es: { gerund: 'teniendo', participle: 'tenido' },
    pt: { gerund: 'tendo', participle: 'tido' },
    ja: { te: '持って', te_reading: 'もって', nai: '持たない', nai_reading: 'もたない', passive: '持たれる', passive_reading: 'もたれる' },
  },
  ACQUIRE: {
    en: { gerund: 'acquiring', participle: 'acquired' },
    it: { gerund: 'acquisendo', participle: 'acquisito' },
    fr: { participle: 'acquis' }, de: { participle: 'erworben' },
    es: { gerund: 'adquiriendo', participle: 'adquirido' },
    pt: { gerund: 'adquirindo', participle: 'adquirido' },
    ja: { te: '取得して', te_reading: 'しゅとくして', nai: '取得しない', nai_reading: 'しゅとくしない', passive: '取得される', passive_reading: 'しゅとくされる' },
  },
  TAKE: {
    en: { gerund: 'taking', participle: 'taken' },
    it: { gerund: 'prendendo', participle: 'preso' },
    fr: { participle: 'pris' }, de: { participle: 'genommen' },
    es: { gerund: 'tomando', participle: 'tomado' },
    pt: { gerund: 'pegando', participle: 'pegado' },
    ja: { te: '取って', te_reading: 'とって', nai: '取らない', nai_reading: 'とらない', passive: '取られる', passive_reading: 'とられる' },
  },
  DIVIDE: {
    en: { gerund: 'dividing', participle: 'divided' },
    it: { gerund: 'dividendo', participle: 'diviso' },
    fr: { participle: 'divisé' }, de: { participle: 'geteilt' },
    es: { gerund: 'dividiendo', participle: 'dividido' },
    pt: { gerund: 'dividindo', participle: 'dividido' },
    ja: { te: '分けて', te_reading: 'わけて', nai: '分けない', nai_reading: 'わけない', passive: '分けられる', passive_reading: 'わけられる' },
  },
  STRIKE: {
    en: { gerund: 'striking', participle: 'struck' },
    it: { gerund: 'colpendo', participle: 'colpito' },
    fr: { participle: 'frappé' }, de: { participle: 'geschlagen' },
    es: { gerund: 'golpeando', participle: 'golpeado' },
    pt: { gerund: 'golpeando', participle: 'golpeado' },
    ja: { te: '打って', te_reading: 'うって', nai: '打たない', nai_reading: 'うたない', passive: '打たれる', passive_reading: 'うたれる' },
  },
  TRANSFER: {
    en: { gerund: 'transferring', participle: 'transferred' },
    it: { gerund: 'trasferendo', participle: 'trasferito' },
    fr: { participle: 'transféré' }, de: { participle: 'übertragen' },
    es: { gerund: 'transfiriendo', participle: 'transferido' },
    pt: { gerund: 'transferindo', participle: 'transferido' },
    ja: { te: '移して', te_reading: 'うつして', nai: '移さない', nai_reading: 'うつさない', passive: '移される', passive_reading: 'うつされる' },
  },
  INDICATE: {
    en: { gerund: 'indicating', participle: 'indicated' },
    it: { gerund: 'indicando', participle: 'indicato' },
    fr: { participle: 'indiqué' }, de: { participle: 'bezeichnet' },
    es: { gerund: 'indicando', participle: 'indicado' },
    pt: { gerund: 'indicando', participle: 'indicado' },
    ja: { te: '示して', te_reading: 'しめして', nai: '示さない', nai_reading: 'しめさない', passive: '示される', passive_reading: 'しめされる' },
  },
  CHANGE: {
    en: { gerund: 'changing', participle: 'changed' },
    it: { gerund: 'cambiando', participle: 'cambiato' },
    fr: { participle: 'changé' }, de: { participle: 'geändert' },
    es: { gerund: 'cambiando', participle: 'cambiado' },
    pt: { gerund: 'mudando', participle: 'mudado' },
    ja: { te: '変えて', te_reading: 'かえて', nai: '変えない', nai_reading: 'かえない', passive: '変えられる', passive_reading: 'かえられる' },
  },
  TRANSFORM: {
    en: { gerund: 'transforming', participle: 'transformed' },
    it: { gerund: 'trasformando', participle: 'trasformato' },
    fr: { participle: 'transformé' }, de: { participle: 'verwandelt' },
    es: { gerund: 'transformando', participle: 'transformado' },
    pt: { gerund: 'transformando', participle: 'transformado' },
    ja: { te: '変えて', te_reading: 'かえて', nai: '変えない', nai_reading: 'かえない', passive: '変えられる', passive_reading: 'かえられる' },
  },
  FEEL: {
    en: { gerund: 'feeling', participle: 'felt' },
    it: { gerund: 'provando', participle: 'provato' },
    fr: { participle: 'éprouvé' }, de: { participle: 'gefühlt' },
    es: { gerund: 'sintiendo', participle: 'sentido' },
    pt: { gerund: 'sentindo', participle: 'sentido' },
    ja: { te: '感じて', te_reading: 'かんじて', nai: '感じない', nai_reading: 'かんじない', passive: '感じられる', passive_reading: 'かんじられる' },
  },
  SHED: {
    en: { gerund: 'shedding', participle: 'shed' },
    it: { gerund: 'versando', participle: 'versato' },
    fr: { participle: 'versé' }, de: { participle: 'vergossen' },
    es: { gerund: 'derramando', participle: 'derramado' },
    pt: { gerund: 'derramando', participle: 'derramado' },
    ja: { te: '流して', te_reading: 'ながして', nai: '流さない', nai_reading: 'ながさない', passive: '流される', passive_reading: 'ながされる' },
  },
  PRODUCE: {
    en: { gerund: 'producing', participle: 'produced' },
    it: { gerund: 'producendo', participle: 'prodotto' },
    fr: { participle: 'produit' }, de: { participle: 'erzeugt' },
    es: { gerund: 'produciendo', participle: 'producido' },
    pt: { gerund: 'produzindo', participle: 'produzido' },
    ja: { te: '出して', te_reading: 'だして', nai: '出さない', nai_reading: 'ださない', passive: '出される', passive_reading: 'だされる' },
  },
  CAUSE_VERB: {
    en: { gerund: 'causing', participle: 'caused' },
    it: { gerund: 'inducendo', participle: 'indotto' },
    fr: { participle: 'induit' }, de: { participle: 'veranlasst' },
    es: { gerund: 'induciendo', participle: 'inducido' },
    pt: { gerund: 'induzindo', participle: 'induzido' },
    ja: { te: '引き起こして', te_reading: 'ひきおこして', nai: '引き起こさない', nai_reading: 'ひきおこさない', passive: '引き起こされる', passive_reading: 'ひきおこされる' },
  },
  PRESS: {
    en: { gerund: 'pressing', participle: 'pressed' },
    it: { gerund: 'premendo', participle: 'premuto' },
    fr: { participle: 'pressé' }, de: { participle: 'gedrückt' },
    es: { gerund: 'pulsando', participle: 'pulsado' },
    pt: { gerund: 'pressionando', participle: 'pressionado' },
    ja: { te: '押して', te_reading: 'おして', nai: '押さない', nai_reading: 'おさない', passive: '押される', passive_reading: 'おされる' },
  },
  WRITE: {
    en: { gerund: 'writing', participle: 'written' },
    it: { gerund: 'scrivendo', participle: 'scritto' },
    fr: { participle: 'écrit' }, de: { participle: 'geschrieben' },
    es: { gerund: 'escribiendo', participle: 'escrito' },
    pt: { gerund: 'escrevendo', participle: 'escrito' },
    ja: { te: '書いて', te_reading: 'かいて', nai: '書かない', nai_reading: 'かかない', passive: '書かれる', passive_reading: 'かかれる' },
  },
  COMPACT: {
    en: { gerund: 'compacting', participle: 'compacted' },
    it: { gerund: 'compattando', participle: 'compattato' },
    fr: { participle: 'compacté' }, de: { participle: 'verdichtet' },
    es: { gerund: 'compactando', participle: 'compactado' },
    pt: { gerund: 'compactando', participle: 'compactado' },
    ja: { te: '圧縮して', te_reading: 'あっしゅくして', nai: '圧縮しない', nai_reading: 'あっしゅくしない', passive: '圧縮される', passive_reading: 'あっしゅくされる' },
  },
  EXPAND: {
    en: { gerund: 'expanding', participle: 'expanded' },
    it: { gerund: 'espandendo', participle: 'espanso' },
    fr: { participle: 'étendu' }, de: { participle: 'erweitert' },
    es: { gerund: 'expandiendo', participle: 'expandido' },
    pt: { gerund: 'expandindo', participle: 'expandido' },
    ja: { te: '展開して', te_reading: 'てんかいして', nai: '展開しない', nai_reading: 'てんかいしない', passive: '展開される', passive_reading: 'てんかいされる' },
  },
  SHRINK: {
    en: { gerund: 'shrinking', participle: 'shrunk' },
    it: { gerund: 'rimpicciolendo', participle: 'rimpicciolito' },
    fr: { participle: 'réduit' }, de: { participle: 'verkleinert' },
    es: { gerund: 'reduciendo', participle: 'reducido' },
    pt: { gerund: 'reduzindo', participle: 'reduzido' },
    ja: { te: '縮小して', te_reading: 'しゅくしょうして', nai: '縮小しない', nai_reading: 'しゅくしょうしない', passive: '縮小される', passive_reading: 'しゅくしょうされる' },
  },
  HIDE: {
    en: { gerund: 'hiding', participle: 'hidden' },
    it: { gerund: 'nascondendo', participle: 'nascosto' },
    fr: { participle: 'caché' }, de: { participle: 'versteckt' },
    es: { gerund: 'escondiendo', participle: 'escondido' },
    pt: { gerund: 'escondendo', participle: 'escondido' },
    ja: { te: '隠して', te_reading: 'かくして', nai: '隠さない', nai_reading: 'かくさない', passive: '隠される', passive_reading: 'かくされる' },
  },
  START: {
    en: { gerund: 'starting', participle: 'started' },
    it: { gerund: 'iniziando', participle: 'iniziato' },
    fr: { participle: 'commencé' }, de: { participle: 'begonnen' },
    es: { gerund: 'empezando', participle: 'empezado' },
    pt: { gerund: 'começando', participle: 'começado' },
    ja: { te: '始めて', te_reading: 'はじめて', nai: '始めない', nai_reading: 'はじめない', passive: '始められる', passive_reading: 'はじめられる' },
  },
  // The inchoative BEGIN, not START. Italian selects essere for it ("l'azione è iniziata") where
  // the causative takes avere ("ha iniziato l'azione") — the same verb, the auxiliary carrying the
  // difference. French commencer and German beginnen keep avoir/haben either way.
  BEGIN: {
    en: { gerund: 'beginning', participle: 'begun' },
    it: { gerund: 'iniziando', participle: 'iniziato', aux: 'be' },
    fr: { participle: 'commencé' }, de: { participle: 'begonnen' },
    es: { gerund: 'empezando', participle: 'empezado' },
    pt: { gerund: 'começando', participle: 'começado' },
    ja: { te: '始まって', te_reading: 'はじまって', nai: '始まらない', nai_reading: 'はじまらない' },
  },
  // The inchoative CHANGE_ONESELF, not CHANGE: essere in Italian ("il piano è cambiato"), and the
  // German reflexive takes haben ("hat sich geändert"), as every German reflexive does.
  CHANGE_ONESELF: {
    en: { gerund: 'changing', participle: 'changed' },
    it: { gerund: 'cambiando', participle: 'cambiato', aux: 'be' },
    fr: { participle: 'changé' }, de: { participle: 'geändert' },
    es: { gerund: 'cambiando', participle: 'cambiado' },
    pt: { gerund: 'mudando', participle: 'mudado' },
    ja: { te: '変わって', te_reading: 'かわって', nai: '変わらない', nai_reading: 'かわらない' },
  },
  // The verbs of a program's everyday controls (B25–B28). All transitive → the HAVE default.
  CANCEL: {
    en: { gerund: 'canceling', participle: 'canceled' },
    it: { gerund: 'annullando', participle: 'annullato' },
    fr: { participle: 'annulé' }, de: { participle: 'annulliert' },
    es: { gerund: 'cancelando', participle: 'cancelado' },
    pt: { gerund: 'cancelando', participle: 'cancelado' },
    ja: { te: 'キャンセルして', te_reading: 'きゃんせるして', nai: 'キャンセルしない', nai_reading: 'きゃんせるしない', passive: 'キャンセルされる', passive_reading: 'きゃんせるされる' },
  },
  // UNDO and REDO (B40). German UNDO's particle is written apart, so its participle is two words.
  UNDO: {
    en: { gerund: 'undoing', participle: 'undone' },
    it: { gerund: 'annullando', participle: 'annullato' },
    fr: { participle: 'annulé' }, de: { participle: 'rückgängig gemacht' },
    es: { gerund: 'deshaciendo', participle: 'deshecho' },
    pt: { gerund: 'desfazendo', participle: 'desfeito' },
    ja: { te: '元に戻して', te_reading: 'もとにもどして', nai: '元に戻さない', nai_reading: 'もとにもどさない', passive: '元に戻される', passive_reading: 'もとにもどされる' },
  },
  REDO: {
    en: { gerund: 'redoing', participle: 'redone' },
    it: { gerund: 'ripetendo', participle: 'ripetuto' },
    fr: { participle: 'rétabli' }, de: { participle: 'wiederholt' },
    es: { gerund: 'rehaciendo', participle: 'rehecho' },
    pt: { gerund: 'refazendo', participle: 'refeito' },
    ja: { te: 'やり直して', te_reading: 'やりなおして', nai: 'やり直さない', nai_reading: 'やりなおさない', passive: 'やり直される', passive_reading: 'やりなおされる' },
  },
  // RESTORE (C22). German zurückholen is separable, so its participle takes the ge- inside.
  RESTORE: {
    en: { gerund: 'restoring', participle: 'restored' },
    it: { gerund: 'ripristinando', participle: 'ripristinato' },
    fr: { participle: 'restauré' }, de: { participle: 'zurückgeholt' },
    es: { gerund: 'restaurando', participle: 'restaurado' },
    pt: { gerund: 'restaurando', participle: 'restaurado' },
    ja: { te: '復元して', te_reading: 'ふくげんして', nai: '復元しない', nai_reading: 'ふくげんしない', passive: '復元される', passive_reading: 'ふくげんされる' },
  },
  // The participles are irregular everywhere but in English and German: aperto, ouvert, abierto, aberto.
  OPEN: {
    en: { gerund: 'opening', participle: 'opened' },
    it: { gerund: 'aprendo', participle: 'aperto' },
    fr: { participle: 'ouvert' }, de: { participle: 'geöffnet' },
    es: { gerund: 'abriendo', participle: 'abierto' },
    pt: { gerund: 'abrindo', participle: 'aberto' },
    ja: { te: '開いて', te_reading: 'ひらいて', nai: '開かない', nai_reading: 'ひらかない', passive: '開かれる', passive_reading: 'ひらかれる' },
  },
  CLOSE: {
    en: { gerund: 'closing', participle: 'closed' },
    it: { gerund: 'chiudendo', participle: 'chiuso' },
    fr: { participle: 'fermé' }, de: { participle: 'geschlossen' },
    es: { gerund: 'cerrando', participle: 'cerrado' },
    pt: { gerund: 'fechando', participle: 'fechado' },
    ja: { te: '閉じて', te_reading: 'とじて', nai: '閉じない', nai_reading: 'とじない', passive: '閉じられる', passive_reading: 'とじられる' },
  },
  RETRY: {
    en: { gerund: 'retrying', participle: 'retried' },
    it: { gerund: 'riprovando', participle: 'riprovato' },
    fr: { participle: 'réessayé' }, de: { participle: 'wiederholt' },
    es: { gerund: 'reintentando', participle: 'reintentado' },
    pt: { gerund: 'repetindo', participle: 'repetido' },
    ja: { te: '再試行して', te_reading: 'さいしこうして', nai: '再試行しない', nai_reading: 'さいしこうしない', passive: '再試行される', passive_reading: 'さいしこうされる' },
  },
  USE: {
    en: { gerund: 'using', participle: 'used' },
    it: { gerund: 'usando', participle: 'usato' },
    fr: { participle: 'utilisé' }, de: { participle: 'verwendet' },
    es: { gerund: 'usando', participle: 'usado' },
    pt: { gerund: 'usando', participle: 'usado' },
    ja: { te: '使って', te_reading: 'つかって', nai: '使わない', nai_reading: 'つかわない', passive: '使われる', passive_reading: 'つかわれる' },
  },
  COPY: {
    en: { gerund: 'copying', participle: 'copied' },
    it: { gerund: 'copiando', participle: 'copiato' },
    fr: { participle: 'copié' }, de: { participle: 'kopiert' },
    es: { gerund: 'copiando', participle: 'copiado' },
    pt: { gerund: 'copiando', participle: 'copiado' },
    ja: { te: 'コピーして', te_reading: 'こぴーして', nai: 'コピーしない', nai_reading: 'こぴーしない', passive: 'コピーされる', passive_reading: 'こぴーされる' },
  },
  MOVE: {
    en: { gerund: 'moving', participle: 'moved' },
    it: { gerund: 'spostando', participle: 'spostato' },
    fr: { participle: 'déplacé' }, de: { participle: 'verschoben' },
    es: { gerund: 'moviendo', participle: 'movido' },
    pt: { gerund: 'movendo', participle: 'movido' },
    ja: { te: '移動して', te_reading: 'いどうして', nai: '移動しない', nai_reading: 'いどうしない', passive: '移動される', passive_reading: 'いどうされる' },
  },
  // Italian uscire selects essere ("è uscita dalla casa"); French quitter and German verlassen take
  // their HAVE auxiliary with a direct object.
  LEAVE: {
    en: { gerund: 'leaving', participle: 'left' },
    it: { gerund: 'uscendo', participle: 'uscito', aux: 'be' },
    fr: { participle: 'quitté' }, de: { participle: 'verlassen' },
    es: { gerund: 'saliendo', participle: 'salido' },
    pt: { gerund: 'saindo', participle: 'saído' },
    ja: { te: '出て', te_reading: 'でて', nai: '出ない', nai_reading: 'でない', passive: '出られる', passive_reading: 'でられる' },
  },
  DRAG: {
    en: { gerund: 'dragging', participle: 'dragged' },
    it: { gerund: 'trascinando', participle: 'trascinato' },
    fr: { participle: 'glissé' }, de: { participle: 'gezogen' },
    es: { gerund: 'arrastrando', participle: 'arrastrado' },
    pt: { gerund: 'arrastando', participle: 'arrastado' },
    ja: { te: 'ドラッグして', te_reading: 'どらっぐして', nai: 'ドラッグしない', nai_reading: 'どらっぐしない', passive: 'ドラッグされる' },
  },
  RESIZE: {
    en: { gerund: 'resizing', participle: 'resized' },
    it: { gerund: 'ridimensionando', participle: 'ridimensionato' },
    fr: { participle: 'redimensionné' }, de: { participle: 'skaliert' },
    es: { gerund: 'redimensionando', participle: 'redimensionado' },
    pt: { gerund: 'redimensionando', participle: 'redimensionado' },
    ja: { te: 'サイズ変更して', te_reading: 'さいずへんこうして', nai: 'サイズ変更しない', nai_reading: 'さいずへんこうしない', passive: 'サイズ変更される', passive_reading: 'さいずへんこうされる' },
  },
  TURN_OFF: {
    en: { gerund: 'turning off', participle: 'turned off' },
    it: { gerund: 'disattivando', participle: 'disattivato' },
    fr: { participle: 'désactivé' }, de: { participle: 'deaktiviert' },
    es: { gerund: 'desactivando', participle: 'desactivado' },
    pt: { gerund: 'desativando', participle: 'desativado' },
    ja: { te: 'オフにして', nai: 'オフにしない', passive: 'オフにされる' },
  },
  // de festlegen is separable: the particle goes inside the participle (festgelegt).
  SET: {
    en: { gerund: 'setting', participle: 'set' },
    it: { gerund: 'impostando', participle: 'impostato' },
    fr: { participle: 'défini' }, de: { participle: 'festgelegt' },
    es: { gerund: 'estableciendo', participle: 'establecido' },
    pt: { gerund: 'definindo', participle: 'definido' },
    ja: { te: '設定して', te_reading: 'せっていして', nai: '設定しない', nai_reading: 'せっていしない', passive: '設定される', passive_reading: 'せっていされる' },
  },
  // The console's verbs (B45). German anheften and anwenden are separable, so the participle takes
  // ge- inside: angeheftet, angewandt. Japanese are verbal nouns with する.
  PIN: {
    en: { gerund: 'pinning', participle: 'pinned' },
    it: { gerund: 'fissando', participle: 'fissato' },
    fr: { participle: 'épinglé' }, de: { participle: 'angeheftet' },
    es: { gerund: 'fijando', participle: 'fijado' },
    pt: { gerund: 'fixando', participle: 'fixado' },
    ja: { te: 'ピン留めして', te_reading: 'ぴんどめして', nai: 'ピン留めしない', nai_reading: 'ぴんどめしない', passive: 'ピン留めされる', passive_reading: 'ぴんどめされる' },
  },
  UNPIN: {
    en: { gerund: 'unpinning', participle: 'unpinned' },
    it: { gerund: 'sbloccando', participle: 'sbloccato' },
    fr: { participle: 'désépinglé' }, de: { participle: 'gelöst' },
    es: { gerund: 'desfijando', participle: 'desfijado' },
    pt: { gerund: 'desafixando', participle: 'desafixado' },
    ja: { te: 'ピン留め解除して', te_reading: 'ぴんどめかいじょして', nai: 'ピン留め解除しない', nai_reading: 'ぴんどめかいじょしない', passive: 'ピン留め解除される', passive_reading: 'ぴんどめかいじょされる' },
  },
  COMPLETE: {
    en: { gerund: 'completing', participle: 'completed' },
    it: { gerund: 'completando', participle: 'completato' },
    fr: { participle: 'complété' }, de: { participle: 'vervollständigt' },
    es: { gerund: 'completando', participle: 'completado' },
    pt: { gerund: 'completando', participle: 'completado' },
    ja: { te: '補完して', te_reading: 'ほかんして', nai: '補完しない', nai_reading: 'ほかんしない', passive: '補完される', passive_reading: 'ほかんされる' },
  },
  APPLY: {
    en: { gerund: 'applying', participle: 'applied' },
    it: { gerund: 'applicando', participle: 'applicato' },
    fr: { participle: 'appliqué' }, de: { participle: 'angewandt' },
    es: { gerund: 'aplicando', participle: 'aplicado' },
    pt: { gerund: 'aplicando', participle: 'aplicado' },
    ja: { te: '適用して', te_reading: 'てきようして', nai: '適用しない', nai_reading: 'てきようしない', passive: '適用される', passive_reading: 'てきようされる' },
  },
  // Grammar-word verbs (B06). All transitive → avere/haber/ter default (no aux key).
  NAME: {
    en: { gerund: 'naming', participle: 'named' },
    it: { gerund: 'nominando', participle: 'nominato' },
    fr: { participle: 'nommé' }, de: { participle: 'benannt' },
    es: { gerund: 'nombrando', participle: 'nombrado' },
    pt: { gerund: 'nomeando', participle: 'nomeado' },
    ja: { te: '名付けて', te_reading: 'なづけて', nai: '名付けない', nai_reading: 'なづけない', passive: '名付けられる', passive_reading: 'なづけられる' },
  },
  DESCRIBE: {
    en: { gerund: 'describing', participle: 'described' },
    it: { gerund: 'descrivendo', participle: 'descritto' },
    fr: { participle: 'décrit' }, de: { participle: 'beschrieben' },
    es: { gerund: 'describiendo', participle: 'descrito' },
    pt: { gerund: 'descrevendo', participle: 'descrito' },
    ja: { te: '描写して', te_reading: 'びょうしゃして', nai: '描写しない', nai_reading: 'びょうしゃしない', passive: '描写される', passive_reading: 'びょうしゃされる' },
  },
  MODIFY: {
    en: { gerund: 'modifying', participle: 'modified' },
    it: { gerund: 'modificando', participle: 'modificato' },
    fr: { participle: 'modifié' }, de: { participle: 'modifiziert' },
    es: { gerund: 'modificando', participle: 'modificado' },
    pt: { gerund: 'modificando', participle: 'modificado' },
    ja: { te: '修飾して', te_reading: 'しゅうしょくして', nai: '修飾しない', nai_reading: 'しゅうしょくしない', passive: '修飾される', passive_reading: 'しゅうしょくされる' },
  },
  // B51: DETERMINER's verb. de bestimmen has no ge- (an inseparable be- verb): bestimmt.
  SPECIFY: {
    en: { gerund: 'specifying', participle: 'specified' },
    it: { gerund: 'specificando', participle: 'specificato' },
    fr: { participle: 'précisé' }, de: { participle: 'bestimmt' },
    es: { gerund: 'especificando', participle: 'especificado' },
    pt: { gerund: 'especificando', participle: 'especificado' },
    ja: { te: '特定して', te_reading: 'とくていして', nai: '特定しない', nai_reading: 'とくていしない', passive: '特定される', passive_reading: 'とくていされる' },
  },
  // it reggere → retto; es regir raises e→i in the gerund (rigiendo).
  GOVERN: {
    en: { gerund: 'governing', participle: 'governed' },
    it: { gerund: 'reggendo', participle: 'retto' },
    fr: { participle: 'régi' }, de: { participle: 'regiert' },
    es: { gerund: 'rigiendo', participle: 'regido' },
    pt: { gerund: 'regendo', participle: 'regido' },
    ja: { te: '支配して', te_reading: 'しはいして', nai: '支配しない', nai_reading: 'しはいしない', passive: '支配される', passive_reading: 'しはいされる' },
  },
  // pt aceitar is abundant: aceitado after ter, aceite with ser.
  ACCEPT: {
    en: { gerund: 'accepting', participle: 'accepted' },
    it: { gerund: 'accettando', participle: 'accettato' },
    fr: { participle: 'accepté' }, de: { participle: 'akzeptiert' },
    es: { gerund: 'aceptando', participle: 'aceptado' },
    pt: { gerund: 'aceitando', participle: 'aceitado', participle_passive: 'aceite' },
    ja: { te: '受け付けて', te_reading: 'うけつけて', nai: '受け付けない', nai_reading: 'うけつけない', passive: '受け付けられる', passive_reading: 'うけつけられる' },
  },
  NEGATE: {
    en: { gerund: 'negating', participle: 'negated' },
    it: { gerund: 'negando', participle: 'negato' },
    fr: { participle: 'nié' }, de: { participle: 'verneint' },
    es: { gerund: 'negando', participle: 'negado' },
    pt: { gerund: 'negando', participle: 'negado' },
    ja: { te: '否定して', te_reading: 'ひていして', nai: '否定しない', nai_reading: 'ひていしない', passive: '否定される', passive_reading: 'ひていされる' },
  },
  ASSERT: {
    en: { gerund: 'asserting', participle: 'asserted' },
    it: { gerund: 'affermando', participle: 'affermato' },
    fr: { participle: 'affirmé' }, de: { participle: 'festgestellt' },
    es: { gerund: 'afirmando', participle: 'afirmado' },
    pt: { gerund: 'afirmando', participle: 'afirmado' },
    ja: { te: '述べて', te_reading: 'のべて', nai: '述べない', nai_reading: 'のべない', passive: '述べられる', passive_reading: 'のべられる' },
  },
  EDIT: {
    en: { gerund: 'editing', participle: 'edited' },
    it: { gerund: 'modificando', participle: 'modificato' },
    fr: { participle: 'modifié' }, de: { participle: 'bearbeitet' },
    es: { gerund: 'editando', participle: 'editado' },
    pt: { gerund: 'editando', participle: 'editado' },
    ja: { te: '編集して', te_reading: 'へんしゅうして', nai: '編集しない', nai_reading: 'へんしゅうしない', passive: '編集される', passive_reading: 'へんしゅうされる' },
  },
  EXPRESS: {
    en: { gerund: 'expressing', participle: 'expressed' },
    it: { gerund: 'esprimendo', participle: 'espresso' },
    fr: { participle: 'exprimé' }, de: { participle: 'vermittelt' },
    es: { gerund: 'expresando', participle: 'expresado' },
    pt: { gerund: 'exprimindo', participle: 'exprimido' },
    ja: { te: '表して', te_reading: 'あらわして', nai: '表さない', nai_reading: 'あらわさない', passive: '表される', passive_reading: 'あらわされる' },
  },
  // The saying and thinking verbs of localization B60. The strong participles: detto, dit, dicho,
  // dito; chiesto; creduto, cru, creído; told, thought, meant. German anrufen puts ge- after its
  // particle (angerufen), erzählen and bedeuten take none. Italian takes avere for all of them.
  SAY: {
    en: { gerund: 'saying', participle: 'said' },
    it: { gerund: 'dicendo', participle: 'detto' },
    fr: { participle: 'dit' }, de: { participle: 'gesagt' },
    es: { gerund: 'diciendo', participle: 'dicho' },
    pt: { gerund: 'dizendo', participle: 'dito' },
    ja: { te: '言って', te_reading: 'いって', nai: '言わない', nai_reading: 'いわない', passive: '言われる', passive_reading: 'いわれる' },
  },
  TELL: {
    en: { gerund: 'telling', participle: 'told' },
    it: { gerund: 'raccontando', participle: 'raccontato' },
    fr: { participle: 'raconté' }, de: { participle: 'erzählt' },
    es: { gerund: 'contando', participle: 'contado' },
    pt: { gerund: 'contando', participle: 'contado' },
    ja: { te: '伝えて', te_reading: 'つたえて', nai: '伝えない', nai_reading: 'つたえない', passive: '伝えられる', passive_reading: 'つたえられる' },
  },
  ASK: {
    en: { gerund: 'asking', participle: 'asked' },
    it: { gerund: 'chiedendo', participle: 'chiesto' },
    fr: { participle: 'demandé' }, de: { participle: 'gefragt' },
    es: { gerund: 'preguntando', participle: 'preguntado' },
    pt: { gerund: 'perguntando', participle: 'perguntado' },
    ja: { te: '尋ねて', te_reading: 'たずねて', nai: '尋ねない', nai_reading: 'たずねない', passive: '尋ねられる', passive_reading: 'たずねられる' },
  },
  CALL: {
    en: { gerund: 'calling', participle: 'called' },
    it: { gerund: 'chiamando', participle: 'chiamato' },
    fr: { participle: 'appelé' }, de: { participle: 'gerufen' },
    es: { gerund: 'llamando', participle: 'llamado' },
    pt: { gerund: 'chamando', participle: 'chamado' },
    ja: { te: '呼んで', te_reading: 'よんで', nai: '呼ばない', nai_reading: 'よばない', passive: '呼ばれる', passive_reading: 'よばれる' },
  },
  CALL_PHONE: {
    en: { gerund: 'calling', participle: 'called' },
    it: { gerund: 'telefonando', participle: 'telefonato' },
    fr: { participle: 'téléphoné' }, de: { participle: 'angerufen' },
    es: { gerund: 'llamando', participle: 'llamado' },
    pt: { gerund: 'telefonando', participle: 'telefonado' },
    ja: { te: '電話して', te_reading: 'でんわして', nai: '電話しない', nai_reading: 'でんわしない', passive: '電話される', passive_reading: 'でんわされる' },
  },
  MEAN: {
    en: { gerund: 'meaning', participle: 'meant' },
    it: { gerund: 'significando', participle: 'significato' },
    fr: { participle: 'signifié' }, de: { participle: 'bedeutet' },
    es: { gerund: 'significando', participle: 'significado' },
    pt: { gerund: 'significando', participle: 'significado' },
    ja: { te: '意味して', te_reading: 'いみして', nai: '意味しない', nai_reading: 'いみしない', passive: '意味される', passive_reading: 'いみされる' },
  },
  BELIEVE: {
    en: { gerund: 'believing', participle: 'believed' },
    it: { gerund: 'credendo', participle: 'creduto' },
    fr: { participle: 'cru' }, de: { participle: 'geglaubt' },
    es: { gerund: 'creyendo', participle: 'creído' },
    pt: { gerund: 'acreditando', participle: 'acreditado' },
    ja: { te: '信じて', te_reading: 'しんじて', nai: '信じない', nai_reading: 'しんじない', passive: '信じられる', passive_reading: 'しんじられる' },
  },
  THINK: {
    en: { gerund: 'thinking', participle: 'thought' },
    it: { gerund: 'pensando', participle: 'pensato' },
    fr: { participle: 'pensé' }, de: { participle: 'gedacht' },
    es: { gerund: 'pensando', participle: 'pensado' },
    pt: { gerund: 'pensando', participle: 'pensado' },
    ja: { te: '考えて', te_reading: 'かんがえて', nai: '考えない', nai_reading: 'かんがえない' },
  },
  REPLACE: {
    en: { gerund: 'replacing', participle: 'replaced' },
    it: { gerund: 'sostituendo', participle: 'sostituito' },
    fr: { participle: 'remplacé' }, de: { participle: 'ersetzt' },
    es: { gerund: 'reemplazando', participle: 'reemplazado' },
    pt: { gerund: 'substituindo', participle: 'substituído' },
    ja: { te: '置き換えて', te_reading: 'おきかえて', nai: '置き換えない', nai_reading: 'おきかえない', passive: '置き換えられる', passive_reading: 'おきかえられる' },
  },
  // B32's three. it abitare and de wohnen both take the HAVE auxiliary ("ha abitato", "hat
  // gewohnt"), unlike the motion verbs above; de inhaftieren is an -ieren verb, so its participle
  // takes no ge-.
  LIVE: {
    en: { gerund: 'living', participle: 'lived' },
    it: { gerund: 'abitando', participle: 'abitato' },
    fr: { participle: 'habité' }, de: { participle: 'gewohnt' },
    es: { gerund: 'viviendo', participle: 'vivido' },
    pt: { gerund: 'morando', participle: 'morado' },
    ja: { te: '住んで', te_reading: 'すんで', nai: '住まない', nai_reading: 'すまない' },
  },
  LIVE_ALIVE: {
    en: { gerund: 'living', participle: 'lived' },
    it: { gerund: 'vivendo', participle: 'vissuto' },
    fr: { participle: 'vécu' }, de: { participle: 'gelebt' },
    es: { gerund: 'viviendo', participle: 'vivido' },
    pt: { gerund: 'vivendo', participle: 'vivido' },
    ja: { te: '生きて', te_reading: 'いきて', nai: '生きない', nai_reading: 'いきない' },
  },
  TRADE: {
    en: { gerund: 'trading', participle: 'traded' },
    it: { gerund: 'commerciando', participle: 'commerciato' },
    fr: { participle: 'commercé' }, de: { participle: 'gehandelt' },
    es: { gerund: 'comerciando', participle: 'comerciado' },
    pt: { gerund: 'comerciando', participle: 'comerciado' },
    ja: { te: '売買して', te_reading: 'ばいばいして', nai: '売買しない', nai_reading: 'ばいばいしない' },
  },
  ACT: {
    en: { gerund: 'acting', participle: 'acted' },
    it: { gerund: 'agendo', participle: 'agito' },
    fr: { participle: 'agi' }, de: { participle: 'gehandelt' },
    es: { gerund: 'actuando', participle: 'actuado' },
    pt: { gerund: 'agindo', participle: 'agido' },
    ja: { te: '行動して', te_reading: 'こうどうして', nai: '行動しない', nai_reading: 'こうどうしない' },
  },
  // WORK (C22): avere in Italian ("ha funzionato"), and German funktionieren has no ge-.
  WORK: {
    en: { gerund: 'working', participle: 'worked' },
    it: { gerund: 'funzionando', participle: 'funzionato' },
    fr: { participle: 'fonctionné' }, de: { participle: 'funktioniert' },
    es: { gerund: 'funcionando', participle: 'funcionado' },
    pt: { gerund: 'funcionando', participle: 'funcionado' },
    ja: { te: '動作して', te_reading: 'どうさして', nai: '動作しない', nai_reading: 'どうさしない' },
  },
  CONFINE: {
    en: { gerund: 'confining', participle: 'confined' },
    it: { gerund: 'rinchiudendo', participle: 'rinchiuso' },
    fr: { participle: 'enfermé' }, de: { participle: 'inhaftiert' },
    es: { gerund: 'encerrando', participle: 'encerrado' },
    pt: { gerund: 'encarcerando', participle: 'encarcerado' },
    ja: { te: '閉じ込めて', te_reading: 'とじこめて', nai: '閉じ込めない', nai_reading: 'とじこめない', passive: '閉じ込められる', passive_reading: 'とじこめられる' },
  },
  TAME: {
    en: { gerund: 'taming', participle: 'tamed' },
    it: { gerund: 'domando', participle: 'domato' },
    fr: { participle: 'apprivoisé' }, de: { participle: 'gezähmt' },
    es: { gerund: 'domando', participle: 'domado' },
    pt: { gerund: 'domando', participle: 'domado' },
    ja: { te: '飼い慣らして', te_reading: 'かいならして', nai: '飼い慣らさない', nai_reading: 'かいならさない', passive: '飼い慣らされる', passive_reading: 'かいならされる' },
  },
  // ── The definition words of localization B52–B57 ───────────────────
  // fliegen is a motion verb, so its German resultative selects sein ("ist geflogen"); Italian
  // volare takes avere for the activity ("ha volato").
  FLY: {
    en: { gerund: 'flying', participle: 'flown' },
    it: { gerund: 'volando', participle: 'volato' },
    fr: { participle: 'volé' }, de: { participle: 'geflogen', aux: 'be' },
    es: { gerund: 'volando', participle: 'volado' },
    pt: { gerund: 'voando', participle: 'voado' },
    ja: { te: '飛んで', te_reading: 'とんで', nai: '飛ばない', nai_reading: 'とばない' },
  },
  BREATHE: {
    en: { gerund: 'breathing', participle: 'breathed' },
    it: { gerund: 'respirando', participle: 'respirato' },
    fr: { participle: 'respiré' }, de: { participle: 'geatmet' },
    es: { gerund: 'respirando', participle: 'respirado' },
    pt: { gerund: 'respirando', participle: 'respirado' },
    ja: { te: '呼吸して', te_reading: 'こきゅうして', nai: '呼吸しない', nai_reading: 'こきゅうしない', passive: '呼吸される', passive_reading: 'こきゅうされる' },
  },
  EXCHANGE: {
    en: { gerund: 'exchanging', participle: 'exchanged' },
    it: { gerund: 'scambiando', participle: 'scambiato' },
    fr: { participle: 'échangé' }, de: { participle: 'getauscht' },
    es: { gerund: 'intercambiando', participle: 'intercambiado' },
    pt: { gerund: 'trocando', participle: 'trocado' },
    ja: { te: '交換して', te_reading: 'こうかんして', nai: '交換しない', nai_reading: 'こうかんしない', passive: '交換される', passive_reading: 'こうかんされる' },
  },
  // umschließen is strong and inseparable, so its participle has no ge-: umschlossen.
  ENCLOSE: {
    en: { gerund: 'enclosing', participle: 'enclosed' },
    it: { gerund: 'racchiudendo', participle: 'racchiuso' },
    fr: { participle: 'entouré' }, de: { participle: 'umschlossen' },
    es: { gerund: 'encerrando', participle: 'encerrado' },
    pt: { gerund: 'cercando', participle: 'cercado' },
    ja: { te: '囲んで', te_reading: 'かこんで', nai: '囲まない', nai_reading: 'かこまない', passive: '囲まれる', passive_reading: 'かこまれる' },
  },
  HEAR: {
    en: { gerund: 'hearing', participle: 'heard' },
    it: { gerund: 'sentendo', participle: 'sentito' },
    fr: { participle: 'entendu' }, de: { participle: 'gehört' },
    es: { gerund: 'oyendo', participle: 'oído' },
    pt: { gerund: 'ouvindo', participle: 'ouvido' },
    ja: { te: '聞いて', te_reading: 'きいて', nai: '聞かない', nai_reading: 'きかない', passive: '聞かれる', passive_reading: 'きかれる' },
  },
  // regieren is a -ieren verb: its participle has no ge-.
  GOVERN_STATE: {
    en: { gerund: 'governing', participle: 'governed' },
    it: { gerund: 'governando', participle: 'governato' },
    fr: { participle: 'gouverné' }, de: { participle: 'regiert' },
    es: { gerund: 'gobernando', participle: 'gobernado' },
    pt: { gerund: 'governando', participle: 'governado' },
    ja: { te: '統治して', te_reading: 'とうちして', nai: '統治しない', nai_reading: 'とうちしない', passive: '統治される', passive_reading: 'とうちされる' },
  },
  SPEAK: {
    en: { gerund: 'speaking', participle: 'spoken' },
    it: { gerund: 'parlando', participle: 'parlato' },
    fr: { participle: 'parlé' }, de: { participle: 'gesprochen' },
    es: { gerund: 'hablando', participle: 'hablado' },
    pt: { gerund: 'falando', participle: 'falado' },
    ja: { te: '話して', te_reading: 'はなして', nai: '話さない', nai_reading: 'はなさない' },
  },
  // The order, time, growth and substance verbs of localization C24. Italian precedere and seguire
  // take avere; succedere, crescere and scorrere take essere, as vorangehen, folgen, geschehen,
  // wachsen and fließen take sein.
  PRECEDE: {
    en: { gerund: 'preceding', participle: 'preceded' },
    it: { gerund: 'precedendo', participle: 'preceduto' },
    fr: { participle: 'précédé' }, de: { participle: 'vorangegangen', aux: 'be' },
    es: { gerund: 'precediendo', participle: 'precedido' },
    pt: { gerund: 'precedendo', participle: 'precedido' },
    ja: { te: '先行して', te_reading: 'せんこうして', nai: '先行しない', nai_reading: 'せんこうしない' },
  },
  DEPEND: {
    en: { gerund: 'depending', participle: 'depended' },
    it: { gerund: 'dipendendo', participle: 'dipeso', aux: 'be' },
    fr: { participle: 'dépendu' }, de: { participle: 'abgehangen' },
    es: { gerund: 'dependiendo', participle: 'dependido' },
    pt: { gerund: 'dependendo', participle: 'dependido' },
    ja: { te: '依存して', te_reading: 'いぞんして', nai: '依存しない', nai_reading: 'いぞんしない' },
  },
  FOLLOW: {
    en: { gerund: 'following', participle: 'followed' },
    it: { gerund: 'seguendo', participle: 'seguito' },
    fr: { participle: 'suivi' }, de: { participle: 'gefolgt', aux: 'be' },
    es: { gerund: 'siguiendo', participle: 'seguido' },
    pt: { gerund: 'seguindo', participle: 'seguido' },
    ja: { te: '続いて', te_reading: 'つづいて', nai: '続かない', nai_reading: 'つづかない' },
  },
  HAPPEN: {
    en: { gerund: 'happening', participle: 'happened' },
    it: { gerund: 'succedendo', participle: 'successo', aux: 'be' },
    fr: { participle: 'arrivé', aux: 'be' }, de: { participle: 'geschehen', aux: 'be' },
    es: { gerund: 'ocurriendo', participle: 'ocurrido' },
    pt: { gerund: 'acontecendo', participle: 'acontecido' },
    ja: { te: '起こって', te_reading: 'おこって', nai: '起こらない', nai_reading: 'おこらない' },
  },
  GROW: {
    en: { gerund: 'growing', participle: 'grown' },
    it: { gerund: 'crescendo', participle: 'cresciuto', aux: 'be' },
    fr: { participle: 'grandi' }, de: { participle: 'gewachsen', aux: 'be' },
    es: { gerund: 'creciendo', participle: 'crecido' },
    pt: { gerund: 'crescendo', participle: 'crescido' },
    ja: { te: '成長して', te_reading: 'せいちょうして', nai: '成長しない', nai_reading: 'せいちょうしない' },
  },
  FLOW: {
    en: { gerund: 'flowing', participle: 'flowed' },
    it: { gerund: 'scorrendo', participle: 'scorso', aux: 'be' },
    fr: { participle: 'coulé' }, de: { participle: 'geflossen', aux: 'be' },
    es: { gerund: 'fluyendo', participle: 'fluido' },
    pt: { gerund: 'fluindo', participle: 'fluído' },
    ja: { te: '流れて', te_reading: 'ながれて', nai: '流れない', nai_reading: 'ながれない' },
  },
  ACCOMPANY: {
    en: { gerund: 'accompanying', participle: 'accompanied' },
    it: { gerund: 'accompagnando', participle: 'accompagnato' },
    fr: { participle: 'accompagné' }, de: { participle: 'begleitet' },
    es: { gerund: 'acompañando', participle: 'acompañado' },
    pt: { gerund: 'acompanhando', participle: 'acompanhado' },
    ja: { te: '同行して', te_reading: 'どうこうして', nai: '同行しない', nai_reading: 'どうこうしない', passive: '同行される', passive_reading: 'どうこうされる' },
  },
  ANSWER: {
    en: { gerund: 'answering', participle: 'answered' },
    it: { gerund: 'rispondendo', participle: 'risposto' },
    fr: { participle: 'répondu' }, de: { participle: 'geantwortet' },
    es: { gerund: 'respondiendo', participle: 'respondido' },
    pt: { gerund: 'respondendo', participle: 'respondido' },
    ja: { te: '答えて', te_reading: 'こたえて', nai: '答えない', nai_reading: 'こたえない', passive: '答えられる', passive_reading: 'こたえられる' },
  },
  SEARCH: {
    en: { gerund: 'seeking', participle: 'sought' },
    it: { gerund: 'cercando', participle: 'cercato' },
    fr: { participle: 'cherché' }, de: { participle: 'gesucht' },
    es: { gerund: 'buscando', participle: 'buscado' },
    pt: { gerund: 'procurando', participle: 'procurado' },
    ja: { te: '探して', te_reading: 'さがして', nai: '探さない', nai_reading: 'さがさない', passive: '探される', passive_reading: 'さがされる' },
  },
  FIND: {
    en: { gerund: 'finding', participle: 'found' },
    it: { gerund: 'trovando', participle: 'trovato' },
    fr: { participle: 'trouvé' }, de: { participle: 'gefunden' },
    es: { gerund: 'encontrando', participle: 'encontrado' },
    pt: { gerund: 'encontrando', participle: 'encontrado' },
    ja: { te: '見つけて', te_reading: 'みつけて', nai: '見つけない', nai_reading: 'みつけない', passive: '見つけられる', passive_reading: 'みつけられる' },
  },
  // anordnen is separable: the ge- goes between the particle and the stem, angeordnet.
  ARRANGE: {
    en: { gerund: 'arranging', participle: 'arranged' },
    it: { gerund: 'disponendo', participle: 'disposto' },
    fr: { participle: 'disposé' }, de: { participle: 'angeordnet' },
    es: { gerund: 'disponiendo', participle: 'dispuesto' },
    pt: { gerund: 'dispondo', participle: 'disposto' },
    ja: { te: '並べて', te_reading: 'ならべて', nai: '並べない', nai_reading: 'ならべない', passive: '並べられる', passive_reading: 'ならべられる' },
  },
  CONNECT: {
    en: { gerund: 'connecting', participle: 'connected' },
    it: { gerund: 'connettendo', participle: 'connesso' },
    fr: { participle: 'connecté' }, de: { participle: 'verbunden' },
    es: { gerund: 'conectando', participle: 'conectado' },
    pt: { gerund: 'conectando', participle: 'conectado' },
    ja: { te: '接続して', te_reading: 'せつぞくして', nai: '接続しない', nai_reading: 'せつぞくしない', passive: '接続される', passive_reading: 'せつぞくされる' },
  },
};
