/**
 * Non-finite verb forms that feed the grammatical *aspect* (progressive / prospective /
 * resultative). Kept as one table rather than scattered across every verb block: the seed
 * loop merges the per-language entry into that verb's forms before persisting them.
 *   • gerund     — present participle / gerundio / gerúndio (en/it/es/pt progressive).
 *   • participle — past participle (all Romance + de/en resultative; fr also for resultative).
 *   • te / te_reading — Japanese te-form, the base for ～ている / ～てしまう.
 *   • nai / nai_reading — Japanese plain negative (食べない), the base for the negative たら
 *     (食べなかったら). Only the "if" clause reads it; a negated relative clause or citation keeps the
 *     polite negative (B13).
 *   • aux        — "be" on the verbs whose resultative selects the BE auxiliary instead of
 *     the HAVE default (it essere / fr être / de sein). Selection is lexical, not syntactic,
 *     and it does not match across languages: "correre" takes avere but "laufen" takes sein.
 *     Absent = HAVE. es/pt/en/ja have a single auxiliary and ignore the key.
 * French/German need no gerund (their progressive is periphrastic on the infinitive/adverb);
 * Japanese needs only the te-form. Irregular forms (gone, corso, gegangen, visto…) can't be
 * derived by rule, so they are listed explicitly. Copular verbs (become/seem/appear) get
 * best-effort forms — aspect on them is linguistically marginal.
 */
export const NONFINITE: Record<string, Record<string, Record<string, string>>> = {
  // The copula's resultative selects BE in it/de (è stato / ist gewesen); fr/es/pt/en use
  // HAVE (a été / ha sido / tem sido / has been). Aspect on a copula is marginal, so these
  // are best-effort. ja renders the copula specially and never reads a te-form.
  BE: {
    en: { gerund: 'being', participle: 'been' },
    it: { gerund: 'essendo', participle: 'stato', aux: 'be' },
    fr: { participle: 'été' }, de: { participle: 'gewesen', aux: 'be' },
    es: { gerund: 'siendo', participle: 'sido' },
    pt: { gerund: 'sendo', participle: 'sido' },
  },
  CUT: {
    en: { gerund: 'cutting', participle: 'cut' },
    it: { gerund: 'tagliando', participle: 'tagliato' },
    fr: { participle: 'coupé' }, de: { participle: 'geschnitten' },
    es: { gerund: 'cortando', participle: 'cortado' },
    pt: { gerund: 'cortando', participle: 'cortado' },
    ja: { te: '切って', te_reading: 'きって', nai: '切らない', nai_reading: 'きらない' },
  },
  EAT: {
    en: { gerund: 'eating', participle: 'eaten' },
    it: { gerund: 'mangiando', participle: 'mangiato' },
    fr: { participle: 'mangé' }, de: { participle: 'gegessen' },
    es: { gerund: 'comiendo', participle: 'comido' },
    pt: { gerund: 'comendo', participle: 'comido' },
    ja: { te: '食べて', te_reading: 'たべて', nai: '食べない', nai_reading: 'たべない' },
  },
  DRINK: {
    en: { gerund: 'drinking', participle: 'drunk' },
    it: { gerund: 'bevendo', participle: 'bevuto' },
    fr: { participle: 'bu' }, de: { participle: 'getrunken' },
    es: { gerund: 'bebiendo', participle: 'bebido' },
    pt: { gerund: 'bebendo', participle: 'bebido' },
    ja: { te: '飲んで', te_reading: 'のんで', nai: '飲まない', nai_reading: 'のまない' },
  },
  CONSUME: {
    en: { gerund: 'consuming', participle: 'consumed' },
    it: { gerund: 'consumando', participle: 'consumato' },
    fr: { participle: 'consommé' }, de: { participle: 'konsumiert' },
    es: { gerund: 'consumiendo', participle: 'consumido' },
    pt: { gerund: 'consumindo', participle: 'consumido' },
    ja: { te: '摂取して', te_reading: 'せっしゅして', nai: '摂取しない', nai_reading: 'せっしゅしない' },
  },
  RUN: {
    en: { gerund: 'running', participle: 'run' },
    it: { gerund: 'correndo', participle: 'corso' },
    fr: { participle: 'couru' }, de: { participle: 'gelaufen', aux: 'be' },
    es: { gerund: 'corriendo', participle: 'corrido' },
    pt: { gerund: 'correndo', participle: 'corrido' },
    ja: { te: '走って', te_reading: 'はしって', nai: '走らない', nai_reading: 'はしらない' },
  },
  SEE: {
    en: { gerund: 'seeing', participle: 'seen' },
    it: { gerund: 'vedendo', participle: 'visto' },
    fr: { participle: 'vu' }, de: { participle: 'gesehen' },
    es: { gerund: 'viendo', participle: 'visto' },
    pt: { gerund: 'vendo', participle: 'visto' },
    ja: { te: '見て', te_reading: 'みて', nai: '見ない', nai_reading: 'みない' },
  },
  LOVE: {
    en: { gerund: 'loving', participle: 'loved' },
    it: { gerund: 'amando', participle: 'amato' },
    fr: { participle: 'aimé' }, de: { participle: 'geliebt' },
    es: { gerund: 'amando', participle: 'amado' },
    pt: { gerund: 'amando', participle: 'amado' },
    ja: { te: '愛して', te_reading: 'あいして', nai: '愛さない', nai_reading: 'あいさない' },
  },
  KILL: {
    en: { gerund: 'killing', participle: 'killed' },
    it: { gerund: 'uccidendo', participle: 'ucciso' },
    fr: { participle: 'tué' }, de: { participle: 'getötet' },
    es: { gerund: 'matando', participle: 'matado' },
    pt: { gerund: 'matando', participle: 'matado' },
    ja: { te: '殺して', te_reading: 'ころして', nai: '殺さない', nai_reading: 'ころさない' },
  },
  KNOW: {
    en: { gerund: 'knowing', participle: 'known' },
    it: { gerund: 'sapendo', participle: 'saputo' },
    fr: { participle: 'su' }, de: { participle: 'gewusst' },
    es: { gerund: 'sabiendo', participle: 'sabido' },
    pt: { gerund: 'sabendo', participle: 'sabido' },
    ja: { te: '知って', te_reading: 'しって', nai: '知らない', nai_reading: 'しらない' },
  },
  KNOW_ACQUAINTED: {
    en: { gerund: 'knowing', participle: 'known' },
    it: { gerund: 'conoscendo', participle: 'conosciuto' },
    fr: { participle: 'connu' }, de: { participle: 'gekannt' },
    es: { gerund: 'conociendo', participle: 'conocido' },
    pt: { gerund: 'conhecendo', participle: 'conhecido' },
    ja: { te: '知って', te_reading: 'しって', nai: '知らない', nai_reading: 'しらない' },
  },
  READ: {
    en: { gerund: 'reading', participle: 'read' },
    it: { gerund: 'leggendo', participle: 'letto' },
    fr: { participle: 'lu' }, de: { participle: 'gelesen' },
    es: { gerund: 'leyendo', participle: 'leído' },
    pt: { gerund: 'lendo', participle: 'lido' },
    ja: { te: '読んで', te_reading: 'よんで', nai: '読まない', nai_reading: 'よまない' },
  },
  JUMP: {
    en: { gerund: 'jumping', participle: 'jumped' },
    it: { gerund: 'saltando', participle: 'saltato' },
    fr: { participle: 'sauté' }, de: { participle: 'gesprungen', aux: 'be' },
    es: { gerund: 'saltando', participle: 'saltado' },
    pt: { gerund: 'pulando', participle: 'pulado' },
    ja: { te: '跳んで', te_reading: 'とんで', nai: '跳ばない', nai_reading: 'とばない' },
  },
  COME: {
    en: { gerund: 'coming', participle: 'come' },
    it: { gerund: 'venendo', participle: 'venuto', aux: 'be' },
    fr: { participle: 'venu', aux: 'be' }, de: { participle: 'gekommen', aux: 'be' },
    es: { gerund: 'viniendo', participle: 'venido' },
    pt: { gerund: 'vindo', participle: 'vindo' },
    ja: { te: '来て', te_reading: 'きて', nai: '来ない', nai_reading: 'こない' },
  },
  CRY: {
    en: { gerund: 'crying', participle: 'cried' },
    it: { gerund: 'piangendo', participle: 'pianto' },
    fr: { participle: 'pleuré' }, de: { participle: 'geweint' },
    es: { gerund: 'llorando', participle: 'llorado' },
    pt: { gerund: 'chorando', participle: 'chorado' },
    ja: { te: '泣いて', te_reading: 'ないて', nai: '泣かない', nai_reading: 'なかない' },
  },
  CRY_OUT: {
    en: { gerund: 'crying', participle: 'cried' },
    it: { gerund: 'gridando', participle: 'gridato' },
    fr: { participle: 'crié' }, de: { participle: 'gerufen' },
    es: { gerund: 'gritando', participle: 'gritado' },
    pt: { gerund: 'gritando', participle: 'gritado' },
    ja: { te: '叫んで', te_reading: 'さけんで', nai: '叫ばない', nai_reading: 'さけばない' },
  },
  BITE: {
    en: { gerund: 'biting', participle: 'bitten' },
    it: { gerund: 'mordendo', participle: 'morso' },
    fr: { participle: 'mordu' }, de: { participle: 'gebissen' },
    es: { gerund: 'mordiendo', participle: 'mordido' },
    pt: { gerund: 'mordendo', participle: 'mordido' },
    ja: { te: '噛んで', te_reading: 'かんで', nai: '噛まない', nai_reading: 'かまない' },
  },
  BEAT: {
    en: { gerund: 'beating', participle: 'beaten' },
    it: { gerund: 'battendo', participle: 'battuto' },
    fr: { participle: 'battu' }, de: { participle: 'geschlagen' },
    es: { gerund: 'batiendo', participle: 'batido' },
    pt: { gerund: 'batendo', participle: 'batido' },
    ja: { te: '打って', te_reading: 'うって', nai: '打たない', nai_reading: 'うたない' },
  },
  BURN: {
    en: { gerund: 'burning', participle: 'burned' },
    it: { gerund: 'bruciando', participle: 'bruciato' },
    fr: { participle: 'brûlé' }, de: { participle: 'gebrannt' },
    es: { gerund: 'ardiendo', participle: 'ardido' },
    pt: { gerund: 'ardendo', participle: 'ardido' },
    ja: { te: '燃えて', te_reading: 'もえて', nai: '燃えない', nai_reading: 'もえない' },
  },
  SET_ON_FIRE: {
    en: { gerund: 'burning', participle: 'burned' },
    it: { gerund: 'bruciando', participle: 'bruciato' },
    fr: { participle: 'brûlé' }, de: { participle: 'verbrannt' },
    es: { gerund: 'quemando', participle: 'quemado' },
    pt: { gerund: 'queimando', participle: 'queimado' },
    ja: { te: '燃やして', te_reading: 'もやして', nai: '燃やさない', nai_reading: 'もやさない' },
  },
  EXTINGUISH: {
    en: { gerund: 'putting out', participle: 'put out' },
    it: { gerund: 'spegnendo', participle: 'spento' },
    fr: { participle: 'éteint' }, de: { participle: 'gelöscht' },
    es: { gerund: 'apagando', participle: 'apagado' },
    pt: { gerund: 'apagando', participle: 'apagado' },
    ja: { te: '消して', te_reading: 'けして', nai: '消さない', nai_reading: 'けさない' },
  },
  BUY: {
    en: { gerund: 'buying', participle: 'bought' },
    it: { gerund: 'comprando', participle: 'comprato' },
    fr: { participle: 'acheté' }, de: { participle: 'gekauft' },
    es: { gerund: 'comprando', participle: 'comprado' },
    pt: { gerund: 'comprando', participle: 'comprado' },
    ja: { te: '買って', te_reading: 'かって', nai: '買わない', nai_reading: 'かわない' },
  },
  OWN: {
    en: { gerund: 'owning', participle: 'owned' },
    it: { gerund: 'possedendo', participle: 'posseduto' },
    fr: { participle: 'possédé' }, de: { participle: 'besessen' },
    es: { gerund: 'poseyendo', participle: 'poseído' },
    pt: { gerund: 'possuindo', participle: 'possuído' },
    ja: { te: '所有して', te_reading: 'しょゆうして', nai: '所有しない', nai_reading: 'しょゆうしない' },
  },
  HOLD: {
    en: { gerund: 'holding', participle: 'held' },
    it: { gerund: 'contenendo', participle: 'contenuto' },
    fr: { participle: 'contenu' }, de: { participle: 'enthalten' },
    es: { gerund: 'conteniendo', participle: 'contenido' },
    pt: { gerund: 'contendo', participle: 'contido' },
    ja: { te: '保持して', te_reading: 'ほじして', nai: '保持しない', nai_reading: 'ほじしない' },
  },
  CLICK: {
    en: { gerund: 'clicking', participle: 'clicked' },
    it: { gerund: 'cliccando', participle: 'cliccato' },
    fr: { participle: 'cliqué' }, de: { participle: 'geklickt' },
    es: { gerund: 'clicando', participle: 'clicado' },
    pt: { gerund: 'clicando', participle: 'clicado' },
    ja: { te: 'クリックして', te_reading: 'くりっくして', nai: 'クリックしない', nai_reading: 'くりっくしない' },
  },
  CHOOSE: {
    en: { gerund: 'choosing', participle: 'chosen' },
    it: { gerund: 'scegliendo', participle: 'scelto' },
    fr: { participle: 'choisi' }, de: { participle: 'gewählt' },
    es: { gerund: 'eligiendo', participle: 'elegido' },
    pt: { gerund: 'escolhendo', participle: 'escolhido' },
    ja: { te: '選んで', te_reading: 'えらんで', nai: '選ばない', nai_reading: 'えらばない' },
  },
  SELECT: {
    en: { gerund: 'selecting', participle: 'selected' },
    it: { gerund: 'selezionando', participle: 'selezionato' },
    fr: { participle: 'sélectionné' }, de: { participle: 'selektiert' },
    es: { gerund: 'seleccionando', participle: 'seleccionado' },
    pt: { gerund: 'selecionando', participle: 'selecionado' },
    ja: { te: '選択して', te_reading: 'せんたくして', nai: '選択しない', nai_reading: 'せんたくしない' },
  },
  TYPE: {
    en: { gerund: 'typing', participle: 'typed' },
    it: { gerund: 'digitando', participle: 'digitato' },
    fr: { participle: 'tapé' }, de: { participle: 'getippt' },
    es: { gerund: 'tecleando', participle: 'tecleado' },
    pt: { gerund: 'digitando', participle: 'digitado' },
    ja: { te: '入力して', te_reading: 'にゅうりょくして', nai: '入力しない', nai_reading: 'にゅうりょくしない' },
  },
  GIVE: {
    en: { gerund: 'giving', participle: 'given' },
    it: { gerund: 'dando', participle: 'dato' },
    fr: { participle: 'donné' }, de: { participle: 'gegeben' },
    es: { gerund: 'dando', participle: 'dado' },
    pt: { gerund: 'dando', participle: 'dado' },
    ja: { te: 'あげて', te_reading: 'あげて', nai: 'あげない' },
  },
  SHOW: {
    en: { gerund: 'showing', participle: 'shown' },
    it: { gerund: 'mostrando', participle: 'mostrato' },
    fr: { participle: 'montré' }, de: { participle: 'gezeigt' },
    es: { gerund: 'mostrando', participle: 'mostrado' },
    pt: { gerund: 'mostrando', participle: 'mostrado' },
    ja: { te: '見せて', te_reading: 'みせて', nai: '見せない', nai_reading: 'みせない' },
  },
  SEND: {
    en: { gerund: 'sending', participle: 'sent' },
    it: { gerund: 'mandando', participle: 'mandato' },
    fr: { participle: 'envoyé' }, de: { participle: 'geschickt' },
    es: { gerund: 'enviando', participle: 'enviado' },
    pt: { gerund: 'enviando', participle: 'enviado' },
    ja: { te: '送って', te_reading: 'おくって', nai: '送らない', nai_reading: 'おくらない' },
  },
  GO: {
    en: { gerund: 'going', participle: 'gone', aux: 'be' }, // "is gone", not "has gone"
    it: { gerund: 'andando', participle: 'andato', aux: 'be' },
    fr: { participle: 'allé', aux: 'be' }, de: { participle: 'gegangen', aux: 'be' },
    es: { gerund: 'yendo', participle: 'ido' },
    pt: { gerund: 'indo', participle: 'ido' },
    ja: { te: '行って', te_reading: 'いって', nai: '行かない', nai_reading: 'いかない' },
  },
  BECOME: {
    en: { gerund: 'becoming', participle: 'become' },
    it: { gerund: 'diventando', participle: 'diventato', aux: 'be' },
    fr: { participle: 'devenu', aux: 'be' }, de: { participle: 'geworden', aux: 'be' },
    es: { gerund: 'volviéndose', participle: 'vuelto' },
    pt: { gerund: 'tornando-se', participle: 'tornado' },
    ja: { te: 'なって', te_reading: 'なって', nai: 'ならない', nai_reading: 'ならない' },
  },
  SEEM: {
    en: { gerund: 'seeming', participle: 'seemed' },
    it: { gerund: 'sembrando', participle: 'sembrato', aux: 'be' },
    fr: { participle: 'semblé' }, de: { participle: 'geschienen' },
    es: { gerund: 'pareciendo', participle: 'parecido' },
    pt: { gerund: 'parecendo', participle: 'parecido' },
    ja: { te: '思えて', te_reading: 'おもえて', nai: '思えない', nai_reading: 'おもえない' },
  },
  APPEAR: {
    en: { gerund: 'appearing', participle: 'appeared' },
    it: { gerund: 'apparendo', participle: 'apparso', aux: 'be' },
    fr: { participle: 'apparu', aux: 'be' }, de: { participle: 'erschienen', aux: 'be' },
    es: { gerund: 'apareciendo', participle: 'aparecido' },
    pt: { gerund: 'aparecendo', participle: 'aparecido' },
    ja: { te: '現れて', te_reading: 'あらわれて', nai: '現れない', nai_reading: 'あらわれない' },
  },
  SAVE: {
    en: { gerund: 'saving', participle: 'saved' },
    it: { gerund: 'salvando', participle: 'salvato' },
    fr: { participle: 'enregistré' }, de: { participle: 'gespeichert' },
    es: { gerund: 'guardando', participle: 'guardado' },
    pt: { gerund: 'salvando', participle: 'salvado' },
    ja: { te: '保存して', te_reading: 'ほぞんして', nai: '保存しない', nai_reading: 'ほぞんしない' },
  },
  LOAD: {
    en: { gerund: 'loading', participle: 'loaded' },
    it: { gerund: 'caricando', participle: 'caricato' },
    fr: { participle: 'chargé' }, de: { participle: 'geladen' },
    es: { gerund: 'cargando', participle: 'cargado' },
    pt: { gerund: 'carregando', participle: 'carregado' },
    ja: { te: '読み込んで', te_reading: 'よみこんで', nai: '読み込まない', nai_reading: 'よみこまない' },
  },
  ADD: {
    en: { gerund: 'adding', participle: 'added' },
    it: { gerund: 'aggiungendo', participle: 'aggiunto' },
    fr: { participle: 'ajouté' }, de: { participle: 'hinzugefügt' },
    es: { gerund: 'añadiendo', participle: 'añadido' },
    pt: { gerund: 'adicionando', participle: 'adicionado' },
    ja: { te: '加えて', te_reading: 'くわえて', nai: '加えない', nai_reading: 'くわえない' },
  },
  EXPORT: {
    en: { gerund: 'exporting', participle: 'exported' },
    it: { gerund: 'esportando', participle: 'esportato' },
    fr: { participle: 'exporté' }, de: { participle: 'exportiert' },
    es: { gerund: 'exportando', participle: 'exportado' },
    pt: { gerund: 'exportando', participle: 'exportado' },
    ja: { te: '書き出して', te_reading: 'かきだして', nai: '書き出さない', nai_reading: 'かきださない' },
  },
  IMPORT: {
    en: { gerund: 'importing', participle: 'imported' },
    it: { gerund: 'importando', participle: 'importato' },
    fr: { participle: 'importé' }, de: { participle: 'importiert' },
    es: { gerund: 'importando', participle: 'importado' },
    pt: { gerund: 'importando', participle: 'importado' },
    ja: { te: '取り込んで', te_reading: 'とりこんで', nai: '取り込まない', nai_reading: 'とりこまない' },
  },
  CLEAR: {
    en: { gerund: 'clearing', participle: 'cleared' },
    it: { gerund: 'cancellando', participle: 'cancellato' },
    fr: { participle: 'effacé' }, de: { participle: 'gelöscht' },
    es: { gerund: 'borrando', participle: 'borrado' },
    pt: { gerund: 'limpando', participle: 'limpado' },
    ja: { te: '消去して', te_reading: 'しょうきょして', nai: '消去しない', nai_reading: 'しょうきょしない' },
  },
  // it rimosso is irregular. de entfernt takes no ge- after its unstressed ent-, where löschen does
  // (gelöscht). pt excluído keeps the accent that splits its u-i.
  REMOVE: {
    en: { gerund: 'removing', participle: 'removed' },
    it: { gerund: 'rimuovendo', participle: 'rimosso' },
    fr: { participle: 'retiré' }, de: { participle: 'entfernt' },
    es: { gerund: 'quitando', participle: 'quitado' },
    pt: { gerund: 'removendo', participle: 'removido' },
    ja: { te: '取り除いて', te_reading: 'とりのぞいて', nai: '取り除かない', nai_reading: 'とりのぞかない' },
  },
  DELETE: {
    en: { gerund: 'deleting', participle: 'deleted' },
    it: { gerund: 'eliminando', participle: 'eliminato' },
    fr: { participle: 'supprimé' }, de: { participle: 'gelöscht' },
    es: { gerund: 'eliminando', participle: 'eliminado' },
    pt: { gerund: 'excluindo', participle: 'excluído' },
    ja: { te: '削除して', te_reading: 'さくじょして', nai: '削除しない', nai_reading: 'さくじょしない' },
  },
  COORDINATE: {
    en: { gerund: 'coordinating', participle: 'coordinated' },
    it: { gerund: 'coordinando', participle: 'coordinato' },
    fr: { participle: 'coordonné' }, de: { participle: 'koordiniert' },
    es: { gerund: 'coordinando', participle: 'coordinado' },
    pt: { gerund: 'coordenando', participle: 'coordenado' },
    ja: { te: '調整して', te_reading: 'ちょうせいして', nai: '調整しない', nai_reading: 'ちょうせいしない' },
  },
  // it crollare and de kollabieren both select BE; the fr participle drops the reflexive clitic
  // its finite forms carry, so the resultative reads as the resulting state ("est effondré").
  COLLAPSE: {
    en: { gerund: 'collapsing', participle: 'collapsed' },
    it: { gerund: 'crollando', participle: 'crollato', aux: 'be' },
    fr: { participle: 'effondré', aux: 'be' }, de: { participle: 'kollabiert', aux: 'be' },
    es: { gerund: 'colapsando', participle: 'colapsado' },
    pt: { gerund: 'desabando', participle: 'desabado' },
    ja: { te: '崩れて', te_reading: 'くずれて', nai: '崩れない', nai_reading: 'くずれない' },
  },
  TIDY_UP: {
    en: { gerund: 'tidying up', participle: 'tidied up' },
    it: { gerund: 'riordinando', participle: 'riordinato' },
    fr: { participle: 'rangé' }, de: { participle: 'geordnet' },
    es: { gerund: 'ordenando', participle: 'ordenado' },
    pt: { gerund: 'arrumando', participle: 'arrumado' },
    ja: { te: '片付けて', te_reading: 'かたづけて', nai: '片付けない', nai_reading: 'かたづけない' },
  },
  MAKE: {
    en: { gerund: 'making', participle: 'made' },
    it: { gerund: 'facendo', participle: 'fatto' },
    fr: { participle: 'fait' }, de: { participle: 'gemacht' },
    es: { gerund: 'haciendo', participle: 'hecho' },
    pt: { gerund: 'fazendo', participle: 'feito' },
    ja: { te: '作って', te_reading: 'つくって', nai: '作らない', nai_reading: 'つくらない' },
  },
  CREATE: {
    en: { gerund: 'creating', participle: 'created' },
    it: { gerund: 'creando', participle: 'creato' },
    fr: { participle: 'créé' }, de: { participle: 'erschaffen' },
    es: { gerund: 'creando', participle: 'creado' },
    pt: { gerund: 'criando', participle: 'criado' },
    ja: { te: '生み出して', te_reading: 'うみだして', nai: '生み出さない', nai_reading: 'うみださない' },
  },
  DESTROY: {
    en: { gerund: 'destroying', participle: 'destroyed' },
    it: { gerund: 'distruggendo', participle: 'distrutto' },
    fr: { participle: 'détruit' }, de: { participle: 'zerstört' },
    es: { gerund: 'destruyendo', participle: 'destruido' },
    pt: { gerund: 'destruindo', participle: 'destruído' },
    ja: { te: '破壊して', te_reading: 'はかいして', nai: '破壊しない', nai_reading: 'はかいしない' },
  },
  PERCEIVE: {
    en: { gerund: 'perceiving', participle: 'perceived' },
    it: { gerund: 'percependo', participle: 'percepito' },
    fr: { participle: 'perçu' }, de: { participle: 'empfunden' },
    es: { gerund: 'percibiendo', participle: 'percibido' },
    pt: { gerund: 'percebendo', participle: 'percebido' },
    ja: { te: '知覚して', te_reading: 'ちかくして', nai: '知覚しない', nai_reading: 'ちかくしない' },
  },
  UNDERSTAND: {
    en: { gerund: 'understanding', participle: 'understood' },
    it: { gerund: 'comprendendo', participle: 'compreso' },
    fr: { participle: 'compris' }, de: { participle: 'verstanden' },
    es: { gerund: 'comprendiendo', participle: 'comprendido' },
    pt: { gerund: 'compreendendo', participle: 'compreendido' },
    ja: { te: '理解して', te_reading: 'りかいして', nai: '理解しない', nai_reading: 'りかいしない' },
  },
  // Genus verbs for the B12–B18 verb definitions. All transitive/ditransitive → HAVE auxiliary.
  HAVE: {
    en: { gerund: 'having', participle: 'had' },
    it: { gerund: 'avendo', participle: 'avuto' },
    fr: { participle: 'eu' }, de: { participle: 'gehabt' },
    es: { gerund: 'teniendo', participle: 'tenido' },
    pt: { gerund: 'tendo', participle: 'tido' },
    ja: { te: '持って', te_reading: 'もって', nai: '持たない', nai_reading: 'もたない' },
  },
  ACQUIRE: {
    en: { gerund: 'acquiring', participle: 'acquired' },
    it: { gerund: 'acquisendo', participle: 'acquisito' },
    fr: { participle: 'acquis' }, de: { participle: 'erworben' },
    es: { gerund: 'adquiriendo', participle: 'adquirido' },
    pt: { gerund: 'adquirindo', participle: 'adquirido' },
    ja: { te: '取得して', te_reading: 'しゅとくして', nai: '取得しない', nai_reading: 'しゅとくしない' },
  },
  DIVIDE: {
    en: { gerund: 'dividing', participle: 'divided' },
    it: { gerund: 'dividendo', participle: 'diviso' },
    fr: { participle: 'divisé' }, de: { participle: 'geteilt' },
    es: { gerund: 'dividiendo', participle: 'dividido' },
    pt: { gerund: 'dividindo', participle: 'dividido' },
    ja: { te: '分けて', te_reading: 'わけて', nai: '分けない', nai_reading: 'わけない' },
  },
  STRIKE: {
    en: { gerund: 'striking', participle: 'struck' },
    it: { gerund: 'colpendo', participle: 'colpito' },
    fr: { participle: 'frappé' }, de: { participle: 'geschlagen' },
    es: { gerund: 'golpeando', participle: 'golpeado' },
    pt: { gerund: 'golpeando', participle: 'golpeado' },
    ja: { te: '打って', te_reading: 'うって', nai: '打たない', nai_reading: 'うたない' },
  },
  TRANSFER: {
    en: { gerund: 'transferring', participle: 'transferred' },
    it: { gerund: 'trasferendo', participle: 'trasferito' },
    fr: { participle: 'transféré' }, de: { participle: 'übertragen' },
    es: { gerund: 'transfiriendo', participle: 'transferido' },
    pt: { gerund: 'transferindo', participle: 'transferido' },
    ja: { te: '移して', te_reading: 'うつして', nai: '移さない', nai_reading: 'うつさない' },
  },
  INDICATE: {
    en: { gerund: 'indicating', participle: 'indicated' },
    it: { gerund: 'indicando', participle: 'indicato' },
    fr: { participle: 'indiqué' }, de: { participle: 'bezeichnet' },
    es: { gerund: 'indicando', participle: 'indicado' },
    pt: { gerund: 'indicando', participle: 'indicado' },
    ja: { te: '示して', te_reading: 'しめして', nai: '示さない', nai_reading: 'しめさない' },
  },
  CHANGE: {
    en: { gerund: 'changing', participle: 'changed' },
    it: { gerund: 'cambiando', participle: 'cambiato' },
    fr: { participle: 'changé' }, de: { participle: 'geändert' },
    es: { gerund: 'cambiando', participle: 'cambiado' },
    pt: { gerund: 'mudando', participle: 'mudado' },
    ja: { te: '変えて', te_reading: 'かえて', nai: '変えない', nai_reading: 'かえない' },
  },
  FEEL: {
    en: { gerund: 'feeling', participle: 'felt' },
    it: { gerund: 'provando', participle: 'provato' },
    fr: { participle: 'éprouvé' }, de: { participle: 'gefühlt' },
    es: { gerund: 'sintiendo', participle: 'sentido' },
    pt: { gerund: 'sentindo', participle: 'sentido' },
    ja: { te: '感じて', te_reading: 'かんじて', nai: '感じない', nai_reading: 'かんじない' },
  },
  SHED: {
    en: { gerund: 'shedding', participle: 'shed' },
    it: { gerund: 'versando', participle: 'versato' },
    fr: { participle: 'versé' }, de: { participle: 'vergossen' },
    es: { gerund: 'derramando', participle: 'derramado' },
    pt: { gerund: 'derramando', participle: 'derramado' },
    ja: { te: '流して', te_reading: 'ながして', nai: '流さない', nai_reading: 'ながさない' },
  },
  PRODUCE: {
    en: { gerund: 'producing', participle: 'produced' },
    it: { gerund: 'producendo', participle: 'prodotto' },
    fr: { participle: 'produit' }, de: { participle: 'erzeugt' },
    es: { gerund: 'produciendo', participle: 'producido' },
    pt: { gerund: 'produzindo', participle: 'produzido' },
    ja: { te: '出して', te_reading: 'だして', nai: '出さない', nai_reading: 'ださない' },
  },
  PRESS: {
    en: { gerund: 'pressing', participle: 'pressed' },
    it: { gerund: 'premendo', participle: 'premuto' },
    fr: { participle: 'pressé' }, de: { participle: 'gedrückt' },
    es: { gerund: 'pulsando', participle: 'pulsado' },
    pt: { gerund: 'pressionando', participle: 'pressionado' },
    ja: { te: '押して', te_reading: 'おして', nai: '押さない', nai_reading: 'おさない' },
  },
  WRITE: {
    en: { gerund: 'writing', participle: 'written' },
    it: { gerund: 'scrivendo', participle: 'scritto' },
    fr: { participle: 'écrit' }, de: { participle: 'geschrieben' },
    es: { gerund: 'escribiendo', participle: 'escrito' },
    pt: { gerund: 'escrevendo', participle: 'escrito' },
    ja: { te: '書いて', te_reading: 'かいて', nai: '書かない', nai_reading: 'かかない' },
  },
  COMPACT: {
    en: { gerund: 'compacting', participle: 'compacted' },
    it: { gerund: 'compattando', participle: 'compattato' },
    fr: { participle: 'compacté' }, de: { participle: 'verdichtet' },
    es: { gerund: 'compactando', participle: 'compactado' },
    pt: { gerund: 'compactando', participle: 'compactado' },
    ja: { te: '圧縮して', te_reading: 'あっしゅくして', nai: '圧縮しない', nai_reading: 'あっしゅくしない' },
  },
  EXPAND: {
    en: { gerund: 'expanding', participle: 'expanded' },
    it: { gerund: 'espandendo', participle: 'espanso' },
    fr: { participle: 'étendu' }, de: { participle: 'erweitert' },
    es: { gerund: 'expandiendo', participle: 'expandido' },
    pt: { gerund: 'expandindo', participle: 'expandido' },
    ja: { te: '展開して', te_reading: 'てんかいして', nai: '展開しない', nai_reading: 'てんかいしない' },
  },
  HIDE: {
    en: { gerund: 'hiding', participle: 'hidden' },
    it: { gerund: 'nascondendo', participle: 'nascosto' },
    fr: { participle: 'caché' }, de: { participle: 'versteckt' },
    es: { gerund: 'escondiendo', participle: 'escondido' },
    pt: { gerund: 'escondendo', participle: 'escondido' },
    ja: { te: '隠して', te_reading: 'かくして', nai: '隠さない', nai_reading: 'かくさない' },
  },
  START: {
    en: { gerund: 'starting', participle: 'started' },
    it: { gerund: 'iniziando', participle: 'iniziato' },
    fr: { participle: 'commencé' }, de: { participle: 'begonnen' },
    es: { gerund: 'empezando', participle: 'empezado' },
    pt: { gerund: 'começando', participle: 'começado' },
    ja: { te: '始めて', te_reading: 'はじめて', nai: '始めない', nai_reading: 'はじめない' },
  },
  // Grammar-word verbs (B06). All transitive → avere/haber/ter default (no aux key).
  NAME: {
    en: { gerund: 'naming', participle: 'named' },
    it: { gerund: 'nominando', participle: 'nominato' },
    fr: { participle: 'nommé' }, de: { participle: 'benannt' },
    es: { gerund: 'nombrando', participle: 'nombrado' },
    pt: { gerund: 'nomeando', participle: 'nomeado' },
    ja: { te: '名付けて', te_reading: 'なづけて', nai: '名付けない', nai_reading: 'なづけない' },
  },
  DESCRIBE: {
    en: { gerund: 'describing', participle: 'described' },
    it: { gerund: 'descrivendo', participle: 'descritto' },
    fr: { participle: 'décrit' }, de: { participle: 'beschrieben' },
    es: { gerund: 'describiendo', participle: 'descrito' },
    pt: { gerund: 'descrevendo', participle: 'descrito' },
    ja: { te: '描写して', te_reading: 'びょうしゃして', nai: '描写しない', nai_reading: 'びょうしゃしない' },
  },
  MODIFY: {
    en: { gerund: 'modifying', participle: 'modified' },
    it: { gerund: 'modificando', participle: 'modificato' },
    fr: { participle: 'modifié' }, de: { participle: 'modifiziert' },
    es: { gerund: 'modificando', participle: 'modificado' },
    pt: { gerund: 'modificando', participle: 'modificado' },
    ja: { te: '修飾して', te_reading: 'しゅうしょくして', nai: '修飾しない', nai_reading: 'しゅうしょくしない' },
  },
  EXPRESS: {
    en: { gerund: 'expressing', participle: 'expressed' },
    it: { gerund: 'esprimendo', participle: 'espresso' },
    fr: { participle: 'exprimé' }, de: { participle: 'vermittelt' },
    es: { gerund: 'expresando', participle: 'expresado' },
    pt: { gerund: 'exprimindo', participle: 'exprimido' },
    ja: { te: '表して', te_reading: 'あらわして', nai: '表さない', nai_reading: 'あらわさない' },
  },
  REPLACE: {
    en: { gerund: 'replacing', participle: 'replaced' },
    it: { gerund: 'sostituendo', participle: 'sostituito' },
    fr: { participle: 'remplacé' }, de: { participle: 'ersetzt' },
    es: { gerund: 'reemplazando', participle: 'reemplazado' },
    pt: { gerund: 'substituindo', participle: 'substituído' },
    ja: { te: '置き換えて', te_reading: 'おきかえて', nai: '置き換えない', nai_reading: 'おきかえない' },
  },
};
