import type { ConceptSeed } from '../types.js';

// Plain transitive verbs.
export const transitiveVerbs: ConceptSeed[] = [
  {
    id: 'CUT',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['terminus', 'cause'],
    description: 'to divide or wound with a sharp edge',
    emoji: '✂️',
    forms: {
      en: {
        base: 'cut',
        '1sg_present': 'cut', '2sg_present': 'cut', '3sg_present': 'cuts',
        '1pl_present': 'cut', '2pl_present': 'cut', '3pl_present': 'cut',
        past: 'cut',
      },
      it: {
        base: 'tagliare',
        '1sg_present': 'taglio', '2sg_present': 'tagli', '3sg_present': 'taglia',
        '1pl_present': 'tagliamo', '2pl_present': 'tagliate', '3pl_present': 'tagliano',
        '1sg_past': 'tagliai', '2sg_past': 'tagliasti', '3sg_past': 'tagliò',
        '1pl_past': 'tagliammo', '2pl_past': 'tagliaste', '3pl_past': 'tagliarono',
        '1sg_future': 'taglierò', '2sg_future': 'taglierai', '3sg_future': 'taglierà',
        '1pl_future': 'taglieremo', '2pl_future': 'taglierete', '3pl_future': 'taglieranno',
      },
      fr: {
        base: 'couper',
        '1sg_present': 'coupe', '2sg_present': 'coupes', '3sg_present': 'coupe',
        '1pl_present': 'coupons', '2pl_present': 'coupez', '3pl_present': 'coupent',
        '1sg_past': 'coupai', '2sg_past': 'coupas', '3sg_past': 'coupa',
        '1pl_past': 'coupâmes', '2pl_past': 'coupâtes', '3pl_past': 'coupèrent',
        '1sg_future': 'couperai', '2sg_future': 'couperas', '3sg_future': 'coupera',
        '1pl_future': 'couperons', '2pl_future': 'couperez', '3pl_future': 'couperont',
      },
      de: {
        base: 'schneiden',
        '1sg_present': 'schneide', '2sg_present': 'schneidest', '3sg_present': 'schneidet',
        '1pl_present': 'schneiden', '2pl_present': 'schneidet', '3pl_present': 'schneiden',
        '1sg_past': 'schnitt', '2sg_past': 'schnittest', '3sg_past': 'schnitt',
        '1pl_past': 'schnitten', '2pl_past': 'schnittet', '3pl_past': 'schnitten',
      },
      es: {
        base: 'cortar',
        '1sg_present': 'corto', '2sg_present': 'cortas', '3sg_present': 'corta',
        '1pl_present': 'cortamos', '2pl_present': 'cortáis', '3pl_present': 'cortan',
        '1sg_past': 'corté', '2sg_past': 'cortaste', '3sg_past': 'cortó',
        '1pl_past': 'cortamos', '2pl_past': 'cortasteis', '3pl_past': 'cortaron',
        '1sg_future': 'cortaré', '2sg_future': 'cortarás', '3sg_future': 'cortará',
        '1pl_future': 'cortaremos', '2pl_future': 'cortaréis', '3pl_future': 'cortarán',
      },
      ja: {
        base: '切る',
        reading: 'きる',
        masu_present: '切ります',
        masu_present_reading: 'きります',
      },
      pt: {
        base: 'cortar',
        '1sg_present': 'corto', '2sg_present': 'corta', '3sg_present': 'corta',
        '1pl_present': 'cortamos', '2pl_present': 'cortam', '3pl_present': 'cortam',
        '1sg_past': 'cortei', '2sg_past': 'cortou', '3sg_past': 'cortou',
        '1pl_past': 'cortamos', '2pl_past': 'cortaram', '3pl_past': 'cortaram',
        '1sg_future': 'cortarei', '2sg_future': 'cortará', '3sg_future': 'cortará',
        '1pl_future': 'cortaremos', '2pl_future': 'cortarão', '3pl_future': 'cortarão',
      },
    },
  },

  {
    id: 'EAT',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to consume food',
    emoji: '🍴',
    forms: {
      en: {
        base: 'eat',
        '1sg_present': 'eat', '2sg_present': 'eat', '3sg_present': 'eats',
        '1pl_present': 'eat', '2pl_present': 'eat', '3pl_present': 'eat',
        past: 'ate',
      },
      it: {
        base: 'mangiare',
        '1sg_present': 'mangio', '2sg_present': 'mangi', '3sg_present': 'mangia',
        '1pl_present': 'mangiamo', '2pl_present': 'mangiate', '3pl_present': 'mangiano',
        '1sg_past': 'mangiai', '2sg_past': 'mangiasti', '3sg_past': 'mangiò',
        '1pl_past': 'mangiammo', '2pl_past': 'mangiaste', '3pl_past': 'mangiarono',
        '1sg_future': 'mangerò', '2sg_future': 'mangerai', '3sg_future': 'mangerà',
        '1pl_future': 'mangeremo', '2pl_future': 'mangerete', '3pl_future': 'mangeranno',
      },
      fr: {
        base: 'manger',
        '1sg_present': 'mange', '2sg_present': 'manges', '3sg_present': 'mange',
        '1pl_present': 'mangeons', '2pl_present': 'mangez', '3pl_present': 'mangent',
        '1sg_past': 'mangeai', '2sg_past': 'mangeas', '3sg_past': 'mangea',
        '1pl_past': 'mangeâmes', '2pl_past': 'mangeâtes', '3pl_past': 'mangèrent',
        '1sg_future': 'mangerai', '2sg_future': 'mangeras', '3sg_future': 'mangera',
        '1pl_future': 'mangerons', '2pl_future': 'mangerez', '3pl_future': 'mangeront',
      },
      de: {
        base: 'essen',
        '1sg_present': 'esse', '2sg_present': 'isst', '3sg_present': 'isst',
        '1pl_present': 'essen', '2pl_present': 'esst', '3pl_present': 'essen',
        '1sg_past': 'aß', '2sg_past': 'aßest', '3sg_past': 'aß',
        '1pl_past': 'aßen', '2pl_past': 'aßt', '3pl_past': 'aßen',
      },
      es: {
        base: 'comer',
        '1sg_present': 'como', '2sg_present': 'comes', '3sg_present': 'come',
        '1pl_present': 'comemos', '2pl_present': 'coméis', '3pl_present': 'comen',
        '1sg_past': 'comí', '2sg_past': 'comiste', '3sg_past': 'comió',
        '1pl_past': 'comimos', '2pl_past': 'comisteis', '3pl_past': 'comieron',
        '1sg_future': 'comeré', '2sg_future': 'comerás', '3sg_future': 'comerá',
        '1pl_future': 'comeremos', '2pl_future': 'comeréis', '3pl_future': 'comerán',
      },
      ja: {
        base: '食べる',
        reading: 'たべる',
        masu_present: '食べます',
        masu_present_reading: 'たべます',
      },
      pt: {
        base: 'comer',
        '1sg_present': 'como', '2sg_present': 'come', '3sg_present': 'come',
        '1pl_present': 'comemos', '2pl_present': 'comem', '3pl_present': 'comem',
        '1sg_past': 'comi', '2sg_past': 'comeu', '3sg_past': 'comeu',
        '1pl_past': 'comemos', '2pl_past': 'comeram', '3pl_past': 'comeram',
        '1sg_future': 'comerei', '2sg_future': 'comerá', '3sg_future': 'comerá',
        '1pl_future': 'comeremos', '2pl_future': 'comerão', '3pl_future': 'comerão',
      },
    },
  },

  {
    id: 'DRINK',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to consume liquid',
    emoji: '🥤',
    forms: {
      en: {
        base: 'drink',
        '1sg_present': 'drink', '2sg_present': 'drink', '3sg_present': 'drinks',
        '1pl_present': 'drink', '2pl_present': 'drink', '3pl_present': 'drink',
        past: 'drank',
      },
      it: {
        base: 'bere',
        '1sg_present': 'bevo', '2sg_present': 'bevi', '3sg_present': 'beve',
        '1pl_present': 'beviamo', '2pl_present': 'bevete', '3pl_present': 'bevono',
        '1sg_past': 'bevvi', '2sg_past': 'bevesti', '3sg_past': 'bevve',
        '1pl_past': 'bevemmo', '2pl_past': 'beveste', '3pl_past': 'bevvero',
        '1sg_future': 'berrò', '2sg_future': 'berrai', '3sg_future': 'berrà',
        '1pl_future': 'berremo', '2pl_future': 'berrete', '3pl_future': 'berranno',
      },
      fr: {
        base: 'boire',
        '1sg_present': 'bois', '2sg_present': 'bois', '3sg_present': 'boit',
        '1pl_present': 'buvons', '2pl_present': 'buvez', '3pl_present': 'boivent',
        '1sg_past': 'bus', '2sg_past': 'bus', '3sg_past': 'but',
        '1pl_past': 'bûmes', '2pl_past': 'bûtes', '3pl_past': 'burent',
        '1sg_future': 'boirai', '2sg_future': 'boiras', '3sg_future': 'boira',
        '1pl_future': 'boirons', '2pl_future': 'boirez', '3pl_future': 'boiront',
      },
      de: {
        base: 'trinken',
        '1sg_present': 'trinke', '2sg_present': 'trinkst', '3sg_present': 'trinkt',
        '1pl_present': 'trinken', '2pl_present': 'trinkt', '3pl_present': 'trinken',
        '1sg_past': 'trank', '2sg_past': 'trankst', '3sg_past': 'trank',
        '1pl_past': 'tranken', '2pl_past': 'trankt', '3pl_past': 'tranken',
      },
      es: {
        base: 'beber',
        '1sg_present': 'bebo', '2sg_present': 'bebes', '3sg_present': 'bebe',
        '1pl_present': 'bebemos', '2pl_present': 'bebéis', '3pl_present': 'beben',
        '1sg_past': 'bebí', '2sg_past': 'bebiste', '3sg_past': 'bebió',
        '1pl_past': 'bebimos', '2pl_past': 'bebisteis', '3pl_past': 'bebieron',
        '1sg_future': 'beberé', '2sg_future': 'beberás', '3sg_future': 'beberá',
        '1pl_future': 'beberemos', '2pl_future': 'beberéis', '3pl_future': 'beberán',
      },
      ja: {
        base: '飲む',
        reading: 'のむ',
        masu_present: '飲みます',
        masu_present_reading: 'のみます',
      },
      pt: {
        base: 'beber',
        '1sg_present': 'bebo', '2sg_present': 'bebe', '3sg_present': 'bebe',
        '1pl_present': 'bebemos', '2pl_present': 'bebem', '3pl_present': 'bebem',
        '1sg_past': 'bebi', '2sg_past': 'bebeu', '3sg_past': 'bebeu',
        '1pl_past': 'bebemos', '2pl_past': 'beberam', '3pl_past': 'beberam',
        '1sg_future': 'beberei', '2sg_future': 'beberá', '3sg_future': 'beberá',
        '1pl_future': 'beberemos', '2pl_future': 'beberão', '3pl_future': 'beberão',
      },
    },
  },

  {
    id: 'SEE',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to perceive with the eyes',
    emoji: '👁️',
    forms: {
      en: {
        base: 'see',
        '1sg_present': 'see', '2sg_present': 'see', '3sg_present': 'sees',
        '1pl_present': 'see', '2pl_present': 'see', '3pl_present': 'see',
        past: 'saw',
      },
      it: {
        base: 'vedere',
        '1sg_present': 'vedo', '2sg_present': 'vedi', '3sg_present': 'vede',
        '1pl_present': 'vediamo', '2pl_present': 'vedete', '3pl_present': 'vedono',
        '1sg_past': 'vidi', '2sg_past': 'vedesti', '3sg_past': 'vide',
        '1pl_past': 'vedemmo', '2pl_past': 'vedeste', '3pl_past': 'videro',
        '1sg_future': 'vedrò', '2sg_future': 'vedrai', '3sg_future': 'vedrà',
        '1pl_future': 'vedremo', '2pl_future': 'vedrete', '3pl_future': 'vedranno',
      },
      fr: {
        base: 'voir',
        '1sg_present': 'vois', '2sg_present': 'vois', '3sg_present': 'voit',
        '1pl_present': 'voyons', '2pl_present': 'voyez', '3pl_present': 'voient',
        '1sg_past': 'vis', '2sg_past': 'vis', '3sg_past': 'vit',
        '1pl_past': 'vîmes', '2pl_past': 'vîtes', '3pl_past': 'virent',
        '1sg_future': 'verrai', '2sg_future': 'verras', '3sg_future': 'verra',
        '1pl_future': 'verrons', '2pl_future': 'verrez', '3pl_future': 'verront',
      },
      de: {
        base: 'sehen',
        '1sg_present': 'sehe', '2sg_present': 'siehst', '3sg_present': 'sieht',
        '1pl_present': 'sehen', '2pl_present': 'seht', '3pl_present': 'sehen',
        '1sg_past': 'sah', '2sg_past': 'sahst', '3sg_past': 'sah',
        '1pl_past': 'sahen', '2pl_past': 'saht', '3pl_past': 'sahen',
      },
      es: {
        base: 'ver',
        '1sg_present': 'veo', '2sg_present': 'ves', '3sg_present': 've',
        '1pl_present': 'vemos', '2pl_present': 'veis', '3pl_present': 'ven',
        '1sg_past': 'vi', '2sg_past': 'viste', '3sg_past': 'vio',
        '1pl_past': 'vimos', '2pl_past': 'visteis', '3pl_past': 'vieron',
        '1sg_future': 'veré', '2sg_future': 'verás', '3sg_future': 'verá',
        '1pl_future': 'veremos', '2pl_future': 'veréis', '3pl_future': 'verán',
      },
      ja: {
        base: '見る',
        reading: 'みる',
        masu_present: '見ます',
        masu_present_reading: 'みます',
      },
      pt: {
        base: 'ver',
        '1sg_present': 'vejo', '2sg_present': 'vê', '3sg_present': 'vê',
        '1pl_present': 'vemos', '2pl_present': 'veem', '3pl_present': 'veem',
        '1sg_past': 'vi', '2sg_past': 'viu', '3sg_past': 'viu',
        '1pl_past': 'vimos', '2pl_past': 'viram', '3pl_past': 'viram',
        '1sg_future': 'verei', '2sg_future': 'verá', '3sg_future': 'verá',
        '1pl_future': 'veremos', '2pl_future': 'verão', '3pl_future': 'verão',
      },
    },
  },

  {
    id: 'LOVE',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to feel deep affection',
    emoji: '❤️',
    forms: {
      en: {
        base: 'love',
        '1sg_present': 'love', '2sg_present': 'love', '3sg_present': 'loves',
        '1pl_present': 'love', '2pl_present': 'love', '3pl_present': 'love',
        past: 'loved',
      },
      it: {
        base: 'amare',
        '1sg_present': 'amo', '2sg_present': 'ami', '3sg_present': 'ama',
        '1pl_present': 'amiamo', '2pl_present': 'amate', '3pl_present': 'amano',
        '1sg_past': 'amai', '2sg_past': 'amasti', '3sg_past': 'amò',
        '1pl_past': 'amammo', '2pl_past': 'amaste', '3pl_past': 'amarono',
        '1sg_future': 'amerò', '2sg_future': 'amerai', '3sg_future': 'amerà',
        '1pl_future': 'ameremo', '2pl_future': 'amerete', '3pl_future': 'ameranno',
      },
      fr: {
        base: 'aimer',
        '1sg_present': 'aime', '2sg_present': 'aimes', '3sg_present': 'aime',
        '1pl_present': 'aimons', '2pl_present': 'aimez', '3pl_present': 'aiment',
        '1sg_past': 'aimai', '2sg_past': 'aimas', '3sg_past': 'aima',
        '1pl_past': 'aimâmes', '2pl_past': 'aimâtes', '3pl_past': 'aimèrent',
        '1sg_future': 'aimerai', '2sg_future': 'aimeras', '3sg_future': 'aimera',
        '1pl_future': 'aimerons', '2pl_future': 'aimerez', '3pl_future': 'aimeront',
      },
      de: {
        base: 'lieben',
        '1sg_present': 'liebe', '2sg_present': 'liebst', '3sg_present': 'liebt',
        '1pl_present': 'lieben', '2pl_present': 'liebt', '3pl_present': 'lieben',
        '1sg_past': 'liebte', '2sg_past': 'liebtest', '3sg_past': 'liebte',
        '1pl_past': 'liebten', '2pl_past': 'liebtet', '3pl_past': 'liebten',
      },
      es: {
        base: 'amar',
        '1sg_present': 'amo', '2sg_present': 'amas', '3sg_present': 'ama',
        '1pl_present': 'amamos', '2pl_present': 'amáis', '3pl_present': 'aman',
        '1sg_past': 'amé', '2sg_past': 'amaste', '3sg_past': 'amó',
        '1pl_past': 'amamos', '2pl_past': 'amasteis', '3pl_past': 'amaron',
        '1sg_future': 'amaré', '2sg_future': 'amarás', '3sg_future': 'amará',
        '1pl_future': 'amaremos', '2pl_future': 'amaréis', '3pl_future': 'amarán',
      },
      ja: {
        base: '愛する',
        reading: 'あいする',
        masu_present: '愛します',
        masu_present_reading: 'あいします',
      },
      pt: {
        base: 'amar',
        '1sg_present': 'amo', '2sg_present': 'ama', '3sg_present': 'ama',
        '1pl_present': 'amamos', '2pl_present': 'amam', '3pl_present': 'amam',
        '1sg_past': 'amei', '2sg_past': 'amou', '3sg_past': 'amou',
        '1pl_past': 'amamos', '2pl_past': 'amaram', '3pl_past': 'amaram',
        '1sg_future': 'amarei', '2sg_future': 'amará', '3sg_future': 'amará',
        '1pl_future': 'amaremos', '2pl_future': 'amarão', '3pl_future': 'amarão',
      },
    },
  },

  {
    id: 'KILL',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to cause the death of',
    emoji: '🔪',
    forms: {
      en: {
        base: 'kill',
        '1sg_present': 'kill', '2sg_present': 'kill', '3sg_present': 'kills',
        '1pl_present': 'kill', '2pl_present': 'kill', '3pl_present': 'kill',
        past: 'killed',
      },
      it: {
        base: 'uccidere',
        '1sg_present': 'uccido', '2sg_present': 'uccidi', '3sg_present': 'uccide',
        '1pl_present': 'uccidiamo', '2pl_present': 'uccidete', '3pl_present': 'uccidono',
        '1sg_past': 'uccisi', '2sg_past': 'uccidesti', '3sg_past': 'uccise',
        '1pl_past': 'uccidemmo', '2pl_past': 'uccideste', '3pl_past': 'uccisero',
        '1sg_future': 'ucciderò', '2sg_future': 'ucciderai', '3sg_future': 'ucciderà',
        '1pl_future': 'uccideremo', '2pl_future': 'ucciderete', '3pl_future': 'uccideranno',
      },
      fr: {
        base: 'tuer',
        '1sg_present': 'tue', '2sg_present': 'tues', '3sg_present': 'tue',
        '1pl_present': 'tuons', '2pl_present': 'tuez', '3pl_present': 'tuent',
        '1sg_past': 'tuai', '2sg_past': 'tuas', '3sg_past': 'tua',
        '1pl_past': 'tuâmes', '2pl_past': 'tuâtes', '3pl_past': 'tuèrent',
        '1sg_future': 'tuerai', '2sg_future': 'tueras', '3sg_future': 'tuera',
        '1pl_future': 'tuerons', '2pl_future': 'tuerez', '3pl_future': 'tueront',
      },
      de: {
        base: 'töten',
        '1sg_present': 'töte', '2sg_present': 'tötest', '3sg_present': 'tötet',
        '1pl_present': 'töten', '2pl_present': 'tötet', '3pl_present': 'töten',
        '1sg_past': 'tötete', '2sg_past': 'tötetest', '3sg_past': 'tötete',
        '1pl_past': 'töteten', '2pl_past': 'tötetet', '3pl_past': 'töteten',
      },
      es: {
        base: 'matar',
        '1sg_present': 'mato', '2sg_present': 'matas', '3sg_present': 'mata',
        '1pl_present': 'matamos', '2pl_present': 'matáis', '3pl_present': 'matan',
        '1sg_past': 'maté', '2sg_past': 'mataste', '3sg_past': 'mató',
        '1pl_past': 'matamos', '2pl_past': 'matasteis', '3pl_past': 'mataron',
        '1sg_future': 'mataré', '2sg_future': 'matarás', '3sg_future': 'matará',
        '1pl_future': 'mataremos', '2pl_future': 'mataréis', '3pl_future': 'matarán',
      },
      ja: {
        base: '殺す',
        reading: 'ころす',
        masu_present: '殺します',
        masu_present_reading: 'ころします',
      },
      pt: {
        base: 'matar',
        '1sg_present': 'mato', '2sg_present': 'mata', '3sg_present': 'mata',
        '1pl_present': 'matamos', '2pl_present': 'matam', '3pl_present': 'matam',
        '1sg_past': 'matei', '2sg_past': 'matou', '3sg_past': 'matou',
        '1pl_past': 'matamos', '2pl_past': 'mataram', '3pl_past': 'mataram',
        '1sg_future': 'matarei', '2sg_future': 'matará', '3sg_future': 'matará',
        '1pl_future': 'mataremos', '2pl_future': 'matarão', '3pl_future': 'matarão',
      },
    },
  },

  {
    id: 'KNOW',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to have knowledge or understanding of',
    emoji: '🧠',
    forms: {
      en: {
        base: 'know',
        '1sg_present': 'know', '2sg_present': 'know', '3sg_present': 'knows',
        '1pl_present': 'know', '2pl_present': 'know', '3pl_present': 'know',
        past: 'knew',
      },
      it: {
        base: 'sapere',
        '1sg_present': 'so', '2sg_present': 'sai', '3sg_present': 'sa',
        '1pl_present': 'sappiamo', '2pl_present': 'sapete', '3pl_present': 'sanno',
        '1sg_past': 'seppi', '2sg_past': 'sapesti', '3sg_past': 'seppe',
        '1pl_past': 'sapemmo', '2pl_past': 'sapeste', '3pl_past': 'seppero',
        '1sg_future': 'saprò', '2sg_future': 'saprai', '3sg_future': 'saprà',
        '1pl_future': 'sapremo', '2pl_future': 'saprete', '3pl_future': 'sapranno',
      },
      fr: {
        base: 'savoir',
        '1sg_present': 'sais', '2sg_present': 'sais', '3sg_present': 'sait',
        '1pl_present': 'savons', '2pl_present': 'savez', '3pl_present': 'savent',
        '1sg_past': 'sus', '2sg_past': 'sus', '3sg_past': 'sut',
        '1pl_past': 'sûmes', '2pl_past': 'sûtes', '3pl_past': 'surent',
        '1sg_future': 'saurai', '2sg_future': 'sauras', '3sg_future': 'saura',
        '1pl_future': 'saurons', '2pl_future': 'saurez', '3pl_future': 'sauront',
      },
      de: {
        base: 'wissen',
        '1sg_present': 'weiß', '2sg_present': 'weißt', '3sg_present': 'weiß',
        '1pl_present': 'wissen', '2pl_present': 'wisst', '3pl_present': 'wissen',
        '1sg_past': 'wusste', '2sg_past': 'wusstest', '3sg_past': 'wusste',
        '1pl_past': 'wussten', '2pl_past': 'wusstet', '3pl_past': 'wussten',
      },
      es: {
        base: 'saber',
        '1sg_present': 'sé', '2sg_present': 'sabes', '3sg_present': 'sabe',
        '1pl_present': 'sabemos', '2pl_present': 'sabéis', '3pl_present': 'saben',
        '1sg_past': 'supe', '2sg_past': 'supiste', '3sg_past': 'supo',
        '1pl_past': 'supimos', '2pl_past': 'supisteis', '3pl_past': 'supieron',
        '1sg_future': 'sabré', '2sg_future': 'sabrás', '3sg_future': 'sabrá',
        '1pl_future': 'sabremos', '2pl_future': 'sabréis', '3pl_future': 'sabrán',
      },
      ja: {
        base: '知る',
        reading: 'しる',
        masu_present: '知っています',
        masu_present_reading: 'しっています',
      },
      pt: {
        base: 'saber',
        '1sg_present': 'sei', '2sg_present': 'sabe', '3sg_present': 'sabe',
        '1pl_present': 'sabemos', '2pl_present': 'sabem', '3pl_present': 'sabem',
        '1sg_past': 'soube', '2sg_past': 'soube', '3sg_past': 'soube',
        '1pl_past': 'soubemos', '2pl_past': 'souberam', '3pl_past': 'souberam',
        '1sg_future': 'saberei', '2sg_future': 'saberá', '3sg_future': 'saberá',
        '1pl_future': 'saberemos', '2pl_future': 'saberão', '3pl_future': 'saberão',
      },
    },
  },

  {
    id: 'READ',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['terminus', 'cause'],
    description: 'to look at and understand written text',
    emoji: '📖',
    forms: {
      en: {
        base: 'read',
        '1sg_present': 'read', '2sg_present': 'read', '3sg_present': 'reads',
        '1pl_present': 'read', '2pl_present': 'read', '3pl_present': 'read',
        past: 'read',
      },
      it: {
        base: 'leggere',
        '1sg_present': 'leggo', '2sg_present': 'leggi', '3sg_present': 'legge',
        '1pl_present': 'leggiamo', '2pl_present': 'leggete', '3pl_present': 'leggono',
        '1sg_past': 'lessi', '2sg_past': 'leggesti', '3sg_past': 'lesse',
        '1pl_past': 'leggemmo', '2pl_past': 'leggeste', '3pl_past': 'lessero',
        '1sg_future': 'leggerò', '2sg_future': 'leggerai', '3sg_future': 'leggerà',
        '1pl_future': 'leggeremo', '2pl_future': 'leggerete', '3pl_future': 'leggeranno',
      },
      fr: {
        base: 'lire',
        '1sg_present': 'lis', '2sg_present': 'lis', '3sg_present': 'lit',
        '1pl_present': 'lisons', '2pl_present': 'lisez', '3pl_present': 'lisent',
        '1sg_past': 'lus', '2sg_past': 'lus', '3sg_past': 'lut',
        '1pl_past': 'lûmes', '2pl_past': 'lûtes', '3pl_past': 'lurent',
        '1sg_future': 'lirai', '2sg_future': 'liras', '3sg_future': 'lira',
        '1pl_future': 'lirons', '2pl_future': 'lirez', '3pl_future': 'liront',
      },
      de: {
        base: 'lesen',
        '1sg_present': 'lese', '2sg_present': 'liest', '3sg_present': 'liest',
        '1pl_present': 'lesen', '2pl_present': 'lest', '3pl_present': 'lesen',
        '1sg_past': 'las', '2sg_past': 'lasest', '3sg_past': 'las',
        '1pl_past': 'lasen', '2pl_past': 'last', '3pl_past': 'lasen',
      },
      es: {
        base: 'leer',
        '1sg_present': 'leo', '2sg_present': 'lees', '3sg_present': 'lee',
        '1pl_present': 'leemos', '2pl_present': 'leéis', '3pl_present': 'leen',
        '1sg_past': 'leí', '2sg_past': 'leíste', '3sg_past': 'leyó',
        '1pl_past': 'leímos', '2pl_past': 'leísteis', '3pl_past': 'leyeron',
        '1sg_future': 'leeré', '2sg_future': 'leerás', '3sg_future': 'leerá',
        '1pl_future': 'leeremos', '2pl_future': 'leeréis', '3pl_future': 'leerán',
      },
      ja: {
        base: '読む',
        reading: 'よむ',
        masu_present: '読みます',
        masu_present_reading: 'よみます',
      },
      pt: {
        base: 'ler',
        '1sg_present': 'leio', '2sg_present': 'lê', '3sg_present': 'lê',
        '1pl_present': 'lemos', '2pl_present': 'leem', '3pl_present': 'leem',
        '1sg_past': 'li', '2sg_past': 'leu', '3sg_past': 'leu',
        '1pl_past': 'lemos', '2pl_past': 'leram', '3pl_past': 'leram',
        '1sg_future': 'lerei', '2sg_future': 'lerá', '3sg_future': 'lerá',
        '1pl_future': 'leremos', '2pl_future': 'lerão', '3pl_future': 'lerão',
      },
    },
  },

  {
    id: 'CRY_OUT',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to cry out; to shout or exclaim loudly',
    emoji: '📢',
    synonym: 'shout',
    forms: {
      en: {
        base: 'cry',
        '1sg_present': 'cry', '2sg_present': 'cry', '3sg_present': 'cries',
        '1pl_present': 'cry', '2pl_present': 'cry', '3pl_present': 'cry',
        past: 'cried',
      },
      it: {
        base: 'gridare',
        '1sg_present': 'grido', '2sg_present': 'gridi', '3sg_present': 'grida',
        '1pl_present': 'gridiamo', '2pl_present': 'gridate', '3pl_present': 'gridano',
        '1sg_past': 'gridai', '2sg_past': 'gridasti', '3sg_past': 'gridò',
        '1pl_past': 'gridammo', '2pl_past': 'gridaste', '3pl_past': 'gridarono',
        '1sg_future': 'griderò', '2sg_future': 'griderai', '3sg_future': 'griderà',
        '1pl_future': 'grideremo', '2pl_future': 'griderete', '3pl_future': 'grideranno',
      },
      fr: {
        base: 'crier',
        '1sg_present': 'crie', '2sg_present': 'cries', '3sg_present': 'crie',
        '1pl_present': 'crions', '2pl_present': 'criez', '3pl_present': 'crient',
        '1sg_past': 'criai', '2sg_past': 'crias', '3sg_past': 'cria',
        '1pl_past': 'criâmes', '2pl_past': 'criâtes', '3pl_past': 'crièrent',
        '1sg_future': 'crierai', '2sg_future': 'crieras', '3sg_future': 'criera',
        '1pl_future': 'crierons', '2pl_future': 'crierez', '3pl_future': 'crieront',
      },
      de: {
        base: 'rufen',
        '1sg_present': 'rufe', '2sg_present': 'rufst', '3sg_present': 'ruft',
        '1pl_present': 'rufen', '2pl_present': 'ruft', '3pl_present': 'rufen',
        '1sg_past': 'rief', '2sg_past': 'riefst', '3sg_past': 'rief',
        '1pl_past': 'riefen', '2pl_past': 'rieft', '3pl_past': 'riefen',
      },
      es: {
        base: 'gritar',
        '1sg_present': 'grito', '2sg_present': 'gritas', '3sg_present': 'grita',
        '1pl_present': 'gritamos', '2pl_present': 'gritáis', '3pl_present': 'gritan',
        '1sg_past': 'grité', '2sg_past': 'gritaste', '3sg_past': 'gritó',
        '1pl_past': 'gritamos', '2pl_past': 'gritasteis', '3pl_past': 'gritaron',
        '1sg_future': 'gritaré', '2sg_future': 'gritarás', '3sg_future': 'gritará',
        '1pl_future': 'gritaremos', '2pl_future': 'gritaréis', '3pl_future': 'gritarán',
      },
      ja: {
        base: '叫ぶ',
        reading: 'さけぶ',
        masu_present: '叫びます',
        masu_present_reading: 'さけびます',
      },
      pt: {
        base: 'gritar',
        '1sg_present': 'grito', '2sg_present': 'grita', '3sg_present': 'grita',
        '1pl_present': 'gritamos', '2pl_present': 'gritam', '3pl_present': 'gritam',
        '1sg_past': 'gritei', '2sg_past': 'gritou', '3sg_past': 'gritou',
        '1pl_past': 'gritamos', '2pl_past': 'gritaram', '3pl_past': 'gritaram',
        '1sg_future': 'gritarei', '2sg_future': 'gritará', '3sg_future': 'gritará',
        '1pl_future': 'gritaremos', '2pl_future': 'gritarão', '3pl_future': 'gritarão',
      },
    },
  },

  {
    id: 'BITE',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to grip or cut into with the teeth',
    emoji: '🦷',
    forms: {
      en: {
        base: 'bite',
        '1sg_present': 'bite', '2sg_present': 'bite', '3sg_present': 'bites',
        '1pl_present': 'bite', '2pl_present': 'bite', '3pl_present': 'bite',
        past: 'bit',
      },
      it: {
        base: 'mordere',
        '1sg_present': 'mordo', '2sg_present': 'mordi', '3sg_present': 'morde',
        '1pl_present': 'mordiamo', '2pl_present': 'mordete', '3pl_present': 'mordono',
        '1sg_past': 'morsi', '2sg_past': 'mordesti', '3sg_past': 'morse',
        '1pl_past': 'mordemmo', '2pl_past': 'mordeste', '3pl_past': 'morsero',
        '1sg_future': 'morderò', '2sg_future': 'morderai', '3sg_future': 'morderà',
        '1pl_future': 'morderemo', '2pl_future': 'morderete', '3pl_future': 'morderanno',
      },
      fr: {
        base: 'mordre',
        '1sg_present': 'mords', '2sg_present': 'mords', '3sg_present': 'mord',
        '1pl_present': 'mordons', '2pl_present': 'mordez', '3pl_present': 'mordent',
        '1sg_past': 'mordis', '2sg_past': 'mordis', '3sg_past': 'mordit',
        '1pl_past': 'mordîmes', '2pl_past': 'mordîtes', '3pl_past': 'mordirent',
        '1sg_future': 'mordrai', '2sg_future': 'mordras', '3sg_future': 'mordra',
        '1pl_future': 'mordrons', '2pl_future': 'mordrez', '3pl_future': 'mordront',
      },
      de: {
        base: 'beißen',
        '1sg_present': 'beiße', '2sg_present': 'beißt', '3sg_present': 'beißt',
        '1pl_present': 'beißen', '2pl_present': 'beißt', '3pl_present': 'beißen',
        '1sg_past': 'biss', '2sg_past': 'bissest', '3sg_past': 'biss',
        '1pl_past': 'bissen', '2pl_past': 'bisst', '3pl_past': 'bissen',
      },
      es: {
        base: 'morder',
        '1sg_present': 'muerdo', '2sg_present': 'muerdes', '3sg_present': 'muerde',
        '1pl_present': 'mordemos', '2pl_present': 'mordéis', '3pl_present': 'muerden',
        '1sg_past': 'mordí', '2sg_past': 'mordiste', '3sg_past': 'mordió',
        '1pl_past': 'mordimos', '2pl_past': 'mordisteis', '3pl_past': 'mordieron',
        '1sg_future': 'morderé', '2sg_future': 'morderás', '3sg_future': 'morderá',
        '1pl_future': 'morderemos', '2pl_future': 'morderéis', '3pl_future': 'morderán',
      },
      ja: {
        base: '噛む',
        reading: 'かむ',
        masu_present: '噛みます',
        masu_present_reading: 'かみます',
      },
      pt: {
        base: 'morder',
        '1sg_present': 'mordo', '2sg_present': 'morde', '3sg_present': 'morde',
        '1pl_present': 'mordemos', '2pl_present': 'mordem', '3pl_present': 'mordem',
        '1sg_past': 'mordi', '2sg_past': 'mordeu', '3sg_past': 'mordeu',
        '1pl_past': 'mordemos', '2pl_past': 'morderam', '3pl_past': 'morderam',
        '1sg_future': 'morderei', '2sg_future': 'morderá', '3sg_future': 'morderá',
        '1pl_future': 'morderemos', '2pl_future': 'morderão', '3pl_future': 'morderão',
      },
    },
  },

  {
    id: 'BEAT',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to strike repeatedly; to defeat in a contest',
    emoji: '🥊',
    synonym: 'hit/defeat',
    forms: {
      en: {
        base: 'beat',
        '1sg_present': 'beat', '2sg_present': 'beat', '3sg_present': 'beats',
        '1pl_present': 'beat', '2pl_present': 'beat', '3pl_present': 'beat',
        past: 'beat',
      },
      it: {
        base: 'battere',
        '1sg_present': 'batto', '2sg_present': 'batti', '3sg_present': 'batte',
        '1pl_present': 'battiamo', '2pl_present': 'battete', '3pl_present': 'battono',
        '1sg_past': 'battei', '2sg_past': 'battesti', '3sg_past': 'batté',
        '1pl_past': 'battemmo', '2pl_past': 'batteste', '3pl_past': 'batterono',
        '1sg_future': 'batterò', '2sg_future': 'batterai', '3sg_future': 'batterà',
        '1pl_future': 'batteremo', '2pl_future': 'batterete', '3pl_future': 'batteranno',
      },
      fr: {
        base: 'battre',
        '1sg_present': 'bats', '2sg_present': 'bats', '3sg_present': 'bat',
        '1pl_present': 'battons', '2pl_present': 'battez', '3pl_present': 'battent',
        '1sg_past': 'battis', '2sg_past': 'battis', '3sg_past': 'battit',
        '1pl_past': 'battîmes', '2pl_past': 'battîtes', '3pl_past': 'battirent',
        '1sg_future': 'battrai', '2sg_future': 'battras', '3sg_future': 'battra',
        '1pl_future': 'battrons', '2pl_future': 'battrez', '3pl_future': 'battront',
      },
      de: {
        base: 'schlagen',
        '1sg_present': 'schlage', '2sg_present': 'schlägst', '3sg_present': 'schlägt',
        '1pl_present': 'schlagen', '2pl_present': 'schlagt', '3pl_present': 'schlagen',
        '1sg_past': 'schlug', '2sg_past': 'schlugst', '3sg_past': 'schlug',
        '1pl_past': 'schlugen', '2pl_past': 'schlugt', '3pl_past': 'schlugen',
      },
      es: {
        base: 'batir',
        '1sg_present': 'bato', '2sg_present': 'bates', '3sg_present': 'bate',
        '1pl_present': 'batimos', '2pl_present': 'batís', '3pl_present': 'baten',
        '1sg_past': 'batí', '2sg_past': 'batiste', '3sg_past': 'batió',
        '1pl_past': 'batimos', '2pl_past': 'batisteis', '3pl_past': 'batieron',
        '1sg_future': 'batiré', '2sg_future': 'batirás', '3sg_future': 'batirá',
        '1pl_future': 'batiremos', '2pl_future': 'batiréis', '3pl_future': 'batirán',
      },
      ja: {
        base: '打つ',
        reading: 'うつ',
        masu_present: '打ちます',
        masu_present_reading: 'うちます',
      },
      pt: {
        base: 'bater',
        '1sg_present': 'bato', '2sg_present': 'bate', '3sg_present': 'bate',
        '1pl_present': 'batemos', '2pl_present': 'batem', '3pl_present': 'batem',
        '1sg_past': 'bati', '2sg_past': 'bateu', '3sg_past': 'bateu',
        '1pl_past': 'batemos', '2pl_past': 'bateram', '3pl_past': 'bateram',
        '1sg_future': 'baterei', '2sg_future': 'baterá', '3sg_future': 'baterá',
        '1pl_future': 'bateremos', '2pl_future': 'baterão', '3pl_future': 'baterão',
      },
    },
  },

  {
    id: 'SET_ON_FIRE',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to set (something) on fire; to cause to burn',
    emoji: '🧨',
    synonym: 'set on fire',
    forms: {
      en: {
        base: 'burn',
        '1sg_present': 'burn', '2sg_present': 'burn', '3sg_present': 'burns',
        '1pl_present': 'burn', '2pl_present': 'burn', '3pl_present': 'burn',
        past: 'burned',
      },
      it: {
        // labile: same verb as intransitive BURN, used transitively (bruciare qualcosa)
        base: 'bruciare',
        '1sg_present': 'brucio', '2sg_present': 'bruci', '3sg_present': 'brucia',
        '1pl_present': 'bruciamo', '2pl_present': 'bruciate', '3pl_present': 'bruciano',
        '1sg_past': 'bruciai', '2sg_past': 'bruciasti', '3sg_past': 'bruciò',
        '1pl_past': 'bruciammo', '2pl_past': 'bruciaste', '3pl_past': 'bruciarono',
        '1sg_future': 'brucerò', '2sg_future': 'brucerai', '3sg_future': 'brucerà',
        '1pl_future': 'bruceremo', '2pl_future': 'brucerete', '3pl_future': 'bruceranno',
      },
      fr: {
        // labile: brûler quelque chose
        base: 'brûler',
        '1sg_present': 'brûle', '2sg_present': 'brûles', '3sg_present': 'brûle',
        '1pl_present': 'brûlons', '2pl_present': 'brûlez', '3pl_present': 'brûlent',
        '1sg_past': 'brûlai', '2sg_past': 'brûlas', '3sg_past': 'brûla',
        '1pl_past': 'brûlâmes', '2pl_past': 'brûlâtes', '3pl_past': 'brûlèrent',
        '1sg_future': 'brûlerai', '2sg_future': 'brûleras', '3sg_future': 'brûlera',
        '1pl_future': 'brûlerons', '2pl_future': 'brûlerez', '3pl_future': 'brûleront',
      },
      de: {
        base: 'verbrennen',
        '1sg_present': 'verbrenne', '2sg_present': 'verbrennst', '3sg_present': 'verbrennt',
        '1pl_present': 'verbrennen', '2pl_present': 'verbrennt', '3pl_present': 'verbrennen',
        '1sg_past': 'verbrannte', '2sg_past': 'verbranntest', '3sg_past': 'verbrannte',
        '1pl_past': 'verbrannten', '2pl_past': 'verbranntet', '3pl_past': 'verbrannten',
      },
      es: {
        base: 'quemar',
        '1sg_present': 'quemo', '2sg_present': 'quemas', '3sg_present': 'quema',
        '1pl_present': 'quemamos', '2pl_present': 'quemáis', '3pl_present': 'queman',
        '1sg_past': 'quemé', '2sg_past': 'quemaste', '3sg_past': 'quemó',
        '1pl_past': 'quemamos', '2pl_past': 'quemasteis', '3pl_past': 'quemaron',
        '1sg_future': 'quemaré', '2sg_future': 'quemarás', '3sg_future': 'quemará',
        '1pl_future': 'quemaremos', '2pl_future': 'quemaréis', '3pl_future': 'quemarán',
      },
      ja: {
        base: '燃やす',
        reading: 'もやす',
        masu_present: '燃やします',
        masu_present_reading: 'もやします',
      },
      pt: {
        base: 'queimar',
        '1sg_present': 'queimo', '2sg_present': 'queima', '3sg_present': 'queima',
        '1pl_present': 'queimamos', '2pl_present': 'queimam', '3pl_present': 'queimam',
        '1sg_past': 'queimei', '2sg_past': 'queimou', '3sg_past': 'queimou',
        '1pl_past': 'queimamos', '2pl_past': 'queimaram', '3pl_past': 'queimaram',
        '1sg_future': 'queimarei', '2sg_future': 'queimará', '3sg_future': 'queimará',
        '1pl_future': 'queimaremos', '2pl_future': 'queimarão', '3pl_future': 'queimarão',
      },
    },
  },

  {
    id: 'EXTINGUISH',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to put out (a fire); to cause to stop burning',
    emoji: '🧯',
    synonym: 'extinguish',
    forms: {
      en: {
        // phrasal: the particle stays adjacent to the verb, since a direct object
        // is always a full noun phrase here ("puts out the fire"), never a pronoun.
        base: 'put out',
        '1sg_present': 'put out', '2sg_present': 'put out', '3sg_present': 'puts out',
        '1pl_present': 'put out', '2pl_present': 'put out', '3pl_present': 'put out',
        past: 'put out',
      },
      it: {
        base: 'spegnere',
        '1sg_present': 'spengo', '2sg_present': 'spegni', '3sg_present': 'spegne',
        '1pl_present': 'spegniamo', '2pl_present': 'spegnete', '3pl_present': 'spengono',
        '1sg_past': 'spensi', '2sg_past': 'spegnesti', '3sg_past': 'spense',
        '1pl_past': 'spegnemmo', '2pl_past': 'spegneste', '3pl_past': 'spensero',
        '1sg_future': 'spegnerò', '2sg_future': 'spegnerai', '3sg_future': 'spegnerà',
        '1pl_future': 'spegneremo', '2pl_future': 'spegnerete', '3pl_future': 'spegneranno',
      },
      fr: {
        base: 'éteindre',
        '1sg_present': 'éteins', '2sg_present': 'éteins', '3sg_present': 'éteint',
        '1pl_present': 'éteignons', '2pl_present': 'éteignez', '3pl_present': 'éteignent',
        '1sg_past': 'éteignis', '2sg_past': 'éteignis', '3sg_past': 'éteignit',
        '1pl_past': 'éteignîmes', '2pl_past': 'éteignîtes', '3pl_past': 'éteignirent',
        '1sg_future': 'éteindrai', '2sg_future': 'éteindras', '3sg_future': 'éteindra',
        '1pl_future': 'éteindrons', '2pl_future': 'éteindrez', '3pl_future': 'éteindront',
      },
      de: {
        base: 'löschen',
        '1sg_present': 'lösche', '2sg_present': 'löschst', '3sg_present': 'löscht',
        '1pl_present': 'löschen', '2pl_present': 'löscht', '3pl_present': 'löschen',
        '1sg_past': 'löschte', '2sg_past': 'löschtest', '3sg_past': 'löschte',
        '1pl_past': 'löschten', '2pl_past': 'löschtet', '3pl_past': 'löschten',
      },
      es: {
        base: 'apagar',
        '1sg_present': 'apago', '2sg_present': 'apagas', '3sg_present': 'apaga',
        '1pl_present': 'apagamos', '2pl_present': 'apagáis', '3pl_present': 'apagan',
        '1sg_past': 'apagué', '2sg_past': 'apagaste', '3sg_past': 'apagó',
        '1pl_past': 'apagamos', '2pl_past': 'apagasteis', '3pl_past': 'apagaron',
        '1sg_future': 'apagaré', '2sg_future': 'apagarás', '3sg_future': 'apagará',
        '1pl_future': 'apagaremos', '2pl_future': 'apagaréis', '3pl_future': 'apagarán',
      },
      ja: {
        base: '消す',
        reading: 'けす',
        masu_present: '消します',
        masu_present_reading: 'けします',
      },
      pt: {
        base: 'apagar',
        '1sg_present': 'apago', '2sg_present': 'apaga', '3sg_present': 'apaga',
        '1pl_present': 'apagamos', '2pl_present': 'apagam', '3pl_present': 'apagam',
        '1sg_past': 'apaguei', '2sg_past': 'apagou', '3sg_past': 'apagou',
        '1pl_past': 'apagamos', '2pl_past': 'apagaram', '3pl_past': 'apagaram',
        '1sg_future': 'apagarei', '2sg_future': 'apagará', '3sg_future': 'apagará',
        '1pl_future': 'apagaremos', '2pl_future': 'apagarão', '3pl_future': 'apagarão',
      },
    },
  },

  {
    id: 'BUY',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to acquire in exchange for money',
    emoji: '🛒',
    forms: {
      en: {
        base: 'buy',
        '1sg_present': 'buy', '2sg_present': 'buy', '3sg_present': 'buys',
        '1pl_present': 'buy', '2pl_present': 'buy', '3pl_present': 'buy',
        past: 'bought',
      },
      it: {
        base: 'comprare',
        '1sg_present': 'compro', '2sg_present': 'compri', '3sg_present': 'compra',
        '1pl_present': 'compriamo', '2pl_present': 'comprate', '3pl_present': 'comprano',
        '1sg_past': 'comprai', '2sg_past': 'comprasti', '3sg_past': 'comprò',
        '1pl_past': 'comprammo', '2pl_past': 'compraste', '3pl_past': 'comprarono',
        '1sg_future': 'comprerò', '2sg_future': 'comprerai', '3sg_future': 'comprerà',
        '1pl_future': 'compreremo', '2pl_future': 'comprerete', '3pl_future': 'compreranno',
      },
      fr: {
        base: 'acheter',
        '1sg_present': 'achète', '2sg_present': 'achètes', '3sg_present': 'achète',
        '1pl_present': 'achetons', '2pl_present': 'achetez', '3pl_present': 'achètent',
        '1sg_past': 'achetai', '2sg_past': 'achetas', '3sg_past': 'acheta',
        '1pl_past': 'achetâmes', '2pl_past': 'achetâtes', '3pl_past': 'achetèrent',
        '1sg_future': 'achèterai', '2sg_future': 'achèteras', '3sg_future': 'achètera',
        '1pl_future': 'achèterons', '2pl_future': 'achèterez', '3pl_future': 'achèteront',
      },
      de: {
        base: 'kaufen',
        '1sg_present': 'kaufe', '2sg_present': 'kaufst', '3sg_present': 'kauft',
        '1pl_present': 'kaufen', '2pl_present': 'kauft', '3pl_present': 'kaufen',
        '1sg_past': 'kaufte', '2sg_past': 'kauftest', '3sg_past': 'kaufte',
        '1pl_past': 'kauften', '2pl_past': 'kauftet', '3pl_past': 'kauften',
      },
      es: {
        base: 'comprar',
        '1sg_present': 'compro', '2sg_present': 'compras', '3sg_present': 'compra',
        '1pl_present': 'compramos', '2pl_present': 'compráis', '3pl_present': 'compran',
        '1sg_past': 'compré', '2sg_past': 'compraste', '3sg_past': 'compró',
        '1pl_past': 'compramos', '2pl_past': 'comprasteis', '3pl_past': 'compraron',
        '1sg_future': 'compraré', '2sg_future': 'comprarás', '3sg_future': 'comprará',
        '1pl_future': 'compraremos', '2pl_future': 'compraréis', '3pl_future': 'comprarán',
      },
      ja: {
        base: '買う',
        reading: 'かう',
        masu_present: '買います',
        masu_present_reading: 'かいます',
      },
      pt: {
        base: 'comprar',
        '1sg_present': 'compro', '2sg_present': 'compra', '3sg_present': 'compra',
        '1pl_present': 'compramos', '2pl_present': 'compram', '3pl_present': 'compram',
        '1sg_past': 'comprei', '2sg_past': 'comprou', '3sg_past': 'comprou',
        '1pl_past': 'compramos', '2pl_past': 'compraram', '3pl_past': 'compraram',
        '1sg_future': 'comprarei', '2sg_future': 'comprará', '3sg_future': 'comprará',
        '1pl_future': 'compraremos', '2pl_future': 'comprarão', '3pl_future': 'comprarão',
      },
    },
  },

  {
    id: 'CLICK',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to press a mouse button or select by pressing',
    emoji: '🖱️',
    forms: {
      en: {
        base: 'click',
        '1sg_present': 'click', '2sg_present': 'click', '3sg_present': 'clicks',
        '1pl_present': 'click', '2pl_present': 'click', '3pl_present': 'click',
        past: 'clicked',
      },
      it: {
        base: 'cliccare',
        '1sg_present': 'clicco', '2sg_present': 'clicchi', '3sg_present': 'clicca',
        '1pl_present': 'clicchiamo', '2pl_present': 'cliccate', '3pl_present': 'cliccano',
        '1sg_past': 'cliccai', '2sg_past': 'cliccasti', '3sg_past': 'cliccò',
        '1pl_past': 'cliccammo', '2pl_past': 'cliccaste', '3pl_past': 'cliccarono',
        '1sg_future': 'cliccherò', '2sg_future': 'cliccherai', '3sg_future': 'cliccherà',
        '1pl_future': 'cliccheremo', '2pl_future': 'cliccherete', '3pl_future': 'cliccheranno',
      },
      fr: {
        base: 'cliquer',
        '1sg_present': 'clique', '2sg_present': 'cliques', '3sg_present': 'clique',
        '1pl_present': 'cliquons', '2pl_present': 'cliquez', '3pl_present': 'cliquent',
        '1sg_past': 'cliquai', '2sg_past': 'cliquas', '3sg_past': 'cliqua',
        '1pl_past': 'cliquâmes', '2pl_past': 'cliquâtes', '3pl_past': 'cliquèrent',
        '1sg_future': 'cliquerai', '2sg_future': 'cliqueras', '3sg_future': 'cliquera',
        '1pl_future': 'cliquerons', '2pl_future': 'cliquerez', '3pl_future': 'cliqueront',
      },
      de: {
        base: 'klicken',
        '1sg_present': 'klicke', '2sg_present': 'klickst', '3sg_present': 'klickt',
        '1pl_present': 'klicken', '2pl_present': 'klickt', '3pl_present': 'klicken',
        '1sg_past': 'klickte', '2sg_past': 'klicktest', '3sg_past': 'klickte',
        '1pl_past': 'klickten', '2pl_past': 'klicktet', '3pl_past': 'klickten',
      },
      es: {
        base: 'clicar',
        '1sg_present': 'clico', '2sg_present': 'clicas', '3sg_present': 'clica',
        '1pl_present': 'clicamos', '2pl_present': 'clicáis', '3pl_present': 'clican',
        '1sg_past': 'cliqué', '2sg_past': 'clicaste', '3sg_past': 'clicó',
        '1pl_past': 'clicamos', '2pl_past': 'clicasteis', '3pl_past': 'clicaron',
        '1sg_future': 'clicaré', '2sg_future': 'clicarás', '3sg_future': 'clicará',
        '1pl_future': 'clicaremos', '2pl_future': 'clicaréis', '3pl_future': 'clicarán',
      },
      ja: {
        base: 'クリックする',
        reading: 'くりっくする',
        masu_present: 'クリックします',
        masu_present_reading: 'くりっくします',
      },
      pt: {
        base: 'clicar',
        '1sg_present': 'clico', '2sg_present': 'clica', '3sg_present': 'clica',
        '1pl_present': 'clicamos', '2pl_present': 'clicam', '3pl_present': 'clicam',
        '1sg_past': 'cliquei', '2sg_past': 'clicou', '3sg_past': 'clicou',
        '1pl_past': 'clicamos', '2pl_past': 'clicaram', '3pl_past': 'clicaram',
        '1sg_future': 'clicarei', '2sg_future': 'clicará', '3sg_future': 'clicará',
        '1pl_future': 'clicaremos', '2pl_future': 'clicarão', '3pl_future': 'clicarão',
      },
    },
  },

  {
    id: 'CHOOSE',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to pick one option from several',
    emoji: '☑️',
    synonym: 'select',
    forms: {
      en: {
        base: 'choose',
        '1sg_present': 'choose', '2sg_present': 'choose', '3sg_present': 'chooses',
        '1pl_present': 'choose', '2pl_present': 'choose', '3pl_present': 'choose',
        past: 'chose',
      },
      it: {
        base: 'scegliere',
        '1sg_present': 'scelgo', '2sg_present': 'scegli', '3sg_present': 'sceglie',
        '1pl_present': 'scegliamo', '2pl_present': 'scegliete', '3pl_present': 'scelgono',
        '1sg_past': 'scelsi', '2sg_past': 'scegliesti', '3sg_past': 'scelse',
        '1pl_past': 'scegliemmo', '2pl_past': 'sceglieste', '3pl_past': 'scelsero',
        '1sg_future': 'sceglierò', '2sg_future': 'sceglierai', '3sg_future': 'sceglierà',
        '1pl_future': 'sceglieremo', '2pl_future': 'sceglierete', '3pl_future': 'sceglieranno',
      },
      fr: {
        base: 'choisir',
        '1sg_present': 'choisis', '2sg_present': 'choisis', '3sg_present': 'choisit',
        '1pl_present': 'choisissons', '2pl_present': 'choisissez', '3pl_present': 'choisissent',
        '1sg_past': 'choisis', '2sg_past': 'choisis', '3sg_past': 'choisit',
        '1pl_past': 'choisîmes', '2pl_past': 'choisîtes', '3pl_past': 'choisirent',
        '1sg_future': 'choisirai', '2sg_future': 'choisiras', '3sg_future': 'choisira',
        '1pl_future': 'choisirons', '2pl_future': 'choisirez', '3pl_future': 'choisiront',
      },
      de: {
        base: 'wählen',
        '1sg_present': 'wähle', '2sg_present': 'wählst', '3sg_present': 'wählt',
        '1pl_present': 'wählen', '2pl_present': 'wählt', '3pl_present': 'wählen',
        '1sg_past': 'wählte', '2sg_past': 'wähltest', '3sg_past': 'wählte',
        '1pl_past': 'wählten', '2pl_past': 'wähltet', '3pl_past': 'wählten',
      },
      es: {
        base: 'elegir',
        '1sg_present': 'elijo', '2sg_present': 'eliges', '3sg_present': 'elige',
        '1pl_present': 'elegimos', '2pl_present': 'elegís', '3pl_present': 'eligen',
        '1sg_past': 'elegí', '2sg_past': 'elegiste', '3sg_past': 'eligió',
        '1pl_past': 'elegimos', '2pl_past': 'elegisteis', '3pl_past': 'eligieron',
        '1sg_future': 'elegiré', '2sg_future': 'elegirás', '3sg_future': 'elegirá',
        '1pl_future': 'elegiremos', '2pl_future': 'elegiréis', '3pl_future': 'elegirán',
      },
      ja: {
        base: '選ぶ',
        reading: 'えらぶ',
        masu_present: '選びます',
        masu_present_reading: 'えらびます',
      },
      pt: {
        base: 'escolher',
        '1sg_present': 'escolho', '2sg_present': 'escolhe', '3sg_present': 'escolhe',
        '1pl_present': 'escolhemos', '2pl_present': 'escolhem', '3pl_present': 'escolhem',
        '1sg_past': 'escolhi', '2sg_past': 'escolheu', '3sg_past': 'escolheu',
        '1pl_past': 'escolhemos', '2pl_past': 'escolheram', '3pl_past': 'escolheram',
        '1sg_future': 'escolherei', '2sg_future': 'escolherá', '3sg_future': 'escolherá',
        '1pl_future': 'escolheremos', '2pl_future': 'escolherão', '3pl_future': 'escolherão',
      },
    },
  },

  {
    id: 'TYPE',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['cause'],
    description: 'to write with a keyboard',
    emoji: '⌨️',
    forms: {
      en: {
        base: 'type',
        '1sg_present': 'type', '2sg_present': 'type', '3sg_present': 'types',
        '1pl_present': 'type', '2pl_present': 'type', '3pl_present': 'type',
        past: 'typed',
      },
      it: {
        base: 'digitare',
        '1sg_present': 'digito', '2sg_present': 'digiti', '3sg_present': 'digita',
        '1pl_present': 'digitiamo', '2pl_present': 'digitate', '3pl_present': 'digitano',
        '1sg_past': 'digitai', '2sg_past': 'digitasti', '3sg_past': 'digitò',
        '1pl_past': 'digitammo', '2pl_past': 'digitaste', '3pl_past': 'digitarono',
        '1sg_future': 'digiterò', '2sg_future': 'digiterai', '3sg_future': 'digiterà',
        '1pl_future': 'digiteremo', '2pl_future': 'digiterete', '3pl_future': 'digiteranno',
      },
      fr: {
        base: 'taper',
        '1sg_present': 'tape', '2sg_present': 'tapes', '3sg_present': 'tape',
        '1pl_present': 'tapons', '2pl_present': 'tapez', '3pl_present': 'tapent',
        '1sg_past': 'tapai', '2sg_past': 'tapas', '3sg_past': 'tapa',
        '1pl_past': 'tapâmes', '2pl_past': 'tapâtes', '3pl_past': 'tapèrent',
        '1sg_future': 'taperai', '2sg_future': 'taperas', '3sg_future': 'tapera',
        '1pl_future': 'taperons', '2pl_future': 'taperez', '3pl_future': 'taperont',
      },
      de: {
        base: 'tippen',
        '1sg_present': 'tippe', '2sg_present': 'tippst', '3sg_present': 'tippt',
        '1pl_present': 'tippen', '2pl_present': 'tippt', '3pl_present': 'tippen',
        '1sg_past': 'tippte', '2sg_past': 'tipptest', '3sg_past': 'tippte',
        '1pl_past': 'tippten', '2pl_past': 'tipptet', '3pl_past': 'tippten',
      },
      es: {
        base: 'teclear',
        '1sg_present': 'tecleo', '2sg_present': 'tecleas', '3sg_present': 'teclea',
        '1pl_present': 'tecleamos', '2pl_present': 'tecleáis', '3pl_present': 'teclean',
        '1sg_past': 'tecleé', '2sg_past': 'tecleaste', '3sg_past': 'tecleó',
        '1pl_past': 'tecleamos', '2pl_past': 'tecleasteis', '3pl_past': 'teclearon',
        '1sg_future': 'teclearé', '2sg_future': 'teclearás', '3sg_future': 'tecleará',
        '1pl_future': 'teclearemos', '2pl_future': 'teclearéis', '3pl_future': 'teclearán',
      },
      ja: {
        base: '入力する',
        reading: 'にゅうりょくする',
        masu_present: '入力します',
        masu_present_reading: 'にゅうりょくします',
        label: '入力',
      },
      pt: {
        base: 'digitar',
        '1sg_present': 'digito', '2sg_present': 'digita', '3sg_present': 'digita',
        '1pl_present': 'digitamos', '2pl_present': 'digitam', '3pl_present': 'digitam',
        '1sg_past': 'digitei', '2sg_past': 'digitou', '3sg_past': 'digitou',
        '1pl_past': 'digitamos', '2pl_past': 'digitaram', '3pl_past': 'digitaram',
        '1sg_future': 'digitarei', '2sg_future': 'digitará', '3sg_future': 'digitará',
        '1pl_future': 'digitaremos', '2pl_future': 'digitarão', '3pl_future': 'digitarão',
      },
    },
  },

  {
    id: 'SAVE',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['terminus', 'cause'],
    description: 'to store something so it can be retrieved later',
    emoji: '💾',
    forms: {
      en: {
        base: 'save',
        '1sg_present': 'save', '2sg_present': 'save', '3sg_present': 'saves',
        '1pl_present': 'save', '2pl_present': 'save', '3pl_present': 'save',
        past: 'saved',
      },
      it: {
        base: 'salvare',
        '1sg_present': 'salvo', '2sg_present': 'salvi', '3sg_present': 'salva',
        '1pl_present': 'salviamo', '2pl_present': 'salvate', '3pl_present': 'salvano',
        '1sg_past': 'salvai', '2sg_past': 'salvasti', '3sg_past': 'salvò',
        '1pl_past': 'salvammo', '2pl_past': 'salvaste', '3pl_past': 'salvarono',
        '1sg_future': 'salverò', '2sg_future': 'salverai', '3sg_future': 'salverà',
        '1pl_future': 'salveremo', '2pl_future': 'salverete', '3pl_future': 'salveranno',
      },
      fr: {
        base: 'enregistrer',
        '1sg_present': 'enregistre', '2sg_present': 'enregistres', '3sg_present': 'enregistre',
        '1pl_present': 'enregistrons', '2pl_present': 'enregistrez', '3pl_present': 'enregistrent',
        '1sg_past': 'enregistrai', '2sg_past': 'enregistras', '3sg_past': 'enregistra',
        '1pl_past': 'enregistrâmes', '2pl_past': 'enregistrâtes', '3pl_past': 'enregistrèrent',
        '1sg_future': 'enregistrerai', '2sg_future': 'enregistreras', '3sg_future': 'enregistrera',
        '1pl_future': 'enregistrerons', '2pl_future': 'enregistrerez', '3pl_future': 'enregistreront',
      },
      de: {
        base: 'speichern',
        '1sg_present': 'speichere', '2sg_present': 'speicherst', '3sg_present': 'speichert',
        '1pl_present': 'speichern', '2pl_present': 'speichert', '3pl_present': 'speichern',
        '1sg_past': 'speicherte', '2sg_past': 'speichertest', '3sg_past': 'speicherte',
        '1pl_past': 'speicherten', '2pl_past': 'speichertet', '3pl_past': 'speicherten',
      },
      es: {
        base: 'guardar',
        '1sg_present': 'guardo', '2sg_present': 'guardas', '3sg_present': 'guarda',
        '1pl_present': 'guardamos', '2pl_present': 'guardáis', '3pl_present': 'guardan',
        '1sg_past': 'guardé', '2sg_past': 'guardaste', '3sg_past': 'guardó',
        '1pl_past': 'guardamos', '2pl_past': 'guardasteis', '3pl_past': 'guardaron',
        '1sg_future': 'guardaré', '2sg_future': 'guardarás', '3sg_future': 'guardará',
        '1pl_future': 'guardaremos', '2pl_future': 'guardaréis', '3pl_future': 'guardarán',
      },
      ja: {
        base: '保存する',
        reading: 'ほぞんする',
        masu_present: '保存します',
        masu_present_reading: 'ほぞんします',
        label: '保存',
      },
      pt: {
        base: 'salvar',
        '1sg_present': 'salvo', '2sg_present': 'salva', '3sg_present': 'salva',
        '1pl_present': 'salvamos', '2pl_present': 'salvam', '3pl_present': 'salvam',
        '1sg_past': 'salvei', '2sg_past': 'salvou', '3sg_past': 'salvou',
        '1pl_past': 'salvamos', '2pl_past': 'salvaram', '3pl_past': 'salvaram',
        '1sg_future': 'salvarei', '2sg_future': 'salvará', '3sg_future': 'salvará',
        '1pl_future': 'salvaremos', '2pl_future': 'salvarão', '3pl_future': 'salvarão',
      },
    },
  },

  {
    id: 'LOAD',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['source', 'cause'],
    description: 'to bring stored content back in',
    emoji: '📂',
    forms: {
      en: {
        base: 'load',
        '1sg_present': 'load', '2sg_present': 'load', '3sg_present': 'loads',
        '1pl_present': 'load', '2pl_present': 'load', '3pl_present': 'load',
        past: 'loaded',
      },
      it: {
        base: 'caricare',
        '1sg_present': 'carico', '2sg_present': 'carichi', '3sg_present': 'carica',
        '1pl_present': 'carichiamo', '2pl_present': 'caricate', '3pl_present': 'caricano',
        '1sg_past': 'caricai', '2sg_past': 'caricasti', '3sg_past': 'caricò',
        '1pl_past': 'caricammo', '2pl_past': 'caricaste', '3pl_past': 'caricarono',
        '1sg_future': 'caricherò', '2sg_future': 'caricherai', '3sg_future': 'caricherà',
        '1pl_future': 'caricheremo', '2pl_future': 'caricherete', '3pl_future': 'caricheranno',
      },
      fr: {
        base: 'charger',
        '1sg_present': 'charge', '2sg_present': 'charges', '3sg_present': 'charge',
        '1pl_present': 'chargeons', '2pl_present': 'chargez', '3pl_present': 'chargent',
        '1sg_past': 'chargeai', '2sg_past': 'chargeas', '3sg_past': 'chargea',
        '1pl_past': 'chargeâmes', '2pl_past': 'chargeâtes', '3pl_past': 'chargèrent',
        '1sg_future': 'chargerai', '2sg_future': 'chargeras', '3sg_future': 'chargera',
        '1pl_future': 'chargerons', '2pl_future': 'chargerez', '3pl_future': 'chargeront',
      },
      de: {
        base: 'laden',
        '1sg_present': 'lade', '2sg_present': 'lädst', '3sg_present': 'lädt',
        '1pl_present': 'laden', '2pl_present': 'ladet', '3pl_present': 'laden',
        '1sg_past': 'lud', '2sg_past': 'ludst', '3sg_past': 'lud',
        '1pl_past': 'luden', '2pl_past': 'ludet', '3pl_past': 'luden',
      },
      es: {
        base: 'cargar',
        '1sg_present': 'cargo', '2sg_present': 'cargas', '3sg_present': 'carga',
        '1pl_present': 'cargamos', '2pl_present': 'cargáis', '3pl_present': 'cargan',
        '1sg_past': 'cargué', '2sg_past': 'cargaste', '3sg_past': 'cargó',
        '1pl_past': 'cargamos', '2pl_past': 'cargasteis', '3pl_past': 'cargaron',
        '1sg_future': 'cargaré', '2sg_future': 'cargarás', '3sg_future': 'cargará',
        '1pl_future': 'cargaremos', '2pl_future': 'cargaréis', '3pl_future': 'cargarán',
      },
      ja: {
        base: '読み込む',
        reading: 'よみこむ',
        masu_present: '読み込みます',
        masu_present_reading: 'よみこみます',
        label: '読み込み',
      },
      pt: {
        base: 'carregar',
        '1sg_present': 'carrego', '2sg_present': 'carrega', '3sg_present': 'carrega',
        '1pl_present': 'carregamos', '2pl_present': 'carregam', '3pl_present': 'carregam',
        '1sg_past': 'carreguei', '2sg_past': 'carregou', '3sg_past': 'carregou',
        '1pl_past': 'carregamos', '2pl_past': 'carregaram', '3pl_past': 'carregaram',
        '1sg_future': 'carregarei', '2sg_future': 'carregará', '3sg_future': 'carregará',
        '1pl_future': 'carregaremos', '2pl_future': 'carregarão', '3pl_future': 'carregarão',
      },
    },
  },

  {
    id: 'ADD',
    role: 'verb',
    transitivity: 'transitive',
    complements: ['terminus', 'cause'],
    description: 'to put something together with something else',
    emoji: '➕',
    forms: {
      en: {
        base: 'add',
        '1sg_present': 'add', '2sg_present': 'add', '3sg_present': 'adds',
        '1pl_present': 'add', '2pl_present': 'add', '3pl_present': 'add',
        past: 'added',
      },
      it: {
        base: 'aggiungere',
        '1sg_present': 'aggiungo', '2sg_present': 'aggiungi', '3sg_present': 'aggiunge',
        '1pl_present': 'aggiungiamo', '2pl_present': 'aggiungete', '3pl_present': 'aggiungono',
        '1sg_past': 'aggiunsi', '2sg_past': 'aggiungesti', '3sg_past': 'aggiunse',
        '1pl_past': 'aggiungemmo', '2pl_past': 'aggiungeste', '3pl_past': 'aggiunsero',
        '1sg_future': 'aggiungerò', '2sg_future': 'aggiungerai', '3sg_future': 'aggiungerà',
        '1pl_future': 'aggiungeremo', '2pl_future': 'aggiungerete', '3pl_future': 'aggiungeranno',
      },
      fr: {
        base: 'ajouter',
        '1sg_present': 'ajoute', '2sg_present': 'ajoutes', '3sg_present': 'ajoute',
        '1pl_present': 'ajoutons', '2pl_present': 'ajoutez', '3pl_present': 'ajoutent',
        '1sg_past': 'ajoutai', '2sg_past': 'ajoutas', '3sg_past': 'ajouta',
        '1pl_past': 'ajoutâmes', '2pl_past': 'ajoutâtes', '3pl_past': 'ajoutèrent',
        '1sg_future': 'ajouterai', '2sg_future': 'ajouteras', '3sg_future': 'ajoutera',
        '1pl_future': 'ajouterons', '2pl_future': 'ajouterez', '3pl_future': 'ajouteront',
      },
      de: {
        base: 'addieren',
        '1sg_present': 'addiere', '2sg_present': 'addierst', '3sg_present': 'addiert',
        '1pl_present': 'addieren', '2pl_present': 'addiert', '3pl_present': 'addieren',
        '1sg_past': 'addierte', '2sg_past': 'addiertest', '3sg_past': 'addierte',
        '1pl_past': 'addierten', '2pl_past': 'addiertet', '3pl_past': 'addierten',
      },
      es: {
        base: 'añadir',
        '1sg_present': 'añado', '2sg_present': 'añades', '3sg_present': 'añade',
        '1pl_present': 'añadimos', '2pl_present': 'añadís', '3pl_present': 'añaden',
        '1sg_past': 'añadí', '2sg_past': 'añadiste', '3sg_past': 'añadió',
        '1pl_past': 'añadimos', '2pl_past': 'añadisteis', '3pl_past': 'añadieron',
        '1sg_future': 'añadiré', '2sg_future': 'añadirás', '3sg_future': 'añadirá',
        '1pl_future': 'añadiremos', '2pl_future': 'añadiréis', '3pl_future': 'añadirán',
      },
      ja: {
        base: '加える',
        reading: 'くわえる',
        masu_present: '加えます',
        masu_present_reading: 'くわえます',
        label: '追加',
      },
      pt: {
        base: 'adicionar',
        '1sg_present': 'adiciono', '2sg_present': 'adiciona', '3sg_present': 'adiciona',
        '1pl_present': 'adicionamos', '2pl_present': 'adicionam', '3pl_present': 'adicionam',
        '1sg_past': 'adicionei', '2sg_past': 'adicionou', '3sg_past': 'adicionou',
        '1pl_past': 'adicionamos', '2pl_past': 'adicionaram', '3pl_past': 'adicionaram',
        '1sg_future': 'adicionarei', '2sg_future': 'adicionará', '3sg_future': 'adicionará',
        '1pl_future': 'adicionaremos', '2pl_future': 'adicionarão', '3pl_future': 'adicionarão',
      },
    },
  },
];
