import type { GswColumn } from './types.js';

export const GSW_ADJECTIVES: GswColumn = {
  BIG: { base: 'gross', umlaut: 'true', superlative: 'gröscht' },
  SMALL: { base: 'chlii', attributive: 'chliin' }, // chliin- before an ending: en chliine Hund, e chliini Chatz (verify)
  HIGH: { base: 'hööch', attributive: 'hööch', comparative: 'höcher', superlative: 'höchscht' }, // no h/ch alternation in Zürich (verify vowel length)
  LONG: { base: 'lang', umlaut: 'true' },
  GREAT: { base: 'gross', umlaut: 'true', superlative: 'gröscht' },
  LOW: { base: 'tüüf' }, // Zürich says tüüf (tiefe Priise), not niedrig
  NEAR: { base: 'nooch', umlaut: 'true', superlative: 'nächscht' }, // (verify) nooch vs nööch
  FAR: { base: 'wiit' }, // fern is bookish; Zürich wiit
  GOOD: { base: 'guet', comparative: 'besser', superlative: 'bescht' },
  BAD: { base: 'schlächt' },
  HAPPY: { base: 'glücklich' },
  OKAY: { base: 'guet', copula: 'BE_FARING', experiencer: '1' },
  SAD: { base: 'truurig' },
  OLD: { base: 'alt', umlaut: 'true' },
  YOUNG: { base: 'jung', umlaut: 'true' },
  ELDER: { base: 'elter' },
  YOUNGER: { base: 'jünger' },
  ADULT: { base: 'erwachse' },
  MALE: { base: 'männlich' },
  FEMALE: { base: 'wiiblich' },
  CASTRATED: { base: 'kastriert' },
  NEW: { base: 'nöi' },
  BEAUTIFUL: { base: 'schön' }, // (verify) Dieth doubling would give schöön
  STRONG: { base: 'starch', umlaut: 'true' },
  WEAK: { base: 'schwach', umlaut: 'true' },
  TIRED: { base: 'müed' },
  HUNGRY: { base: 'hungrig' },
  COLD: { base: 'chalt', umlaut: 'true' },
  COLD_CLIMATE: { base: 'chalt', umlaut: 'true' },
  WARM: { base: 'warm' },
  HOT: { base: 'heiss' },
  HOT_CLIMATE: { base: 'heiss' },
  INTERESTING: { base: 'interessant' },
  IMPORTANT: { base: 'wichtig' },
  QUICK: { base: 'schnäll' },
  BROWN: { base: 'bruun' },
  BLACK: { base: 'schwarz', umlaut: 'true' },
  WHITE: { base: 'wiiss' },
  DARK: { base: 'tunkel' }, // (verify) tunkel vs dunkel
  WILD: { base: 'wild' },
  DOMESTIC: { base: 'zahm' },
  CANINE: { base: 'hundeartig' },
  LAZY: { base: 'fuul' },
  CAREFUL: { base: 'vorsichtig' },
  POSSIBLE: { base: 'möglich' },
  ABLE: { base: 'fähig' },
  OBLIGED: { base: 'verpflichtet' },
  ALLOWED: { base: 'berächtigt' },
  WHOLE: { base: 'ganz' },
  ROUND: { base: 'rund' },
  SHARP: { base: 'scharf', umlaut: 'true' },
  LOUD: { base: 'luut' },
  WRITTEN: { base: 'gschribe' },
  LOADED: { base: 'glade' },
  TIDY: { base: 'ordentlich' },
  SAVED: { base: 'gspeicheret' },
  ADDED: { base: 'hinzuegfüegt' },
  REMOVED: { base: 'entfärnt' },
  FAILED: { base: 'fählgschlage' },
  COPIED: { base: 'kopiert' },
  LINKED: { base: 'verchnüpft' },
  PINNED: { base: 'aaghäftet' },
  UNPINNED: { base: 'nüme aaghäftet' }, // nicht mehr → nüme
  RECENT: { base: 'zletscht bruucht' }, // verwenden → bruuche
  NUMBERED: { base: 'nummeriert' },
  ACTIVE: { base: 'aktiv' },
  UNTITLED: { base: 'unbenannt' },
  EMPTY: { base: 'läär' },
  VALID: { base: 'gültig' },
  MISSING: { base: 'fäälend' }, // (verify) present participle of fääle
  UNKNOWN: { base: 'unbekannt' },
  KNOWN: { base: 'bekannt' },
  UNEXPECTED: { base: 'unerwartet' },
  SINGULAR: { base: 'singularisch' },
  PLURAL: { base: 'pluralisch' },
  NEUTER: { base: 'sächlich' },
  DEFINITE: { base: 'bestimmt' },
  INDEFINITE: { base: 'unbestimmt' },
  ZERO: { base: 'artikellos' },
  PROXIMAL: { base: 'proximal' },
  DISTAL: { base: 'distal' },
  PARTITIVE: { base: 'partitiv' },
  NEGATIVE: { base: 'negativ' },
  MULTAL: { base: 'multal' },
  PAUCAL: { base: 'paukal' },
  UNIVERSAL: { base: 'universal' },
  DISTRIBUTIVE: { base: 'distributiv' },
  EXHAUSTIVE: { base: 'exhaustiv' },
  DUAL: { base: 'dual' },
  PROPORTIONAL: { base: 'proportional' },
  MULTIPLE: { base: 'mehrfach' },
  SUFFICIENT: { base: 'usreichend' },
  APPROXIMATE: { base: 'ungfähr' },
  SIMILATIVE: { base: 'similativ' },
  FIRST: { base: 'erscht', ordinal: '1' },
  SECOND: { base: 'zweit', ordinal: '1' },
  THIRD: { base: 'dritt', ordinal: '1' },
  NEXT: { base: 'nächscht' },
  PREVIOUS: { base: 'vorig' }, // vorherig → vorig
  LAST_FINAL: { base: 'letscht', ordinal: '1' },
  LAST_PREVIOUS: { base: 'letscht', ordinal: '1' },
  NEXT_COMING: { base: 'nächscht', ordinal: '1' },
  SAME: { base: 'gliich' },
  DIFFERENT: { base: 'verschide' },
  SURE: { base: 'sicher' },
  REAL_EXISTING: { base: 'würklich' },
  REAL_GENUINE: { base: 'echt' },
  AMERICAN: { base: 'amerikanisch' },
  RIGHT_CORRECT: { base: 'richtig' },
  RIGHT_SIDE: { base: 'rächt' },
  IMPERSONAL: { base: 'unpersönlich' },
  OTHER: { base: 'ander', after_pronoun: 'ander' },
  OPPOSITE: { base: 'entgägegsetzt' },
  MAIN: { base: 'übergordnet' },
  CONDITIONAL: { base: 'konditional' },
  COORDINATED: { base: 'biigordnet' },
  SUBORDINATE: { base: 'undergordnet' },
  COPULATIVE: { base: 'kopulativ' },
  DISJUNCTIVE: { base: 'disjunktiv' },
  ADVERSATIVE: { base: 'adversativ' },
  EXPLICATIVE: { base: 'explikativ' },
  CONCLUSIVE: { base: 'konklusiv' },
  TEMPORAL: { base: 'temporal' },
  SPATIAL: { base: 'rüümlich' },
  NATIONAL: { base: 'national' },
  SOCIAL: { base: 'sozial' },
  POLITICAL: { base: 'politisch' },
  PUBLIC: { base: 'öffentlich' },
  NEUTRAL: { base: 'neutral' },
  ACTIVE_VOICE: { base: 'aktiv' },
  PASSIVE: { base: 'passiv' },
  HUMBLE_GRAMMAR: { base: 'bescheide' },
  PROGRESSIVE: { base: 'progressiv' },
  PROSPECTIVE: { base: 'prospektiv' },
  RESULTATIVE: { base: 'resultativ' },
  POSITIVE: { base: 'positiv' },
  SEMANTIC: { base: 'semantisch' },
  DIRECT: { base: 'direkt' },
  INDIRECT: { base: 'indirekt' },
  UNCONNECTED: { base: 'unverbunde' },
  HIDDEN: { base: 'usbländet' },
  CLOSED: { base: 'gschlosse' },
  OPEN_ADJECTIVE: { base: 'offe' },
  VISIBLE: { base: 'sichtbar' },
  SWEET: { base: 'süess' },
  SOLID: { base: 'fescht' },
  PRESENT: { base: 'gägewärtig' },
  PAST: { base: 'vergange' },
  FUTURE: { base: 'zuekünftig' },
  OWN_ADJECTIVE: { base: 'eige' },
  SOLE: { base: 'einzig' },
  STANDARD: { base: 'normiert' },
  MANIFOLD: { base: 'mehrfach' },
};
