import type { GswColumn } from './types.js';

export const GSW_NOUNS_3: GswColumn = {
  // Grössi, plural Grössene: the Zürich -i abstract (verify)
  STANDARD_OF_COMPARISON: { base: 'Vergliichsgrössi', plural: 'Vergliichsgrössene', gender: 'fem', count: 'singular' },
  COMPARISON_SET: { base: 'Vergliichsmängi', plural: 'Vergliichsmängene', gender: 'fem', count: 'singular' }, // (verify)
  MODAL: { base: 'Modalverb', plural: 'Modalverbe', gender: 'neut', count: 'singular' },
  COMMAND: { base: 'Befehl', plural: 'Befehl', gender: 'masc', count: 'singular', compound: 'Befehls' },
  ORDER: { base: 'Befehl', plural: 'Befehl', gender: 'masc', count: 'singular', compound: 'Befehls' },
  INSTRUCTION: { base: 'Aawiisig', plural: 'Aawiisige', gender: 'fem', count: 'singular' },
  REGISTER: { base: 'Register', plural: 'Register', gender: 'neut', count: 'singular' },
  FORMALITY: { base: 'Förmlichkeit', gender: 'fem', count: 'singular' },
  OPTION: { base: 'Option', plural: 'Optione', gender: 'fem', count: 'singular' },
  // de Taste; Zürich presses a Chnopf (a control, not a keyboard key)
  BUTTON: { base: 'Chnopf', plural: 'Chnöpf', gender: 'masc', count: 'singular' },
  KEYBOARD: { base: 'Tastatur', plural: 'Tastature', gender: 'fem', count: 'singular' },
  KEY: { base: 'Taste', plural: 'Taste', gender: 'fem', count: 'singular', compound: 'Taste' },
  ARROW: { base: 'Pfiiltaste', plural: 'Pfiiltaste', gender: 'fem', count: 'singular', compound: 'Pfiiltaste' },
  REGION: { base: 'Beriich', plural: 'Beriich', gender: 'masc', count: 'singular', compound: 'Beriichs' },
  GROUP: { base: 'Gruppe', plural: 'Gruppe', gender: 'fem', count: 'singular', compound: 'Gruppe' },
  MEMBER: { base: 'Mitglied', plural: 'Mitglider', gender: 'neut', count: 'singular', compound: 'Mitglider' },
  PARTY_CELEBRATION: { base: 'Fäst', plural: 'Fäst', gender: 'neut', count: 'singular' },
  ROW: { base: 'Ziile', plural: 'Ziile', gender: 'fem', count: 'singular', compound: 'Ziile' },
  MENU: { base: 'Menü', plural: 'Menüs', gender: 'neut', count: 'singular', compound: 'Menü' },
  TAB: { base: 'Tab', plural: 'Tabs', gender: 'masc', count: 'singular', compound: 'Tab' },
  TARGET: { base: 'Ziil', plural: 'Ziil', gender: 'neut', count: 'singular', compound: 'Ziil' },
  HELP: { base: 'Hilf', gender: 'fem', count: 'singular', compound: 'Hilf' },
  NAVIGATION: { base: 'Navigation', gender: 'fem', count: 'singular', compound: 'Navigations' },
  NAME_NOUN: { base: 'Name', plural: 'Näme', gender: 'masc', count: 'singular', compound: 'Namens' },
  ALIAS: { base: 'Alias', plural: 'Aliasse', gender: 'masc', count: 'singular' },
  TITLE: { base: 'Titel', plural: 'Titel', gender: 'masc', count: 'singular' },
  LOADING: { base: 'Lade', gender: 'neut', count: 'singular', compound: 'Lade' },
  INTERFACE: { base: 'Interface', plural: 'Interfaces', gender: 'neut', count: 'singular' },
  SERVER: { base: 'Server', plural: 'Server', gender: 'masc', count: 'singular' },
  // de Ergebnis; Swiss usage prefers Resultat
  RESULT: { base: 'Resultat', plural: 'Resultat', gender: 'neut', count: 'singular' },
  IMPORT_NOUN: { base: 'Import', plural: 'Importe', gender: 'masc', count: 'singular' },
  ICON: { base: 'Symbol', plural: 'Symbol', gender: 'neut', count: 'singular' },
  FILE: { base: 'Datei', plural: 'Dateie', gender: 'fem', count: 'singular' },
  CLIPBOARD: {
    base: 'Zwüscheablaag', plural: 'Zwüscheablaage', gender: 'fem', count: 'singular', compound: 'Zwüscheablaag', // (verify)
  },
  LINE: { base: 'Ziile', plural: 'Ziile', gender: 'fem', count: 'singular', compound: 'Ziile' },
  HISTORY: { base: 'Verlauf', gender: 'masc', count: 'singular', compound: 'Verlaufs' },
  WORKSPACE: { base: 'Arbetsberiich', plural: 'Arbetsberiich', gender: 'masc', count: 'singular', compound: 'Arbetsberiichs' },
  USAGE: { base: 'Verwändig', gender: 'fem', count: 'singular', compound: 'Verwändigs' },
  EXAMPLE: { base: 'Biispiil', plural: 'Biispiil', gender: 'neut', count: 'singular', compound: 'Biispiil' },
  CONSOLE: { base: 'Konsole', plural: 'Konsole', gender: 'fem', count: 'singular', compound: 'Konsole' },
  CANVAS: {
    base: 'Arbetsflächi', plural: 'Arbetsflächene', gender: 'fem', count: 'singular', compound: 'Arbetsflächi', // (verify)
  },
  PREVIEW: { base: 'Vorschau', plural: 'Vorschaue', gender: 'fem', count: 'singular', compound: 'Vorschau' },
  // Leiste < MHG lîste, so Liiste (verify)
  TOOLBAR: { base: 'Symbolliiste', plural: 'Symbolliiste', gender: 'fem', count: 'singular', compound: 'Symbolliiste' },
  LIST: { base: 'Liste', plural: 'Liste', gender: 'fem', count: 'singular', compound: 'Liste' },
  VALUE: { base: 'Wärt', plural: 'Wärt', gender: 'masc', count: 'singular', compound: 'Wärt' },
  CURSOR: { base: 'Cursor', plural: 'Cursor', gender: 'masc', count: 'singular', compound: 'Cursor' },
  TEXT: { base: 'Text', plural: 'Text', gender: 'masc', count: 'singular', compound: 'Text' },
  REFERENCE: { base: 'Verwiis', plural: 'Verwiis', gender: 'masc', count: 'singular', compound: 'Verwiis' },
  CAUSE: { base: 'Ursach', plural: 'Ursache', gender: 'fem', count: 'singular' },
  POSSESSOR: {
    base: 'Bsitzer', plural: 'Bsitzer', gender: 'masc', count: 'singular', fem: 'Bsitzerin', fem_plural: 'Bsitzerinne',
  },
  PROPERTY: { base: 'Bsitz', gender: 'masc', count: 'singular' },
  FEATURE: { base: 'Märkmaal', plural: 'Märkmaal', gender: 'neut', count: 'singular', compound: 'Märkmaals' },
  DOMAIN: { base: 'Gebiet', plural: 'Gebiet', gender: 'neut', count: 'singular', compound: 'Gebiets' },
  MEANS: { base: 'Mittel', plural: 'Mittel', gender: 'neut', count: 'singular' },
  PURPOSE: { base: 'Zwäck', plural: 'Zwäck', gender: 'masc', count: 'singular' },
  USE_NOUN: { base: 'Verwändig', plural: 'Verwändige', gender: 'fem', count: 'singular' },
  WORK_NOUN: { base: 'Arbet', gender: 'fem', count: 'singular' },
  RESEARCH: { base: 'Forschig', gender: 'fem', count: 'singular' },
  STUDY_NOUN: { base: 'Studie', plural: 'Studie', gender: 'fem', count: 'singular' },
  MATERIAL: { base: 'Material', plural: 'Materialie', gender: 'neut', count: 'singular' },
  WOOD: { base: 'Holz', gender: 'neut', count: 'singular' },
  LEVEL: { base: 'Ebeni', plural: 'Ebene', gender: 'fem', count: 'singular', compound: 'Ebene' }, // (verify)
  PROCESS: { base: 'Prozess', plural: 'Prozess', gender: 'masc', count: 'singular' },
  CHANGE_NOUN: { base: 'Änderig', plural: 'Änderige', gender: 'fem', count: 'singular' },
  SYSTEM: { base: 'System', plural: 'System', gender: 'neut', count: 'singular' },
  PROGRAM_SOFTWARE: { base: 'Programm', plural: 'Programm', gender: 'neut', count: 'singular' },
  PROGRAM_SHOW: { base: 'Sändig', plural: 'Sändige', gender: 'fem', count: 'singular' },
  CONCEPT: { base: 'Begriff', plural: 'Begriff', gender: 'masc', count: 'singular', compound: 'Begriffs' },
  IDEA: { base: 'Idee', plural: 'Idee', gender: 'fem', count: 'singular' },
  ACTION: { base: 'Handlig', plural: 'Handlige', gender: 'fem', count: 'singular' },
  GAME: { base: 'Spiil', plural: 'Spiil', gender: 'neut', count: 'singular' },
  OBJECT_THING: { base: 'Gägestand', plural: 'Gägeständ', gender: 'masc', count: 'singular', compound: 'Gägestands' },
  THING: { base: 'Ding', plural: 'Ding', gender: 'neut', count: 'singular' },
  PROBLEM: { base: 'Problem', plural: 'Problem', gender: 'neut', count: 'singular' },
  ISSUE: { base: 'Fraag', plural: 'Frage', gender: 'fem', count: 'singular' },
  CASE_INSTANCE: { base: 'Fall', plural: 'Fäll', gender: 'masc', count: 'singular' },
  BEING: { base: 'Wääse', plural: 'Wääse', gender: 'neut', count: 'singular' }, // (verify)
  BODY: { base: 'Körper', plural: 'Körper', gender: 'masc', count: 'singular' },
  ORGAN: { base: 'Organ', plural: 'Organ', gender: 'neut', count: 'singular' },
  TESTICLE: { base: 'Hode', plural: 'Hode', gender: 'masc', count: 'singular' },
  OVARY: { base: 'Eierstock', plural: 'Eierstöck', gender: 'masc', count: 'singular' },
  MILK: { base: 'Milch', gender: 'fem', count: 'singular' },
  GRASS: { base: 'Gras', gender: 'neut', count: 'singular' },
  HEAT: { base: 'Hitz', gender: 'fem', count: 'singular', compound: 'Hitz' },
  EYE: { base: 'Aug', plural: 'Auge', gender: 'neut', count: 'singular', compound: 'Auge' },
  HAND: { base: 'Hand', plural: 'Händ', gender: 'fem', count: 'singular' },
  HEAD: { base: 'Chopf', plural: 'Chöpf', gender: 'masc', count: 'singular' },
  FACE: { base: 'Gsicht', plural: 'Gsichter', gender: 'neut', count: 'singular' },
  BACK_BODY: { base: 'Rugge', plural: 'Rugge', gender: 'masc', count: 'singular' },
  HEALTH: { base: 'Gsundheit', gender: 'fem', count: 'singular' },
  STORY: { base: 'Gschicht', plural: 'Gschichte', gender: 'fem', count: 'singular' },
  HISTORY_PAST: { base: 'Gschicht', gender: 'fem', count: 'singular' },
  NEWS: { base: 'Nachrichte', gender: 'fem', count: 'plural' },
  SUBSTANCE: { base: 'Stoff', gender: 'masc', count: 'singular' },
  STATE: { base: 'Zuestand', plural: 'Zueständ', gender: 'masc', count: 'singular', compound: 'Zuestands' },
  GAS: { base: 'Gas', gender: 'neut', count: 'singular' },
  JOY: { base: 'Freud', gender: 'fem', count: 'singular' },
  SORROW: { base: 'Truur', gender: 'fem', count: 'singular' },
  ERROR: { base: 'Fehler', plural: 'Fehler', gender: 'masc', count: 'singular' },
  REALITY: { base: 'Wirklichkeit', plural: 'Wirklichkeite', gender: 'fem', count: 'singular' },
  REST: { base: 'Rueh', gender: 'fem', count: 'singular', compound: 'Rueh' },
  ATTENTION: { base: 'Ufmerksamkeit', gender: 'fem', count: 'singular' },
  ABILITY: { base: 'Fähigkeit', plural: 'Fähigkeite', gender: 'fem', count: 'singular' },
  DUTY: { base: 'Pflicht', plural: 'Pflichte', gender: 'fem', count: 'singular' },
  KINDNESS: { base: 'Fründlichkeit', gender: 'fem', count: 'singular' },
  LAND: { base: 'Land', gender: 'neut', count: 'singular' },
  NATION: { base: 'Nation', plural: 'Natione', gender: 'fem', count: 'singular' },
  SCHOOL: { base: 'Schuel', plural: 'Schuele', gender: 'fem', count: 'singular', compound: 'Schuel' },
  STUDENT: {
    base: 'Student', plural: 'Studente', gender: 'masc', count: 'singular', fem: 'Studentin', fem_plural: 'Studentinne',
  },
  COMPANY_BUSINESS: { base: 'Firma', plural: 'Firme', gender: 'fem', count: 'singular', compound: 'Firme' },
  TEAM: { base: 'Mannschaft', plural: 'Mannschafte', gender: 'fem', count: 'singular' },
  COMMUNITY: { base: 'Gmeinschaft', plural: 'Gmeinschafte', gender: 'fem', count: 'singular' },
  UNIVERSITY: { base: 'Universität', plural: 'Universitäte', gender: 'fem', count: 'singular' },
  SERVICE: { base: 'Dienst', plural: 'Dienst', gender: 'masc', count: 'singular' },
  BUSINESS: { base: 'Handel', gender: 'masc', count: 'singular', compound: 'Handels' },
  STATE_NATION: { base: 'Staat', plural: 'Staate', gender: 'masc', count: 'singular', compound: 'Staats' },
  POWER: { base: 'Macht', plural: 'Mächt', gender: 'fem', count: 'singular' },
  GOVERNMENT: { base: 'Regierig', plural: 'Regierige', gender: 'fem', count: 'singular' },
  PARTY_POLITICAL: { base: 'Partei', plural: 'Parteie', gender: 'fem', count: 'singular' },
  LAW: { base: 'Gsetz', plural: 'Gsetz', gender: 'neut', count: 'singular', compound: 'Gsetzes' },
  COURT_LAW: { base: 'Gricht', plural: 'Gricht', gender: 'neut', count: 'singular', compound: 'Grichts' },
  RIGHT_NOUN: { base: 'Rächt', plural: 'Rächt', gender: 'neut', count: 'singular', compound: 'Rächts' },
  WAR: { base: 'Chrieg', plural: 'Chrieg', gender: 'masc', count: 'singular', compound: 'Chriegs' },
  WORLD: { base: 'Wält', plural: 'Wälte', gender: 'fem', count: 'singular' },
  PICTURE: { base: 'Bild', plural: 'Bilder', gender: 'neut', count: 'singular' },
  SCREEN: { base: 'Bildschirm', plural: 'Bildschirm', gender: 'masc', count: 'singular' },
  PART: { base: 'Teil', plural: 'Teil', gender: 'masc', count: 'singular' },
};
