import type { GswColumn } from './types.js';

export const GSW_NOUNS_2: GswColumn = {
  PHRASE: { base: 'Phrase', plural: 'Phrase', gender: 'fem', count: 'singular' },
  SLOT: { base: 'Schlitz', plural: 'Schlitz', gender: 'masc', count: 'singular' },
  SLOT_COMPUTING: { base: 'Slot', plural: 'Slots', gender: 'masc', count: 'singular' },
  SLOT_MACHINE: { base: 'Spiilautomat', plural: 'Spiilautomate', gender: 'masc', count: 'singular' },
  WORD: { base: 'Wort', plural: 'Wörter', gender: 'neut', count: 'singular' },
  MEANING: { base: 'Bedüütig', plural: 'Bedüütige', gender: 'fem', count: 'singular' },
  FACT: { base: 'Tatsach', plural: 'Tatsache', gender: 'fem', count: 'singular' },
  REASON: { base: 'Grund', plural: 'Gründ', gender: 'masc', count: 'singular' },
  INFORMATION: { base: 'Information', gender: 'fem', count: 'singular' },
  PROBABILITY: { base: 'Wahrschiinlichkeit', plural: 'Wahrschiinlichkeite', gender: 'fem', count: 'singular' },
  TRANSLATION: { base: 'Übersetzig', plural: 'Übersetzige', gender: 'fem', count: 'singular' },
  QUESTION: { base: 'Frag', plural: 'Frage', gender: 'fem', count: 'singular' },
  TELEPHONE: { base: 'Telefon', plural: 'Telefon', gender: 'neut', count: 'singular' },
  MIND: { base: 'Verstand', plural: 'Verständ', gender: 'masc', count: 'singular' },
  CONTINENT: { base: 'Kontinent', plural: 'Kontinent', gender: 'masc', count: 'singular' },
  AFRICA: { base: 'Afrika', gender: 'neut', count: 'singular' },
  // Swiss German articles a person's name, as Portuguese does: "de Peter chunt", "em Dieth sini
  // Rächtschriibig" (verify, E14).
  PETER: { base: 'Peter', gender: 'masc', count: 'singular', takes_article: '1' },
  MARY: { base: 'Maria', gender: 'fem', count: 'singular', takes_article: '1' },
  DIETH: { base: 'Dieth', gender: 'masc', count: 'singular', takes_article: '1' },
  MR: { base: 'Herr', plural: 'Herre', gender: 'masc', count: 'singular' },
  EUROPE: { base: 'Europa', gender: 'neut', count: 'singular' },
  ASIA: { base: 'Asie', gender: 'neut', count: 'singular' },
  OCEANIA: { base: 'Ozeanie', gender: 'neut', count: 'singular' },
  NORTH_AMERICA: { base: 'Nordamerika', gender: 'neut', count: 'singular' },
  SOUTH_AMERICA: { base: 'Süüdamerika', gender: 'neut', count: 'singular' }, // long ü doubled (verify)
  ANTARCTICA: { base: 'Antarktis', gender: 'fem', count: 'singular', takes_article: '1' },
  COUNTRY: { base: 'Land', plural: 'Länder', gender: 'neut', count: 'singular', compound: 'Landes' },
  CITY: { base: 'Stadt', plural: 'Städt', gender: 'fem', count: 'singular' },
  ENGLAND: { base: 'Ängland', gender: 'neut', count: 'singular' },
  ITALY: { base: 'Italie', gender: 'neut', count: 'singular' },
  FRANCE: { base: 'Frankriich', gender: 'neut', count: 'singular' },
  GERMANY: { base: 'Tüütschland', gender: 'neut', count: 'singular' },
  SPAIN: { base: 'Spanie', gender: 'neut', count: 'singular' },
  JAPAN: { base: 'Japan', gender: 'neut', count: 'singular' },
  PORTUGAL: { base: 'Portugal', gender: 'neut', count: 'singular' },
  ZURICH: { base: 'Züri', gender: 'neut', count: 'singular' },
  LANGUAGE: { base: 'Spraach', plural: 'Spraache', gender: 'fem', count: 'singular', compound: 'Spraach' },
  ENGLISH: { base: 'Änglisch', gender: 'neut', count: 'singular' },
  ITALIAN: { base: 'Italiänisch', gender: 'neut', count: 'singular' },
  FRENCH: { base: 'Französisch', gender: 'neut', count: 'singular' },
  GERMAN: { base: 'Tüütsch', gender: 'neut', count: 'singular' },
  SPANISH: { base: 'Spanisch', gender: 'neut', count: 'singular' },
  JAPANESE: { base: 'Japanisch', gender: 'neut', count: 'singular' },
  PORTUGUESE: { base: 'Portugiisisch', gender: 'neut', count: 'singular' },
  SWISS_GERMAN: { base: 'Schwiizerdütsch', gender: 'neut', count: 'singular' },
  SPELLING: { base: 'Rächtschriibig', plural: 'Rächtschriibige', gender: 'fem', count: 'singular' },
  PERIOD_TIME: { base: 'Ziitruum', plural: 'Ziitrüüm', gender: 'masc', count: 'singular' },
  MOMENT: { base: 'Augeblick', plural: 'Augeblick', gender: 'masc', count: 'singular' },
  DAY: { base: 'Tag', plural: 'Täg', gender: 'masc', count: 'singular', temporal_prep: 'a' },
  HOUR: { base: 'Stund', plural: 'Stunde', gender: 'fem', count: 'singular' },
  MINUTE: { base: 'Minute', plural: 'Minute', gender: 'fem', count: 'singular' },
  MONTH: { base: 'Monet', plural: 'Monet', gender: 'masc', count: 'singular', temporal_prep: 'i' },
  WEEK: { base: 'Wuche', plural: 'Wuche', gender: 'fem', count: 'singular', temporal_prep: 'i' },
  NIGHT: { base: 'Nacht', plural: 'Nächt', gender: 'fem', count: 'singular' },
  MORNING: { base: 'Morge', plural: 'Morge', gender: 'masc', count: 'singular', temporal_prep: 'a' },
  YEAR: { base: 'Jaar', plural: 'Jaar', gender: 'neut', count: 'singular', temporal_prep: 'i' },
  PARTICIPANT_GRAMMAR: { base: 'Partizipant', plural: 'Partizipante', gender: 'masc', count: 'singular' },
  AGENT_GRAMMAR: { base: 'Agens', plural: 'Agentie', gender: 'neut', count: 'singular' },
  SUBJECT_GRAMMAR: { base: 'Subjekt', plural: 'Subjekt', gender: 'neut', count: 'singular' },
  VOCATIVE: { base: 'Aarede', plural: 'Aarede', gender: 'fem', count: 'singular' },
  OBJECT_GRAMMAR: { base: 'Objekt', plural: 'Objekt', gender: 'neut', count: 'singular' },
  SUBJECT_COMPLEMENT: { base: 'Prädikativ', plural: 'Prädikativ', gender: 'neut', count: 'singular' },
  OBJECT_COMPLEMENT: { base: 'Objektsprädikativ', plural: 'Objektsprädikativ', gender: 'neut', count: 'singular' },
  INSTRUMENTAL: { base: 'Instrumental', plural: 'Instrumental', gender: 'masc', count: 'singular' },
  COMITATIVE: { base: 'Komitativ', plural: 'Komitativ', gender: 'masc', count: 'singular' },
  // no genitive: the German genitive postnominals become vo + dative
  ADVERBIAL_OF_MANNER: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vo de Art und Wiis',
    citation: 'adverbiali Bestimmig vo de Art und Wiis', gender: 'fem', count: 'singular',
  },
  COMPLEMENT_GRAMMAR: { base: 'Ergänzig', plural: 'Ergänzige', gender: 'fem', count: 'singular' },
  LOCATIVE: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vom Ort',
    citation: 'adverbiali Bestimmig vom Ort', gender: 'fem', count: 'singular',
  },
  DIRECTION: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vo de Richtig',
    citation: 'adverbiali Bestimmig vo de Richtig', gender: 'fem', count: 'singular',
  },
  SOURCE: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vo de Herkunft',
    citation: 'adverbiali Bestimmig vo de Herkunft', gender: 'fem', count: 'singular',
  },
  ROUTE: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vom Wäg',
    citation: 'adverbiali Bestimmig vom Wäg', gender: 'fem', count: 'singular',
  },
  CAUSE_COMPLEMENT: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vom Grund',
    citation: 'adverbiali Bestimmig vom Grund', gender: 'fem', count: 'singular',
  },
  TEMPORAL_COMPLEMENT: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vo de Ziit',
    citation: 'adverbiali Bestimmig vo de Ziit', gender: 'fem', count: 'singular',
  },
  PURPOSE_COMPLEMENT: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vom Zwäck',
    citation: 'adverbiali Bestimmig vom Zwäck', gender: 'fem', count: 'singular',
  },
  OPPONENT_COMPLEMENT: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vom Gägner',
    citation: 'adverbiali Bestimmig vom Gägner', gender: 'fem', count: 'singular',
  },
  TOPIC_COMPLEMENT: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vom Thema',
    citation: 'adverbiali Bestimmig vom Thema', gender: 'fem', count: 'singular',
  },
  ROLE_COMPLEMENT: {
    base: 'Bestimmig', plural: 'Bestimmige', adjective: 'adverbial', postnominal: 'vo de Rolle',
    citation: 'adverbiali Bestimmig vo de Rolle', gender: 'fem', count: 'singular',
  },
  INTERJECTION: { base: 'Interjektion', plural: 'Interjektione', gender: 'fem', count: 'singular' },
  TERMINUS: { base: 'Dativobjekt', plural: 'Dativobjekt', gender: 'neut', count: 'singular' },
  NOUN: { base: 'Substantiv', plural: 'Substantiv', gender: 'neut', count: 'singular' },
  PRONOUN: { base: 'Pronome', plural: 'Pronome', gender: 'neut', count: 'singular' },
  VERB: { base: 'Verb', plural: 'Verbe', gender: 'neut', count: 'singular' },
  ADVERB: { base: 'Adverb', plural: 'Adverbie', gender: 'neut', count: 'singular' },
  ADJECTIVE: { base: 'Adjektiv', plural: 'Adjektiv', gender: 'neut', count: 'singular' },
  INFINITIVE_PHRASE: { base: 'Infinitivphrase', plural: 'Infinitivphrase', gender: 'fem', count: 'singular' },
  VERB_PHRASE: { base: 'Verbalphrase', plural: 'Verbalphrase', gender: 'fem', count: 'singular' },
  NOUN_PHRASE: {
    base: 'Nominalphrase', plural: 'Nominalphrase', gender: 'fem', count: 'singular', compound: 'Nominalphrase',
  },
  CLAUSE: { base: 'Satz', plural: 'Sätz', gender: 'masc', count: 'singular' },
  RELATIVE_CLAUSE: { base: 'Relativsatz', plural: 'Relativsätz', gender: 'masc', count: 'singular' },
  STATEMENT: { base: 'Uussagsatz', plural: 'Uussagsätz', gender: 'masc', count: 'singular' }, // Uussag (verify)
  CONDITION: { base: 'Bedingig', plural: 'Bedingige', gender: 'fem', count: 'singular' },
  COORDINATION: { base: 'Koordination', plural: 'Koordinatione', gender: 'fem', count: 'singular' },
  CONJUNCT: { base: 'Konjunkt', plural: 'Konjunkt', gender: 'neut', count: 'singular' },
  CONJUNCTION: { base: 'Konjunktion', plural: 'Konjunktione', gender: 'fem', count: 'singular' },
  MODIFIER: { base: 'Modifikator', plural: 'Modifikatore', gender: 'masc', count: 'singular' },
  HYPERNYM: { base: 'Hyperonym', plural: 'Hyperonym', gender: 'neut', count: 'singular' },
  DETERMINER: { base: 'Determinativ', plural: 'Determinativ', gender: 'neut', count: 'singular' },
  ARTICLE: { base: 'Artikel', plural: 'Artikel', gender: 'masc', count: 'singular' },
  DEMONSTRATIVE: {
    base: 'Demonstrativum', plural: 'Demonstrativa', gender: 'neut', count: 'singular', compound: 'Demonstrativ',
  },
  QUANTIFIER: { base: 'Quantor', plural: 'Quantore', gender: 'masc', count: 'singular', compound: 'Quantore' },
  PERIOD_SENTENCE: { base: 'Satzgfüeg', plural: 'Satzgfüeg', gender: 'neut', count: 'singular' },
  PERIOD_PUNCTUATION: { base: 'Punkt', plural: 'Pünkt', gender: 'masc', count: 'singular' },
  // native Klammer: initial k → ch
  BRACKET: { base: 'Chlammere', plural: 'Chlammere', gender: 'fem', count: 'singular', compound: 'Chlammer' },
  CONTAINER: { base: 'Behälter', plural: 'Behälter', gender: 'masc', count: 'singular' },
  MAP: { base: 'Charte', plural: 'Charte', gender: 'fem', count: 'singular' },
  NODE: { base: 'Chnopf', plural: 'Chnöpf', gender: 'masc', count: 'singular' }, // Zürich knot word, not Knoten (verify)
  RELATIONSHIP: { base: 'Beziehig', plural: 'Beziehige', gender: 'fem', count: 'singular' },
  PERSON_GRAMMAR: { base: 'Person', plural: 'Persone', gender: 'fem', count: 'singular', compound: 'Personal' },
  NUMBER: { base: 'Zaal', plural: 'Zaale', gender: 'fem', count: 'singular', compound: 'Zaale' },
  NUMBER_LABEL: { base: 'Nummere', plural: 'Nummere', gender: 'fem', count: 'singular' },
  QUANTITY: { base: 'Mängi', plural: 'Mängene', gender: 'fem', count: 'singular' }, // plural (verify)
  PERCENT: { base: 'Prozent', plural: 'Prozent', gender: 'neut', count: 'singular' },
  CATEGORY: { base: 'Kategorie', plural: 'Kategorie', gender: 'fem', count: 'singular' },
  KIND_SORT: { base: 'Art', plural: 'Arte', gender: 'fem', count: 'singular' },
  NUMBER_GRAMMAR: { base: 'Numerus', plural: 'Numeri', gender: 'masc', count: 'singular' },
  SINGULAR_GRAMMAR: { base: 'Singular', plural: 'Singular', gender: 'masc', count: 'singular' },
  PLURAL_GRAMMAR: { base: 'Plural', plural: 'Plural', gender: 'masc', count: 'singular' },
  CASE_GRAMMAR: { base: 'Fall', plural: 'Fäll', gender: 'masc', count: 'singular' },
  DATIVE: { base: 'Dativ', plural: 'Dativ', gender: 'masc', count: 'singular' },
  GENITIVE: { base: 'Genitiv', plural: 'Genitiv', gender: 'masc', count: 'singular' },
  GENDER: { base: 'Gschlächt', plural: 'Gschlächter', gender: 'neut', count: 'singular', compound: 'Gschlächts' },
  TENSE: { base: 'Tempus', plural: 'Tempora', gender: 'neut', count: 'singular' },
  PRESENT_TENSE: { base: 'Präsens', plural: 'Präsentia', gender: 'neut', count: 'singular' },
  PAST_TENSE: { base: 'Präteritum', plural: 'Präterita', gender: 'neut', count: 'singular', compound: 'Präteritum' },
  FUTURE_TENSE: { base: 'Futur', plural: 'Future', gender: 'neut', count: 'singular' },
  ASPECT: { base: 'Aspekt', plural: 'Aspekt', gender: 'masc', count: 'singular' },
  VOICE: { base: 'Diathese', plural: 'Diathese', gender: 'fem', count: 'singular' },
  POLARITY: { base: 'Polarität', plural: 'Polaritäte', gender: 'fem', count: 'singular' },
  SENTIMENT: { base: 'Bewärtig', plural: 'Bewärtige', gender: 'fem', count: 'singular' },
  MOOD: { base: 'Modus', plural: 'Modi', gender: 'masc', count: 'singular' },
  DEGREE_GRAMMAR: { base: 'Steigerigsstufe', plural: 'Steigerigsstufe', gender: 'fem', count: 'singular' },
  POSITIVE_DEGREE: { base: 'Positiv', plural: 'Positiv', gender: 'masc', count: 'singular' },
};
