import type { LanguageColumn } from '../types.js';

// The adjectives, each with its four agreeing forms stored — masculine and feminine, singular and
// plural — since Rumantsch Grischun's are not all derivable (*vegl, veglia*; *ault, auta*;
// *pitschen, pitschna*; *pussaivel, pussaivla*). Written out, never computed by the engine.
// `position: 'pre'` marks the ones that normally precede the noun (*in bun di*, *l'auter giat*);
// the rest follow it (verify the list, P04-E7).
type Forms = Record<string, string>;
const a = (base: string, fem: string, masc_plural: string, fem_plural: string, extra: Forms = {}): Forms => ({
  base, fem, masc_plural, fem_plural, ...extra,
});
/** A word or phrase that does not inflect (*standard*, *senza titel*). */
const inv = (base: string, extra: Forms = {}): Forms => a(base, base, base, base, extra);
const PRE = { position: 'pre' };

export const RM_RUMGR_ADJECTIVES: LanguageColumn = {
  BIG: a('grond', 'gronda', 'gronds', 'grondas', PRE),
  SMALL: a('pitschen', 'pitschna', 'pitschens', 'pitschnas', PRE),
  HIGH: a('ault', 'auta', 'auts', 'autas'),
  LONG: a('lung', 'lunga', 'lungs', 'lungas'),
  GREAT: a('grond', 'gronda', 'gronds', 'grondas', PRE),
  LOW: a('bass', 'bassa', 'bass', 'bassas'), // (verify) no plural -s after -ss
  NEAR: a('vischin', 'vischina', 'vischins', 'vischinas'),
  FAR: a('lontan', 'lontana', 'lontans', 'lontanas'),
  GOOD: a('bun', 'buna', 'buns', 'bunas', { ...PRE, content_clause_mood: 'subjunctive' }),
  BAD: a('nausch', 'nauscha', 'nauschs', 'nauschas'),
  HAPPY: a('led', 'leda', 'leds', 'ledas'), // (verify) led vs cuntent
  // *jau stun bain*: the adverb, invariable, after *star* as Italian *sto bene*.
  OKAY: inv('bain', { copula: 'BE_FARING' }),
  SAD: a('trist', 'trista', 'trists', 'tristas'),
  OLD: a('vegl', 'veglia', 'vegls', 'veglias', PRE),
  YOUNG: a('giuven', 'giuvna', 'giuvens', 'giuvnas', PRE),
  // The comparative of *vegl*, *giuven*: *il frar pli vegl*, *la sora pli giuvna* (verify).
  ELDER: a('pli vegl', 'pli veglia', 'pli vegls', 'pli veglias'),
  YOUNGER: a('pli giuven', 'pli giuvna', 'pli giuvens', 'pli giuvnas'),
  ADULT: a('creschì', 'creschida', 'creschids', 'creschidas'),
  MALE: a('masculin', 'masculina', 'masculins', 'masculinas'),
  FEMALE: a('feminin', 'feminina', 'feminins', 'femininas'),
  CASTRATED: a('castrà', 'castrada', 'castrads', 'castradas'),
  NEW: a('nov', 'nova', 'novs', 'novas'),
  BEAUTIFUL: a('bel', 'bella', 'bels', 'bellas', PRE),
  STRONG: a('ferm', 'ferma', 'ferms', 'fermas'),
  WEAK: a('flaivel', 'flaivla', 'flaivels', 'flaivlas'),
  TIRED: a('stanchel', 'stancla', 'stanchels', 'stanclas'), // (verify)
  HUNGRY: a('fomentà', 'fomentada', 'fomentads', 'fomentadas'), // (verify)
  COLD: a('fraid', 'fraida', 'fraids', 'fraidas'),
  COLD_CLIMATE: a('fraid', 'fraida', 'fraids', 'fraidas'),
  WARM: a('cordial', 'cordiala', 'cordials', 'cordialas'),
  HOT: a('chaud', 'chauda', 'chauds', 'chaudas'),
  HOT_CLIMATE: a('chaud', 'chauda', 'chauds', 'chaudas'),
  INTERESTING: a('interessant', 'interessanta', 'interessants', 'interessantas'),
  IMPORTANT: a('impurtant', 'impurtanta', 'impurtants', 'impurtantas'),
  QUICK: a('spert', 'sperta', 'sperts', 'spertas'),
  BROWN: a('brin', 'brina', 'brins', 'brinas'),
  BLACK: a('nair', 'naira', 'nairs', 'nairas'),
  WHITE: a('alv', 'alva', 'alvs', 'alvas'),
  DARK: a('stgir', 'stgira', 'stgirs', 'stgiras'),
  WILD: a('selvadi', 'selvadia', 'selvadis', 'selvadias'),
  DOMESTIC: a('dumestg', 'dumestga', 'dumestgs', 'dumestgas'), // (verify)
  CANINE: a('canin', 'canina', 'canins', 'caninas'),
  LAZY: a('marschlent', 'marschlenta', 'marschlents', 'marschlentas'), // (verify)
  CAREFUL: a('attent', 'attenta', 'attents', 'attentas'),
  POSSIBLE: a('pussaivel', 'pussaivla', 'pussaivels', 'pussaivlas', { content_clause_mood: 'subjunctive' }),
  ABLE: a('abel', 'abla', 'abels', 'ablas', { infinitive_link: 'da' }),
  OBLIGED: a('obligà', 'obligada', 'obligads', 'obligadas', { infinitive_link: 'da' }),
  ALLOWED: a('lubì', 'lubida', 'lubids', 'lubidas', { infinitive_link: 'da' }),
  WHOLE: a('entir', 'entira', 'entirs', 'entiras'),
  ROUND: a('radund', 'radunda', 'radunds', 'radundas'),
  SHARP: a('agid', 'agida', 'agids', 'agidas'), // (verify)
  LOUD: a('ferm', 'ferma', 'ferms', 'fermas'),
  WRITTEN: a('scrit', 'scritta', 'scrits', 'scrittas'),
  LOADED: a('chargià', 'chargiada', 'chargiads', 'chargiadas'),
  TIDY: a('urdinà', 'urdinada', 'urdinads', 'urdinadas'),
  SAVED: a('memorisà', 'memorisada', 'memorisads', 'memorisadas'), // (verify) the computing sense
  ADDED: a('agiuntà', 'agiuntada', 'agiuntads', 'agiuntadas'),
  REMOVED: a('allontanà', 'allontanada', 'allontanads', 'allontanadas'), // (verify)
  FAILED: a('fallì', 'fallida', 'fallids', 'fallidas'),
  COPIED: a('copià', 'copiada', 'copiads', 'copiadas'),
  LINKED: a('collià', 'colliada', 'colliads', 'colliadas'),
  PINNED: a('fixà', 'fixada', 'fixads', 'fixadas'),
  UNPINNED: a('betg pli fixà', 'betg pli fixada', 'betg pli fixads', 'betg pli fixadas'),
  RECENT: a('recent', 'recenta', 'recents', 'recentas'),
  NUMBERED: a('numerà', 'numerada', 'numerads', 'numeradas'),
  ACTIVE: a('activ', 'activa', 'activs', 'activas'),
  UNTITLED: inv('senza titel'),
  EMPTY: a('vid', 'vida', 'vids', 'vidas'),
  VALID: a('valaivel', 'valaivla', 'valaivels', 'valaivlas'),
  MISSING: a('mancant', 'mancanta', 'mancants', 'mancantas'),
  UNKNOWN: a('nunenconuschent', 'nunenconuschenta', 'nunenconuschents', 'nunenconuschentas'),
  KNOWN: a('enconuschent', 'enconuschenta', 'enconuschents', 'enconuschentas'),
  UNEXPECTED: a('nunspetgà', 'nunspetgada', 'nunspetgads', 'nunspetgadas'),
  SINGULAR: a('singular', 'singulara', 'singulars', 'singularas'),
  PLURAL: a('plural', 'plurala', 'plurals', 'pluralas'),
  NEUTER: a('neutrum', 'neutra', 'neutrums', 'neutras'), // (verify) the grammar term
  DEFINITE: a('definì', 'definida', 'definids', 'definidas'),
  INDEFINITE: a('indefinì', 'indefinida', 'indefinids', 'indefinidas'),
  ZERO: inv('zero'),
  PROXIMAL: a('proximal', 'proximala', 'proximals', 'proximalas'),
  DISTAL: a('distal', 'distala', 'distals', 'distalas'),
  PARTITIVE: a('partitiv', 'partitiva', 'partitivs', 'partitivas'),
  NEGATIVE: a('negativ', 'negativa', 'negativs', 'negativas'),
  MULTAL: a('multal', 'multala', 'multals', 'multalas'),
  PAUCAL: a('paucal', 'paucala', 'paucals', 'paucalas'),
  UNIVERSAL: a('universal', 'universala', 'universals', 'universalas'),
  DISTRIBUTIVE: a('distributiv', 'distributiva', 'distributivs', 'distributivas'),
  EXHAUSTIVE: a('exhaustiv', 'exhaustiva', 'exhaustivs', 'exhaustivas'),
  DUAL: a('dual', 'duala', 'duals', 'dualas'),
  PROPORTIONAL: a('proporziunal', 'proporziunala', 'proporziunals', 'proporziunalas'),
  MULTIPLE: a('multipel', 'multipla', 'multipels', 'multiplas'),
  SUFFICIENT: a('suffizient', 'suffizienta', 'suffizients', 'suffizientas'),
  APPROXIMATE: a('approximativ', 'approximativa', 'approximativs', 'approximativas'),
  SIMILATIVE: a('similativ', 'similativa', 'similativs', 'similativas'),
  FIRST: a('emprim', 'emprima', 'emprims', 'emprimas', PRE),
  SECOND: a('segund', 'segunda', 'segunds', 'segundas', PRE),
  THIRD: a('terz', 'terza', 'terzs', 'terzas', PRE),
  NEXT: a('proxim', 'proxima', 'proxims', 'proximas', PRE),
  PREVIOUS: a('precedent', 'precedenta', 'precedents', 'precedentas'),
  LAST_FINAL: a('ultim', 'ultima', 'ultims', 'ultimas', PRE),
  // After the noun, of a period: *l'emna passada*, *l'onn proxim* (verify).
  LAST_PREVIOUS: a('passà', 'passada', 'passads', 'passadas'),
  NEXT_COMING: a('proxim', 'proxima', 'proxims', 'proximas'),
  SAME: a('medem', 'medema', 'medems', 'medemas', { ...PRE, predicate_article: '1' }),
  DIFFERENT: a('different', 'differenta', 'differents', 'differentas'),
  SURE: a('segir', 'segira', 'segirs', 'segiras'),
  REAL_EXISTING: a('real', 'reala', 'reals', 'realas'),
  REAL_GENUINE: a('vair', 'vaira', 'vairs', 'vairas', PRE),
  AMERICAN: a('american', 'americana', 'americans', 'americanas'),
  RIGHT_CORRECT: a('correct', 'correcta', 'corrects', 'correctas', { content_clause_mood: 'subjunctive' }),
  RIGHT_SIDE: a('dretg', 'dretga', 'dretgs', 'dretgas'),
  IMPERSONAL: a('impersunal', 'impersunala', 'impersunals', 'impersunalas'),
  OTHER: a('auter', 'autra', 'auters', 'autras', { ...PRE, after_pronoun: 'auter' }),
  OPPOSITE: a('cuntrari', 'cuntraria', 'cuntraris', 'cuntrarias'),
  MAIN: a('principal', 'principala', 'principals', 'principalas'),
  CONDITIONAL: a('condiziunal', 'condiziunala', 'condiziunals', 'condiziunalas'),
  COORDINATED: a('coordinà', 'coordinada', 'coordinads', 'coordinadas'),
  SUBORDINATE: a('subordinà', 'subordinada', 'subordinads', 'subordinadas'),
  COPULATIVE: a('copulativ', 'copulativa', 'copulativs', 'copulativas'),
  DISJUNCTIVE: a('disjunctiv', 'disjunctiva', 'disjunctivs', 'disjunctivas'),
  ADVERSATIVE: a('adversativ', 'adversativa', 'adversativs', 'adversativas'),
  EXPLICATIVE: a('explicativ', 'explicativa', 'explicativs', 'explicativas'),
  CONCLUSIVE: a('conclusiv', 'conclusiva', 'conclusivs', 'conclusivas'),
  TEMPORAL: a('temporal', 'temporala', 'temporals', 'temporalas'),
  SPATIAL: a('spazial', 'spaziala', 'spazials', 'spazialas'),
  NATIONAL: a('naziunal', 'naziunala', 'naziunals', 'naziunalas'),
  SOCIAL: a('social', 'sociala', 'socials', 'socialas'),
  POLITICAL: a('politic', 'politica', 'politics', 'politicas'),
  PUBLIC: a('public', 'publica', 'publics', 'publicas'),
  NEUTRAL: a('neutral', 'neutrala', 'neutrals', 'neutralas'),
  ACTIVE_VOICE: a('activ', 'activa', 'activs', 'activas'),
  PASSIVE: a('passiv', 'passiva', 'passivs', 'passivas'),
  HUMBLE_GRAMMAR: a('umil', 'umila', 'umils', 'umilas'),
  PROGRESSIVE: a('progressiv', 'progressiva', 'progressivs', 'progressivas'),
  PROSPECTIVE: a('prospectiv', 'prospectiva', 'prospectivs', 'prospectivas'),
  RESULTATIVE: a('resultativ', 'resultativa', 'resultativs', 'resultativas'),
  POSITIVE: a('positiv', 'positiva', 'positivs', 'positivas'),
  SEMANTIC: a('semantic', 'semantica', 'semantics', 'semanticas'),
  DIRECT: a('direct', 'directa', 'directs', 'directas'),
  INDIRECT: a('indirect', 'indirecta', 'indirects', 'indirectas'),
  UNCONNECTED: a('betg collià', 'betg colliada', 'betg colliads', 'betg colliadas'), // (verify)
  HIDDEN: a('zuppà', 'zuppada', 'zuppads', 'zuppadas'),
  CLOSED: a('serrà', 'serrada', 'serrads', 'serradas'),
  OPEN_ADJECTIVE: a('avert', 'averta', 'averts', 'avertas'),
  VISIBLE: a('visibel', 'visibla', 'visibels', 'visiblas'),
  SWEET: a('dultsch', 'dultscha', 'dultschs', 'dultschas'),
  SOLID: a('solid', 'solida', 'solids', 'solidas'),
  PRESENT: a('preschent', 'preschenta', 'preschents', 'preschentas'),
  PAST: a('passà', 'passada', 'passads', 'passadas'),
  FUTURE: a('futur', 'futura', 'futurs', 'futuras'),
  // *ses agen cudesch*, *sia agna chasa* (verify).
  OWN_ADJECTIVE: a('agen', 'agna', 'agens', 'agnas', PRE),
  SOLE: a('sulet', 'suletta', 'sulets', 'sulettas', PRE),
  STANDARD: inv('standard'),
  MANIFOLD: a('multifar', 'multifara', 'multifars', 'multifaras'), // (verify)
};
