import type { LanguageColumn } from '../types.js';

// The nouns, keyed as Italian's are: `base`, `plural` where the noun counts, `gender`, `count`, and
// `fem`/`fem_plural` for a person or animal that has a feminine. The plural is mostly `-s` (*giat,
// giats*), with *-à → -ads* (*martgà, martgads*), *-è → -els* (*utschè, utschels*), no ending after
// a final *-s* (*urs, pajais, cas*), and a few irregulars (*um, umens*). *l'* before a vowel is the
// engine's, never stored (P04-E4 D2). Language names are lowercase (P04 §0.5).
type Forms = Record<string, string>;
const noun = (gender: 'masc' | 'fem', base: string, plural?: string, extra: Forms = {}): Forms => ({
  base, ...(plural === undefined ? {} : { plural }), gender, count: 'singular', ...extra,
});
const m = (base: string, plural?: string, extra?: Forms) => noun('masc', base, plural, extra);
const f = (base: string, plural?: string, extra?: Forms) => noun('fem', base, plural, extra);
/** A person or animal noun with its feminine. */
const mf = (base: string, plural: string, fem: string, fem_plural: string, extra: Forms = {}) =>
  m(base, plural, { fem, fem_plural, ...extra });
// Italian's `kinship` (the singular kin noun takes no article after a possessive, *mio padre*) is
// kept as it describes the concept; RG drops the article after every possessive (*mes bab, mia
// chasa*, P04 §2.1), so it changes nothing here.
const KIN = { kinship: '1' };

export const RM_RUMGR_NOUNS: LanguageColumn = {
  ANIMAL: m('animal', 'animals'),
  MAMMAL: m('mammifer', 'mammifers'),
  CAT: mf('giat', 'giats', 'giatta', 'giattas'),
  DOG: mf('chaun', 'chauns', 'chagna', 'chagnas'), // (verify) fem
  BIRD: m('utschè', 'utschels'),
  FISH: m('pesch', 'peschs'),
  REPTILE: m('reptil', 'reptils'),
  AMPHIBIAN: m('amfibi', 'amfibis'),
  INSECT: m('insect', 'insects'),
  HORSE: mf('chaval', 'chavals', 'giumenta', 'giumentas'),
  PIG: m('portg', 'portgs'),
  SHEEP: f('nuorsa', 'nuorsas'),
  GOAT: f('chaura', 'chauras'),
  RABBIT: mf('cunigl', 'cunigls', 'cuniglia', 'cuniglias'),
  BEAR: mf('urs', 'urs', 'ursa', 'ursas'),
  LION: mf('leun', 'leuns', 'leuna', 'leunas'),
  TIGER: m('tiger', 'tigers'), // (verify) gender
  // The felines, seeded on main while P04 was in flight; every form (verify).
  FELINE: m('felin', 'felins'),
  LEOPARD: m('leopard', 'leopards'),
  PANTHER: f('pantera', 'panteras'),
  PUMA: m('puma', 'pumas'),
  CHEETAH: m('gepard', 'gepards'), // from German Gepard, as RG's animal names often are (verify)
  ELEPHANT: mf('elefant', 'elefants', 'elefanta', 'elefantas'),
  MONKEY: f('schimgia', 'schimgias'),
  DEER: m('tschierv', 'tschiervs'),
  WHALE: f('balena', 'balenas'),
  CHICKEN: f('gaglina', 'gaglinas'),
  DUCK: f('anda', 'andas'),
  EAGLE: f('evla', 'evlas'),
  OWL: f('tschuetta', 'tschuettas'), // (verify)
  PENGUIN: m('pinguin', 'pinguins'),
  SEAGULL: f('muetta', 'muettas'), // (verify)
  SWALLOW: f('randulina', 'randulinas'), // (verify)
  PARROT: m('papagagl', 'papagagls'), // (verify)
  SHARK: m('squal', 'squals'), // (verify)
  SALMON: m('salm', 'salms'),
  SNAKE: m('serp', 'serps'), // (verify) gender
  TURTLE: f('tartaruga', 'tartarugas'), // (verify)
  CROCODILE: m('crocodil', 'crocodils'),
  LIZARD: m('luschard', 'luschards'), // (verify)
  FROG: f('rauna', 'raunas'),
  BEE: m('avieul', 'avieuls'), // (verify)
  ANT: f('furmicla', 'furmiclas'),
  BUTTERFLY: f('tgiralla', 'tgirallas'),
  MOSQUITO: m('mustgin', 'mustgins'), // (verify)
  SPIDER: m('filien', 'filiens'), // (verify)
  BOOK: m('cudesch', 'cudeschs'),
  AIR: f('aria'),
  GROUND: m('terren', 'terrens'),
  WATER: f('aua'),
  SPEED: f('sveltezza', 'sveltezzas'),
  LIGHT: f('glisch', 'glischs'),
  SOUND: m('tun', 'tuns'),
  // Feminine where Italian *modo* is masculine: *en quella moda*.
  WAY: f('moda', 'modas'),
  TIME: m('temp', 'temps'),
  CARE: f('chira'),
  SIZE: f('grondezza', 'grondezzas'),
  HEIGHT: f('autezza', 'autezzas'),
  LENGTH: f('lunghezza', 'lunghezzas'),
  QUALITY: f('qualitad', 'qualitads'),
  STRENGTH: f('forza', 'forzas'),
  AGE: f('vegliadetgna', 'vegliadetgnas'),
  TEMPERATURE: f('temperatura', 'temperaturas'),
  DISTANCE: f('distanza', 'distanzas'),
  SHAPE: f('furma', 'furmas'),
  CIRCLE: m('circul', 'circuls'),
  LINE_MARK: f('lingia', 'lingias'),
  // *ils daners*: a plural-only noun, as Italian stores *le notizie* (NEWS).
  MONEY: m('daners', undefined, { count: 'plural' }),
  FOOD: f('vivonda'),
  ICE_CREAM: f('glatscha', 'glatschas'),
  SUGAR: m('zutger'),
  LIQUID: m('liquid'),
  CONTENT: m('cuntegn', 'cuntegns'),
  PLACE: m('lieu', 'lieus'),
  POINT_NOUN: m('punct', 'puncts'),
  AREA: f('zona', 'zonas'),
  CENTER: m('center', 'centers'),
  SIDE: f('vart', 'varts'),
  DESTINATION: f('destinaziun', 'destinaziuns'),
  ORIGIN: f('origin', 'origins'),
  PATH: m('percurs', 'percurs'),
  DIRECTION_SPACE: f('direcziun', 'direcziuns'),
  BUILDING: m('edifizi', 'edifizis'),
  WALL: m('mir', 'mirs'),
  HOUSE: f('chasa', 'chasas'),
  HOME: f('chasa', 'chasas'),
  ROOM: f('stanza', 'stanzas'),
  OFFICE: m('biro', 'biros'),
  DOOR: m('isch', 'ischs'),
  CAR: m('auto', 'autos'),
  CHILD: mf('uffant', 'uffants', 'uffant', 'uffants'), // (verify) one form for a girl too
  KID: mf('mattet', 'mattets', 'mattetta', 'mattettas'), // (verify)
  PERSON: f('persuna', 'persunas'),
  SPEAKER: mf('pledader', 'pledaders', 'pledadra', 'pledadras'), // (verify)
  COMPANION: mf('cumpogn', 'cumpogns', 'cumpogna', 'cumpognas'),
  RECIPIENT: mf('destinatari', 'destinataris', 'destinataria', 'destinatarias'),
  FOX: f('vulp', 'vulps'),
  BOY: m('mat', 'mats'),
  GIRL: f('matta', 'mattas'),
  MAN: m('um', 'umens'),
  GUY: m('tip', 'tips'),
  WOMAN: f('dunna', 'dunnas'),
  WOLF: mf('luf', 'lufs', 'lufa', 'lufas'), // (verify) fem
  BOVINE: m('bovin', 'bovins'),
  COW: f('vatga', 'vatgas'),
  OX: m('bov', 'bovs'),
  BUTCHER: mf('mazler', 'mazlers', 'mazlera', 'mazleras'),
  ANGEL: m('aunghel', 'aunghels'),
  LIFE: f('vita', 'vitas'),
  END: f('fin', 'fins'),
  BEGINNING: f('entschatta', 'entschattas'),
  DEATH: f('mort', 'morts'),
  FEELING: m('sentiment', 'sentiments'),
  AFFECTION: f('affecziun'),
  MOUSE: f('mieur', 'mieurs'),
  FLY_INSECT: f('mustga', 'mustgas'),
  STICK: m('bastun', 'bastuns'),
  ARROW_PROJECTILE: f('frizza', 'frizzas'),
  BLADE: f('lama', 'lamas'),
  FIRE: m('fieu', 'fieus'),
  FLAME: f('flomma', 'flommas'),
  PARENT: mf('genitur', 'geniturs', 'genitura', 'genituras'), // (verify)
  FATHER: m('bab', 'babs', KIN),
  RELATIVE: mf('parent', 'parents', 'parenta', 'parentas'),
  FAMILY: f('famiglia', 'famiglias'),
  MOTHER: f('mamma', 'mammas', KIN),
  CHILD_OFFSPRING: mf('figl', 'figls', 'figlia', 'figlias', KIN),
  SON: m('figl', 'figls', KIN),
  DAUGHTER: f('figlia', 'figlias', KIN),
  SIBLING: mf('frar', 'frars', 'sora', 'soras', KIN),
  BROTHER: m('frar', 'frars', KIN),
  SISTER: f('sora', 'soras', KIN),
  SPOUSE: mf('consort', 'consorts', 'consorta', 'consortas'), // (verify)
  HUSBAND: m('marid', 'marids', KIN),
  WIFE: f('muglier', 'mugliers', KIN),
  GRANDPARENT: mf('tat', 'tats', 'tatta', 'tattas', KIN),
  GRANDFATHER: m('tat', 'tats', KIN),
  GRANDMOTHER: f('tatta', 'tattas', KIN),
  GRANDCHILD: mf('abiadi', 'abiadis', 'abiadia', 'abiadias', KIN),
  GRANDSON: m('abiadi', 'abiadis', KIN),
  GRANDDAUGHTER: f('abiadia', 'abiadias', KIN),
  UNCLE: m('barba', 'barbas', KIN), // (verify) barba vs aug
  AUNT: f('onda', 'ondas', KIN),
  COUSIN: mf('cusrin', 'cusrins', 'cusrina', 'cusrinas', KIN),
  NEPHEW: m('nevs', 'nevs', KIN),
  NIECE: f('neza', 'nezas', KIN),
  MOTHER_IN_LAW: f('sira', 'siras', KIN),
  FATHER_IN_LAW: m('sir', 'sirs', KIN),
  SON_IN_LAW: m('schender', 'schenders', KIN),
  DAUGHTER_IN_LAW: f('brit', 'brits', KIN), // (verify)
  BROTHER_IN_LAW: m('quinà', 'quinads', KIN),
  SISTER_IN_LAW: f('quinada', 'quinadas', KIN),
  STEPFATHER: m('padraster', 'padrasters'),
  STEPMOTHER: f('madrastra', 'madrastras'),
  MOM: f('mamma', 'mammas'),
  DAD: m('papa', 'papas'),
  PARTNER: mf('partenari', 'partenaris', 'partenaria', 'partenarias'),
  BOYFRIEND: m('ami', 'amis'), // (verify)
  GIRLFRIEND: f('amia', 'amias'), // (verify)
  FIANCE: mf('spus', 'spus', 'spusa', 'spusas'),
  FRIEND: mf('ami', 'amis', 'amia', 'amias'),
  MARKET: m('martgà', 'martgads'),
  COIN: f('munaida', 'munaidas'),
  LEGEND: f('legenda', 'legendas'),
  WING: f('ala', 'alas'),
  TOOTH: m('dent', 'dents'),
  TEAR: f('larma', 'larmas'),
  YOUNG_MAN: m('giuven', 'giuvens'),
  YOUNG_WOMAN: f('giuvna', 'giuvnas'),
  PRISON: f('praschun', 'praschuns'),
  BUILDER: mf('constructur', 'constructurs', 'constructura', 'constructuras'),
  CREATOR: mf('creatur', 'creaturs', 'creatura', 'creaturas'),
  PHRASE: f('frasa', 'frasas'),
  SLOT: f('fessa', 'fessas'), // (verify)
  SLOT_COMPUTING: m('slot', 'slots'), // (verify)
  SLOT_MACHINE: f('maschina da gieu', 'maschinas da gieu'), // (verify)
  WORD: m('pled', 'pleds'),
  MEANING: f('significaziun', 'significaziuns'),
  FACT: m('fatg', 'fatgs'),
  REASON: m('motiv', 'motivs'),
  INFORMATION: f('infurmaziun'),
  PROBABILITY: f('probabilitad', 'probabilitads'),
  TRANSLATION: f('translaziun', 'translaziuns'),
  QUESTION: f('dumonda', 'dumondas'),
  TELEPHONE: m('telefon', 'telefons'),
  MIND: m('spiert', 'spierts'),
  CONTINENT: m('continent', 'continents'),
  AFRICA: f('Africa'),
  // Personal names without the article in writing, as Italian's (verify).
  PETER: m('Peder', undefined, { takes_article: '0' }),
  MARY: f('Maria', undefined, { takes_article: '0' }),
  DIETH: m('Dieth', undefined, { takes_article: '0' }),
  MR: m('signur', 'signurs', { before_name: 'signur', takes_article: '1' }), // (verify) il signur Caduff
  EUROPE: f('Europa'),
  ASIA: f('Asia'),
  OCEANIA: f('Oceania'),
  NORTH_AMERICA: f('America dal Nord'),
  SOUTH_AMERICA: f('America dal Sid'),
  ANTARCTICA: f('Antarctica'), // (verify)
  COUNTRY: m('pajais', 'pajais'),
  CITY: f('citad', 'citads'),
  ENGLAND: f('Engalterra'),
  ITALY: f('Italia'),
  FRANCE: f('Frantscha'),
  GERMANY: f('Germania'),
  SPAIN: f('Spagna'),
  JAPAN: m('Giapun'),
  PORTUGAL: m('Portugal'),
  ZURICH: m('Turitg', undefined, { takes_article: '0' }), // (verify) gender
  LANGUAGE: f('lingua', 'linguas'),
  ENGLISH: m('englais'),
  ITALIAN: m('talian'),
  FRENCH: m('franzos'),
  GERMAN: m('tudestg'),
  SPANISH: m('spagnol'),
  JAPANESE: m('giapunais'),
  PORTUGUESE: m('portugais'),
  SWISS_GERMAN: m('tudestg svizzer'),
  ROMANSH: m('rumantsch'),
  CATALAN: m('catalan'),
  POLISH: m('polac'), // (verify)
  RUMANTSCH_GRISCHUN: m('rumantsch grischun'),
  SURSILVAN: m('sursilvan'),
  VALLADER: m('vallader'),
  SPELLING: f('ortografia', 'ortografias'),
  PERIOD_TIME: f('perioda', 'periodas'),
  MOMENT: m('mument', 'muments'),
  // `temporal_prep` as Italian's *in* (verify: RG may say the time bare, *quest di*).
  DAY: m('di', 'dis', { temporal_prep: 'en' }),
  HOUR: f('ura', 'uras'),
  MINUTE: f('minuta', 'minutas'),
  MONTH: m('mais', 'mais', { temporal_prep: 'en' }),
  WEEK: f('emna', 'emnas', { temporal_prep: 'en' }),
  NIGHT: f('notg', 'notgs'),
  MORNING: f('damaun', 'damauns', { temporal_bare: '1' }),
  YEAR: m('onn', 'onns', { temporal_prep: 'en' }),

  // Grammar terms. *cumplement* (verify the spelling: *cumplement* or *complement*).
  PARTICIPANT_GRAMMAR: m('participant', 'participants'),
  AGENT_GRAMMAR: m('agent', 'agents'),
  SUBJECT_GRAMMAR: m('subject', 'subjects'),
  VOCATIVE: m('vocativ', 'vocativs'),
  OBJECT_GRAMMAR: m('object', 'objects'),
  SUBJECT_COMPLEMENT: m('cumplement predicativ dal subject', 'cumplements predicativs dal subject'),
  OBJECT_COMPLEMENT: m("cumplement predicativ da l'object", "cumplements predicativs da l'object"),
  INSTRUMENTAL: m('cumplement dal med', 'cumplements dal med'),
  COMITATIVE: m('cumplement da cumpagnia', 'cumplements da cumpagnia'),
  ADVERBIAL_OF_MANNER: m('cumplement da moda', 'cumplements da moda'),
  COMPLEMENT_GRAMMAR: m('cumplement', 'cumplements'),
  LOCATIVE: m('cumplement da lieu', 'cumplements da lieu'),
  DIRECTION: m('cumplement da direcziun', 'cumplements da direcziun'),
  SOURCE: m('cumplement da provegnientscha', 'cumplements da provegnientscha'),
  ROUTE: m('cumplement da percurs', 'cumplements da percurs'),
  CAUSE_COMPLEMENT: m('cumplement da chaschun', 'cumplements da chaschun'),
  TEMPORAL_COMPLEMENT: m('cumplement da temp', 'cumplements da temp'),
  PURPOSE_COMPLEMENT: m('cumplement da finamira', 'cumplements da finamira'),
  OPPONENT_COMPLEMENT: m('cumplement da dischavantatg', 'cumplements da dischavantatg'),
  TOPIC_COMPLEMENT: m("cumplement d'argument", "cumplements d'argument"),
  ROLE_COMPLEMENT: m('cumplement da rolla', 'cumplements da rolla'),
  INTERJECTION: f('interjecziun', 'interjecziuns'),
  TERMINUS: m('cumplement da termin', 'cumplements da termin'),
  NOUN: m('substantiv', 'substantivs'),
  PRONOUN: m('pronom', 'pronoms'),
  VERB: m('verb', 'verbs'),
  ADVERB: m('adverb', 'adverbs'),
  ADJECTIVE: m('adjectiv', 'adjectivs'),
  INFINITIVE_PHRASE: f('frasa infinitiva', 'frasas infinitivas'),
  VERB_PHRASE: m('sintagma verbal', 'sintagmas verbals'),
  NOUN_PHRASE: m('sintagma nominal', 'sintagmas nominals'),
  CLAUSE: f('proposiziun', 'proposiziuns'),
  RELATIVE_CLAUSE: f('proposiziun relativa', 'proposiziuns relativas'),
  STATEMENT: f('proposiziun enunciativa', 'proposiziuns enunciativas'),
  CONDITION: f('cundiziun', 'cundiziuns'),
  COORDINATION: f('coordinaziun', 'coordinaziuns'),
  CONJUNCT: m('conjunct', 'conjuncts'),
  CONJUNCTION: f('conjuncziun', 'conjuncziuns'),
  MODIFIER: m('modificatur', 'modificaturs'),
  HYPERNYM: m('iperonim', 'iperonims'),
  DETERMINER: m('determinant', 'determinants'),
  ARTICLE: m('artitgel', 'artitgels'),
  DEMONSTRATIVE: m('demonstrativ', 'demonstrativs'),
  QUANTIFIER: m('quantificatur', 'quantificaturs'),
  PERIOD_SENTENCE: f('perioda', 'periodas'),
  PERIOD_PUNCTUATION: m('punct', 'puncts'),
  BRACKET: f('parentesa', 'parentesas'),
  CONTAINER: m('recipient', 'recipients'), // (verify)
  MAP: f('charta', 'chartas'),
  NODE: m('nuf', 'nufs'),
  RELATIONSHIP: f('relaziun', 'relaziuns'),
  PERSON_GRAMMAR: f('persuna', 'persunas'),
  NUMBER: m('numer', 'numers'),
  NUMBER_LABEL: m('numer', 'numers'),
  QUANTITY: f('quantitad', 'quantitads'),
  UNIT: f('unitad', 'unitads'),
  PERCENT: m('pertschient', 'pertschient'),
  CATEGORY: f('categoria', 'categorias'),
  KIND_SORT: f('sort', 'sorts'),
  NUMBER_GRAMMAR: m('numer', 'numers'),
  SINGULAR_GRAMMAR: m('singular', 'singulars'),
  PLURAL_GRAMMAR: m('plural', 'plurals'),
  CASE_GRAMMAR: m('cas', 'cas'),
  DATIVE: m('dativ', 'dativs'),
  GENITIVE: m('genitiv', 'genitivs'),
  GENDER: m('gener', 'geners'),
  TENSE: m('temp', 'temps'),
  PRESENT_TENSE: m('preschent', 'preschents'),
  PAST_TENSE: m('passà', 'passads'),
  FUTURE_TENSE: m('futur', 'futurs'),
  ASPECT: m('aspect', 'aspects'),
  VOICE: f('diatesa', 'diatesas'), // (verify)
  POLARITY: f('polaritad', 'polaritads'),
  SENTIMENT: f('valitaziun', 'valitaziuns'), // (verify)
  MOOD: m('modus', 'modus'),
  DEGREE_GRAMMAR: m('grad', 'grads'),
  POSITIVE_DEGREE: m('grad positiv', 'grads positivs'),
  STANDARD_OF_COMPARISON: m('term da cumparegliaziun', 'terms da cumparegliaziun'), // (verify)
  COMPARISON_SET: f('gruppa da cumparegliaziun', 'gruppas da cumparegliaziun'), // (verify)
  MODAL: m('verb modal', 'verbs modals'),
  COMMAND: m('cumond', 'cumonds'),
  ORDER: f('ordinaziun', 'ordinaziuns'), // (verify)
  INSTRUCTION: f('instrucziun', 'instrucziuns'),
  REGISTER: m('register', 'registers'),
  FORMALITY: f('formalitad'),
  OPTION: f('opziun', 'opziuns'),
  BUTTON: m('buttun', 'buttuns'),
  KEYBOARD: f('tastatura', 'tastaturas'),
  KEY: f('tasta', 'tastas'),
  ARROW: f('frizza', 'frizzas'),
  REGION: f('regiun', 'regiuns'),
  GROUP: f('gruppa', 'gruppas'),
  MEMBER: m('commember', 'commembers'),
  PARTY_CELEBRATION: f('festa', 'festas'),
  ROW: f('lingia', 'lingias'),
  MENU: m('menu', 'menus'),
  TAB: m('tab', 'tabs'), // (verify)
  TARGET: f('destinaziun', 'destinaziuns'),
  HELP: m('agid'),
  NAVIGATION: f('navigaziun'),
  NAME_NOUN: m('num', 'nums'),
  ALIAS: m('alias', 'alias'),
  TITLE: m('titel', 'titels'),
  LOADING: f('chargiada'), // (verify)
  INTERFACE: f('interfatscha', 'interfatschas'),
  SERVER: m('server', 'servers'),
  RESULT: m('resultat', 'resultats'),
  IMPORT_NOUN: f('importaziun', 'importaziuns'),
  ICON: f('icona', 'iconas'),
  FILE: f('datoteca', 'datotecas'), // (verify)
  CLIPBOARD: f('memoria intermediara', 'memorias intermediaras'), // (verify)
  LINE: f('lingia', 'lingias'),
  HISTORY: f('cronologia'),
  WORKSPACE: m('spazi da lavur', 'spazis da lavur'),
  USAGE: m('diever'),
  EXAMPLE: m('exempel', 'exempels'),
  CONSOLE: f('consola', 'consolas'),
  CANVAS: f('taila', 'tailas'),
  PREVIEW: f('prevista', 'previstas'), // (verify)
  TOOLBAR: f("barra d'utensils", "barras d'utensils"), // (verify)
  LIST: f('glista', 'glistas'),
  VALUE: f('valur', 'valurs'),
  CURSOR: m('cursur', 'cursurs'),
  TEXT: m('text', 'texts'),
  REFERENCE: f('referenza', 'referenzas'),
  CAUSE: f('chaschun', 'chaschuns'),
  POSSESSOR: mf('possessur', 'possessurs', 'possessura', 'possessuras'),
  PROPERTY: f('proprietad'),
  FEATURE: f('caracteristica', 'caracteristicas'),
  DOMAIN: f('domena', 'domenas'), // (verify)
  MEANS: m('med', 'meds'),
  PURPOSE: f('finamira', 'finamiras'),
  USE_NOUN: m('diever', 'dievers'),
  WORK_NOUN: f('lavur'),
  RESEARCH: f('perscrutaziun'),
  STUDY_NOUN: m('studi', 'studis'),
  MATERIAL: m('material', 'materials'),
  WOOD: m('lain'),
  LEVEL: m('nivel', 'nivels'),
  PROCESS: m('process', 'process'),
  CHANGE_NOUN: f('midada', 'midadas'),
  SYSTEM: m('sistem', 'sistems'),
  PROGRAM_SOFTWARE: m('program', 'programs'),
  PROGRAM_SHOW: f('emissiun', 'emissiuns'),
  CONCEPT: m('concept', 'concepts'),
  IDEA: f('idea', 'ideas'),
  ACTION: f('acziun', 'acziuns'),
  EVENT: m('eveniment', 'eveniments'),
  RACE: f('cursa', 'cursas'),
  GAME: m('gieu', 'gieus'),
  OBJECT_THING: m('object', 'objects'),
  DEVICE: m('apparat', 'apparats'),
  BOMB: f('bomba', 'bombas'),
  THING: f('chaussa', 'chaussas'),
  PROBLEM: m('problem', 'problems'),
  ISSUE: f('questiun', 'questiuns'),
  CASE_INSTANCE: m('cas', 'cas'),
  BEING: m('esser', 'essers'),
  BODY: m('corp', 'corps'),
  ORGAN: m('organ', 'organs'),
  TESTICLE: m('testichel', 'testichels'), // (verify)
  OVARY: m('ovari', 'ovaris'),
  MILK: m('latg'),
  GRASS: f('erva'),
  HEAT: f('chalur'),
  EYE: m('egl', 'egls'),
  // Masculine, where Italian *mano* is feminine: *il maun*.
  HAND: m('maun', 'mauns'),
  HEAD: m('chau', 'chaus'),
  FACE: f('fatscha', 'fatschas'),
  BACK_BODY: m('dies', 'dies'),
  HEALTH: f('sanadad'),
  STORY: f('istorgia', 'istorgias'),
  HISTORY_PAST: f('istorgia'),
  // Plural-only, as Italian's *le notizie*.
  NEWS: f('novitads', undefined, { count: 'plural' }),
  SUBSTANCE: f('substanza'),
  STATE: m('stadi', 'stadis'),
  GAS: m('gas'),
  JOY: f('letezia'),
  SORROW: f('tristezza'),
  ERROR: m('sbagl', 'sbagls'),
  REALITY: f('realitad', 'realitads'),
  REST: m('ruaus'),
  ATTENTION: f('attenziun'),
  ABILITY: f('abilitad', 'abilitads'),
  DUTY: f('obligaziun', 'obligaziuns'),
  KINDNESS: f('curtaschia'),
  WISDOM: f('sabientscha'),
  FOLLY: f('narradad'), // (verify)
  LAND: f('terra'),
  NATION: f('naziun', 'naziuns'),
  SCHOOL: f('scola', 'scolas'),
  STUDENT: mf('student', 'students', 'studenta', 'studentas'),
  COMPANY_BUSINESS: f('interpresa', 'interpresas'),
  TEAM: f('equipa', 'equipas'),
  COMMUNITY: f('communitad', 'communitads'),
  UNIVERSITY: f('universitad', 'universitads'),
  SERVICE: m('servetsch', 'servetschs'),
  BUSINESS: m('commerzi'),
  STATE_NATION: m('stadi', 'stadis'),
  POWER: f('pussanza', 'pussanzas'),
  GOVERNMENT: f('regenza', 'regenzas'),
  PARTY_POLITICAL: f('partida', 'partidas'),
  LAW: f('lescha', 'leschas'),
  COURT_LAW: f('dretgira', 'dretgiras'),
  RIGHT_NOUN: m('dretg', 'dretgs'),
  WAR: f('guerra', 'guerras'),
  WORLD: m('mund', 'munds'),
  PICTURE: m('maletg', 'maletgs'),
  SCREEN: m('visur', 'visurs'), // (verify)
  PART: f('part', 'parts'),
};
