import type { ConceptSeed } from './types.js';

export const adjectives: ConceptSeed[] = [
  // ── ADJECTIVES ───────────────────────────────────────────────────
  {
    id: 'BIG',
    role: 'adjective',
    description: 'large in size',
    emoji: '🔭',
    forms: {
      en: { base: 'big' },
      it: { base: 'grande' },
      fr: { base: 'grand' },
      de: { base: 'groß' },
      es: { base: 'grande' },
      ja: { base: '大きい', reading: 'おおきい' },
      pt: { base: 'grande' },
    },
  },
  {
    id: 'SMALL',
    role: 'adjective',
    description: 'little in size',
    emoji: '🔬',
    forms: {
      en: { base: 'small' },
      it: { base: 'piccolo' },
      fr: { base: 'petit' },
      de: { base: 'klein' },
      es: { base: 'pequeño' },
      ja: { base: '小さい', reading: 'ちいさい' },
      pt: { base: 'pequeno' },
    },
  },
  {
    id: 'GOOD',
    role: 'adjective',
    description: 'of high quality or virtue',
    emoji: '✨',
    forms: {
      en: { base: 'good' },
      it: { base: 'buono' },
      fr: { base: 'bon' },
      de: { base: 'gut' },
      es: { base: 'bueno' },
      ja: { base: '良い', reading: 'よい' },
      pt: { base: 'bom' },
    },
  },
  {
    id: 'BAD',
    role: 'adjective',
    description: 'of poor quality or harmful',
    emoji: '💀',
    forms: {
      en: { base: 'bad' },
      it: { base: 'cattivo' },
      fr: { base: 'mauvais' },
      de: { base: 'schlecht' },
      es: { base: 'malo' },
      ja: { base: '悪い', reading: 'わるい' },
      pt: { base: 'mau' },
    },
  },
  {
    id: 'HAPPY',
    role: 'adjective',
    description: 'feeling or expressing joy',
    emoji: '😊',
    forms: {
      en: { base: 'happy' },
      it: { base: 'felice' },
      fr: { base: 'heureux' },
      de: { base: 'glücklich' },
      es: { base: 'feliz' },
      ja: { base: '幸せな', reading: 'しあわせな' },
      pt: { base: 'feliz' },
    },
  },
  {
    id: 'SAD',
    role: 'adjective',
    description: 'feeling or expressing sorrow',
    emoji: '😢',
    forms: {
      en: { base: 'sad' },
      it: { base: 'triste' },
      fr: { base: 'triste' },
      de: { base: 'traurig' },
      es: { base: 'triste' },
      ja: { base: '悲しい', reading: 'かなしい' },
      pt: { base: 'triste' },
    },
  },
  {
    id: 'OLD',
    role: 'adjective',
    description: 'having existed for a long time',
    emoji: '🧓',
    forms: {
      en: { base: 'old' },
      it: { base: 'vecchio' },
      fr: { base: 'vieux' },
      de: { base: 'alt' },
      es: { base: 'viejo' },
      ja: { base: '古い', reading: 'ふるい' },
      pt: { base: 'velho' },
    },
  },
  {
    id: 'YOUNG',
    role: 'adjective',
    description: 'having lived or existed for a short time',
    emoji: '🧒',
    forms: {
      en: { base: 'young' },
      it: { base: 'giovane' },
      fr: { base: 'jeune' },
      de: { base: 'jung' },
      es: { base: 'joven' },
      ja: { base: '若い', reading: 'わかい' },
      pt: { base: 'jovem' },
    },
  },
  {
    id: 'NEW',
    role: 'adjective',
    description: 'recently made or introduced',
    emoji: '🆕',
    forms: {
      en: { base: 'new' },
      it: { base: 'nuovo' },
      fr: { base: 'nouveau' },
      de: { base: 'neu' },
      es: { base: 'nuevo' },
      ja: { base: '新しい', reading: 'あたらしい' },
      pt: { base: 'novo' },
    },
  },
  {
    id: 'BEAUTIFUL',
    role: 'adjective',
    description: 'pleasing to the senses or mind',
    emoji: '🌸',
    forms: {
      en: { base: 'beautiful' },
      it: { base: 'bello' },
      fr: { base: 'beau' },
      de: { base: 'schön' },
      es: { base: 'hermoso' },
      ja: { base: '美しい', reading: 'うつくしい' },
      pt: { base: 'belo' },
    },
  },
  {
    id: 'STRONG',
    role: 'adjective',
    description: 'having great physical power or force',
    emoji: '💪',
    forms: {
      en: { base: 'strong' },
      it: { base: 'forte' },
      fr: { base: 'fort' },
      de: { base: 'stark' },
      es: { base: 'fuerte' },
      ja: { base: '強い', reading: 'つよい' },
      pt: { base: 'forte' },
    },
  },
  {
    id: 'WEAK',
    role: 'adjective',
    description: 'lacking physical power or force',
    emoji: '🥀',
    forms: {
      en: { base: 'weak' },
      it: { base: 'debole' },
      fr: { base: 'faible' },
      de: { base: 'schwach' },
      es: { base: 'débil' },
      ja: { base: '弱い', reading: 'よわい' },
      pt: { base: 'fraco' },
    },
  },
  {
    id: 'TIRED',
    role: 'adjective',
    description: 'feeling a need to rest or sleep',
    emoji: '😴',
    forms: {
      en: { base: 'tired' },
      it: { base: 'stanco' },
      fr: { base: 'fatigué' },
      de: { base: 'müde' },
      es: { base: 'cansado' },
      ja: { base: '疲れた', reading: 'つかれた' },
      pt: { base: 'cansado' },
    },
  },
  {
    id: 'HUNGRY',
    role: 'adjective',
    description: 'feeling a need to eat',
    emoji: '🤤',
    forms: {
      en: { base: 'hungry' },
      it: { base: 'affamato' },
      fr: { base: 'affamé' },
      de: { base: 'hungrig' },
      es: { base: 'hambriento' },
      ja: { base: '空腹な', reading: 'くうふくな' },
      pt: { base: 'faminto' },
    },
  },
  {
    id: 'COLD',
    role: 'adjective',
    description: 'at a low temperature',
    emoji: '🥶',
    forms: {
      en: { base: 'cold' },
      it: { base: 'freddo' },
      fr: { base: 'froid' },
      de: { base: 'kalt' },
      es: { base: 'frío' },
      ja: { base: '冷たい', reading: 'つめたい' },
      pt: { base: 'frio' },
    },
  },
  {
    id: 'HOT',
    role: 'adjective',
    description: 'at a high temperature',
    emoji: '🔥',
    forms: {
      en: { base: 'hot' },
      it: { base: 'caldo' },
      fr: { base: 'chaud' },
      de: { base: 'heiß' },
      es: { base: 'caliente' },
      ja: { base: '熱い', reading: 'あつい' },
      pt: { base: 'quente' },
    },
  },
  {
    id: 'INTERESTING',
    role: 'adjective',
    description: 'arousing curiosity or attention',
    emoji: '🤔',
    forms: {
      en: { base: 'interesting' },
      it: { base: 'interessante' },
      fr: { base: 'intéressant' },
      de: { base: 'interessant' },
      es: { base: 'interesante' },
      ja: { base: '面白い', reading: 'おもしろい' },
      pt: { base: 'interessante' },
    },
  },
  {
    id: 'QUICK',
    role: 'adjective',
    description: 'moving or capable of moving fast',
    emoji: '⚡',
    forms: {
      en: { base: 'quick' },
      it: { base: 'veloce' },
      fr: { base: 'rapide' },
      de: { base: 'schnell' },
      es: { base: 'rápido' },
      ja: { base: '速い', reading: 'はやい' },
      pt: { base: 'rápido' },
    },
  },
  {
    id: 'BROWN',
    role: 'adjective',
    description: 'of a dark color produced by mixing red, black, and yellow',
    emoji: '🟤',
    forms: {
      en: { base: 'brown' },
      it: { base: 'marrone' },
      fr: { base: 'brun' },
      de: { base: 'braun' },
      es: { base: 'marrón' },
      ja: { base: '茶色', reading: 'ちゃいろ' },
      pt: { base: 'castanho' },
    },
  },
  {
    id: 'LAZY',
    role: 'adjective',
    description: 'unwilling to work or use energy',
    emoji: '🦥',
    forms: {
      en: { base: 'lazy' },
      it: { base: 'pigro' },
      fr: { base: 'paresseux' },
      de: { base: 'faul' },
      es: { base: 'perezoso' },
      ja: { base: '怠惰な', reading: 'たいだな' },
      pt: { base: 'preguiçoso' },
    },
  },
  {
    id: 'CAREFUL',
    role: 'adjective',
    description: 'taking care to avoid harm or mistakes',
    emoji: '⚠️',
    forms: {
      en: { base: 'careful' },
      it: { base: 'attento' },
      fr: { base: 'prudent' },
      de: { base: 'vorsichtig' },
      es: { base: 'cuidadoso' },
      ja: { base: '慎重な', reading: 'しんちょうな' },
      pt: { base: 'cuidadoso' },
    },
  },
];
