import type { ConceptSeed } from './types.js';

export const adjectives: ConceptSeed[] = [
  // ── ADJECTIVES ───────────────────────────────────────────────────
  {
    id: 'BIG',
    role: 'adjective',
    description: 'large in size',
    emoji: '🔭',
    forms: {
      en: { base: 'big' },
      it: { base: 'grande' },
      fr: { base: 'grand' },
      // groß umlauts in the comparative (größer, via the flag) but its superlative is
      // irregular — größt, with no epenthetic -e- a -ß stem would otherwise take.
      de: { base: 'groß', umlaut: 'true', superlative: 'größt' },
      es: { base: 'grande' },
      ja: { base: '大きい', reading: 'おおきい' },
      pt: { base: 'grande' },
    },
  },
  {
    id: 'SMALL',
    role: 'adjective',
    description: 'little in size',
    emoji: '🔬',
    forms: {
      en: { base: 'small' },
      it: { base: 'piccolo' },
      fr: { base: 'petit' },
      de: { base: 'klein' },
      es: { base: 'pequeño' },
      ja: { base: '小さい', reading: 'ちいさい' },
      pt: { base: 'pequeno' },
    },
  },
  {
    id: 'GOOD',
    role: 'adjective',
    description: 'of high quality or virtue',
    emoji: '✨',
    forms: {
      en: { base: 'good' },
      it: { base: 'buono' },
      fr: { base: 'bon' },
      // Suppletive: gut → besser / best, no rule derives it (cf. English good → better).
      de: { base: 'gut', comparative: 'besser', superlative: 'best' },
      es: { base: 'bueno' },
      ja: { base: '良い', reading: 'よい' },
      pt: { base: 'bom' },
    },
  },
  {
    id: 'BAD',
    role: 'adjective',
    description: 'of poor quality or harmful',
    emoji: '💀',
    forms: {
      en: { base: 'bad' },
      it: { base: 'cattivo' },
      fr: { base: 'mauvais' },
      de: { base: 'schlecht' },
      es: { base: 'malo' },
      ja: { base: '悪い', reading: 'わるい' },
      pt: { base: 'mau' },
    },
  },
  {
    id: 'HAPPY',
    role: 'adjective',
    description: 'feeling or expressing joy',
    emoji: '😊',
    forms: {
      en: { base: 'happy' },
      it: { base: 'felice' },
      fr: { base: 'heureux' },
      de: { base: 'glücklich' },
      es: { base: 'feliz' },
      ja: { base: '幸せな', reading: 'しあわせな' },
      pt: { base: 'feliz' },
    },
  },
  {
    id: 'SAD',
    role: 'adjective',
    description: 'feeling or expressing sorrow',
    emoji: '😢',
    forms: {
      en: { base: 'sad' },
      it: { base: 'triste' },
      fr: { base: 'triste' },
      de: { base: 'traurig' },
      es: { base: 'triste' },
      ja: { base: '悲しい', reading: 'かなしい' },
      pt: { base: 'triste' },
    },
  },
  {
    id: 'OLD',
    role: 'adjective',
    description: 'having existed for a long time',
    emoji: '🧓',
    forms: {
      en: { base: 'old' },
      it: { base: 'vecchio' },
      fr: { base: 'vieux' },
      de: { base: 'alt', umlaut: 'true' }, // alt → älter / ältest
      es: { base: 'viejo' },
      ja: { base: '古い', reading: 'ふるい' },
      pt: { base: 'velho' },
    },
  },
  {
    id: 'YOUNG',
    role: 'adjective',
    description: 'having lived or existed for a short time',
    emoji: '🧒',
    forms: {
      en: { base: 'young' },
      it: { base: 'giovane' },
      fr: { base: 'jeune' },
      de: { base: 'jung', umlaut: 'true' }, // jung → jünger / jüngst
      es: { base: 'joven' },
      ja: { base: '若い', reading: 'わかい' },
      pt: { base: 'jovem' },
    },
  },
  {
    // "adult" in the general sense — fully grown — applying to people and animals alike, so
    // Japanese takes the everyday 大人の rather than the human-only, legal 成人の. Noun-adjective (の).
    id: 'ADULT',
    role: 'adjective',
    description: 'fully grown',
    emoji: '🧑',
    forms: {
      en: { base: 'adult' },
      it: { base: 'adulto' },
      fr: { base: 'adulte' },
      de: { base: 'erwachsen' },
      es: { base: 'adulto' },
      ja: { base: '大人の', reading: 'おとなの' },
      pt: { base: 'adulto' },
    },
  },
  {
    id: 'MALE',
    role: 'adjective',
    description: 'of the sex that produces sperm; masculine',
    emoji: '♂️',
    forms: {
      en: { base: 'male' },
      it: { base: 'maschile' },
      fr: { base: 'masculin' },
      de: { base: 'männlich' },
      es: { base: 'masculino' },
      ja: { base: '男性の', reading: 'だんせいの' },
      pt: { base: 'masculino' },
    },
  },
  {
    id: 'FEMALE',
    role: 'adjective',
    description: 'of the sex that bears offspring; feminine',
    emoji: '♀️',
    forms: {
      en: { base: 'female' },
      it: { base: 'femminile' },
      fr: { base: 'féminin' },
      de: { base: 'weiblich' },
      es: { base: 'femenino' },
      ja: { base: '女性の', reading: 'じょせいの' },
      pt: { base: 'feminino' },
    },
  },
  {
    // A past-participle adjective: agrees in Romance (castrato/castrata) and, in Japanese, is
    // verb-derived — the plain past 去勢された attaches directly, like 疲れた (TIRED), no linker.
    id: 'CASTRATED',
    role: 'adjective',
    description: 'having the testicles removed',
    emoji: '✂️',
    forms: {
      en: { base: 'castrated' },
      it: { base: 'castrato' },
      fr: { base: 'castré' },
      de: { base: 'kastriert' },
      es: { base: 'castrado' },
      ja: { base: '去勢された', reading: 'きょせいされた' },
      pt: { base: 'castrado' },
    },
  },
  {
    id: 'NEW',
    role: 'adjective',
    description: 'recently made or introduced',
    emoji: '🆕',
    forms: {
      en: { base: 'new' },
      it: { base: 'nuovo' },
      fr: { base: 'nouveau' },
      de: { base: 'neu' },
      es: { base: 'nuevo' },
      ja: { base: '新しい', reading: 'あたらしい' },
      pt: { base: 'novo' },
    },
  },
  {
    id: 'BEAUTIFUL',
    role: 'adjective',
    description: 'pleasing to the senses or mind',
    emoji: '🌸',
    forms: {
      en: { base: 'beautiful' },
      it: { base: 'bello' },
      fr: { base: 'beau' },
      de: { base: 'schön' },
      es: { base: 'hermoso' },
      ja: { base: '美しい', reading: 'うつくしい' },
      pt: { base: 'belo' },
    },
  },
  {
    id: 'STRONG',
    role: 'adjective',
    description: 'having great physical power or force',
    emoji: '💪',
    forms: {
      en: { base: 'strong' },
      it: { base: 'forte' },
      fr: { base: 'fort' },
      de: { base: 'stark', umlaut: 'true' }, // stark → stärker / stärkst
      es: { base: 'fuerte' },
      ja: { base: '強い', reading: 'つよい' },
      pt: { base: 'forte' },
    },
  },
  {
    id: 'WEAK',
    role: 'adjective',
    description: 'lacking physical power or force',
    emoji: '🥀',
    forms: {
      en: { base: 'weak' },
      it: { base: 'debole' },
      fr: { base: 'faible' },
      de: { base: 'schwach', umlaut: 'true' }, // schwach → schwächer / schwächst
      es: { base: 'débil' },
      ja: { base: '弱い', reading: 'よわい' },
      pt: { base: 'fraco' },
    },
  },
  {
    id: 'TIRED',
    role: 'adjective',
    description: 'feeling a need to rest or sleep',
    emoji: '😴',
    forms: {
      en: { base: 'tired' },
      it: { base: 'stanco' },
      fr: { base: 'fatigué' },
      de: { base: 'müde' },
      es: { base: 'cansado' },
      ja: { base: '疲れた', reading: 'つかれた' },
      pt: { base: 'cansado' },
    },
  },
  {
    id: 'HUNGRY',
    role: 'adjective',
    description: 'feeling a need to eat',
    emoji: '🤤',
    forms: {
      en: { base: 'hungry' },
      it: { base: 'affamato' },
      fr: { base: 'affamé' },
      de: { base: 'hungrig' },
      es: { base: 'hambriento' },
      ja: { base: '空腹な', reading: 'くうふくな' },
      pt: { base: 'faminto' },
    },
  },
  {
    id: 'COLD',
    role: 'adjective',
    description: 'at a low temperature',
    emoji: '🥶',
    forms: {
      en: { base: 'cold' },
      it: { base: 'freddo' },
      fr: { base: 'froid' },
      de: { base: 'kalt', umlaut: 'true' }, // kalt → kälter / kältest
      es: { base: 'frío' },
      ja: { base: '冷たい', reading: 'つめたい' },
      pt: { base: 'frio' },
    },
  },
  {
    id: 'HOT',
    role: 'adjective',
    description: 'at a high temperature',
    emoji: '🔥',
    forms: {
      en: { base: 'hot' },
      it: { base: 'caldo' },
      fr: { base: 'chaud' },
      de: { base: 'heiß' },
      es: { base: 'caliente' },
      ja: { base: '熱い', reading: 'あつい' },
      pt: { base: 'quente' },
    },
  },
  {
    id: 'INTERESTING',
    role: 'adjective',
    description: 'arousing curiosity or attention',
    emoji: '🤔',
    forms: {
      en: { base: 'interesting' },
      it: { base: 'interessante' },
      fr: { base: 'intéressant' },
      de: { base: 'interessant' },
      es: { base: 'interesante' },
      ja: { base: '面白い', reading: 'おもしろい' },
      pt: { base: 'interessante' },
    },
  },
  {
    id: 'QUICK',
    role: 'adjective',
    description: 'moving or capable of moving fast',
    emoji: '⚡',
    forms: {
      en: { base: 'quick' },
      it: { base: 'veloce' },
      fr: { base: 'rapide' },
      de: { base: 'schnell' },
      es: { base: 'rápido' },
      ja: { base: '速い', reading: 'はやい' },
      pt: { base: 'rápido' },
    },
  },
  {
    id: 'BROWN',
    role: 'adjective',
    description: 'of a dark color produced by mixing red, black, and yellow',
    emoji: '🟤',
    forms: {
      en: { base: 'brown' },
      it: { base: 'marrone' },
      fr: { base: 'brun' },
      de: { base: 'braun' },
      es: { base: 'marrón' },
      ja: { base: '茶色の', reading: 'ちゃいろの' },
      pt: { base: 'castanho' },
    },
  },
  {
    id: 'WILD',
    role: 'adjective',
    description: 'living in nature, not tamed',
    emoji: '🌿',
    forms: {
      en: { base: 'wild' },
      it: { base: 'selvatico' },
      fr: { base: 'sauvage' },
      de: { base: 'wild' },
      es: { base: 'salvaje' },
      ja: { base: '野生の', reading: 'やせいの' },
      pt: { base: 'selvagem' },
    },
  },
  {
    // "domestic" in the animal sense — kept by or living with people. German has no plain
    // adjective for it (Haus- is a prefix, Haustier); zahm ("tame") is the standalone adjective
    // that inflects. Japanese 家畜の is specifically livestock, so 家庭の ("of the household").
    id: 'DOMESTIC',
    role: 'adjective',
    description: 'kept by or living with people',
    emoji: '🏠',
    forms: {
      en: { base: 'domestic' },
      it: { base: 'domestico' },
      fr: { base: 'domestique' },
      de: { base: 'zahm' },
      es: { base: 'doméstico' },
      ja: { base: '家庭の', reading: 'かていの' },
      pt: { base: 'doméstico' },
    },
  },
  {
    // "canine" — of or resembling dogs. German Hunde- is a prefix; hundeartig is the adjective.
    id: 'CANINE',
    role: 'adjective',
    description: 'of or resembling dogs',
    emoji: '🐕',
    forms: {
      en: { base: 'canine' },
      it: { base: 'canino' },
      fr: { base: 'canin' },
      de: { base: 'hundeartig' },
      es: { base: 'canino' },
      ja: { base: '犬の', reading: 'いぬの' },
      pt: { base: 'canino' },
    },
  },
  {
    id: 'LAZY',
    role: 'adjective',
    description: 'unwilling to work or use energy',
    emoji: '🦥',
    forms: {
      en: { base: 'lazy' },
      it: { base: 'pigro' },
      fr: { base: 'paresseux' },
      de: { base: 'faul' },
      es: { base: 'perezoso' },
      ja: { base: '怠惰な', reading: 'たいだな' },
      pt: { base: 'preguiçoso' },
    },
  },
  {
    id: 'CAREFUL',
    role: 'adjective',
    description: 'taking care to avoid harm or mistakes',
    emoji: '⚠️',
    forms: {
      en: { base: 'careful' },
      it: { base: 'attento' },
      fr: { base: 'prudent' },
      de: { base: 'vorsichtig' },
      es: { base: 'cuidadoso' },
      ja: { base: '慎重な', reading: 'しんちょうな' },
      pt: { base: 'cuidadoso' },
    },
  },
  {
    id: 'WHOLE',
    role: 'adjective',
    description: 'complete, with no part missing',
    emoji: '⭕',
    forms: {
      en: { base: 'whole' },
      it: { base: 'intero' },
      fr: { base: 'entier' },
      de: { base: 'ganz' },
      es: { base: 'entero' },
      ja: { base: '全体の', reading: 'ぜんたいの' },
      pt: { base: 'inteiro' },
    },
  },
  {
    id: 'LOADED',
    role: 'adjective',
    description: 'brought in from storage and ready to use',
    emoji: '📂',
    forms: {
      en: { base: 'loaded' },
      it: { base: 'caricato' },
      fr: { base: 'chargé' },
      de: { base: 'geladen' },
      es: { base: 'cargado' },
      ja: { base: '読み込み済みの', reading: 'よみこみずみの' },
      pt: { base: 'carregado' },
    },
  },
  {
    id: 'SAVED',
    role: 'adjective',
    description: 'stored so it can be retrieved later',
    emoji: '💾',
    forms: {
      en: { base: 'saved' },
      it: { base: 'salvato' },
      fr: { base: 'enregistré' },
      de: { base: 'gespeichert' },
      es: { base: 'guardado' },
      ja: { base: '保存済みの', reading: 'ほぞんずみの' },
      pt: { base: 'salvo' },
    },
  },
  {
    id: 'SINGULAR',
    role: 'adjective',
    description: 'referring to one (grammar)',
    emoji: '1️⃣',
    forms: {
      en: { base: 'singular' },
      it: { base: 'singolare' },
      fr: { base: 'singulier' },
      de: { base: 'singularisch' },
      es: { base: 'singular' },
      ja: { base: '単数の', reading: 'たんすうの' },
      pt: { base: 'singular' },
    },
  },
  {
    id: 'PLURAL',
    role: 'adjective',
    description: 'referring to more than one (grammar)',
    emoji: '🔢',
    forms: {
      en: { base: 'plural' },
      it: { base: 'plurale' },
      fr: { base: 'pluriel' },
      de: { base: 'pluralisch' },
      es: { base: 'plural' },
      ja: { base: '複数の', reading: 'ふくすうの' },
      pt: { base: 'plural' },
    },
  },
  {
    id: 'NEUTER',
    role: 'adjective',
    description: 'of the gender that is neither masculine nor feminine (grammar)',
    emoji: '⚪',
    forms: {
      en: { base: 'neuter' },
      it: { base: 'neutro' },
      fr: { base: 'neutre' },
      de: { base: 'sächlich' },
      es: { base: 'neutro' },
      ja: { base: '中性の', reading: 'ちゅうせいの' },
      pt: { base: 'neutro' },
    },
  },
  // ── Determiner values ────────────────────────────────────────────
  // What each determiner *means*, as the grammar traditions name it — the entries of the
  // determiner menu, which says "Definite" where it used to say "the". Adjectives, not nouns:
  // each qualifies the noun of the section it sits under (an article that is definite, a
  // demonstrative that is proximal, a quantifier that is universal), so the menu cites them
  // with ARTICLE / DEMONSTRATIVE / QUANTIFIER and the Romance forms come out agreeing —
  // it "articolo determinativo", "quantificatore universale".
  //
  // Japanese has no adjective for these: it names each with the noun the tradition coined
  // (定冠詞, 近称, 全称). Seeded with the の that makes a noun attributive, which ja's renderWord
  // strips when the word stands alone — so the menu shows 定冠詞, not 定冠詞の.
  {
    id: 'DEFINITE',
    role: 'adjective',
    description: 'pointing at a referent the hearer can already identify (grammar)',
    emoji: '🎯',
    forms: {
      en: { base: 'definite' },
      it: { base: 'determinativo' },
      fr: { base: 'défini' },
      de: { base: 'bestimmt' },
      es: { base: 'definido' },
      ja: { base: '定冠詞の', reading: 'ていかんしの' },
      pt: { base: 'definido' },
    },
  },
  {
    id: 'INDEFINITE',
    role: 'adjective',
    description: 'pointing at a referent the hearer cannot yet identify (grammar)',
    emoji: '❓',
    forms: {
      en: { base: 'indefinite' },
      it: { base: 'indeterminativo' },
      fr: { base: 'indéfini' },
      de: { base: 'unbestimmt' },
      es: { base: 'indefinido' },
      ja: { base: '不定冠詞の', reading: 'ふていかんしの' },
      pt: { base: 'indefinido' },
    },
  },
  {
    // The article that is no word at all — a positive choice, not the absence of one. German
    // says "artikellos" rather than "null", which alone would read as the number.
    id: 'ZERO',
    role: 'adjective',
    description: 'spelled with no article at all, meaningfully (grammar)',
    emoji: '⃠',
    forms: {
      en: { base: 'zero' },
      it: { base: 'zero' },
      fr: { base: 'zéro' },
      de: { base: 'artikellos' },
      es: { base: 'cero' },
      ja: { base: '無冠詞の', reading: 'むかんしの' },
      pt: { base: 'zero' },
    },
  },
  {
    id: 'PROXIMAL',
    role: 'adjective',
    description: 'pointing at what is near the speaker (grammar)',
    emoji: '👉',
    forms: {
      en: { base: 'proximal' },
      it: { base: 'vicinale' },
      fr: { base: 'proximal' },
      de: { base: 'proximal' },
      es: { base: 'proximal' },
      ja: { base: '近称の', reading: 'きんしょうの' },
      pt: { base: 'proximal' },
    },
  },
  {
    id: 'DISTAL',
    role: 'adjective',
    description: 'pointing at what is far from the speaker (grammar)',
    emoji: '🔭',
    forms: {
      en: { base: 'distal' },
      it: { base: 'distale' },
      fr: { base: 'distal' },
      de: { base: 'distal' },
      es: { base: 'distal' },
      ja: { base: '遠称の', reading: 'えんしょうの' },
      pt: { base: 'distal' },
    },
  },
  {
    id: 'PARTITIVE',
    role: 'adjective',
    description: 'naming a part of a whole, an unspecified some of it (grammar)',
    emoji: '🍰',
    forms: {
      en: { base: 'partitive' },
      it: { base: 'partitivo' },
      fr: { base: 'partitif' },
      de: { base: 'partitiv' },
      es: { base: 'partitivo' },
      ja: { base: '部分詞の', reading: 'ぶぶんしの' },
      pt: { base: 'partitivo' },
    },
  },
  {
    id: 'NEGATIVE',
    role: 'adjective',
    description: 'asserting that there is none of it (grammar)',
    emoji: '🚫',
    forms: {
      en: { base: 'negative' },
      it: { base: 'negativo' },
      fr: { base: 'négatif' },
      de: { base: 'negativ' },
      es: { base: 'negativo' },
      ja: { base: '否定の', reading: 'ひていの' },
      pt: { base: 'negativo' },
    },
  },
  {
    // Multal and paucal are the quantities "many" and "few" — a large and a small amount, with
    // no claim about halves. "Majority"/"minority" would make that claim, and it is not one
    // "many books" makes.
    id: 'MULTAL',
    role: 'adjective',
    description: 'naming a large quantity, without claiming most (grammar)',
    emoji: '🔺',
    forms: {
      en: { base: 'multal' },
      it: { base: 'multale' },
      fr: { base: 'multal' },
      de: { base: 'multal' },
      es: { base: 'multal' },
      ja: { base: '多数の', reading: 'たすうの' },
      pt: { base: 'multal' },
    },
  },
  {
    id: 'PAUCAL',
    role: 'adjective',
    description: 'naming a small quantity, without claiming a minority (grammar)',
    emoji: '🔻',
    forms: {
      en: { base: 'paucal' },
      it: { base: 'paucale' },
      fr: { base: 'paucal' },
      de: { base: 'paukal' },
      es: { base: 'paucal' },
      ja: { base: '少数の', reading: 'しょうすうの' },
      pt: { base: 'paucal' },
    },
  },
  {
    id: 'UNIVERSAL',
    role: 'adjective',
    description: 'taking in every one of them, with no exception (grammar)',
    emoji: '🌐',
    forms: {
      en: { base: 'universal' },
      it: { base: 'universale' },
      fr: { base: 'universel' },
      de: { base: 'universal' },
      es: { base: 'universal' },
      ja: { base: '全称の', reading: 'ぜんしょうの' },
      pt: { base: 'universal' },
    },
  },
  // ── Ordinals ─────────────────────────────────────────────────────
  // Position in a sequence. Seeded so the pronoun chooser can name the three grammatical
  // persons in the UI language. German declines from an uninflected stem, but its endings
  // absorb a leading -e after a stem in -e (the "müde" rule), so the -e citation form
  // ("erste") both declines correctly and reads as a word on its own.
  {
    id: 'FIRST',
    role: 'adjective',
    description: 'coming before all others in a sequence',
    emoji: '🥇',
    forms: {
      en: { base: 'first' },
      it: { base: 'primo' },
      fr: { base: 'premier' },
      de: { base: 'erste' },
      es: { base: 'primero' },
      ja: { base: '第一の', reading: 'だいいちの' },
      pt: { base: 'primeiro' },
    },
  },
  {
    id: 'SECOND',
    role: 'adjective',
    description: 'coming after the first in a sequence',
    emoji: '🥈',
    forms: {
      en: { base: 'second' },
      it: { base: 'secondo' },
      fr: { base: 'deuxième' },
      de: { base: 'zweite' },
      es: { base: 'segundo' },
      ja: { base: '第二の', reading: 'だいにの' },
      pt: { base: 'segundo' },
    },
  },
  {
    id: 'THIRD',
    role: 'adjective',
    description: 'coming after the second in a sequence',
    emoji: '🥉',
    forms: {
      en: { base: 'third' },
      it: { base: 'terzo' },
      fr: { base: 'troisième' },
      de: { base: 'dritte' },
      es: { base: 'tercero' },
      ja: { base: '第三の', reading: 'だいさんの' },
      pt: { base: 'terceiro' },
    },
  },
  {
    id: 'SEMANTIC',
    role: 'adjective',
    description: 'relating to meaning in language',
    emoji: '🔤',
    forms: {
      en: { base: 'semantic' },
      it: { base: 'semantico' },
      fr: { base: 'sémantique' },
      de: { base: 'semantisch' },
      es: { base: 'semántico' },
      ja: { base: '意味的な', reading: 'いみてきな' },
      pt: { base: 'semântico' },
    },
  },
  {
    id: 'DIRECT',
    role: 'adjective',
    description: 'reaching its end with nothing in between',
    emoji: '➡️',
    forms: {
      en: { base: 'direct' },
      it: { base: 'diretto' },
      fr: { base: 'direct' },
      de: { base: 'direkt' },
      es: { base: 'directo' },
      ja: { base: '直接の', reading: 'ちょくせつの' },
      pt: { base: 'direto' },
    },
  },
  {
    id: 'INDIRECT',
    role: 'adjective',
    description: 'reaching its end through something in between',
    emoji: '↪️',
    forms: {
      en: { base: 'indirect' },
      it: { base: 'indiretto' },
      fr: { base: 'indirect' },
      de: { base: 'indirekt' },
      es: { base: 'indirecto' },
      ja: { base: '間接の', reading: 'かんせつの' },
      pt: { base: 'indireto' },
    },
  },
  {
    // Joined to nothing else — said of a word no relation of the map reaches. The negative is
    // built into the word in en/de ("unconnected", "unverbunden") and spelled as a separate
    // negator in the Romance ones (it "non collegato", fr "non connecté").
    id: 'UNCONNECTED',
    role: 'adjective',
    description: 'joined to nothing else',
    emoji: '⚪',
    forms: {
      en: { base: 'unconnected' },
      it: { base: 'non collegato' },
      fr: { base: 'non connecté' },
      de: { base: 'unverbunden' },
      es: { base: 'no conectado' },
      ja: { base: '孤立した', reading: 'こりつした' },
      pt: { base: 'não conectado' },
    },
  },
  {
    // Kept out of sight — said of what the map does not draw. Japanese takes the attributive
    // 非表示の (literally "not-displayed"), the word an interface uses of what it is not showing,
    // rather than 隠れた, which is something concealing itself.
    id: 'HIDDEN',
    role: 'adjective',
    description: 'kept out of sight',
    emoji: '🙈',
    forms: {
      en: { base: 'hidden' },
      it: { base: 'nascosto' },
      fr: { base: 'caché' },
      de: { base: 'ausgeblendet' },
      es: { base: 'oculto' },
      ja: { base: '非表示の', reading: 'ひひょうじの' },
      pt: { base: 'oculto' },
    },
  },
];
