import type { ConceptSeed } from './types.js';

export const nouns: ConceptSeed[] = [
  // ── NOUNS ────────────────────────────────────────────────────────
  {
    id: 'CAT',
    role: 'noun',
    description: 'domestic feline animal',
    emoji: '🐱',
    animate: true,
    forms: {
      en: { base: 'cat',   plural: 'cats',   count: 'singular' },
      it: { base: 'gatto', plural: 'gatti',  gender: 'masc', count: 'singular', fem: 'gatta',   fem_plural: 'gatte' },
      fr: { base: 'chat',  plural: 'chats',  gender: 'masc', count: 'singular', fem: 'chatte',  fem_plural: 'chattes' },
      de: { base: 'Kater', plural: 'Kater',  gender: 'masc', count: 'singular', fem: 'Katze',   fem_plural: 'Katzen' },
      es: { base: 'gato',  plural: 'gatos',  gender: 'masc', count: 'singular', fem: 'gata',    fem_plural: 'gatas' },
      ja: { base: '猫',   count: 'singular', reading: 'ねこ' },
      pt: { base: 'gato',  plural: 'gatos',  gender: 'masc', count: 'singular', fem: 'gata',    fem_plural: 'gatas' },
    },
  },
  {
    id: 'DOG',
    role: 'noun',
    description: 'domestic canine animal',
    emoji: '🐶',
    animate: true,
    forms: {
      en: { base: 'dog',    plural: 'dogs',   count: 'singular' },
      it: { base: 'cane',   plural: 'cani',   gender: 'masc', count: 'singular', fem: 'cagna',   fem_plural: 'cagne' },
      fr: { base: 'chien',  plural: 'chiens', gender: 'masc', count: 'singular', fem: 'chienne', fem_plural: 'chiennes' },
      de: { base: 'Hund',   plural: 'Hunde',  gender: 'masc', count: 'singular', fem: 'Hündin',  fem_plural: 'Hündinnen' },
      es: { base: 'perro',  plural: 'perros', gender: 'masc', count: 'singular', fem: 'perra',   fem_plural: 'perras' },
      ja: { base: '犬',    count: 'singular', reading: 'いぬ' },
      pt: { base: 'cão',    plural: 'cães',   gender: 'masc', count: 'singular', fem: 'cadela',  fem_plural: 'cadelas' },
    },
  },
  {
    id: 'BOOK',
    role: 'noun',
    description: 'a written or printed work',
    emoji: '📚',
    forms: {
      en: { base: 'book', plural: 'books', count: 'singular' },
      it: { base: 'libro', plural: 'libri', gender: 'masc', count: 'singular' },
      fr: { base: 'livre', plural: 'livres', gender: 'masc', count: 'singular' },
      de: { base: 'Buch', plural: 'Bücher', gender: 'neut', count: 'singular' },
      es: { base: 'libro', plural: 'libros', gender: 'masc', count: 'singular' },
      ja: { base: '本', count: 'singular', reading: 'ほん' },
      pt: { base: 'livro', plural: 'livros', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'WATER',
    role: 'noun',
    description: 'the liquid H₂O',
    emoji: '💧',
    countable: false,
    forms: {
      en: { base: 'water', count: 'singular' },
      it: { base: 'acqua', gender: 'fem', count: 'singular' },
      fr: { base: 'eau', gender: 'fem', count: 'singular' },
      de: { base: 'Wasser', gender: 'neut', count: 'singular' },
      es: { base: 'agua', gender: 'masc', count: 'singular' }, // special: uses "el" even though feminine
      ja: { base: '水', count: 'singular', reading: 'みず' },
      pt: { base: 'água', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'FOOD',
    role: 'noun',
    description: 'nourishment, something to eat',
    emoji: '🍽️',
    countable: false,
    forms: {
      en: { base: 'food', count: 'singular' },
      it: { base: 'cibo', gender: 'masc', count: 'singular' },
      fr: { base: 'nourriture', gender: 'fem', count: 'singular' },
      de: { base: 'Essen', gender: 'neut', count: 'singular' },
      es: { base: 'comida', gender: 'fem', count: 'singular' },
      ja: { base: '食べ物', count: 'singular', reading: 'たべもの' },
      pt: { base: 'comida', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'HOUSE',
    role: 'noun',
    description: 'a building used as a dwelling',
    emoji: '🏠',
    forms: {
      en: { base: 'house', plural: 'houses', count: 'singular' },
      it: { base: 'casa', plural: 'case', gender: 'fem', count: 'singular' },
      fr: { base: 'maison', plural: 'maisons', gender: 'fem', count: 'singular' },
      de: { base: 'Haus', plural: 'Häuser', gender: 'neut', count: 'singular' },
      es: { base: 'casa', plural: 'casas', gender: 'fem', count: 'singular' },
      ja: { base: '家', count: 'singular', reading: 'いえ' },
      pt: { base: 'casa', plural: 'casas', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'HOME',
    role: 'noun',
    description: 'the place where one lives',
    emoji: '🏡',
    forms: {
      en: { base: 'home', plural: 'homes', count: 'singular' },
      it: { base: 'casa', plural: 'case', gender: 'fem', count: 'singular' },
      fr: { base: 'foyer', plural: 'foyers', gender: 'masc', count: 'singular' },
      de: { base: 'Zuhause', plural: 'Zuhause', gender: 'neut', count: 'singular' },
      es: { base: 'hogar', plural: 'hogares', gender: 'masc', count: 'singular' },
      ja: { base: '家', count: 'singular', reading: 'いえ' },
      pt: { base: 'lar', plural: 'lares', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'CHILD',
    role: 'noun',
    description: 'a young human being',
    emoji: '👦',
    animate: true,
    forms: {
      en: { base: 'child',    plural: 'children', count: 'singular' },
      it: { base: 'bambino',  plural: 'bambini',  gender: 'masc', count: 'singular', fem: 'bambina',  fem_plural: 'bambine' },
      fr: { base: 'enfant',   plural: 'enfants',  gender: 'masc', count: 'singular', fem: 'enfant',   fem_plural: 'enfants' },
      de: { base: 'Kind',     plural: 'Kinder',   gender: 'neut', count: 'singular' },
      es: { base: 'niño',     plural: 'niños',    gender: 'masc', count: 'singular', fem: 'niña',     fem_plural: 'niñas' },
      ja: { base: '子供',    count: 'singular', reading: 'こども' },
      pt: { base: 'criança',  plural: 'crianças', gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'FOX',
    role: 'noun',
    description: 'a carnivorous mammal with reddish fur',
    emoji: '🦊',
    animate: true,
    forms: {
      en: { base: 'fox',     plural: 'foxes',   count: 'singular' },
      it: { base: 'volpe',   plural: 'volpi',   gender: 'fem', count: 'singular' },
      fr: { base: 'renard',  plural: 'renards', gender: 'masc', count: 'singular' },
      de: { base: 'Fuchs',   plural: 'Füchse',  gender: 'masc', count: 'singular' },
      es: { base: 'zorro',   plural: 'zorros',  gender: 'masc', count: 'singular', fem: 'zorra',   fem_plural: 'zorras' },
      ja: { base: 'キツネ',  count: 'singular' },
      pt: { base: 'raposa',  plural: 'raposas', gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'BOY',
    role: 'noun',
    description: 'a young male human',
    emoji: '👦',
    animate: true,
    forms: {
      en: { base: 'boy',      plural: 'boys',     count: 'singular' },
      it: { base: 'ragazzo',  plural: 'ragazzi',  gender: 'masc', count: 'singular' },
      fr: { base: 'garçon',   plural: 'garçons',  gender: 'masc', count: 'singular' },
      de: { base: 'Junge',    plural: 'Jungen',   gender: 'masc', count: 'singular' },
      es: { base: 'niño',     plural: 'niños',    gender: 'masc', count: 'singular' },
      ja: { base: '男の子',   count: 'singular', reading: 'おとこのこ' },
      pt: { base: 'menino',   plural: 'meninos',  gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'MAN',
    role: 'noun',
    description: 'an adult male human',
    emoji: '👨',
    animate: true,
    forms: {
      en: { base: 'man',    plural: 'men',     count: 'singular' },
      it: { base: 'uomo',   plural: 'uomini',  gender: 'masc', count: 'singular' },
      fr: { base: 'homme',  plural: 'hommes',  gender: 'masc', count: 'singular' },
      de: { base: 'Mann',   plural: 'Männer',  gender: 'masc', count: 'singular' },
      es: { base: 'hombre', plural: 'hombres', gender: 'masc', count: 'singular' },
      ja: { base: '男',     count: 'singular', reading: 'おとこ' },
      pt: { base: 'homem',  plural: 'homens',  gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'WOLF',
    role: 'noun',
    description: 'a wild canine animal',
    emoji: '🐺',
    animate: true,
    forms: {
      en: { base: 'wolf',   plural: 'wolves', count: 'singular' },
      it: { base: 'lupo',   plural: 'lupi',   gender: 'masc', count: 'singular', fem: 'lupa',    fem_plural: 'lupe' },
      fr: { base: 'loup',   plural: 'loups',  gender: 'masc', count: 'singular', fem: 'louve',   fem_plural: 'louves' },
      de: { base: 'Wolf',   plural: 'Wölfe',  gender: 'masc', count: 'singular', fem: 'Wölfin',  fem_plural: 'Wölfinnen' },
      es: { base: 'lobo',   plural: 'lobos',  gender: 'masc', count: 'singular', fem: 'loba',    fem_plural: 'lobas' },
      ja: { base: '狼',    count: 'singular', reading: 'おおかみ' },
      pt: { base: 'lobo',   plural: 'lobos',  gender: 'masc', count: 'singular', fem: 'loba',    fem_plural: 'lobas' },
    },
  },
  {
    id: 'COW',
    role: 'noun',
    description: 'an adult female bovine kept for milk or meat',
    emoji: '🐄',
    animate: true,
    forms: {
      en: { base: 'cow',    plural: 'cows',   count: 'singular' },
      it: { base: 'mucca',  plural: 'mucche', gender: 'fem', count: 'singular' },
      fr: { base: 'vache',  plural: 'vaches', gender: 'fem', count: 'singular' },
      de: { base: 'Kuh',    plural: 'Kühe',   gender: 'fem', count: 'singular' },
      es: { base: 'vaca',   plural: 'vacas',  gender: 'fem', count: 'singular' },
      ja: { base: '牛',     count: 'singular', reading: 'うし' },
      pt: { base: 'vaca',   plural: 'vacas',  gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'OX',
    role: 'noun',
    description: 'a castrated adult male bovine used as a draft animal',
    emoji: '🐂',
    animate: true,
    forms: {
      en: { base: 'ox',     plural: 'oxen',   count: 'singular' },
      it: { base: 'bue',    plural: 'buoi',   gender: 'masc', count: 'singular' },
      fr: { base: 'bœuf',   plural: 'bœufs',  gender: 'masc', count: 'singular' },
      de: { base: 'Ochse',  plural: 'Ochsen', gender: 'masc', count: 'singular' },
      es: { base: 'buey',   plural: 'bueyes', gender: 'masc', count: 'singular' },
      ja: { base: '雄牛',   count: 'singular', reading: 'おうし' },
      pt: { base: 'boi',    plural: 'bois',   gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'BUTCHER',
    role: 'noun',
    description: 'a person who slaughters animals or sells meat',
    emoji: '🔪',
    animate: true,
    forms: {
      en: { base: 'butcher',     plural: 'butchers',     count: 'singular' },
      it: { base: 'macellaio',   plural: 'macellai',     gender: 'masc', count: 'singular', fem: 'macellaia',   fem_plural: 'macellaie' },
      fr: { base: 'boucher',     plural: 'bouchers',     gender: 'masc', count: 'singular', fem: 'bouchère',    fem_plural: 'bouchères' },
      de: { base: 'Metzger',     plural: 'Metzger',      gender: 'masc', count: 'singular', fem: 'Metzgerin',   fem_plural: 'Metzgerinnen' },
      es: { base: 'carnicero',   plural: 'carniceros',   gender: 'masc', count: 'singular', fem: 'carnicera',   fem_plural: 'carniceras' },
      ja: { base: '肉屋',        count: 'singular', reading: 'にくや' },
      pt: { base: 'açougueiro',  plural: 'açougueiros',  gender: 'masc', count: 'singular', fem: 'açougueira',  fem_plural: 'açougueiras' },
    },
  },
  {
    id: 'ANGEL',
    role: 'noun',
    description: 'a spiritual being; a messenger of God',
    emoji: '👼',
    animate: true,
    forms: {
      en: { base: 'angel',   plural: 'angels',  count: 'singular' },
      it: { base: 'angelo',  plural: 'angeli',  gender: 'masc', count: 'singular' },
      fr: { base: 'ange',    plural: 'anges',   gender: 'masc', count: 'singular' },
      de: { base: 'Engel',   plural: 'Engel',   gender: 'masc', count: 'singular' },
      es: { base: 'ángel',   plural: 'ángeles', gender: 'masc', count: 'singular' },
      ja: { base: '天使',    count: 'singular', reading: 'てんし' },
      pt: { base: 'anjo',    plural: 'anjos',   gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'DEATH',
    role: 'noun',
    description: 'the end of life; the state of being dead',
    emoji: '💀',
    forms: {
      en: { base: 'death',  plural: 'deaths',  count: 'singular' },
      it: { base: 'morte',  plural: 'morti',   gender: 'fem', count: 'singular' },
      fr: { base: 'mort',   plural: 'morts',   gender: 'fem', count: 'singular' },
      de: { base: 'Tod',    plural: 'Tode',    gender: 'masc', count: 'singular' },
      es: { base: 'muerte', plural: 'muertes', gender: 'fem', count: 'singular' },
      ja: { base: '死',    count: 'singular', reading: 'し' },
      pt: { base: 'morte',  plural: 'mortes',  gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'MOUSE',
    role: 'noun',
    description: 'a small rodent',
    emoji: '🐭',
    animate: true,
    synonym: 'rodent',
    forms: {
      en: { base: 'mouse',  plural: 'mice',    count: 'singular' },
      it: { base: 'topo',   plural: 'topi',    gender: 'masc', count: 'singular' },
      fr: { base: 'souris', plural: 'souris',  gender: 'fem',  count: 'singular' },
      de: { base: 'Maus',   plural: 'Mäuse',   gender: 'fem',  count: 'singular' },
      es: { base: 'ratón',  plural: 'ratones', gender: 'masc', count: 'singular' },
      ja: { base: 'ネズミ', count: 'singular', reading: 'ねずみ' },
      pt: { base: 'rato',   plural: 'ratos',   gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'STICK',
    role: 'noun',
    description: 'a thin elongated piece of wood',
    emoji: '🥢',
    synonym: 'rod',
    forms: {
      en: { base: 'stick',   plural: 'sticks',  count: 'singular' },
      it: { base: 'bastone', plural: 'bastoni', gender: 'masc', count: 'singular' },
      fr: { base: 'bâton',   plural: 'bâtons',  gender: 'masc', count: 'singular' },
      de: { base: 'Stock',   plural: 'Stöcke',  gender: 'masc', count: 'singular' },
      es: { base: 'palo',    plural: 'palos',   gender: 'masc', count: 'singular' },
      ja: { base: '棒',      count: 'singular', reading: 'ぼう' },
      pt: { base: 'pau',     plural: 'paus',    gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'FIRE',
    role: 'noun',
    description: 'the phenomenon of combustion; flame',
    emoji: '🔥',
    forms: {
      en: { base: 'fire',  plural: 'fires',  count: 'singular' },
      it: { base: 'fuoco', plural: 'fuochi', gender: 'masc', count: 'singular' },
      fr: { base: 'feu',   plural: 'feux',   gender: 'masc', count: 'singular' },
      de: { base: 'Feuer', plural: 'Feuer',  gender: 'neut', count: 'singular' },
      es: { base: 'fuego', plural: 'fuegos', gender: 'masc', count: 'singular' },
      ja: { base: '火',    count: 'singular', reading: 'ひ' },
      pt: { base: 'fogo',  plural: 'fogos',  gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'FATHER',
    role: 'noun',
    description: 'a male parent',
    emoji: '👨',
    animate: true,
    forms: {
      en: { base: 'father', plural: 'fathers', count: 'singular' },
      it: { base: 'padre',  plural: 'padri',   gender: 'masc', count: 'singular' },
      fr: { base: 'père',   plural: 'pères',   gender: 'masc', count: 'singular' },
      de: { base: 'Vater',  plural: 'Väter',   gender: 'masc', count: 'singular' },
      es: { base: 'padre',  plural: 'padres',  gender: 'masc', count: 'singular' },
      ja: { base: '父',     count: 'singular', reading: 'ちち' },
      pt: { base: 'pai',    plural: 'pais',    gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'MARKET',
    role: 'noun',
    description: 'a place where goods are bought and sold',
    emoji: '🏪',
    forms: {
      en: { base: 'market',   plural: 'markets',  count: 'singular' },
      it: { base: 'mercato',  plural: 'mercati',  gender: 'masc', count: 'singular' },
      fr: { base: 'marché',   plural: 'marchés',  gender: 'masc', count: 'singular' },
      de: { base: 'Markt',    plural: 'Märkte',   gender: 'masc', count: 'singular' },
      es: { base: 'mercado',  plural: 'mercados', gender: 'masc', count: 'singular' },
      ja: { base: '市場',     count: 'singular', reading: 'いちば' },
      pt: { base: 'mercado',  plural: 'mercados', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'COIN',
    role: 'noun',
    description: 'a small round piece of metal used as money',
    emoji: '🪙',
    forms: {
      en: { base: 'coin',     plural: 'coins',    count: 'singular' },
      it: { base: 'moneta',   plural: 'monete',   gender: 'fem', count: 'singular' },
      fr: { base: 'pièce',    plural: 'pièces',   gender: 'fem', count: 'singular' },
      de: { base: 'Münze',    plural: 'Münzen',   gender: 'fem', count: 'singular' },
      es: { base: 'moneda',   plural: 'monedas',  gender: 'fem', count: 'singular' },
      ja: { base: '硬貨',     count: 'singular', reading: 'こうか' },
      pt: { base: 'moeda',    plural: 'moedas',   gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'LEGEND',
    role: 'noun',
    description: 'a traditional story or a famous person',
    emoji: '📜',
    forms: {
      en: { base: 'legend',   plural: 'legends',   count: 'singular' },
      it: { base: 'leggenda', plural: 'leggende',  gender: 'fem', count: 'singular' },
      fr: { base: 'légende',  plural: 'légendes',  gender: 'fem', count: 'singular' },
      de: { base: 'Legende',  plural: 'Legenden',  gender: 'fem', count: 'singular' },
      es: { base: 'leyenda',  plural: 'leyendas',  gender: 'fem', count: 'singular' },
      ja: { base: '伝説',     count: 'singular', reading: 'でんせつ' },
      pt: { base: 'lenda',    plural: 'lendas',    gender: 'fem', count: 'singular' },
    },
  },

  {
    id: 'WING',
    role: 'noun',
    description: 'a limb or organ used for flight',
    emoji: '🪽',
    forms: {
      en: { base: 'wing',   plural: 'wings',  count: 'singular' },
      it: { base: 'ala',    plural: 'ali',    gender: 'fem', count: 'singular' },
      fr: { base: 'aile',   plural: 'ailes',  gender: 'fem', count: 'singular' },
      de: { base: 'Flügel', plural: 'Flügel', gender: 'masc', count: 'singular' },
      es: { base: 'ala',    plural: 'alas',   gender: 'fem', count: 'singular' },
      ja: { base: '翼',     count: 'singular', reading: 'つばさ' },
      pt: { base: 'asa',    plural: 'asas',   gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'YOUNG_MAN',
    role: 'noun',
    description: 'a young male person',
    emoji: '👱‍♂️',
    animate: true,
    synonym: 'youth',
    forms: {
      en: { base: 'young man', plural: 'young men',    count: 'singular' },
      it: { base: 'giovane',   plural: 'giovani',      gender: 'masc', count: 'singular' },
      fr: { base: 'jeune homme', plural: 'jeunes hommes', gender: 'masc', count: 'singular' },
      de: { base: 'Bursche',   plural: 'Burschen',     gender: 'masc', count: 'singular' },
      es: { base: 'joven',     plural: 'jóvenes',      gender: 'masc', count: 'singular' },
      ja: { base: '青年',      count: 'singular', reading: 'せいねん' },
      pt: { base: 'jovem',     plural: 'jovens',       gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'YOUNG_WOMAN',
    role: 'noun',
    description: 'a young female person',
    emoji: '👱‍♀️',
    animate: true,
    synonym: 'youth',
    forms: {
      en: { base: 'young woman', plural: 'young women',  count: 'singular' },
      it: { base: 'giovane',   plural: 'giovani',      gender: 'fem', count: 'singular' },
      fr: { base: 'jeune femme', plural: 'jeunes femmes', gender: 'fem', count: 'singular' },
      // "jung" is stored as the head's inherent attributive adjective, not baked into the
      // lemma: German declines it for case + determiner ("die junge Frau", "die jungen
      // Frauen", "von einer jungen Frau"), so no single surface string is right everywhere.
      de: { base: 'Frau', plural: 'Frauen', adjective: 'jung', gender: 'fem', count: 'singular' },
      es: { base: 'joven',     plural: 'jóvenes',      gender: 'fem', count: 'singular' },
      ja: { base: '若い女性',  count: 'singular', reading: 'わかいじょせい' },
      pt: { base: 'jovem',     plural: 'jovens',       gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'PRISON',
    role: 'noun',
    description: 'a building where people are confined as punishment',
    emoji: '🔒',
    forms: {
      en: { base: 'prison',     plural: 'prisons',      count: 'singular' },
      it: { base: 'prigione',   plural: 'prigioni',     gender: 'fem',  count: 'singular' },
      fr: { base: 'prison',     plural: 'prisons',      gender: 'fem',  count: 'singular' },
      de: { base: 'Gefängnis',  plural: 'Gefängnisse',  gender: 'neut', count: 'singular' },
      es: { base: 'prisión',    plural: 'prisiones',    gender: 'fem',  count: 'singular' },
      ja: { base: '刑務所',     count: 'singular', reading: 'けいむしょ' },
      pt: { base: 'prisão',     plural: 'prisões',      gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'BUILDER',
    role: 'noun',
    description: 'a person who constructs things',
    emoji: '👷',
    animate: true,
    forms: {
      en: { base: 'builder',     plural: 'builders',      count: 'singular' },
      it: { base: 'costruttore', plural: 'costruttori',   gender: 'masc', count: 'singular', fem: 'costruttrice', fem_plural: 'costruttrici' },
      fr: { base: 'constructeur', plural: 'constructeurs', gender: 'masc', count: 'singular', fem: 'constructrice', fem_plural: 'constructrices' },
      de: { base: 'Bauarbeiter', plural: 'Bauarbeiter',   gender: 'masc', count: 'singular', fem: 'Bauarbeiterin', fem_plural: 'Bauarbeiterinnen' },
      es: { base: 'constructor', plural: 'constructores', gender: 'masc', count: 'singular', fem: 'constructora', fem_plural: 'constructoras' },
      ja: { base: '建築者',      count: 'singular', reading: 'けんちくしゃ' },
      pt: { base: 'construtor',  plural: 'construtores',  gender: 'masc', count: 'singular', fem: 'construtora', fem_plural: 'construtoras' },
    },
  },
  {
    id: 'CREATOR',
    role: 'noun',
    description: 'someone or something that creates things',
    emoji: '✨',
    animate: true,
    forms: {
      en: { base: 'creator',    plural: 'creators',     count: 'singular' },
      it: { base: 'creatore',   plural: 'creatori',     gender: 'masc', count: 'singular', fem: 'creatrice', fem_plural: 'creatrici' },
      fr: { base: 'créateur',   plural: 'créateurs',    gender: 'masc', count: 'singular', fem: 'créatrice', fem_plural: 'créatrices' },
      de: { base: 'Schöpfer',   plural: 'Schöpfer',     gender: 'masc', count: 'singular', fem: 'Schöpferin', fem_plural: 'Schöpferinnen' },
      es: { base: 'creador',    plural: 'creadores',    gender: 'masc', count: 'singular', fem: 'creadora', fem_plural: 'creadoras' },
      ja: { base: '創造者',     count: 'singular', reading: 'そうぞうしゃ' },
      pt: { base: 'criador',    plural: 'criadores',    gender: 'masc', count: 'singular', fem: 'criadora', fem_plural: 'criadoras' },
    },
  },
  {
    id: 'PHRASE',
    role: 'noun',
    description: 'a small group of words expressing a concept',
    emoji: '💬',
    forms: {
      en: { base: 'phrase',  plural: 'phrases', count: 'singular' },
      it: { base: 'frase',   plural: 'frasi',   gender: 'fem', count: 'singular' },
      fr: { base: 'phrase',  plural: 'phrases', gender: 'fem', count: 'singular' },
      de: { base: 'Phrase',  plural: 'Phrasen', gender: 'fem', count: 'singular' },
      es: { base: 'frase',   plural: 'frases',  gender: 'fem', count: 'singular' },
      ja: { base: 'フレーズ', count: 'singular', reading: 'ふれーず' },
      pt: { base: 'frase',   plural: 'frases',  gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'SLOT',
    role: 'noun',
    description: 'a narrow opening or an allotted position',
    emoji: '🎰',
    forms: {
      en: { base: 'slot',    plural: 'slots',    count: 'singular' },
      it: { base: 'fessura', plural: 'fessure',  gender: 'fem',  count: 'singular' },
      fr: { base: 'fente',   plural: 'fentes',   gender: 'fem',  count: 'singular' },
      de: { base: 'Schlitz', plural: 'Schlitze', gender: 'masc', count: 'singular' },
      es: { base: 'ranura',  plural: 'ranuras',  gender: 'fem',  count: 'singular' },
      ja: { base: 'スロット', count: 'singular', reading: 'すろっと' },
      pt: { base: 'ranhura', plural: 'ranhuras', gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'SLOT_COMPUTING',
    role: 'noun',
    description: 'a reserved position in memory or a schedule (informatics)',
    emoji: '🧩',
    forms: {
      en: { base: 'slot',    plural: 'slots',    count: 'singular' },
      it: { base: 'slot',    plural: 'slot',     gender: 'masc', count: 'singular' },
      fr: { base: 'slot',    plural: 'slots',    gender: 'masc', count: 'singular' },
      de: { base: 'Slot',    plural: 'Slots',    gender: 'masc', count: 'singular' },
      es: { base: 'slot',    plural: 'slots',    gender: 'masc', count: 'singular' },
      ja: { base: 'スロット', count: 'singular', reading: 'すろっと' },
      pt: { base: 'slot',    plural: 'slots',    gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'SLOT_MACHINE',
    role: 'noun',
    description: 'a coin-operated gambling machine with spinning reels',
    emoji: '🎰',
    forms: {
      en: { base: 'slot machine',   plural: 'slot machines',   count: 'singular' },
      it: { base: 'slot machine',   plural: 'slot machine',    gender: 'fem',  count: 'singular' },
      fr: { base: 'machine à sous',  plural: 'machines à sous', gender: 'fem',  count: 'singular' },
      de: { base: 'Spielautomat',    plural: 'Spielautomaten',  gender: 'masc', count: 'singular' },
      es: { base: 'máquina tragaperras', plural: 'máquinas tragaperras', gender: 'fem', count: 'singular' },
      ja: { base: 'スロットマシン', count: 'singular', reading: 'すろっとましん' },
      pt: { base: 'caça-níqueis',    plural: 'caça-níqueis',    gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'WORD',
    role: 'noun',
    description: 'a single unit of language',
    emoji: '🔤',
    forms: {
      en: { base: 'word',    plural: 'words',    count: 'singular' },
      it: { base: 'parola',  plural: 'parole',   gender: 'fem',  count: 'singular' },
      fr: { base: 'mot',     plural: 'mots',     gender: 'masc', count: 'singular' },
      de: { base: 'Wort',    plural: 'Wörter',   gender: 'neut', count: 'singular' },
      es: { base: 'palabra', plural: 'palabras', gender: 'fem',  count: 'singular' },
      ja: { base: '単語',    count: 'singular', reading: 'たんご' },
      pt: { base: 'palavra', plural: 'palavras', gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'TRANSLATION',
    role: 'noun',
    description: 'a rendering of text or speech from one language into another',
    emoji: '🌐',
    forms: {
      en: { base: 'translation',  plural: 'translations',   count: 'singular' },
      it: { base: 'traduzione',   plural: 'traduzioni',     gender: 'fem',  count: 'singular' },
      fr: { base: 'traduction',   plural: 'traductions',    gender: 'fem',  count: 'singular' },
      de: { base: 'Übersetzung',  plural: 'Übersetzungen',  gender: 'fem',  count: 'singular' },
      es: { base: 'traducción',   plural: 'traducciones',   gender: 'fem',  count: 'singular' },
      ja: { base: '翻訳',         count: 'singular', reading: 'ほんやく' },
      pt: { base: 'tradução',     plural: 'traduções',      gender: 'fem',  count: 'singular' },
    },
  },

  {
    id: 'AFRICA',
    role: 'noun',
    description: 'the continent south of the Mediterranean',
    emoji: '🌍',
    // A proper noun: no plural, and the article is the language's to fix — English, German,
    // Spanish and Japanese take none; Italian, French and Portuguese take the definite one.
    proper: true,
    countable: false,
    forms: {
      en: { base: 'Africa',   count: 'singular' },
      it: { base: 'Africa',   gender: 'fem', count: 'singular' },
      fr: { base: 'Afrique',  gender: 'fem', count: 'singular' },
      de: { base: 'Afrika',   gender: 'neut', count: 'singular' },
      es: { base: 'África',   gender: 'fem', count: 'singular' },
      ja: { base: 'アフリカ', count: 'singular' },
      pt: { base: 'África',   gender: 'fem', count: 'singular' },
    },
  },

  // ── Language names ────────────────────────────────────────────────
  // The seven UI languages, as mass nouns, so the engine can render each language's name
  // in any language (e.g. the header language selector shows them in the current UI
  // language). English capitalises language names; the others lower-case them; German
  // capitalises all nouns. Uncountable (no plural), gender masc in the Romance languages,
  // neuter in German. See backend languages.ts for the LanguageCode → concept mapping.
  {
    id: 'ENGLISH',
    role: 'noun',
    description: 'the English language',
    emoji: '🇬🇧',
    countable: false,
    forms: {
      en: { base: 'English',  count: 'singular' },
      it: { base: 'inglese',  gender: 'masc', count: 'singular' },
      fr: { base: 'anglais',  gender: 'masc', count: 'singular' },
      de: { base: 'Englisch', gender: 'neut', count: 'singular' },
      es: { base: 'inglés',   gender: 'masc', count: 'singular' },
      ja: { base: '英語',     count: 'singular', reading: 'えいご' },
      pt: { base: 'inglês',   gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'ITALIAN',
    role: 'noun',
    description: 'the Italian language',
    emoji: '🇮🇹',
    countable: false,
    forms: {
      en: { base: 'Italian',      count: 'singular' },
      it: { base: 'italiano',     gender: 'masc', count: 'singular' },
      fr: { base: 'italien',      gender: 'masc', count: 'singular' },
      de: { base: 'Italienisch',  gender: 'neut', count: 'singular' },
      es: { base: 'italiano',     gender: 'masc', count: 'singular' },
      ja: { base: 'イタリア語',   count: 'singular', reading: 'いたりあご' },
      pt: { base: 'italiano',     gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'FRENCH',
    role: 'noun',
    description: 'the French language',
    emoji: '🇫🇷',
    countable: false,
    forms: {
      en: { base: 'French',       count: 'singular' },
      it: { base: 'francese',     gender: 'masc', count: 'singular' },
      fr: { base: 'français',     gender: 'masc', count: 'singular' },
      de: { base: 'Französisch',  gender: 'neut', count: 'singular' },
      es: { base: 'francés',      gender: 'masc', count: 'singular' },
      ja: { base: 'フランス語',   count: 'singular', reading: 'ふらんすご' },
      pt: { base: 'francês',      gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'GERMAN',
    role: 'noun',
    description: 'the German language',
    emoji: '🇩🇪',
    countable: false,
    forms: {
      en: { base: 'German',    count: 'singular' },
      it: { base: 'tedesco',   gender: 'masc', count: 'singular' },
      fr: { base: 'allemand',  gender: 'masc', count: 'singular' },
      de: { base: 'Deutsch',   gender: 'neut', count: 'singular' },
      es: { base: 'alemán',    gender: 'masc', count: 'singular' },
      ja: { base: 'ドイツ語',  count: 'singular', reading: 'どいつご' },
      pt: { base: 'alemão',    gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'SPANISH',
    role: 'noun',
    description: 'the Spanish language',
    emoji: '🇪🇸',
    countable: false,
    forms: {
      en: { base: 'Spanish',    count: 'singular' },
      it: { base: 'spagnolo',   gender: 'masc', count: 'singular' },
      fr: { base: 'espagnol',   gender: 'masc', count: 'singular' },
      de: { base: 'Spanisch',   gender: 'neut', count: 'singular' },
      es: { base: 'español',    gender: 'masc', count: 'singular' },
      ja: { base: 'スペイン語', count: 'singular', reading: 'すぺいんご' },
      pt: { base: 'espanhol',   gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'JAPANESE',
    role: 'noun',
    description: 'the Japanese language',
    emoji: '🇯🇵',
    countable: false,
    forms: {
      en: { base: 'Japanese',   count: 'singular' },
      it: { base: 'giapponese', gender: 'masc', count: 'singular' },
      fr: { base: 'japonais',   gender: 'masc', count: 'singular' },
      de: { base: 'Japanisch',  gender: 'neut', count: 'singular' },
      es: { base: 'japonés',    gender: 'masc', count: 'singular' },
      ja: { base: '日本語',     count: 'singular', reading: 'にほんご' },
      pt: { base: 'japonês',    gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'PORTUGUESE',
    role: 'noun',
    description: 'the Portuguese language',
    emoji: '🇵🇹',
    countable: false,
    forms: {
      en: { base: 'Portuguese',      count: 'singular' },
      it: { base: 'portoghese',      gender: 'masc', count: 'singular' },
      fr: { base: 'portugais',       gender: 'masc', count: 'singular' },
      de: { base: 'Portugiesisch',   gender: 'neut', count: 'singular' },
      es: { base: 'portugués',       gender: 'masc', count: 'singular' },
      ja: { base: 'ポルトガル語',    count: 'singular', reading: 'ぽるとがるご' },
      pt: { base: 'português',       gender: 'masc', count: 'singular' },
    },
  },
];
