import type { ConceptSeed } from './types.js';
import type { PhrasePlan } from '@signi/shared';

// A genus-differentia gloss the engine renders into every language: an indefinite noun phrase
// whose head is the genus (usually the concept's own hypernym) carrying differentia adjectives —
// glossOf('MAMMAL', 'SMALL') → en "a small mammal", it "un piccolo mammifero", de "ein kleines
// Säugetier", ja "小さい哺乳類". Set as a concept's `definition` to localize its picker tooltip
// without hand-writing a literal per language (see ConceptSeed.definition).
const glossOf = (genus: string, ...adjectives: string[]): PhrasePlan => ({
  subject: { concept: genus, definiteness: 'indefinite', adjectives },
});

// A genus + subject-gap relative-clause gloss: an indefinite head noun restricted by a relative
// clause whose subject the head fills — whoGloss('PERSON', 'MAKE', 'OBJECT_THING') → en "a person
// who makes objects", it "una persona che fa oggetti", de "eine Person, die Gegenstände macht", ja
// "物体を作る人". The optional object renders as a bare plural ("objects", not "the objects").
const whoGloss = (genus: string, verb: string, object?: string): PhrasePlan => ({
  subject: {
    concept: genus,
    definiteness: 'indefinite',
    relative: {
      verbPhrase: { verb },
      ...(object ? { directObject: { concept: object, definiteness: 'bare', number: 'plural' } } : {}),
    },
  },
});

export const nouns: ConceptSeed[] = [
  // ── NOUNS ────────────────────────────────────────────────────────
  {
    id: 'ANIMAL',
    role: 'noun',
    description: 'a living creature other than a person',
    emoji: '🐾',
    animate: true,
    forms: {
      en: { base: 'animal', plural: 'animals', count: 'singular' },
      it: { base: 'animale', plural: 'animali', gender: 'masc', count: 'singular' },
      // fr -al → -aux and pt -al → -ais: the plural is irregular in both.
      fr: { base: 'animal', plural: 'animaux', gender: 'masc', count: 'singular' },
      de: { base: 'Tier', plural: 'Tiere', gender: 'neut', count: 'singular' },
      es: { base: 'animal', plural: 'animales', gender: 'masc', count: 'singular' },
      ja: { base: '動物', count: 'singular', reading: 'どうぶつ' },
      pt: { base: 'animal', plural: 'animais', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'MAMMAL',
    role: 'noun',
    description: 'a warm-blooded animal that suckles its young',
    emoji: '🐘',
    animate: true,
    isA: 'ANIMAL',
    forms: {
      en: { base: 'mammal', plural: 'mammals', count: 'singular' },
      it: { base: 'mammifero', plural: 'mammiferi', gender: 'masc', count: 'singular' },
      fr: { base: 'mammifère', plural: 'mammifères', gender: 'masc', count: 'singular' },
      de: { base: 'Säugetier', plural: 'Säugetiere', gender: 'neut', count: 'singular' },
      es: { base: 'mamífero', plural: 'mamíferos', gender: 'masc', count: 'singular' },
      ja: { base: '哺乳類', count: 'singular', reading: 'ほにゅうるい' },
      pt: { base: 'mamífero', plural: 'mamíferos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'CAT',
    role: 'noun',
    description: 'domestic feline animal',
    definition: glossOf('MAMMAL', 'SMALL'),
    emoji: '🐱',
    animate: true,
    isA: 'MAMMAL',
    forms: {
      en: { base: 'cat', plural: 'cats', count: 'singular' },
      it: { base: 'gatto', plural: 'gatti', gender: 'masc', count: 'singular', fem: 'gatta', fem_plural: 'gatte' },
      fr: { base: 'chat', plural: 'chats', gender: 'masc', count: 'singular', fem: 'chatte', fem_plural: 'chattes' },
      de: { base: 'Kater', plural: 'Kater', gender: 'masc', count: 'singular', fem: 'Katze', fem_plural: 'Katzen' },
      es: { base: 'gato', plural: 'gatos', gender: 'masc', count: 'singular', fem: 'gata', fem_plural: 'gatas' },
      ja: { base: '猫', count: 'singular', reading: 'ねこ' },
      pt: { base: 'gato', plural: 'gatos', gender: 'masc', count: 'singular', fem: 'gata', fem_plural: 'gatas' },
    },
  },
  {
    id: 'DOG',
    role: 'noun',
    description: 'domestic canine animal',
    emoji: '🐶',
    animate: true,
    isA: 'MAMMAL',
    forms: {
      en: { base: 'dog', plural: 'dogs', count: 'singular' },
      it: { base: 'cane', plural: 'cani', gender: 'masc', count: 'singular', fem: 'cagna', fem_plural: 'cagne' },
      fr: { base: 'chien', plural: 'chiens', gender: 'masc', count: 'singular', fem: 'chienne', fem_plural: 'chiennes' },
      de: { base: 'Hund', plural: 'Hunde', gender: 'masc', count: 'singular', fem: 'Hündin', fem_plural: 'Hündinnen' },
      es: { base: 'perro', plural: 'perros', gender: 'masc', count: 'singular', fem: 'perra', fem_plural: 'perras' },
      ja: { base: '犬', count: 'singular', reading: 'いぬ' },
      pt: { base: 'cão', plural: 'cães', gender: 'masc', count: 'singular', fem: 'cadela', fem_plural: 'cadelas' },
    },
  },
  {
    id: 'BOOK',
    role: 'noun',
    description: 'a written or printed work',
    emoji: '📚',
    forms: {
      en: { base: 'book', plural: 'books', count: 'singular' },
      it: { base: 'libro', plural: 'libri', gender: 'masc', count: 'singular' },
      fr: { base: 'livre', plural: 'livres', gender: 'masc', count: 'singular' },
      de: { base: 'Buch', plural: 'Bücher', gender: 'neut', count: 'singular' },
      es: { base: 'libro', plural: 'libros', gender: 'masc', count: 'singular' },
      ja: { base: '本', count: 'singular', reading: 'ほん' },
      pt: { base: 'livro', plural: 'livros', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'WATER',
    role: 'noun',
    description: 'the liquid H₂O',
    emoji: '💧',
    countable: false,
    forms: {
      en: { base: 'water', count: 'singular' },
      it: { base: 'acqua', gender: 'fem', count: 'singular' },
      fr: { base: 'eau', gender: 'fem', count: 'singular' },
      de: { base: 'Wasser', gender: 'neut', count: 'singular' },
      // "agua" is feminine but takes the masculine singular article ("el agua") because it
      // begins with a stressed a-; stressed_a marks that, and only the article obeys it —
      // every other agreement stays feminine ("esta agua fría", "toda el agua").
      es: { base: 'agua', gender: 'fem', stressed_a: '1', count: 'singular' },
      ja: { base: '水', count: 'singular', reading: 'みず' },
      pt: { base: 'água', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'FOOD',
    role: 'noun',
    description: 'nourishment, something to eat',
    emoji: '🍽️',
    countable: false,
    forms: {
      en: { base: 'food', count: 'singular' },
      it: { base: 'cibo', gender: 'masc', count: 'singular' },
      fr: { base: 'nourriture', gender: 'fem', count: 'singular' },
      de: { base: 'Essen', gender: 'neut', count: 'singular' },
      es: { base: 'comida', gender: 'fem', count: 'singular' },
      ja: { base: '食べ物', count: 'singular', reading: 'たべもの' },
      pt: { base: 'comida', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'HOUSE',
    role: 'noun',
    description: 'a building used as a dwelling',
    emoji: '🏠',
    forms: {
      en: { base: 'house', plural: 'houses', count: 'singular' },
      it: { base: 'casa', plural: 'case', gender: 'fem', count: 'singular' },
      fr: { base: 'maison', plural: 'maisons', gender: 'fem', count: 'singular' },
      de: { base: 'Haus', plural: 'Häuser', gender: 'neut', count: 'singular' },
      es: { base: 'casa', plural: 'casas', gender: 'fem', count: 'singular' },
      ja: { base: '家', count: 'singular', reading: 'いえ' },
      pt: { base: 'casa', plural: 'casas', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'HOME',
    role: 'noun',
    description: 'the place where one lives',
    emoji: '🏡',
    forms: {
      en: { base: 'home', plural: 'homes', count: 'singular' },
      it: { base: 'casa', plural: 'case', gender: 'fem', count: 'singular' },
      fr: { base: 'foyer', plural: 'foyers', gender: 'masc', count: 'singular' },
      de: { base: 'Zuhause', plural: 'Zuhause', gender: 'neut', count: 'singular' },
      es: { base: 'hogar', plural: 'hogares', gender: 'masc', count: 'singular' },
      ja: { base: '家', count: 'singular', reading: 'いえ' },
      pt: { base: 'lar', plural: 'lares', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'CHILD',
    role: 'noun',
    description: 'a young human being',
    definition: glossOf('PERSON', 'YOUNG'),
    emoji: '👦',
    animate: true,
    human: true,
    forms: {
      en: { base: 'child', plural: 'children', count: 'singular' },
      it: { base: 'bambino', plural: 'bambini', gender: 'masc', count: 'singular', fem: 'bambina', fem_plural: 'bambine' },
      fr: { base: 'enfant', plural: 'enfants', gender: 'masc', count: 'singular', fem: 'enfant', fem_plural: 'enfants' },
      de: { base: 'Kind', plural: 'Kinder', gender: 'neut', count: 'singular' },
      es: { base: 'niño', plural: 'niños', gender: 'masc', count: 'singular', fem: 'niña', fem_plural: 'niñas' },
      ja: { base: '子供', count: 'singular', reading: 'こども' },
      pt: { base: 'criança', plural: 'crianças', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'PERSON',
    role: 'noun',
    description: 'a human being',
    emoji: '🧑',
    animate: true,
    human: true,
    forms: {
      en: { base: 'person', plural: 'people', count: 'singular' },
      it: { base: 'persona', plural: 'persone', gender: 'fem', count: 'singular' },
      fr: { base: 'personne', plural: 'personnes', gender: 'fem', count: 'singular' },
      de: { base: 'Person', plural: 'Personen', gender: 'fem', count: 'singular' },
      es: { base: 'persona', plural: 'personas', gender: 'fem', count: 'singular' },
      ja: { base: '人', count: 'singular', reading: 'ひと' },
      pt: { base: 'pessoa', plural: 'pessoas', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'FOX',
    role: 'noun',
    description: 'a carnivorous mammal with reddish fur',
    definition: glossOf('MAMMAL', 'BROWN'),
    emoji: '🦊',
    animate: true,
    isA: 'MAMMAL',
    forms: {
      en: { base: 'fox', plural: 'foxes', count: 'singular' },
      it: { base: 'volpe', plural: 'volpi', gender: 'fem', count: 'singular' },
      fr: { base: 'renard', plural: 'renards', gender: 'masc', count: 'singular' },
      de: { base: 'Fuchs', plural: 'Füchse', gender: 'masc', count: 'singular' },
      es: { base: 'zorro', plural: 'zorros', gender: 'masc', count: 'singular', fem: 'zorra', fem_plural: 'zorras' },
      ja: { base: 'キツネ', count: 'singular' },
      pt: { base: 'raposa', plural: 'raposas', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'BOY',
    role: 'noun',
    description: 'a young male human',
    definition: glossOf('PERSON', 'YOUNG', 'MALE'),
    emoji: '👦',
    animate: true,
    human: true,
    isA: 'PERSON',
    forms: {
      en: { base: 'boy', plural: 'boys', count: 'singular' },
      it: { base: 'ragazzo', plural: 'ragazzi', gender: 'masc', count: 'singular' },
      fr: { base: 'garçon', plural: 'garçons', gender: 'masc', count: 'singular' },
      de: { base: 'Junge', plural: 'Jungen', gender: 'masc', count: 'singular', weak: '1' },
      es: { base: 'niño', plural: 'niños', gender: 'masc', count: 'singular' },
      ja: { base: '男の子', count: 'singular', reading: 'おとこのこ' },
      pt: { base: 'menino', plural: 'meninos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'MAN',
    role: 'noun',
    description: 'an adult male human',
    emoji: '👨',
    animate: true,
    human: true,
    isA: 'PERSON',
    forms: {
      en: { base: 'man', plural: 'men', count: 'singular' },
      it: { base: 'uomo', plural: 'uomini', gender: 'masc', count: 'singular' },
      // "homme" begins with an h muet: silent, so the article elides ("l'homme") exactly as before
      // a vowel. The flag marks that; an h aspiré noun ("héros" → le héros) would carry none.
      fr: { base: 'homme', plural: 'hommes', gender: 'masc', count: 'singular', elides: '1' },
      de: { base: 'Mann', plural: 'Männer', gender: 'masc', count: 'singular' },
      es: { base: 'hombre', plural: 'hombres', gender: 'masc', count: 'singular' },
      ja: { base: '男', count: 'singular', reading: 'おとこ' },
      pt: { base: 'homem', plural: 'homens', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'WOLF',
    role: 'noun',
    description: 'a wild canine animal',
    emoji: '🐺',
    animate: true,
    isA: 'MAMMAL',
    forms: {
      en: { base: 'wolf', plural: 'wolves', count: 'singular' },
      it: { base: 'lupo', plural: 'lupi', gender: 'masc', count: 'singular', fem: 'lupa', fem_plural: 'lupe' },
      fr: { base: 'loup', plural: 'loups', gender: 'masc', count: 'singular', fem: 'louve', fem_plural: 'louves' },
      de: { base: 'Wolf', plural: 'Wölfe', gender: 'masc', count: 'singular', fem: 'Wölfin', fem_plural: 'Wölfinnen' },
      es: { base: 'lobo', plural: 'lobos', gender: 'masc', count: 'singular', fem: 'loba', fem_plural: 'lobas' },
      ja: { base: '狼', count: 'singular', reading: 'おおかみ' },
      pt: { base: 'lobo', plural: 'lobos', gender: 'masc', count: 'singular', fem: 'loba', fem_plural: 'lobas' },
    },
  },
  {
    id: 'COW',
    role: 'noun',
    description: 'an adult female bovine kept for milk or meat',
    definition: glossOf('MAMMAL', 'BIG'),
    emoji: '🐄',
    animate: true,
    forms: {
      en: { base: 'cow', plural: 'cows', count: 'singular' },
      it: { base: 'mucca', plural: 'mucche', gender: 'fem', count: 'singular' },
      fr: { base: 'vache', plural: 'vaches', gender: 'fem', count: 'singular' },
      de: { base: 'Kuh', plural: 'Kühe', gender: 'fem', count: 'singular' },
      es: { base: 'vaca', plural: 'vacas', gender: 'fem', count: 'singular' },
      ja: { base: '牛', count: 'singular', reading: 'うし' },
      pt: { base: 'vaca', plural: 'vacas', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'OX',
    role: 'noun',
    description: 'a castrated adult male bovine used as a draft animal',
    emoji: '🐂',
    animate: true,
    forms: {
      en: { base: 'ox', plural: 'oxen', count: 'singular' },
      it: { base: 'bue', plural: 'buoi', gender: 'masc', count: 'singular' },
      fr: { base: 'bœuf', plural: 'bœufs', gender: 'masc', count: 'singular' },
      de: { base: 'Ochse', plural: 'Ochsen', gender: 'masc', count: 'singular', weak: '1' },
      es: { base: 'buey', plural: 'bueyes', gender: 'masc', count: 'singular' },
      ja: { base: '雄牛', count: 'singular', reading: 'おうし' },
      pt: { base: 'boi', plural: 'bois', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'BUTCHER',
    role: 'noun',
    description: 'a person who slaughters animals or sells meat',
    emoji: '🔪',
    animate: true,
    human: true,
    forms: {
      en: { base: 'butcher', plural: 'butchers', count: 'singular' },
      it: { base: 'macellaio', plural: 'macellai', gender: 'masc', count: 'singular', fem: 'macellaia', fem_plural: 'macellaie' },
      fr: { base: 'boucher', plural: 'bouchers', gender: 'masc', count: 'singular', fem: 'bouchère', fem_plural: 'bouchères' },
      de: { base: 'Metzger', plural: 'Metzger', gender: 'masc', count: 'singular', fem: 'Metzgerin', fem_plural: 'Metzgerinnen' },
      es: { base: 'carnicero', plural: 'carniceros', gender: 'masc', count: 'singular', fem: 'carnicera', fem_plural: 'carniceras' },
      ja: { base: '肉屋', count: 'singular', reading: 'にくや' },
      pt: { base: 'açougueiro', plural: 'açougueiros', gender: 'masc', count: 'singular', fem: 'açougueira', fem_plural: 'açougueiras' },
    },
  },
  {
    id: 'ANGEL',
    role: 'noun',
    description: 'a spiritual being; a messenger of God',
    emoji: '👼',
    animate: true,
    forms: {
      en: { base: 'angel', plural: 'angels', count: 'singular' },
      it: { base: 'angelo', plural: 'angeli', gender: 'masc', count: 'singular' },
      fr: { base: 'ange', plural: 'anges', gender: 'masc', count: 'singular' },
      de: { base: 'Engel', plural: 'Engel', gender: 'masc', count: 'singular' },
      es: { base: 'ángel', plural: 'ángeles', gender: 'masc', count: 'singular' },
      ja: { base: '天使', count: 'singular', reading: 'てんし' },
      pt: { base: 'anjo', plural: 'anjos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'DEATH',
    role: 'noun',
    description: 'the end of life; the state of being dead',
    emoji: '💀',
    forms: {
      en: { base: 'death', plural: 'deaths', count: 'singular' },
      it: { base: 'morte', plural: 'morti', gender: 'fem', count: 'singular' },
      fr: { base: 'mort', plural: 'morts', gender: 'fem', count: 'singular' },
      de: { base: 'Tod', plural: 'Tode', gender: 'masc', count: 'singular' },
      es: { base: 'muerte', plural: 'muertes', gender: 'fem', count: 'singular' },
      ja: { base: '死', count: 'singular', reading: 'し' },
      pt: { base: 'morte', plural: 'mortes', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'MOUSE',
    role: 'noun',
    description: 'a small rodent',
    definition: glossOf('MAMMAL', 'SMALL'),
    emoji: '🐭',
    animate: true,
    synonym: 'rodent',
    isA: 'MAMMAL',
    forms: {
      en: { base: 'mouse', plural: 'mice', count: 'singular' },
      it: { base: 'topo', plural: 'topi', gender: 'masc', count: 'singular' },
      fr: { base: 'souris', plural: 'souris', gender: 'fem', count: 'singular' },
      de: { base: 'Maus', plural: 'Mäuse', gender: 'fem', count: 'singular' },
      es: { base: 'ratón', plural: 'ratones', gender: 'masc', count: 'singular' },
      ja: { base: 'ネズミ', count: 'singular', reading: 'ねずみ' },
      pt: { base: 'rato', plural: 'ratos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'STICK',
    role: 'noun',
    description: 'a thin elongated piece of wood',
    emoji: '🥢',
    synonym: 'rod',
    forms: {
      en: { base: 'stick', plural: 'sticks', count: 'singular' },
      it: { base: 'bastone', plural: 'bastoni', gender: 'masc', count: 'singular' },
      fr: { base: 'bâton', plural: 'bâtons', gender: 'masc', count: 'singular' },
      de: { base: 'Stock', plural: 'Stöcke', gender: 'masc', count: 'singular' },
      es: { base: 'palo', plural: 'palos', gender: 'masc', count: 'singular' },
      ja: { base: '棒', count: 'singular', reading: 'ぼう' },
      pt: { base: 'pau', plural: 'paus', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'FIRE',
    role: 'noun',
    description: 'the phenomenon of combustion; flame',
    emoji: '🔥',
    forms: {
      en: { base: 'fire', plural: 'fires', count: 'singular' },
      it: { base: 'fuoco', plural: 'fuochi', gender: 'masc', count: 'singular' },
      fr: { base: 'feu', plural: 'feux', gender: 'masc', count: 'singular' },
      de: { base: 'Feuer', plural: 'Feuer', gender: 'neut', count: 'singular' },
      es: { base: 'fuego', plural: 'fuegos', gender: 'masc', count: 'singular' },
      ja: { base: '火', count: 'singular', reading: 'ひ' },
      pt: { base: 'fogo', plural: 'fogos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'FATHER',
    role: 'noun',
    description: 'a male parent',
    emoji: '👨',
    animate: true,
    human: true,
    forms: {
      en: { base: 'father', plural: 'fathers', count: 'singular' },
      it: { base: 'padre', plural: 'padri', gender: 'masc', count: 'singular' },
      fr: { base: 'père', plural: 'pères', gender: 'masc', count: 'singular' },
      de: { base: 'Vater', plural: 'Väter', gender: 'masc', count: 'singular' },
      es: { base: 'padre', plural: 'padres', gender: 'masc', count: 'singular' },
      ja: { base: '父', count: 'singular', reading: 'ちち' },
      pt: { base: 'pai', plural: 'pais', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'MARKET',
    role: 'noun',
    description: 'a place where goods are bought and sold',
    emoji: '🏪',
    forms: {
      en: { base: 'market', plural: 'markets', count: 'singular' },
      it: { base: 'mercato', plural: 'mercati', gender: 'masc', count: 'singular' },
      fr: { base: 'marché', plural: 'marchés', gender: 'masc', count: 'singular' },
      de: { base: 'Markt', plural: 'Märkte', gender: 'masc', count: 'singular' },
      es: { base: 'mercado', plural: 'mercados', gender: 'masc', count: 'singular' },
      ja: { base: '市場', count: 'singular', reading: 'いちば' },
      pt: { base: 'mercado', plural: 'mercados', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'COIN',
    role: 'noun',
    description: 'a small round piece of metal used as money',
    emoji: '🪙',
    forms: {
      en: { base: 'coin', plural: 'coins', count: 'singular' },
      it: { base: 'moneta', plural: 'monete', gender: 'fem', count: 'singular' },
      fr: { base: 'pièce', plural: 'pièces', gender: 'fem', count: 'singular' },
      de: { base: 'Münze', plural: 'Münzen', gender: 'fem', count: 'singular' },
      es: { base: 'moneda', plural: 'monedas', gender: 'fem', count: 'singular' },
      ja: { base: '硬貨', count: 'singular', reading: 'こうか' },
      pt: { base: 'moeda', plural: 'moedas', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'LEGEND',
    role: 'noun',
    description: 'a traditional story or a famous person',
    emoji: '📜',
    forms: {
      en: { base: 'legend', plural: 'legends', count: 'singular' },
      it: { base: 'leggenda', plural: 'leggende', gender: 'fem', count: 'singular' },
      fr: { base: 'légende', plural: 'légendes', gender: 'fem', count: 'singular' },
      de: { base: 'Legende', plural: 'Legenden', gender: 'fem', count: 'singular' },
      es: { base: 'leyenda', plural: 'leyendas', gender: 'fem', count: 'singular' },
      ja: { base: '伝説', count: 'singular', reading: 'でんせつ' },
      pt: { base: 'lenda', plural: 'lendas', gender: 'fem', count: 'singular' },
    },
  },

  {
    id: 'WING',
    role: 'noun',
    description: 'a limb or organ used for flight',
    emoji: '🪽',
    forms: {
      en: { base: 'wing', plural: 'wings', count: 'singular' },
      it: { base: 'ala', plural: 'ali', gender: 'fem', count: 'singular' },
      fr: { base: 'aile', plural: 'ailes', gender: 'fem', count: 'singular' },
      de: { base: 'Flügel', plural: 'Flügel', gender: 'masc', count: 'singular' },
      es: { base: 'ala', plural: 'alas', gender: 'fem', count: 'singular' },
      ja: { base: '翼', count: 'singular', reading: 'つばさ' },
      pt: { base: 'asa', plural: 'asas', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'YOUNG_MAN',
    role: 'noun',
    description: 'a young male person',
    definition: glossOf('PERSON', 'YOUNG', 'MALE'),
    emoji: '👱‍♂️',
    animate: true,
    human: true,
    synonym: 'youth',
    isA: 'PERSON',
    forms: {
      en: { base: 'young man', plural: 'young men', count: 'singular' },
      it: { base: 'giovane', plural: 'giovani', gender: 'masc', count: 'singular' },
      fr: { base: 'jeune homme', plural: 'jeunes hommes', gender: 'masc', count: 'singular' },
      de: { base: 'Bursche', plural: 'Burschen', gender: 'masc', count: 'singular', weak: '1' },
      es: { base: 'joven', plural: 'jóvenes', gender: 'masc', count: 'singular' },
      ja: { base: '青年', count: 'singular', reading: 'せいねん' },
      pt: { base: 'jovem', plural: 'jovens', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'YOUNG_WOMAN',
    role: 'noun',
    description: 'a young female person',
    definition: glossOf('PERSON', 'YOUNG', 'FEMALE'),
    emoji: '👱‍♀️',
    animate: true,
    human: true,
    synonym: 'youth',
    isA: 'PERSON',
    forms: {
      en: { base: 'young woman', plural: 'young women', count: 'singular' },
      it: { base: 'giovane', plural: 'giovani', gender: 'fem', count: 'singular' },
      fr: { base: 'jeune femme', plural: 'jeunes femmes', gender: 'fem', count: 'singular' },
      // "jung" is stored as the head's inherent attributive adjective, not baked into the
      // lemma: German declines it for case + determiner ("die junge Frau", "die jungen
      // Frauen", "von einer jungen Frau"), so no single surface string is right everywhere.
      de: { base: 'Frau', plural: 'Frauen', adjective: 'jung', gender: 'fem', count: 'singular' },
      es: { base: 'joven', plural: 'jóvenes', gender: 'fem', count: 'singular' },
      ja: { base: '若い女性', count: 'singular', reading: 'わかいじょせい' },
      pt: { base: 'jovem', plural: 'jovens', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'PRISON',
    role: 'noun',
    description: 'a building where people are confined as punishment',
    emoji: '🔒',
    forms: {
      en: { base: 'prison', plural: 'prisons', count: 'singular' },
      it: { base: 'prigione', plural: 'prigioni', gender: 'fem', count: 'singular' },
      fr: { base: 'prison', plural: 'prisons', gender: 'fem', count: 'singular' },
      de: { base: 'Gefängnis', plural: 'Gefängnisse', gender: 'neut', count: 'singular' },
      es: { base: 'prisión', plural: 'prisiones', gender: 'fem', count: 'singular' },
      ja: { base: '刑務所', count: 'singular', reading: 'けいむしょ' },
      pt: { base: 'prisão', plural: 'prisões', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'BUILDER',
    role: 'noun',
    description: 'a person who constructs things',
    definition: whoGloss('PERSON', 'MAKE', 'OBJECT_THING'),
    emoji: '👷',
    animate: true,
    human: true,
    isA: 'PERSON',
    forms: {
      en: { base: 'builder', plural: 'builders', count: 'singular' },
      it: { base: 'costruttore', plural: 'costruttori', gender: 'masc', count: 'singular', fem: 'costruttrice', fem_plural: 'costruttrici' },
      fr: { base: 'constructeur', plural: 'constructeurs', gender: 'masc', count: 'singular', fem: 'constructrice', fem_plural: 'constructrices' },
      de: { base: 'Bauarbeiter', plural: 'Bauarbeiter', gender: 'masc', count: 'singular', fem: 'Bauarbeiterin', fem_plural: 'Bauarbeiterinnen' },
      es: { base: 'constructor', plural: 'constructores', gender: 'masc', count: 'singular', fem: 'constructora', fem_plural: 'constructoras' },
      ja: { base: '建築者', count: 'singular', reading: 'けんちくしゃ' },
      pt: { base: 'construtor', plural: 'construtores', gender: 'masc', count: 'singular', fem: 'construtora', fem_plural: 'construtoras' },
    },
  },
  {
    id: 'CREATOR',
    role: 'noun',
    description: 'someone or something that creates things',
    definition: whoGloss('PERSON', 'MAKE', 'OBJECT_THING'),
    emoji: '✨',
    animate: true,
    forms: {
      en: { base: 'creator', plural: 'creators', count: 'singular' },
      it: { base: 'creatore', plural: 'creatori', gender: 'masc', count: 'singular', fem: 'creatrice', fem_plural: 'creatrici' },
      fr: { base: 'créateur', plural: 'créateurs', gender: 'masc', count: 'singular', fem: 'créatrice', fem_plural: 'créatrices' },
      de: { base: 'Schöpfer', plural: 'Schöpfer', gender: 'masc', count: 'singular', fem: 'Schöpferin', fem_plural: 'Schöpferinnen' },
      es: { base: 'creador', plural: 'creadores', gender: 'masc', count: 'singular', fem: 'creadora', fem_plural: 'creadoras' },
      ja: { base: '創造者', count: 'singular', reading: 'そうぞうしゃ' },
      pt: { base: 'criador', plural: 'criadores', gender: 'masc', count: 'singular', fem: 'criadora', fem_plural: 'criadoras' },
    },
  },
  {
    id: 'PHRASE',
    role: 'noun',
    description: 'a small group of words expressing a concept',
    emoji: '💬',
    forms: {
      en: { base: 'phrase', plural: 'phrases', count: 'singular' },
      it: { base: 'frase', plural: 'frasi', gender: 'fem', count: 'singular' },
      fr: { base: 'phrase', plural: 'phrases', gender: 'fem', count: 'singular' },
      de: { base: 'Phrase', plural: 'Phrasen', gender: 'fem', count: 'singular' },
      es: { base: 'frase', plural: 'frases', gender: 'fem', count: 'singular' },
      ja: { base: 'フレーズ', count: 'singular', reading: 'ふれーず' },
      pt: { base: 'frase', plural: 'frases', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'SLOT',
    role: 'noun',
    description: 'a narrow opening or an allotted position',
    emoji: '🎰',
    forms: {
      en: { base: 'slot', plural: 'slots', count: 'singular' },
      it: { base: 'fessura', plural: 'fessure', gender: 'fem', count: 'singular' },
      fr: { base: 'fente', plural: 'fentes', gender: 'fem', count: 'singular' },
      de: { base: 'Schlitz', plural: 'Schlitze', gender: 'masc', count: 'singular' },
      es: { base: 'ranura', plural: 'ranuras', gender: 'fem', count: 'singular' },
      ja: { base: 'スロット', count: 'singular', reading: 'すろっと' },
      pt: { base: 'ranhura', plural: 'ranhuras', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'SLOT_COMPUTING',
    role: 'noun',
    description: 'a reserved position in memory or a schedule (informatics)',
    emoji: '🧩',
    forms: {
      en: { base: 'slot', plural: 'slots', count: 'singular' },
      it: { base: 'slot', plural: 'slot', gender: 'masc', count: 'singular' },
      fr: { base: 'slot', plural: 'slots', gender: 'masc', count: 'singular' },
      de: { base: 'Slot', plural: 'Slots', gender: 'masc', count: 'singular' },
      es: { base: 'slot', plural: 'slots', gender: 'masc', count: 'singular' },
      ja: { base: 'スロット', count: 'singular', reading: 'すろっと' },
      pt: { base: 'slot', plural: 'slots', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'SLOT_MACHINE',
    role: 'noun',
    description: 'a coin-operated gambling machine with spinning reels',
    emoji: '🎰',
    forms: {
      en: { base: 'slot machine', plural: 'slot machines', count: 'singular' },
      it: { base: 'slot machine', plural: 'slot machine', gender: 'fem', count: 'singular' },
      fr: { base: 'machine à sous', plural: 'machines à sous', gender: 'fem', count: 'singular' },
      de: { base: 'Spielautomat', plural: 'Spielautomaten', gender: 'masc', count: 'singular' },
      es: { base: 'máquina tragaperras', plural: 'máquinas tragaperras', gender: 'fem', count: 'singular' },
      ja: { base: 'スロットマシン', count: 'singular', reading: 'すろっとましん' },
      pt: { base: 'caça-níqueis', plural: 'caça-níqueis', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'WORD',
    role: 'noun',
    description: 'a single unit of language',
    emoji: '🔤',
    forms: {
      en: { base: 'word', plural: 'words', count: 'singular' },
      it: { base: 'parola', plural: 'parole', gender: 'fem', count: 'singular' },
      fr: { base: 'mot', plural: 'mots', gender: 'masc', count: 'singular' },
      de: { base: 'Wort', plural: 'Wörter', gender: 'neut', count: 'singular' },
      es: { base: 'palabra', plural: 'palabras', gender: 'fem', count: 'singular' },
      ja: { base: '単語', count: 'singular', reading: 'たんご' },
      pt: { base: 'palavra', plural: 'palavras', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'TRANSLATION',
    role: 'noun',
    description: 'a rendering of text or speech from one language into another',
    emoji: '🌐',
    forms: {
      en: { base: 'translation', plural: 'translations', count: 'singular' },
      it: { base: 'traduzione', plural: 'traduzioni', gender: 'fem', count: 'singular' },
      fr: { base: 'traduction', plural: 'traductions', gender: 'fem', count: 'singular' },
      de: { base: 'Übersetzung', plural: 'Übersetzungen', gender: 'fem', count: 'singular' },
      es: { base: 'traducción', plural: 'traducciones', gender: 'fem', count: 'singular' },
      ja: { base: '翻訳', count: 'singular', reading: 'ほんやく' },
      pt: { base: 'tradução', plural: 'traduções', gender: 'fem', count: 'singular' },
    },
  },

  {
    id: 'CONTINENT',
    role: 'noun',
    description: 'one of the earth’s great landmasses',
    emoji: '🗺️',
    // The hypernym of AFRICA. An ordinary common noun — countable, and it takes articles the
    // normal way ("a continent", "the continents"), where its proper-noun child does not. That
    // asymmetry is carried by the `proper` / `countable` flags, not by the tree; a rule may test
    // them, but they never enter the specificity contest. Same shape as LANGUAGE over GERMAN.
    forms: {
      en: { base: 'continent',  plural: 'continents',  count: 'singular' },
      it: { base: 'continente', plural: 'continenti',  gender: 'masc', count: 'singular' },
      fr: { base: 'continent',  plural: 'continents',  gender: 'masc', count: 'singular' },
      de: { base: 'Kontinent',  plural: 'Kontinente',  gender: 'masc', count: 'singular' },
      es: { base: 'continente', plural: 'continentes', gender: 'masc', count: 'singular' },
      ja: { base: '大陸',       count: 'singular', reading: 'たいりく' },
      pt: { base: 'continente', plural: 'continentes', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'AFRICA',
    role: 'noun',
    description: 'the continent south of the Mediterranean',
    emoji: '🌍',
    // A proper noun: no plural, and the article is the language's to fix — English, German,
    // Spanish and Japanese take none; Italian, French and Portuguese take the definite one.
    proper: true,
    countable: false,
    isA: 'CONTINENT',
    forms: {
      en: { base: 'Africa', count: 'singular' },
      it: { base: 'Africa', gender: 'fem', count: 'singular' },
      fr: { base: 'Afrique', gender: 'fem', count: 'singular' },
      de: { base: 'Afrika', gender: 'neut', count: 'singular' },
      es: { base: 'África', gender: 'fem', count: 'singular' },
      ja: { base: 'アフリカ', count: 'singular' },
      pt: { base: 'África', gender: 'fem', count: 'singular' },
    },
  },

  // The remaining continents, all shaped like AFRICA above: proper, uncountable, no plural,
  // feminine in the Romance languages and neuter in German. Japanese takes 北米 / 南米 for the
  // Americas rather than a transliteration — they are the ordinary words.
  {
    id: 'EUROPE',
    role: 'noun',
    description: 'the continent north of the Mediterranean',
    emoji: '🇪🇺',
    proper: true,
    countable: false,
    isA: 'CONTINENT',
    forms: {
      en: { base: 'Europe',    count: 'singular' },
      it: { base: 'Europa',    gender: 'fem',  count: 'singular' },
      fr: { base: 'Europe',    gender: 'fem',  count: 'singular' },
      de: { base: 'Europa',    gender: 'neut', count: 'singular' },
      es: { base: 'Europa',    gender: 'fem',  count: 'singular' },
      ja: { base: 'ヨーロッパ', count: 'singular' },
      pt: { base: 'Europa',    gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'ASIA',
    role: 'noun',
    description: 'the largest continent, east of Europe',
    emoji: '🌏',
    proper: true,
    countable: false,
    isA: 'CONTINENT',
    forms: {
      en: { base: 'Asia',   count: 'singular' },
      it: { base: 'Asia',   gender: 'fem',  count: 'singular' },
      fr: { base: 'Asie',   gender: 'fem',  count: 'singular' },
      de: { base: 'Asien',  gender: 'neut', count: 'singular' },
      es: { base: 'Asia',   gender: 'fem',  count: 'singular' },
      ja: { base: 'アジア', count: 'singular' },
      pt: { base: 'Ásia',   gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'OCEANIA',
    role: 'noun',
    description: 'the continent of Australia and the Pacific islands',
    emoji: '🏝️',
    proper: true,
    countable: false,
    isA: 'CONTINENT',
    forms: {
      en: { base: 'Oceania',    count: 'singular' },
      it: { base: 'Oceania',    gender: 'fem',  count: 'singular' },
      fr: { base: 'Océanie',    gender: 'fem',  count: 'singular' },
      de: { base: 'Ozeanien',   gender: 'neut', count: 'singular' },
      es: { base: 'Oceanía',    gender: 'fem',  count: 'singular' },
      ja: { base: 'オセアニア', count: 'singular' },
      pt: { base: 'Oceania',    gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'NORTH_AMERICA',
    role: 'noun',
    description: 'the continent north of the isthmus of Panama',
    emoji: '🌎',
    proper: true,
    countable: false,
    isA: 'CONTINENT',
    forms: {
      en: { base: 'North America',     count: 'singular' },
      it: { base: 'America del Nord',  gender: 'fem',  count: 'singular' },
      fr: { base: 'Amérique du Nord',  gender: 'fem',  count: 'singular' },
      de: { base: 'Nordamerika',       gender: 'neut', count: 'singular' },
      es: { base: 'América del Norte', gender: 'fem',  count: 'singular' },
      ja: { base: '北米',              count: 'singular', reading: 'ほくべい' },
      pt: { base: 'América do Norte',  gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'SOUTH_AMERICA',
    role: 'noun',
    description: 'the continent south of the isthmus of Panama',
    emoji: '🌎',
    proper: true,
    countable: false,
    isA: 'CONTINENT',
    forms: {
      en: { base: 'South America',    count: 'singular' },
      it: { base: 'America del Sud',  gender: 'fem',  count: 'singular' },
      fr: { base: 'Amérique du Sud',  gender: 'fem',  count: 'singular' },
      de: { base: 'Südamerika',       gender: 'neut', count: 'singular' },
      es: { base: 'América del Sur',  gender: 'fem',  count: 'singular' },
      ja: { base: '南米',             count: 'singular', reading: 'なんべい' },
      pt: { base: 'América do Sul',   gender: 'fem',  count: 'singular' },
    },
  },
  {
    id: 'ANTARCTICA',
    role: 'noun',
    description: 'the continent at the south pole',
    emoji: '🧊',
    proper: true,
    countable: false,
    isA: 'CONTINENT',
    forms: {
      en: { base: 'Antarctica',   count: 'singular' },
      it: { base: 'Antartide',    gender: 'fem',  count: 'singular' },
      fr: { base: 'Antarctique',  gender: 'masc', count: 'singular' },
      // The odd one out among the continents: German and Spanish leave every other continent
      // bare but article this one ("die Antarktis", "la Antártida"). takes_article marks that;
      // only de.ts and es.ts read it, and only for proper nouns.
      de: { base: 'Antarktis',    gender: 'fem',  takes_article: '1', count: 'singular' },
      es: { base: 'Antártida',    gender: 'fem',  takes_article: '1', count: 'singular' },
      ja: { base: '南極大陸',     count: 'singular', reading: 'なんきょくたいりく' },
      pt: { base: 'Antártida',    gender: 'fem',  count: 'singular' },
    },
  },

  {
    id: 'LANGUAGE',
    role: 'noun',
    description: 'a system of words used by a people',
    emoji: '🔡',
    // The hypernym of the seven language names below. Countable, unlike its children — one
    // says "seven languages" but not "seven Germans" (of the language). Countability is a
    // flag a rule tests, not a level in the tree, so parent and child differ freely here.
    // Feminine everywhere it has gender except Spanish: "idioma" is masculine despite the
    // -a ending (it is Greek-derived), and takes "el idioma" / "los idiomas" straightforwardly
    // from its declared gender — no stressed_a-style special case needed.
    forms: {
      en: { base: 'language', plural: 'languages', count: 'singular' },
      it: { base: 'lingua', plural: 'lingue', gender: 'fem', count: 'singular' },
      fr: { base: 'langue', plural: 'langues', gender: 'fem', count: 'singular' },
      de: { base: 'Sprache', plural: 'Sprachen', gender: 'fem', count: 'singular' },
      es: { base: 'idioma', plural: 'idiomas', gender: 'masc', count: 'singular' },
      ja: { base: '言語', count: 'singular', reading: 'げんご' },
      pt: { base: 'língua', plural: 'línguas', gender: 'fem', count: 'singular' },
    },
  },

  // ── Language names ────────────────────────────────────────────────
  // The seven UI languages, as mass nouns, so the engine can render each language's name
  // in any language (e.g. the header language selector shows them in the current UI
  // language). English capitalises language names; the others lower-case them; German
  // capitalises all nouns. Uncountable (no plural), gender masc in the Romance languages,
  // neuter in German. All seven are LANGUAGE. See backend languages.ts for the
  // LanguageCode → concept mapping.
  {
    id: 'ENGLISH',
    role: 'noun',
    description: 'the English language',
    emoji: '🇬🇧',
    countable: false,
    isA: 'LANGUAGE',
    forms: {
      en: { base: 'English', count: 'singular' },
      it: { base: 'inglese', gender: 'masc', count: 'singular' },
      fr: { base: 'anglais', gender: 'masc', count: 'singular' },
      de: { base: 'Englisch', gender: 'neut', count: 'singular' },
      es: { base: 'inglés', gender: 'masc', count: 'singular' },
      ja: { base: '英語', count: 'singular', reading: 'えいご' },
      pt: { base: 'inglês', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'ITALIAN',
    role: 'noun',
    description: 'the Italian language',
    emoji: '🇮🇹',
    countable: false,
    isA: 'LANGUAGE',
    forms: {
      en: { base: 'Italian', count: 'singular' },
      it: { base: 'italiano', gender: 'masc', count: 'singular' },
      fr: { base: 'italien', gender: 'masc', count: 'singular' },
      de: { base: 'Italienisch', gender: 'neut', count: 'singular' },
      es: { base: 'italiano', gender: 'masc', count: 'singular' },
      ja: { base: 'イタリア語', count: 'singular', reading: 'いたりあご' },
      pt: { base: 'italiano', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'FRENCH',
    role: 'noun',
    description: 'the French language',
    emoji: '🇫🇷',
    countable: false,
    isA: 'LANGUAGE',
    forms: {
      en: { base: 'French', count: 'singular' },
      it: { base: 'francese', gender: 'masc', count: 'singular' },
      fr: { base: 'français', gender: 'masc', count: 'singular' },
      de: { base: 'Französisch', gender: 'neut', count: 'singular' },
      es: { base: 'francés', gender: 'masc', count: 'singular' },
      ja: { base: 'フランス語', count: 'singular', reading: 'ふらんすご' },
      pt: { base: 'francês', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'GERMAN',
    role: 'noun',
    description: 'the German language',
    emoji: '🇩🇪',
    countable: false,
    isA: 'LANGUAGE',
    forms: {
      en: { base: 'German', count: 'singular' },
      it: { base: 'tedesco', gender: 'masc', count: 'singular' },
      fr: { base: 'allemand', gender: 'masc', count: 'singular' },
      de: { base: 'Deutsch', gender: 'neut', count: 'singular' },
      es: { base: 'alemán', gender: 'masc', count: 'singular' },
      ja: { base: 'ドイツ語', count: 'singular', reading: 'どいつご' },
      pt: { base: 'alemão', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'SPANISH',
    role: 'noun',
    description: 'the Spanish language',
    emoji: '🇪🇸',
    countable: false,
    isA: 'LANGUAGE',
    forms: {
      en: { base: 'Spanish', count: 'singular' },
      it: { base: 'spagnolo', gender: 'masc', count: 'singular' },
      fr: { base: 'espagnol', gender: 'masc', count: 'singular' },
      de: { base: 'Spanisch', gender: 'neut', count: 'singular' },
      es: { base: 'español', gender: 'masc', count: 'singular' },
      ja: { base: 'スペイン語', count: 'singular', reading: 'すぺいんご' },
      pt: { base: 'espanhol', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'JAPANESE',
    role: 'noun',
    description: 'the Japanese language',
    emoji: '🇯🇵',
    countable: false,
    isA: 'LANGUAGE',
    forms: {
      en: { base: 'Japanese', count: 'singular' },
      it: { base: 'giapponese', gender: 'masc', count: 'singular' },
      fr: { base: 'japonais', gender: 'masc', count: 'singular' },
      de: { base: 'Japanisch', gender: 'neut', count: 'singular' },
      es: { base: 'japonés', gender: 'masc', count: 'singular' },
      ja: { base: '日本語', count: 'singular', reading: 'にほんご' },
      pt: { base: 'japonês', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'PORTUGUESE',
    role: 'noun',
    description: 'the Portuguese language',
    emoji: '🇵🇹',
    countable: false,
    isA: 'LANGUAGE',
    forms: {
      en: { base: 'Portuguese', count: 'singular' },
      it: { base: 'portoghese', gender: 'masc', count: 'singular' },
      fr: { base: 'portugais', gender: 'masc', count: 'singular' },
      de: { base: 'Portugiesisch', gender: 'neut', count: 'singular' },
      es: { base: 'portugués', gender: 'masc', count: 'singular' },
      ja: { base: 'ポルトガル語', count: 'singular', reading: 'ぽるとがるご' },
      pt: { base: 'português', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'PERIOD_TIME',
    role: 'noun',
    description: 'a stretch of time with a beginning and an end',
    emoji: '⏳',
    synonym: 'span of time',
    forms: {
      en: { base: 'period', plural: 'periods', count: 'singular' },
      it: { base: 'periodo', plural: 'periodi', gender: 'masc', count: 'singular' },
      fr: { base: 'période', plural: 'périodes', gender: 'fem', count: 'singular' },
      de: { base: 'Zeitraum', plural: 'Zeiträume', gender: 'masc', count: 'singular' },
      es: { base: 'período', plural: 'períodos', gender: 'masc', count: 'singular' },
      ja: { base: '期間', count: 'singular', reading: 'きかん' },
      pt: { base: 'período', plural: 'períodos', gender: 'masc', count: 'singular' },
    },
  },

  // ── Grammar terms ─────────────────────────────────────────────────
  // The metalinguistic vocabulary the builder itself is made of — the words for the parts of
  // speech and the subject position. Seeded so the engine can render the builder's own slot
  // labels in the current UI language. SUBJECT is suffixed _GRAMMAR because the plain word is
  // ambiguous (topic, school subject) and that sense may be seeded later.
  {
    id: 'SUBJECT_GRAMMAR',
    role: 'noun',
    description: 'the noun phrase a clause predicates something of (grammar)',
    emoji: '🎯',
    synonym: 'grammar',
    forms: {
      en: { base: 'subject', plural: 'subjects', count: 'singular' },
      it: { base: 'soggetto', plural: 'soggetti', gender: 'masc', count: 'singular' },
      fr: { base: 'sujet', plural: 'sujets', gender: 'masc', count: 'singular' },
      de: { base: 'Subjekt', plural: 'Subjekte', gender: 'neut', count: 'singular' },
      es: { base: 'sujeto', plural: 'sujetos', gender: 'masc', count: 'singular' },
      ja: { base: '主語', count: 'singular', reading: 'しゅご' },
      pt: { base: 'sujeito', plural: 'sujeitos', gender: 'masc', count: 'singular' },
    },
  },
  {
    // The complement a transitive verb's action falls on, not a physical thing — suffixed like
    // SUBJECT_GRAMMAR because the plain word means both, and only this sense is seeded
    // (ja 目的語, not 物体).
    id: 'OBJECT_GRAMMAR',
    role: 'noun',
    description: 'the noun phrase a verb\'s action falls on (grammar)',
    emoji: '🥅',
    synonym: 'grammar',
    forms: {
      en: { base: 'object', plural: 'objects', count: 'singular' },
      it: { base: 'complemento oggetto', plural: 'complementi oggetto', gender: 'masc', count: 'singular' },
      fr: { base: 'complément d\'objet', plural: 'compléments d\'objet', gender: 'masc', count: 'singular' },
      de: { base: 'Objekt', plural: 'Objekte', gender: 'neut', count: 'singular' },
      es: { base: 'complemento', plural: 'complementos', gender: 'masc', count: 'singular' },
      ja: { base: '目的語', count: 'singular', reading: 'もくてきご' },
      pt: { base: 'objeto', plural: 'objetos', gender: 'masc', count: 'singular' },
    },
  },
  {
    // The name of the predicative complement — what a copular verb predicates of its subject
    // ("becomes a legend", "seems happy"). Seeded as one noun per language rather than composed,
    // because no two traditions cut it the same way: fr/pt name it after the subject, es names it
    // alone (the attribute is the subject's by definition — "atributo del sujeto" is an anglicism),
    // and de must be the wider Prädikativ, not Prädikatsnomen, since the slot also takes an
    // adjective. ja distinguishes it from the object complement (目的格補語) by the case name.
    id: 'SUBJECT_COMPLEMENT',
    role: 'noun',
    description: 'the complement a copular verb predicates of its subject (grammar)',
    emoji: '🪞',
    synonym: 'grammar',
    forms: {
      en: { base: 'subject complement', plural: 'subject complements', count: 'singular' },
      it: { base: 'complemento predicativo del soggetto', plural: 'complementi predicativi del soggetto', gender: 'masc', count: 'singular' },
      fr: { base: 'attribut du sujet', plural: 'attributs du sujet', gender: 'masc', count: 'singular' },
      de: { base: 'Prädikativ', plural: 'Prädikative', gender: 'neut', count: 'singular' },
      es: { base: 'atributo', plural: 'atributos', gender: 'masc', count: 'singular' },
      ja: { base: '主格補語', count: 'singular', reading: 'しゅかくほご' },
      pt: { base: 'predicativo do sujeito', plural: 'predicativos do sujeito', gender: 'masc', count: 'singular' },
    },
  },
  {
    // The name of the instrumental complement — the means or tool an action is carried out
    // with ("start with a word"). Each tradition names it its own way: a bare adjective-turned-
    // noun in en/de (the Indo-European case name), a full phrase in the Romance ones. Only the
    // singular is used (it titles a slot), but the plural is seeded like every other noun.
    id: 'INSTRUMENTAL',
    role: 'noun',
    description: 'the complement naming the means an action is carried out with (grammar)',
    emoji: '🔧',
    synonym: 'grammar',
    forms: {
      en: { base: 'instrumental', plural: 'instrumentals', count: 'singular' },
      it: { base: 'complemento di mezzo', plural: 'complementi di mezzo', gender: 'masc', count: 'singular' },
      fr: { base: 'complément de moyen', plural: 'compléments de moyen', gender: 'masc', count: 'singular' },
      de: { base: 'Instrumental', plural: 'Instrumentale', gender: 'masc', count: 'singular' },
      es: { base: 'complemento circunstancial de instrumento', plural: 'complementos circunstanciales de instrumento', gender: 'masc', count: 'singular' },
      ja: { base: '手段語', count: 'singular', reading: 'しゅだんご' },
      pt: { base: 'adjunto adverbial de instrumento', plural: 'adjuntos adverbiais de instrumento', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'NOUN',
    role: 'noun',
    description: 'a word naming a person, place or thing (grammar)',
    emoji: '🏷️',
    forms: {
      en: { base: 'noun', plural: 'nouns', count: 'singular' },
      it: { base: 'sostantivo', plural: 'sostantivi', gender: 'masc', count: 'singular' },
      fr: { base: 'nom', plural: 'noms', gender: 'masc', count: 'singular' },
      de: { base: 'Substantiv', plural: 'Substantive', gender: 'neut', count: 'singular' },
      es: { base: 'sustantivo', plural: 'sustantivos', gender: 'masc', count: 'singular' },
      ja: { base: '名詞', count: 'singular', reading: 'めいし' },
      pt: { base: 'substantivo', plural: 'substantivos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'PRONOUN',
    role: 'noun',
    description: 'a word standing in for a noun phrase (grammar)',
    emoji: '👉',
    forms: {
      en: { base: 'pronoun', plural: 'pronouns', count: 'singular' },
      it: { base: 'pronome', plural: 'pronomi', gender: 'masc', count: 'singular' },
      fr: { base: 'pronom', plural: 'pronoms', gender: 'masc', count: 'singular' },
      de: { base: 'Pronomen', plural: 'Pronomen', gender: 'neut', count: 'singular' },
      es: { base: 'pronombre', plural: 'pronombres', gender: 'masc', count: 'singular' },
      ja: { base: '代名詞', count: 'singular', reading: 'だいめいし' },
      pt: { base: 'pronome', plural: 'pronomes', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'VERB',
    role: 'noun',
    description: 'a word expressing an action or a state (grammar)',
    emoji: '⚡',
    forms: {
      en: { base: 'verb', plural: 'verbs', count: 'singular' },
      it: { base: 'verbo', plural: 'verbi', gender: 'masc', count: 'singular' },
      fr: { base: 'verbe', plural: 'verbes', gender: 'masc', count: 'singular' },
      de: { base: 'Verb', plural: 'Verben', gender: 'neut', count: 'singular' },
      es: { base: 'verbo', plural: 'verbos', gender: 'masc', count: 'singular' },
      ja: { base: '動詞', count: 'singular', reading: 'どうし' },
      pt: { base: 'verbo', plural: 'verbos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'ADVERB',
    role: 'noun',
    description: 'a word modifying a verb, an adjective or another adverb (grammar)',
    emoji: '💨',
    forms: {
      en: { base: 'adverb', plural: 'adverbs', count: 'singular' },
      it: { base: 'avverbio', plural: 'avverbi', gender: 'masc', count: 'singular' },
      fr: { base: 'adverbe', plural: 'adverbes', gender: 'masc', count: 'singular' },
      de: { base: 'Adverb', plural: 'Adverbien', gender: 'neut', count: 'singular' },
      es: { base: 'adverbio', plural: 'adverbios', gender: 'masc', count: 'singular' },
      ja: { base: '副詞', count: 'singular', reading: 'ふくし' },
      pt: { base: 'advérbio', plural: 'advérbios', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'ADJECTIVE',
    role: 'noun',
    description: 'a word describing a noun (grammar)',
    emoji: '🎨',
    forms: {
      en: { base: 'adjective', plural: 'adjectives', count: 'singular' },
      it: { base: 'aggettivo', plural: 'aggettivi', gender: 'masc', count: 'singular' },
      fr: { base: 'adjectif', plural: 'adjectifs', gender: 'masc', count: 'singular' },
      de: { base: 'Adjektiv', plural: 'Adjektive', gender: 'neut', count: 'singular' },
      es: { base: 'adjetivo', plural: 'adjetivos', gender: 'masc', count: 'singular' },
      ja: { base: '形容詞', count: 'singular', reading: 'けいようし' },
      pt: { base: 'adjetivo', plural: 'adjetivos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'DETERMINER',
    role: 'noun',
    description: 'a word fixing the reference of a noun — the, a, this, some (grammar)',
    emoji: '🔖',
    forms: {
      en: { base: 'determiner', plural: 'determiners', count: 'singular' },
      it: { base: 'determinante', plural: 'determinanti', gender: 'masc', count: 'singular' },
      fr: { base: 'déterminant', plural: 'déterminants', gender: 'masc', count: 'singular' },
      de: { base: 'Determinativ', plural: 'Determinative', gender: 'neut', count: 'singular' },
      es: { base: 'determinante', plural: 'determinantes', gender: 'masc', count: 'singular' },
      ja: { base: '限定詞', count: 'singular', reading: 'げんていし' },
      pt: { base: 'determinante', plural: 'determinantes', gender: 'masc', count: 'singular' },
    },
  },
  // The three kinds of determiner, as each language's own grammar tradition names them. They
  // label the sections of the determiner menu — the words a user knows for the dimensions the
  // model calls identifiability / deixis / quantity (shared DeterminerCategory).
  {
    id: 'ARTICLE',
    role: 'noun',
    description: 'the determiner marking a noun as identifiable or not — the, a (grammar)',
    emoji: '📄',
    synonym: 'grammar',
    forms: {
      en: { base: 'article', plural: 'articles', count: 'singular' },
      it: { base: 'articolo', plural: 'articoli', gender: 'masc', count: 'singular' },
      fr: { base: 'article', plural: 'articles', gender: 'masc', count: 'singular' },
      de: { base: 'Artikel', plural: 'Artikel', gender: 'masc', count: 'singular' },
      es: { base: 'artículo', plural: 'artículos', gender: 'masc', count: 'singular' },
      ja: { base: '冠詞', count: 'singular', reading: 'かんし' },
      pt: { base: 'artigo', plural: 'artigos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'DEMONSTRATIVE',
    role: 'noun',
    description: 'the determiner that points — this, that (grammar)',
    emoji: '👆',
    forms: {
      en: { base: 'demonstrative', plural: 'demonstratives', count: 'singular' },
      it: { base: 'dimostrativo', plural: 'dimostrativi', gender: 'masc', count: 'singular' },
      fr: { base: 'démonstratif', plural: 'démonstratifs', gender: 'masc', count: 'singular' },
      de: { base: 'Demonstrativum', plural: 'Demonstrativa', gender: 'neut', count: 'singular' },
      es: { base: 'demostrativo', plural: 'demostrativos', gender: 'masc', count: 'singular' },
      ja: { base: '指示詞', count: 'singular', reading: 'しじし' },
      pt: { base: 'demonstrativo', plural: 'demonstrativos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'QUANTIFIER',
    role: 'noun',
    description: 'the determiner of amount — some, many, few, all, no (grammar)',
    emoji: '🔢',
    forms: {
      en: { base: 'quantifier', plural: 'quantifiers', count: 'singular' },
      it: { base: 'quantificatore', plural: 'quantificatori', gender: 'masc', count: 'singular' },
      fr: { base: 'quantifieur', plural: 'quantifieurs', gender: 'masc', count: 'singular' },
      de: { base: 'Quantor', plural: 'Quantoren', gender: 'masc', count: 'singular' },
      es: { base: 'cuantificador', plural: 'cuantificadores', gender: 'masc', count: 'singular' },
      ja: { base: '数量詞', count: 'singular', reading: 'すうりょうし' },
      pt: { base: 'quantificador', plural: 'quantificadores', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'PERIOD_SENTENCE',
    role: 'noun',
    description: 'a complete sentence built of one or more clauses (grammar)',
    emoji: '📝',
    synonym: 'sentence',
    forms: {
      en: { base: 'period', plural: 'periods', count: 'singular' },
      it: { base: 'periodo', plural: 'periodi', gender: 'masc', count: 'singular' },
      fr: { base: 'période', plural: 'périodes', gender: 'fem', count: 'singular' },
      de: { base: 'Satzgefüge', plural: 'Satzgefüge', gender: 'neut', count: 'singular' },
      es: { base: 'período', plural: 'períodos', gender: 'masc', count: 'singular' },
      ja: { base: '文', count: 'singular', reading: 'ぶん' },
      pt: { base: 'período', plural: 'períodos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'PERIOD_PUNCTUATION',
    role: 'noun',
    description: 'the full stop that ends a sentence (grammar)',
    emoji: '⏹️',
    synonym: 'full stop',
    forms: {
      en: { base: 'period', plural: 'periods', count: 'singular' },
      it: { base: 'punto', plural: 'punti', gender: 'masc', count: 'singular' },
      fr: { base: 'point', plural: 'points', gender: 'masc', count: 'singular' },
      de: { base: 'Punkt', plural: 'Punkte', gender: 'masc', count: 'singular' },
      es: { base: 'punto', plural: 'puntos', gender: 'masc', count: 'singular' },
      ja: { base: '句点', count: 'singular', reading: 'くてん' },
      pt: { base: 'ponto', plural: 'pontos', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'CONTAINER',
    role: 'noun',
    description: 'an object that holds or stores things',
    emoji: '📦',
    forms: {
      en: { base: 'container', plural: 'containers', count: 'singular' },
      it: { base: 'contenitore', plural: 'contenitori', gender: 'masc', count: 'singular' },
      fr: { base: 'récipient', plural: 'récipients', gender: 'masc', count: 'singular' },
      de: { base: 'Behälter', plural: 'Behälter', gender: 'masc', count: 'singular' },
      es: { base: 'recipiente', plural: 'recipientes', gender: 'masc', count: 'singular' },
      ja: { base: '容器', count: 'singular', reading: 'ようき' },
      pt: { base: 'recipiente', plural: 'recipientes', gender: 'masc', count: 'singular' },
    },
  },
  {
    // A drawing of how things lie in relation to each other. The Romance languages split the word
    // the geographical map fell out of: it "mappa" and es/pt "mapa" keep the drawing sense, while
    // fr "carte" and de "Karte" are the same word as a playing card or a menu — the sense is
    // settled by what it is a map *of*, which is exactly what the noun-modifier supplies.
    id: 'MAP',
    role: 'noun',
    description: 'a diagram showing how things are arranged or connected',
    emoji: '🗺️',
    forms: {
      en: { base: 'map', plural: 'maps', count: 'singular' },
      it: { base: 'mappa', plural: 'mappe', gender: 'fem', count: 'singular' },
      fr: { base: 'carte', plural: 'cartes', gender: 'fem', count: 'singular' },
      de: { base: 'Karte', plural: 'Karten', gender: 'fem', count: 'singular' },
      es: { base: 'mapa', plural: 'mapas', gender: 'masc', count: 'singular' },
      ja: { base: '地図', count: 'singular', reading: 'ちず' },
      pt: { base: 'mapa', plural: 'mapas', gender: 'masc', count: 'singular' },
    },
  },
  {
    // A point where the lines of a network meet — the graph-theory sense, which every language
    // takes from the word for a knot (it "nodo", de "Knoten", pt "nó"). Japanese does not: it
    // borrows ノード outright, and 結び目 (a knot in a rope) would not be understood of a graph.
    id: 'NODE',
    role: 'noun',
    description: 'a point where the lines of a network meet',
    emoji: '⚫',
    forms: {
      en: { base: 'node', plural: 'nodes', count: 'singular' },
      it: { base: 'nodo', plural: 'nodi', gender: 'masc', count: 'singular' },
      fr: { base: 'nœud', plural: 'nœuds', gender: 'masc', count: 'singular' },
      de: { base: 'Knoten', plural: 'Knoten', gender: 'masc', count: 'singular' },
      es: { base: 'nodo', plural: 'nodos', gender: 'masc', count: 'singular' },
      ja: { base: 'ノード', count: 'singular', reading: 'のーど' },
      pt: { base: 'nó', plural: 'nós', gender: 'masc', count: 'singular' },
    },
  },
  {
    // The way two things stand to one another — what an edge of the map draws. Feminine across
    // the Romance languages (it "relazione", es "relación"), which is what makes an adjective
    // agreeing with it come out feminine.
    id: 'RELATIONSHIP',
    role: 'noun',
    description: 'the way two things stand to one another',
    emoji: '🔗',
    forms: {
      en: { base: 'relationship', plural: 'relationships', count: 'singular' },
      it: { base: 'relazione', plural: 'relazioni', gender: 'fem', count: 'singular' },
      fr: { base: 'relation', plural: 'relations', gender: 'fem', count: 'singular' },
      de: { base: 'Beziehung', plural: 'Beziehungen', gender: 'fem', count: 'singular' },
      es: { base: 'relación', plural: 'relaciones', gender: 'fem', count: 'singular' },
      ja: { base: '関係', count: 'singular', reading: 'かんけい' },
      pt: { base: 'relação', plural: 'relações', gender: 'fem', count: 'singular' },
    },
  },
  {
    // The grammatical person (who speaks / is spoken to / is spoken about), not a human being —
    // suffixed like SUBJECT_GRAMMAR because the plain word means both, and only this sense is
    // seeded (ja 人称, not 人).
    id: 'PERSON_GRAMMAR',
    role: 'noun',
    description: 'the speaker, the addressee or the one spoken about (grammar)',
    emoji: '🗣️',
    synonym: 'grammar',
    forms: {
      en: { base: 'person', plural: 'persons', count: 'singular' },
      it: { base: 'persona', plural: 'persone', gender: 'fem', count: 'singular' },
      fr: { base: 'personne', plural: 'personnes', gender: 'fem', count: 'singular' },
      de: { base: 'Person', plural: 'Personen', gender: 'fem', count: 'singular' },
      es: { base: 'persona', plural: 'personas', gender: 'fem', count: 'singular' },
      ja: { base: '人称', count: 'singular', reading: 'にんしょう' },
      pt: { base: 'pessoa', plural: 'pessoas', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'NUMBER',
    role: 'noun',
    description: 'a value used to count or measure',
    emoji: '🔟',
    forms: {
      en: { base: 'number', plural: 'numbers', count: 'singular' },
      it: { base: 'numero', plural: 'numeri', gender: 'masc', count: 'singular' },
      fr: { base: 'nombre', plural: 'nombres', gender: 'masc', count: 'singular' },
      de: { base: 'Zahl', plural: 'Zahlen', gender: 'fem', count: 'singular' },
      es: { base: 'número', plural: 'números', gender: 'masc', count: 'singular' },
      ja: { base: '数', count: 'singular', reading: 'かず' },
      pt: { base: 'número', plural: 'números', gender: 'masc', count: 'singular' },
    },
  },
  {
    // Grammatical number, as against the NUMBER above, which is the one you count with. Most
    // languages happen to use the same word for both (it "numero", fr "nombre"), but German does
    // not — a noun is in the "Numerus" singular, never in the "Zahl" singular — and Japanese
    // reads the same 数 differently in the two senses (すう here, かず for the arithmetic one).
    id: 'NUMBER_GRAMMAR',
    role: 'noun',
    description: 'whether a word refers to one or to more than one (grammar)',
    emoji: '🔢',
    synonym: 'grammar',
    forms: {
      en: { base: 'number', plural: 'numbers', count: 'singular' },
      it: { base: 'numero', plural: 'numeri', gender: 'masc', count: 'singular' },
      fr: { base: 'nombre', plural: 'nombres', gender: 'masc', count: 'singular' },
      de: { base: 'Numerus', plural: 'Numeri', gender: 'masc', count: 'singular' },
      es: { base: 'número', plural: 'números', gender: 'masc', count: 'singular' },
      ja: { base: '数', count: 'singular', reading: 'すう' },
      pt: { base: 'número', plural: 'números', gender: 'masc', count: 'singular' },
    },
  },
  {
    // The two values of NUMBER_GRAMMAR, as nouns — what the number control shows when it names a
    // value on its own ("Singular" / "Plural"), with no noun beside it to agree with. The
    // adjectives of the same meaning are seeded separately (SINGULAR / PLURAL in adjectives.ts):
    // a label that sits next to the noun it describes wants those, one that stands alone wants
    // these. Both are borrowed Latin in every language, which is why they look alike throughout.
    id: 'SINGULAR_GRAMMAR',
    role: 'noun',
    description: 'the form of a word referring to one (grammar)',
    emoji: '1️⃣',
    synonym: 'grammar',
    forms: {
      en: { base: 'singular', plural: 'singulars', count: 'singular' },
      it: { base: 'singolare', plural: 'singolari', gender: 'masc', count: 'singular' },
      fr: { base: 'singulier', plural: 'singuliers', gender: 'masc', count: 'singular' },
      de: { base: 'Singular', plural: 'Singulare', gender: 'masc', count: 'singular' },
      es: { base: 'singular', plural: 'singulares', gender: 'masc', count: 'singular' },
      ja: { base: '単数', count: 'singular', reading: 'たんすう' },
      pt: { base: 'singular', plural: 'singulares', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'PLURAL_GRAMMAR',
    role: 'noun',
    description: 'the form of a word referring to more than one (grammar)',
    emoji: '🔟',
    synonym: 'grammar',
    forms: {
      en: { base: 'plural', plural: 'plurals', count: 'singular' },
      it: { base: 'plurale', plural: 'plurali', gender: 'masc', count: 'singular' },
      fr: { base: 'pluriel', plural: 'pluriels', gender: 'masc', count: 'singular' },
      de: { base: 'Plural', plural: 'Plurale', gender: 'masc', count: 'singular' },
      es: { base: 'plural', plural: 'plurales', gender: 'masc', count: 'singular' },
      ja: { base: '複数', count: 'singular', reading: 'ふくすう' },
      pt: { base: 'plural', plural: 'plurais', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'GENDER',
    role: 'noun',
    description: 'the class a noun belongs to — masculine, feminine, neuter (grammar)',
    emoji: '🚻',
    forms: {
      en: { base: 'gender', plural: 'genders', count: 'singular' },
      it: { base: 'genere', plural: 'generi', gender: 'masc', count: 'singular' },
      fr: { base: 'genre', plural: 'genres', gender: 'masc', count: 'singular' },
      de: { base: 'Geschlecht', plural: 'Geschlechter', gender: 'neut', count: 'singular' },
      es: { base: 'género', plural: 'géneros', gender: 'masc', count: 'singular' },
      ja: { base: '性', count: 'singular', reading: 'せい' },
      pt: { base: 'género', plural: 'géneros', gender: 'masc', count: 'singular' },
    },
  },
  {
    id: 'COMMAND',
    role: 'noun',
    description: 'an instruction telling someone or something to act',
    emoji: '🫡',
    forms: {
      en: { base: 'command', plural: 'commands', count: 'singular' },
      it: { base: 'comando', plural: 'comandi', gender: 'masc', count: 'singular' },
      fr: { base: 'commande', plural: 'commandes', gender: 'fem', count: 'singular' },
      de: { base: 'Befehl', plural: 'Befehle', gender: 'masc', count: 'singular' },
      es: { base: 'comando', plural: 'comandos', gender: 'masc', count: 'singular' },
      ja: { base: '命令', count: 'singular', reading: 'めいれい' },
      pt: { base: 'comando', plural: 'comandos', gender: 'masc', count: 'singular' },
    },
  },
  {
    // The two registers a command is spoken in, named for the addressee selector. An order is
    // addressed to someone ("run!"); an instruction to nobody — a button, a menu entry, a recipe
    // step ("run"), which the engines render in each language's own label form. Only the command
    // sense is seeded: es "la orden" (fem) is the command, "el orden" the sequence.
    id: 'ORDER',
    role: 'noun',
    description: 'a command telling someone to act',
    emoji: '📢',
    forms: {
      en: { base: 'order', plural: 'orders', count: 'singular' },
      it: { base: 'ordine', plural: 'ordini', gender: 'masc', count: 'singular' },
      fr: { base: 'ordre', plural: 'ordres', gender: 'masc', count: 'singular' },
      de: { base: 'Befehl', plural: 'Befehle', gender: 'masc', count: 'singular' },
      es: { base: 'orden', plural: 'órdenes', gender: 'fem', count: 'singular' },
      ja: { base: '命令', count: 'singular', reading: 'めいれい' },
      pt: { base: 'ordem', plural: 'ordens', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'INSTRUCTION',
    role: 'noun',
    description: 'a step telling what to do, addressed to nobody',
    emoji: '📋',
    forms: {
      en: { base: 'instruction', plural: 'instructions', count: 'singular' },
      it: { base: 'istruzione', plural: 'istruzioni', gender: 'fem', count: 'singular' },
      fr: { base: 'instruction', plural: 'instructions', gender: 'fem', count: 'singular' },
      de: { base: 'Anweisung', plural: 'Anweisungen', gender: 'fem', count: 'singular' },
      es: { base: 'instrucción', plural: 'instrucciones', gender: 'fem', count: 'singular' },
      ja: { base: '指示', count: 'singular', reading: 'しじ' },
      pt: { base: 'instrução', plural: 'instruções', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'CAUSE',
    role: 'noun',
    description: 'that which makes something else happen',
    emoji: '💥',
    forms: {
      en: { base: 'cause', plural: 'causes', count: 'singular' },
      it: { base: 'causa', plural: 'cause', gender: 'fem', count: 'singular' },
      fr: { base: 'cause', plural: 'causes', gender: 'fem', count: 'singular' },
      de: { base: 'Ursache', plural: 'Ursachen', gender: 'fem', count: 'singular' },
      es: { base: 'causa', plural: 'causas', gender: 'fem', count: 'singular' },
      ja: { base: '原因', count: 'singular', reading: 'げんいん' },
      pt: { base: 'causa', plural: 'causas', gender: 'fem', count: 'singular' },
    },
  },
  {
    id: 'POSSESSOR',
    role: 'noun',
    description: 'the one who owns or holds something',
    emoji: '🔑',
    animate: true,
    forms: {
      en: { base: 'possessor', plural: 'possessors', count: 'singular' },
      it: { base: 'possessore', plural: 'possessori', gender: 'masc', count: 'singular', fem: 'posseditrice', fem_plural: 'posseditrici' },
      fr: { base: 'possesseur', plural: 'possesseurs', gender: 'masc', count: 'singular', fem: 'possesseuse', fem_plural: 'possesseuses' },
      de: { base: 'Besitzer', plural: 'Besitzer', gender: 'masc', count: 'singular', fem: 'Besitzerin', fem_plural: 'Besitzerinnen' },
      es: { base: 'poseedor', plural: 'poseedores', gender: 'masc', count: 'singular', fem: 'poseedora', fem_plural: 'poseedoras' },
      ja: { base: '所有者', count: 'singular', reading: 'しょゆうしゃ' },
      pt: { base: 'possuidor', plural: 'possuidores', gender: 'masc', count: 'singular', fem: 'possuidora', fem_plural: 'possuidoras' },
    },
  },

  // ── Abstraction levels ────────────────────────────────────────────
  // The three degrees an instrument can be reified to (see AbstractionLevel): an act in flow, the
  // act named, or the thing it leaves behind. Everyday nouns, seeded like any other — the levels
  // just happen to be the first thing that names them.
  {
    id: 'PROCESS',
    role: 'noun',
    description: 'a course of action unfolding step by step',
    emoji: '🔄',
    forms: {
      en: { base: 'process', plural: 'processes', count: 'singular' },
      it: { base: 'processo', plural: 'processi', gender: 'masc', count: 'singular' },
      fr: { base: 'processus', plural: 'processus', gender: 'masc', count: 'singular' },
      de: { base: 'Prozess', plural: 'Prozesse', gender: 'masc', count: 'singular' },
      es: { base: 'proceso', plural: 'procesos', gender: 'masc', count: 'singular' },
      ja: { base: '過程', count: 'singular', reading: 'かてい' },
      pt: { base: 'processo', plural: 'processos', gender: 'masc', count: 'singular' },
    },
  },
  {
    // The abstract notion, not a draft or a plan — de Begriff (the philosophical sense), not
    // Konzept, which is the sketch one writes before doing the thing.
    id: 'CONCEPT',
    role: 'noun',
    description: 'an abstract notion, a thing thought rather than held',
    emoji: '💡',
    forms: {
      en: { base: 'concept', plural: 'concepts', count: 'singular' },
      it: { base: 'concetto', plural: 'concetti', gender: 'masc', count: 'singular' },
      fr: { base: 'concept', plural: 'concepts', gender: 'masc', count: 'singular' },
      de: { base: 'Begriff', plural: 'Begriffe', gender: 'masc', count: 'singular' },
      es: { base: 'concepto', plural: 'conceptos', gender: 'masc', count: 'singular' },
      ja: { base: '概念', count: 'singular', reading: 'がいねん' },
      pt: { base: 'conceito', plural: 'conceitos', gender: 'masc', count: 'singular' },
    },
  },
  {
    // The physical thing, as against the grammatical OBJECT_GRAMMAR the same English word also
    // means: this is the one a hand closes on (ja 物体, not 目的語), which is why the ids split.
    id: 'OBJECT_THING',
    role: 'noun',
    description: 'a material thing one can hold or use',
    emoji: '📦',
    synonym: 'thing',
    forms: {
      en: { base: 'object', plural: 'objects', count: 'singular' },
      it: { base: 'oggetto', plural: 'oggetti', gender: 'masc', count: 'singular' },
      fr: { base: 'objet', plural: 'objets', gender: 'masc', count: 'singular' },
      de: { base: 'Gegenstand', plural: 'Gegenstände', gender: 'masc', count: 'singular' },
      es: { base: 'objeto', plural: 'objetos', gender: 'masc', count: 'singular' },
      ja: { base: '物体', count: 'singular', reading: 'ぶったい' },
      pt: { base: 'objeto', plural: 'objetos', gender: 'masc', count: 'singular' },
    },
  },
];
